### ISSUE TITLE
Option to store subs in metadata when storing next to media is not possible.

### ISSUE THREAD

**Issue by vandalon** [pannal/Sub-Zero.bundle#100]
This could be nice when some file systems with media are readonly and some are not :)

**Comment by pannal** [comment]
Not a bad idea!

**Comment by vandalon** [comment]
Thanks :)

**Comment by pannal** [comment]
Currently there's a feature that determines whether a library folder is writable or not, and tells the user so, in Sub-Zero's channel.

This enhancement still is viable as a fallback setting.
