### ISSUE TITLE
Not downloading full subtitles if forced subtitles are present

### ISSUE THREAD

**Issue by crushergad** [pannal/Sub-Zero.bundle#106]
If the video has embedded "forced" subtitles, and the option "Scan: include embedded subtitles (in the media file (MKV/MP4), don't download if existing)" is selected, the engine doesn't download the full subtitles as it detects some subtitles.

Could you add an option (or make it by default) that if the embedded subtitles are "forced" they should be ignored? This way it would download the full subtitles.

I suppose the same happens with external subtitles and the "Scan: include external subtitles (metadata/filesystem, don't download if existing)" option. So "forced" should be ignored by both options.

Thank you!

**Comment by pannal** [comment]
I don't think it can occur on the second option, as external srt files are never forced :) (or am I getting you wrong?)

**Comment by crushergad** [comment]
Just to clarify, because I didn't explain myself: 

Forced subtitles (definition): only provide subtitles when the characters speak a foreign or alien language, or a sign, flag, or other text in a scene is not translated in the localization and dubbing process.

So this can happen too on external str files that are downloaded with the video. I suppose this is less common but can happen anyway, or I'm the one missing something? If the file is external I could just deleted it, so the important enhancement is when they are embedded.

Thanks for looking into the issue :)

**Comment by pannal** [comment]
Yeah that's what I thought. It would be hard to identify the external forced srts, though. I will focus on solving the embedded problem.

**Comment by jdalton** [comment]
There is a naming convention for forced subtitles it goes `moviename.lang.forced.srt`.
