### ISSUE TITLE
Task: searchAllRecentlyAddedMissing, item stalled for 30 seconds errors

### ISSUE THREAD

**Issue by jamesmacwhite** [pannal/Sub-Zero.bundle#109]
Hi,

I installed this plugin on my Plex Media Server as I was having issues with the OpenSubtitles agent pulling anything (even with VIP account!)

Upon enabling the SubZero agent for both Movies and TV and adjusting the order accordingly, it appears to not be adding the new metadata properly.

My log file consists of DEBUG messages like this:

```
2016-01-02 22:21:03,809 (24a4) :  DEBUG (logkit:13) - Task: searchAllRecentlyAddedMissing, item stalled for 30 seconds: 3250, retrying
2016-01-02 22:21:33,855 (24a4) :  DEBUG (logkit:13) - Task: searchAllRecentlyAddedMissing, item stalled for 30 seconds: 3250, retrying
2016-01-02 22:22:03,885 (24a4) :  DEBUG (logkit:13) - Task: searchAllRecentlyAddedMissing, item stalled for 30 seconds: 3250, retrying
2016-01-02 22:22:33,963 (24a4) :  DEBUG (logkit:13) - Task: searchAllRecentlyAddedMissing, item stalled for 4 times: 3250, skipping
```

This is occurring for every item. I can see the library update notifications appearing and going through my media (Newest items first) VERY slowly.

I've had a look at a Wireshark capture and my Squid proxy logs to see what HTTP requests are happening, nothing looked out of place. Though I only saw `HTTP/1.1` requests made to `images.tmdb.org` and nothing else, no subtitles provider or anything else.

Is this down to some Plex API throttling? I have refreshed large chunks of my library quite a few times lately in an attempt to get subtitles working.

Thanks,

James

**Comment by pannal** [comment]
I'm guessing this is due to API throttling, or something similar. Usually if a request gets stalled, one retry solves the problem again.

I've posted a thread on the Plex forums regarding API request stalling/throttling without any answer yet: https://forums.plex.tv/discussion/192414/does-the-plex-api-throttle-drop-requests-automatically#latest

Though this never happened more than once per run for anyone yet.

Are you sure this isn't an issue with your squid proxy or setup?

**Comment by jamesmacwhite** [comment]
Its something I've not encountered before until enabling this bundle with Freebase and The TV DB. Squid configuration shouldn't be the issue. I've checked requests related to Plex and all are passed OK. There is a DIRECT rule in place for http://ip:32400 because Squid will block `TCP 32400` by default and I don't fancy adding 32400 globally in a Squid ACL.

**Comment by pannal** [comment]
Well, this is something that has never occurred for any of SZ's users before and the feature is months old.

Something seems to be weird with your setup as, as I said, when a request gets stalled, it normally is resolved by the following re-request.

> Its something I've not encountered before until enabling this bundle with Freebase and The TV DB. 
That may be true - SZ has to make a huge amount of requests for every recent item to be able to detect whether it's missing subtitles.

**Comment by jamesmacwhite** [comment]
Yeah fair enough. Please don't take that comment as me blaming your code. I was just highlighting that I hadn't seen this behaviour and log entries till I enabled the agent. I'll have to review my Squid setup I guess. Not sure where to start.

It would be good if Plex would get back to you re: API throttling to confirm or deny such events. However as this is a rare error it may be setup related.

**Comment by pannal** [comment]
Do you mind trying it without any intermediate proxy? That would help confirming the issue.

And yeah, I'd love to receive some answers to my API related questions from Plex :)

**Comment by jamesmacwhite** [comment]
Seems to be the same behaviour without the proxy too sadly. Will have to continue looking at the HTTP packets until I find anything that potentially could be causing it.

**Comment by pannal** [comment]
On what kind of system does your PMS run on? May there be a firewall involved? IPTables?

**Comment by pannal** [comment]
Is HTTP Pipelining active in your PMS?

**Comment by jamesmacwhite** [comment]
My PMS is run on Windows Server 2012 R2 Essentials. The Windows Firewall is active but there is a rule for the Plex components, so its not that.

Pipelining is enabled

Not sure I follow your last question, but I can access `localhost:32400/web` if that's what you mean.

Interestingly I've just noticed that `http://plex.tv/pms/:/ip` is returning `503` via the proxy but if I run it in a browser normally (same proxy) it works OK. I'll have to check that out, as remote access seems broken all of a sudden.

**Comment by pannal** [comment]
Any news on your issue?

**Comment by jamesmacwhite** [comment]
Removed the entire proxy from the situation to make sure that its not the issue. I am just getting this error repeated in the subzero error log, it is cycling through media items very slowly and not actually writing any new metadata (subtitles).

Tried the latest release and the same problem. Really not sure what could be causing this.

**Comment by pannal** [comment]
Are there any further things in the log pointing to anything erroring in that task perhaps? Could you post a full log somewhere? (E.g. cryptbin.com)

**Comment by jamesmacwhite** [comment]
Sure. I've been messing around with various configs and settings. So let me restart PMS and get a clean log from a new session. I'll attach them here when I've got a good sample of the error at work.

**Comment by jamesmacwhite** [comment]
Here's a capture of the logs:

http://cryptb.in/a3TE4

It seems to fail on any "Movies" items but does appear to be performing metadata changes to "TV Shows" to some degree.

Hope this helps.

**Comment by pannal** [comment]
I can't open that paste. Can you post it somewhere else? Somehow my browser(s) crash because of the amount of data.

**Comment by jamesmacwhite** [comment]
I reviewed the log and it really doesn't provide much information as to what the issue is, so it might not be worth your time. The logs show that all "Movies" items stall with the mentioned error above but appears to be processing "TV Show" content to some degree.

The OpenSubtitles Agent behaves in a similar way, no movies have subtitles matched (despite matching hash codes) but TV content does. With Movie items the agent doesn't even appear to try and match anything. Despite reported issues with the agent, I find it interesting that it behaves the same way.

I'm going to leave this for now to be honest, the recent changes have started to mess around with metadata and causing issues, so I've cleaned it up and left it for now.

I'd put it down to something specific to my setup, but I can't see what that is right now. Maybe if I have a bit more time I'll investigate further, thanks for your help :).

**Comment by pannal** [comment]
Well I cought one thing before the browser crashed: Your PMS version is way higher than mine (the current non-PlexPass stable). Perhaps something API related broke?

**Comment by jamesmacwhite** [comment]
I had been trying before on 9.14 releases with similar results. I installed a newer version to rule out any corruption in installation, it just so happens I recently upgraded to Plex Pass so installed the latest PlexPass version.

**Comment by pannal** [comment]
I've just updated to the PlexPass server. I'm seeing weird stuff. I think you could downgrade to the current public server version, that may fix your error.

**Comment by jamesmacwhite** [comment]
I was trying the SubZero agent on a latest stable non-Plex version before I upgraded and had problems with the tasks stalling still, for now I'm going to leave it because constantly changing settings around with the agents started to mess up my metadata. However I'll revisit this agent in the future should anything change.

**Comment by jamesmacwhite** [comment]
Just a note, due to a recent setup change. My PMS instance now runs on on a ESXi VM (CentOS 7) and SZ seems a lot happier. I migrated my cache, metadata and database over to the new Plex Media Server install, I gave SZ another shot and it appears to be functional this time round. It certainly isn't throwing stall errors.

I noticed that someone else is reporting the same issue, might be related to Windows specific servers perhaps if there is a trend forming?

**Comment by pannal** [comment]
Hmm, might really be a Plex issue on Windows...

**Comment by jamesmacwhite** [comment]
Maybe. I guess you need more Windows users to provide feedback on the issue. I'm no longer one of them on Plex!

**Comment by Amaelh** [comment]
Hello, 

I have a likely problem on Ubuntu : no subtitles downloaded and
