### ISSUE TITLE
Doesn't find Shameless TV Show

### ISSUE THREAD

**Issue by jbreuer95** [pannal/Sub-Zero.bundle#121]
2016-01-27 20:52:36,412 (7f72c9ffb700) :  ERROR (logger:34) - subliminal.providers.tvsubtitles: No show id found for u'Shameless (US)' ({u'year': None})

**Comment by sharkone** [comment]
I personnally have no problem finding subs for Shameless. Probably some other provider works for me.

**Comment by DrClimax** [comment]
Yea i have the same problem, Shameless US doesn't seem to work

**Comment by pannal** [comment]
Though that's only for TVSubtitles, correct? The other providers should work.
