### ISSUE TITLE
Podnapisi doesn't match certain shows

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#124]
For example "Marvel's Daredevil" and "Marvel's Jessica Jones". Only "Daredevil" and "Jessica Jones" are in their database.

@Diaoul do you think this is fixable? I couldn't come up with a spot on fix yet. If it was limited to the apostrophe in the first part of the name it may be fixable.

Edit: they match "America's Got Talent" perfectly well ... (just to test the apostrophe idea)

**Comment by Diaoul** [comment]
This is limited to Podnapisi and should be fixed by them IMO. Anything in subliminal would be a hack.
Have you contacted them already on that topic?

**Comment by pannal** [comment]
Nope not yet.

As for the hack approach: using a levensthein distance less or equal to 9 should work. If the name is a part of the full name.
