### ISSUE TITLE
Ability to download newer subtitles?

### ISSUE THREAD

**Issue by pablokbs** [pannal/Sub-Zero.bundle#125]
Hello and thank you for your plugin, it's really awesome. I have it running and it works great, I download subtitles in english and spanish. But the bad thing is that the spanish subtitles from opensubtitles.org are not so great when they just come up. Sometimes is just a google translated version of the english ones, and, as you can imagine, that sucks.

It would be great to add the ability to try to re-download subtitles if there is a new version, not forever, but maybe for a few weeks? That would be awesome

Even if you implement that feature, I'd like to ask you support for http://www.tusubtitulo.com, they have better quality spanish subtitles. I'm not at all a python developer but I can give it a try

Thanks in advance!

EDIT: I've found a XBMC plugin written in python for tusubtitulo.com, [here](https://github.com/ElHappy/service.subtitles.tusubtitulo)

**Comment by pannal** [comment]
That feature has been requested many times in the Sub-Zero Plex forums thread. At some point it will definitely come.

As for the tusubtitulo.com provider: I think it might be better if you post that request in the [subliminal repo](https://github.com/Diaoul/subliminal/issues).

**Comment by ugokanain** [comment]
I have a request related to this one. Found some subtitles to be off for the release I have, so it would be useful to be able to download another version of the subtitle file. For instance for one media file there are at least 7 files at opensubtitles, and 2 in addict7ed

When I used to do it manually, I found that some files had many subtitle files with different time codes. In this case the offset is greater than the 10 s, the pht allows, almost 20 s!

**Comment by pannal** [comment]
Yep manually selecting a subtitle is currently in development.

**Comment by PiehEjtsch** [comment]
Amazing!!! This is probably to one feature missing after an already pretty impressive tool. Good luck. Hope you will be successful soon.

**Comment by pannal** [comment]
Still in development, this will take some time.

**Comment by pannal** [comment]
It's been done. Will be in 1.4.6.

Teaser: 
![szbetter](https://cloud.githubusercontent.com/assets/1359593/20458647/cbfa719a-aeaa-11e6-99ae-7b4aea51b4c3.PNG)

**Comment by Ruvetuve** [comment]
I wonder...who rocks? Ow now i remember, its @pannal!
