### ISSUE TITLE
Remove .en from subtitles

### ISSUE THREAD

**Issue by amaru007** [pannal/Sub-Zero.bundle#126]
Loving the plugin, was hoping thay re could remove the .en when downloading the srt files.
Only have the one language (english) selected, so theres no need for the .en

Thanks

**Comment by TheImmortalOne** [comment]
I subscribe, i'd love such feature (I don't view the series in plex so that'll help tremendously).

**Comment by SvenErik1968** [comment]
@amaru007 : Plex need the language code as part of the file name so it can find out what language the subtitle file is in. Otherwise, it would display *Unknown* as the language for this subtitle.

**Comment by TheImmortalOne** [comment]
...perhaps it could be added as a secondary option, for those of us not really affected by what plex would display as the subs language?

**Comment by DrClimax** [comment]
Why is .en in the subtitle a problem?

**Comment by TheImmortalOne** [comment]
with .en in the subtitle, only PLEX TV automatically plays that subtitle.
Without .en in the subtitle, EVERY player (on every device) plays it automatically.

**Comment by amaru007** [comment]
We use pc's in our household to view the videos over the network, and for some reason MPC wont pick up the srt file with .en in it.
Also use Dreamplex on our satellite box , which won't pick it up either .
If they should, then it must be a problem on my end I guess.

**Comment by pannal** [comment]
This feature has been there before. I will backport it.

**Comment by pannal** [comment]
Backported, will be fixed with the next release

**Comment by pannal** [comment]
Please try https://github.com/pannal/Sub-Zero.bundle/archive/develop.zip

**Comment by enchained** [comment]
Couldn't find this in settings - why isn't this offered as a choice to a user? I'd much prefer Plex to detect the language from the filename instead, in case there are some non-preferred embedded subtitles and Plex won't be able to choose the right language.

**Comment by pannal** [comment]
@enchained https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#language-configuration
Figure 4.
