### ISSUE TITLE
Encoding Problems

### ISSUE THREAD

**Issue by leoheck** [pannal/Sub-Zero.bundle#128]
I am running PLEX from WD NAS (My Cloud Mirror Gen 2). Many subtitles can't be displayed because they are encoded in ISO-8859. To play them I always need to convert them to ASCII or URTF-8. The problem is that I don't have access to the Sub-Zero subtitles. It would be nice if sub-zero could set the encoding properly.

**Comment by SvenErik1968** [comment]
I think you should take a look at the [**SRT2UTF**](https://github.com/ukdtom/SRT2UTF-8.bundle) plugin, it takes care of this job for you.

**Comment by leoheck** [comment]
Oh, nice @SvenErik1968! I will look it, definitely. Thank you.

**Comment by pannal** [comment]
A forced encoding feature may help, yeah. Although the suggested SRT2UTF plugin should work, too.

Why don't you have access to the Sub-Zero subtitles, though? Even if you're using metadata subtitle storage you can access them by going to the right metadata folder.

**Comment by leoheck** [comment]
The SRT2UTF works fine. I could access the Sub-Zero after multiples restarts on plex and in NAS. I don't know what was happening but now all setup is fine.

**Comment by pannal** [comment]
Please try https://github.com/pannal/Sub-Zero.bundle/archive/develop.zip

**Comment by leoheck** [comment]
I've just installed it. What should I test? The forced encoding? Should I disable the SRT2UTF?

**Comment by leoheck** [comment]
Ok, now I can see the subtitles but the encoding isn't right. I am using pt-br (Portuguese, Brazil). 

For example, the word like ``não`` (which means _no_ in English) becomes ``nco``. In pt-br we have many words with accents. In this way, Sub-Zero is making the subtitles kinda difficult to read.

I attached a subtitle here, take a look: [The.Walking.Dead.S06E09.HDTV.XviD-FUM.pt-BR.txt](https://github.com/pannal/Sub-Zero.bundle/files/139888/The.Walking.Dead.S06E09.HDTV.XviD-FUM.pt-BR.txt)

I was using this command convert my subtitles, and it was working well. It was necessary only to reencode the files with ``ISO-8859-1``.
```bash
iconv -f ISO-8859-1 -t UTF-8 my_subtitle.srt > my_new_subtitle.srt
```

**Comment by pannal** [comment]
@leoheck please try the develop.zip again

**Comment by leoheck** [comment]
Perfect, you are the man @pannal! :+1:
