### ISSUE TITLE
Still use OpenSubtitles over Addic7ed.

### ISSUE THREAD

**Issue by Kraziee** [pannal/Sub-Zero.bundle#129]
I have had an issue for the last couple of days. It choose OpenSubtitles over Addic7ed even if Addic7ed: preferred is checked. The subtitle from OpenSubtitleshas advertising in it. It's not the same sub from when I download it manually from OpenSubtitles. I have OpenSubtitles for my foreign language for the movies.

1
00:00:06,000 --> 00:00:12,074
Advertise your product or brand here
contact www.OpenSubtitles.org today

2178
02:12:15,305 --> 02:12:21,401
Support us and become VIP member 
to remove all ads from OpenSubtitles.org

**Comment by pannal** [comment]
Are you sure you're downloading the exact same subtitle? How did you find out which one Sub-Zero downloaded?

Do you have debug logs?

**Comment by Kraziee** [comment]
Actually I don't know if I have downloaded the exact same subtitle, I have tried all of them and it is just trough sub-zero I get these subtitles. But I still have selected addic7ed as preferred.

The.Flash.2014.S02E14.720p.HDTV.X264-DIMENSION

146
00:05:21,000 --> 00:05:27,074
Advertise your product or brand here
contact www.OpenSubtitles.org today


839
00:40:47,305 --> 00:40:53,693
Support us and become VIP member 
to remove all ads from OpenSubtitles.org

[The.Flash.2014.S02E14.720p.HDTV.X264-DIMENSION.en.txt](https://github.com/pannal/Sub-Zero.bundle/files/136643/The.Flash.2014.S02E14.720p.HDTV.X264-DIMENSION.en.txt)


[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/136637/com.plexapp.agents.subzero.txt)

**Comment by pannal** [comment]
Addic7ed boost value will be configurable with the next version.
