### ISSUE TITLE
Left over subtitles from quality upgrades

### ISSUE THREAD

**Issue by xzKinGzxBuRnzx** [pannal/Sub-Zero.bundle#133]
My files are named like so...

"Colony - S01E01 - 720p WEB-DL.m4v"

I've noticed that when a file upgrades from HDTV to WEB-DL or BLU-RAY. The subtitles are left behind,  creating a mess.

"Colony - S01E01 - 720p HD TV.en.srt"
"Colony - S01E01 - 720p WEB-DL.en.srt"

It would be nice if Sub-Zero auto deleted the subs when this happens. As this over time will create a much larger mess, one I'd rather not have to manually cleanup. At that rate it would be easier to just remove all subtitles and let it download them again.

Also another issue I'm thinking is related to the file quality upgrades is that even though I have scan file for embedded subs enabled, I'm seeing English TX3G (mov_text) based sub and English SRT External sub in Plex. 

I'm assuming the HDTV file didn't have the embedded subs so it downloaded external subs. However the WEB-DL file did but it didn't pick up on that?

I'm running the latest version from the master branch.

**Comment by Mirabis** [comment]
I've been doing this with a custom made program on windows atm.
[![https://gyazo.com/6c7b18f77c5d6bbdf117f08a12d503fa](https://i.gyazo.com/6c7b18f77c5d6bbdf117f08a12d503fa.png)](https://gyazo.com/6c7b18f77c5d6bbdf117f08a12d503fa)

Been reading through the plex threads to create a cleanup plugin, but maybe i should pull req for the sub removal

**Comment by pannal** [comment]
I don't think this will be implemented early on. Many have subtitle files laying around their media files from the original releases and don't want to delete those.

**Comment by judhat2** [comment]
I am also interested in having this feature. Until then, @Mirabis do you mind sharing the code for your script?

**Comment by judhat2** [comment]
Until this feature is implemented and just in case someone wants also has this problem, I wrote a bash script to remove the leftover subtitles.  You might have to adjust the code to match your subtitle languages.  It currently searches for English and Korean. This works on linux.
https://gist.github.com/judhat2/bfc7e338b52f10ce4b90

**Comment by Mirabis** [comment]
@judhat2 Oh nice... I just received the e-mail notification on the post.. but the initial question must have slipped past me. My script is windows based but planned to port it to python ( so i can run it from Sonarr trigger).

source dates... uh 2015? https://dl.dropboxusercontent.com/u/41502623/ObsoleteSubsRemover.zip 

Thx for picking it up tho!

**Comment by judhat2** [comment]
@Mirabis Thanks for sharing!

**Comment by pannal** [comment]
Somehow related to #152. May make its way into some future release.

**Comment by pannal** [comment]
Please try the [develop-1.4 branch](https://github.com/pannal/Sub-Zero.bundle/tree/develop-1.4) with the development mode instructions from the Wiki. It should automatically clean your old, unused subtitle files automatically.

**Comment by pannal** [comment]
It's included in the recent release.
