### ISSUE TITLE
Exclude by path

### ISSUE THREAD

**Issue by mbnn** [pannal/Sub-Zero.bundle#134]
An interesting feature request, instead of excluding by file, would it be possible to exclude specific paths? For example I have a TV Shows dir with three directories:
- /nfs/tvshows1, - /nfs/tvshows2 and - /nfs/tvshows-synology

One of them is read only, so it would be great if we could skip that directory completely without having to put a file in there.

**Comment by pannal** [comment]
So this is one Plex library using three folders? Or one library per folder?

**Comment by mbnn** [comment]
Yes exactly :)    a library with multiple folders.

**Comment by pannal** [comment]
I'll see what I can do, but at first glance it seems possible.

**Comment by mbnn** [comment]
Super duper, thank you :)

**Comment by pannal** [comment]
So you'd like an ignore feature that's based on folders, am I correct?
