### ISSUE TITLE
Subtitles (SRT) is downloaded, but zero bytes (empty)

### ISSUE THREAD

**Issue by mrbrowndk** [pannal/Sub-Zero.bundle#139]
Hi Pannal,

Thank you for a great tool!!!!

Though I am having an issue... currently i get zero bytes SRT's, which is really annoying. Can you maybe shed some light on this?

Best,

Casper

**Comment by pannal** [comment]
Can you elaborate? Which files are we talking about? What are your plugin settings?

**Comment by pannal** [comment]
Closing, please reopen if this is still happening, and post more infos (and logs) :)
