### ISSUE TITLE
No option to reduce log volume

### ISSUE THREAD

**Issue by kwaio** [pannal/Sub-Zero.bundle#141]
Hi,
I'm currently trying to reduce the i/o activity of my server, and I narrowed down a good share of the activity to subzero logging to DEBUG despite plex setting to disabled debug logging.

Is there a way to set the plugin log level ? didn't find any that worked.

**Comment by pannal** [comment]
Yeah in the Sub-Zero settings screen, the log level should be on WARNING by default.

**Comment by pannal** [comment]
Closed because of no answer
