### ISSUE TITLE
Have to reinstall after PMS upgrade

### ISSUE THREAD

**Issue by ppucci** [pannal/Sub-Zero.bundle#142]
Hi there! I love this plugin, but I am having an issue with it. Every time I update my PMS to a newer version, the plugin is removed/not installed/not migrated to the plugins folder. I have to manually copy the .bundle folder back to it for it to work again. Did I install it wrong? Anything I can do to fix it?

Also, it says Sub-Zero is on the official Plex Channel directory, but I cannot see it there. Am I going nuts or what?

**Comment by Ruvetuve** [comment]
Channels > Install Channels > More... > All Available Plug-Ins

Any luck?

**Comment by ppucci** [comment]
Well, now I can see it on the Channel Directory, but no other update came out for me to test it. Whenever another one is released, I'll see and if it disappears I'll install from the directory.

**Comment by pannal** [comment]
Update incoming. Waiting for the officials to merge my pull request :)

**Comment by pannal** [comment]
Be sure to remove any remnants of any old (/manually installed) versions of Sub-Zero!

**Comment by pannal** [comment]
Closing until any news
