### ISSUE TITLE
Naming the subtitle file

### ISSUE THREAD

**Issue by haudankaivajasi** [pannal/Sub-Zero.bundle#144]
Hi.

I just encountered a slightly inconvenient feature for my library:

All my subtitles are named the same way as the media file so there are no language prefix in the name such as "en". Now when I scanned my files with this plug-in enabled, it ignored my older subtitles and downloaded new ones and now there are two different subtitles in the same folder. Is there a way to get this notice the old subtitles and save new ones without the language prefix?

**Comment by pannal** [comment]
The setting "Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)")" will be incorporated in the next release.

**Comment by haudankaivajasi** [comment]
Ok, good to know!
Btw, is there a way to update just a certain series to fetch subtitles?

**Comment by pannal** [comment]
The original feature you suggested has been fixed and will be in the next upstream release.

> Btw, is there a way to update just a certain series to fetch subtitles?

What do you mean by that? You can hit the refresh button on a certain series to trigger Sub-Zero's subtitle search.

**Comment by haudankaivajasi** [comment]
Ok, thanks!

**Comment by pannal** [comment]
I guess this can be closed?
