### ISSUE TITLE
Ability to IGNORE en subs from other providers

### ISSUE THREAD

**Issue by vBm** [pannal/Sub-Zero.bundle#145]
At the moment (and for quite some time already) everyone knows that addic7ed is THE GO TO place when it comes to English subtitles for tv shows. Sometimes addic7ed is slow-ish when it comes to releasing less popular ones. There are some users that tend to `google translate` (or do something like free typing) the whole subs from other languages (some have CC avail. in Spanish for example) and upload such subs. One of those places seems to be podnapisi.NET
Case in point is today's release of [Silicon Valley S03E01](https://www.podnapisi.net/subtitles/en-silicon-valley-2014-S03E01/0zxA) which is according to page, not yet audited.

Could we ignore such subs since they tend to be totally wrong, or if we could predefine which langs we want which provider to look up and download. Or if that's too much of a trouble, ability to ignore English ones from everywhere except addic7ed.

Thanks in advance.

**Comment by vBm** [comment]
@pannal Can anything be done regarding this ?
I'm tired of getting really bad eng subs that are downloaded as "better ones" ;x

**Comment by pannal** [comment]
That's hard to do with the current preference limitations Plex imposes on channels. I might add an advanced provider config json file or something like that, where you can fine tune your provider settings.

Or do you have a better idea? I don't think this can be done properly via channel settings.

**Comment by vBm** [comment]
Unfortunately i don't have any better ideas. Having an advance separate config is fine with me. I just wonder will there be more advanced users because implementing it just because of me is waste of your time :)

**Comment by pannal** [comment]
I've had numerous requests regarding advanced provider configuration.
Like score-per-provider, boost-per-provider, provider-order and your per-provider-languages request.

So I might implement something anyway :)
