### ISSUE TITLE
Missing subtitles list includes episodes that should be ignored by agent

### ISSUE THREAD

**Issue by lonelyfairie** [pannal/Sub-Zero.bundle#146]
[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/237226/com.plexapp.agents.subzero.txt)

Agent is reporting missing subtitles on episodes that actually have been skipped due to subs already present in media folder.

I forced a refresh on one of the episodes in question (Lucifer S01E13) and attached the log of that refresh in case it provides any useful info.

**Comment by pannal** [comment]
Your log states: `subliminal_patch.patch_video: Found subtitles {u'lucifer.113.hdtv-lol.srt': <Language [und]>}`, which is why it still tries to find an English subtitle.

The behaviour is correct.

**Comment by lonelyfairie** [comment]
Yes, I have sub zero configured so it doesn't append the language to the subtitle so the naming is correct, the subtitle was downloaded by the agent but is not detecting that it already did due to the missing language? Should I enable the language tagging of the subtitle to see if then it detectes it already downloaded the subtitle for it?

**Comment by pannal** [comment]
Hm nope, I think you've discovered what I'd call a missing feature :)

SZ should treat a single found subtitle language-less. It will be fixed.
In the meantime: you can rename it and add .en to it, then refresh the episode (force-refresh not needed).

**Comment by lonelyfairie** [comment]
OK, I just disabled the Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)") option so it won't cause any more issues. :)

**Comment by pannal** [comment]
It shouldn't - I guess this happens only with external subtitles not downloaded by SZ, with that option enabled, without a language suffix in the filename. Which is considerably rare (for most).

**Comment by lonelyfairie** [comment]
that's my point, the subtitles where downloaded by the agent. Right now I know for sure it downloaded subtitles for a show and that show is in the missing subtitles list due to the unidentified language. 
I only download subs using sub zero, all torrents I download come without subs.

**Comment by pannal** [comment]
OK then that's another bug. I'll fix the first one and we'll check whether this reappears or not.

**Comment by lonelyfairie** [comment]
Well, after disabling that option now the only shows that appearing in the missing subtitles pages are the ones that actually have no subtitles, I will leave it as is and re enable it for testing once you confirm the other bug is solved to see if it still happens. 
Thanks for your work, the agent is awesome 💯
