### ISSUE TITLE
Sub-Zero downloading subs even if the MP4/M4V has embedded subs

### ISSUE THREAD

**Issue by strafer** [pannal/Sub-Zero.bundle#147]
Sub-Zero seems to be ignoring the setting "Scan: include embedded subtitles (in the media file (MKV/MP4), don't download if existing)". I use Sickrage and sickbeard_MP4_automator to automatically download shows and corresponding subtitles. sickbeard_MP4_automator then takes the MKV, remuxes into an MP4, and embeds the external SRT. Then the external SRT is deleted. Unfortunately, Sub-Zero, after scanning the series folder, will download external subs even though the files have embedded subs already and I've enabled the scan option for embedded subs ("don't download if existing"). 

Is this option compatible with MP4/M4V files or just with MKVs? And is there a way to correct the behaviour of Sub-Zero so it doesn't re-download subs?

**Comment by pannal** [comment]
SZ currently isn't able to detect embedded subtitles of other containers than MKV. This may change soon depending on the available MP4 container parsers available out there.

**Comment by pannal** [comment]
It's coming :)

**Comment by pannal** [comment]
The next release will have that. It'll use the info supplied by the PMS and any supported container will be supported by Sub-Zero.
