### ISSUE TITLE
Local req. towards loopback and token

### ISSUE THREAD

**Issue by ukdtom** [pannal/Sub-Zero.bundle#148]
There's no need to use a token for a plugin, when issuing a req. towards 127.0.0.1
PMS auto auth a plugin running in it's framework

Added benefits....

No token loggen in the logs....

And unsure if plex.tv auth then is not needed at all, since I'm just checking this out, and only been testing for 5 min :-)

**Comment by eltismerino** [comment]
It is needed, when your server is inside a plex home - that's why the login/token feature was introduced in the first place.

For a normal server on 127.0.0.1, SZ will work without login/token.

**Comment by pannal** [comment]
It is needed, when your server is inside a plex home - that's why the login/token feature was introduced in the first place.

For a normal server on 127.0.0.1, SZ will work without login/token.

**Comment by ukdtom** [comment]
Plex2CSV and WebTools (UAS2) works without the token, and got this straight from E.lan :-)

**Comment by ukdtom** [comment]
And adding here....

A req. then is though, that you are using HTTP. calls, or XML. or JSON. from the framework, and not urllib etc.

**Comment by pannal** [comment]
Oh yeah, I'm using [fuzeman's Plexpy](https://github.com/fuzeman/plex.py) which does HTTP requests with python's requests library. I'll see if I can change the HTTP request library plexpy uses.

**Comment by pannal** [comment]
Would you care trying the current master branch? I've worked around the requirement.

**Comment by ukdtom** [comment]
Works perfectly.
Huston, you have a go :-)
