### ISSUE TITLE
Plugin does not ignore selected Season/Library

### ISSUE THREAD

**Issue by baglio** [pannal/Sub-Zero.bundle#164]
Hello, I made a new library for TV Shows in a different language than the default. Since I don't need subtitles for this particular library, I set Sub Zero to ignore it, but despite that the Plugin keeps downloading the subtitles.

I tried several time with different situation: ignore before the adding the media, ignore after adding the media, setting ignore and removing subtitles, but nothing changes.

**Comment by pannal** [comment]
So it keeps downloading subtitles for the items in the library?
Do you use the physical ignore or the one from the menu?
