### ISSUE TITLE
Insufficient permissions

### ISSUE THREAD

**Issue by ezar** [pannal/Sub-Zero.bundle#173]
06-24 17:42:33,073 (76ef7000) :  DEBUG (__init__:52) - Sub-Zero 1.3.46.606
2016-06-24 17:42:33,074 (76ef7000) :  ERROR (__init__:55) - Insufficient permissions on library folders:
2016-06-24 17:42:33,076 (76ef7000) :  ERROR (__init__:57) - Insufficient permissions on library Movies, folder: /mnt/usb/Movies
2016-06-24 17:42:33,077 (76ef7000) :  ERROR (__init__:57) - Insufficient permissions on library Music, folder: /mnt/usb/Music
2016-06-24 17:42:33,079 (76ef7000) :  ERROR (__init__:57) - Insufficient permissions on library TV Shows, folder: /mnt/usb/TV shows

Can you help me?

Regards.

**Comment by eltismerino** [comment]
1st: please paste the output of: `ps aux |grep -i plex` and `ls -als /mnt/usb`

**Comment by pannal** [comment]
1st: please paste the output of: `ps aux |grep -i plex` and `ls -als /mnt/usb`

**Comment by ukdtom** [comment]
Also state the OS PMS is running on, since different flavors runs under different users

**Comment by ezar** [comment]
> pi@minibian:~$ ps aux |grep -i plex
> plex      7343  0.0  0.0   1824   360 ?        S    Jun24   0:00 /bin/sh /usr/sbin/start_pms
> plex      7348  0.4  5.2 400676 52680 ?        Sl   Jun24   4:16 ./Plex Media Server
> plex      7484  0.5  3.5 185664 34896 ?        SNl  Jun24   5:09 Plex Plug-in [com.plexapp.system] /usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.0.0.2261-a17e99e /usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e/System.bundle
> plex      7591  0.1  0.7 172044  7392 ?        Sl   Jun24   1:02 /usr/lib/plexmediaserver/Plex DLNA Server
> plex     10832  0.1  2.9 137988 28920 ?        Sl   Jun24   1:05 Plex Plug-in [com.plexapp.agents.subzero] /usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.0.0.2261-a17e99e /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle
> pi       25555  0.0  0.1   4172  1608 pts/0    S+   06:36   0:00 grep -i plex

mnt:
>  4 drwxrwxrwx 10 root root  4096 Jun 24 21:44 .
>  4 drwxr-xr-x  6 root root  4096 Jun 24 11:24 ..
>  4 drwxrwxr-x 16 pi   pi    4096 Jun 24 21:45 Movies
>  4 drwxr-xr-x  9 pi   pi    4096 Mar 10 21:34 Music
>  4 drwxrwxr-x 51 pi   pi    4096 Jun 11 19:46 TV shows

**Comment by ukdtom** [comment]
According to above, your PMS is running under an account named plex....

And the directories it tries to access got rights to a user/group named pi

**Comment by pannal** [comment]
Yep, so either you add the plex user to the pi group and chmod accordingly: `adduser plex pi && chmod -R 775 /mnt/usb` or you change the user of those folders to plex: `chown -R plex /mnt/usb`.

Either way, your plex user has to have write access to those folders.

**Comment by ukdtom** [comment]
And now puzzled about how PMS can play any media in those folders ;-)

**Comment by pannal** [comment]
Because they're r+x for anyone

**Comment by ezar** [comment]
Thank you!
