### ISSUE TITLE
Issue with Thai subtitles encoded in TIS-620

### ISSUE THREAD

**Issue by SvenErik1968** [pannal/Sub-Zero.bundle#174]
I get problems with Thai subtitles that are encoded in TIS-620 (most Thai subs are encoded in TIS-620) where it looks like Sub-Zero assumes they are in UTF-8.

The included sample is (according to Notepad++) encoded in UTF-8, and the text is just "gibberish", but if I in Notepad++ change the encoding to TIS-620, the subs looks ok (though there seems to be some strange control-codes sometimes), and then convert to UTF-8, it will be ok.

[Game of Thrones S06E03.th.srt.txt](https://github.com/pannal/Sub-Zero.bundle/files/336976/Game.of.Thrones.S06E03.th.srt.txt)

**Comment by pannal** [comment]
Are there other encodings you've encountered for correct thai subtitles? (apart from tis-620)

**Comment by SvenErik1968** [comment]
There are a few in UTF-8, but a large majority is in TIS-620. I can't remember seeing Thai subs with other encodings than those two.

If it is an issue with detecting the encoding of the file, then maybe take a look at [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus) and how it detects the encoding of text files. I have never experienced it to not be able to detect TIS-620 encoded text files.

**Comment by pannal** [comment]
OK, thanks. Then the next SZ release will have that issue fixed :)
