### ISSUE TITLE
Sub-zero insufficient permissions on library: /storage/ReadyNAS...

### ISSUE THREAD

**Issue by antonispgs** [pannal/Sub-Zero.bundle#176]
When installing sub-zero from the channel directory on a nvidia shield running pms, this is the message I get and naturally it is not working. ReadyNAS is my NAS which holds my library and the /storage path is the path to my library after it is mounted on the Shield.
I am not sure if it is fixable or if Plex or Nvidia need to do something about it, thought I would let you know.

**Comment by pannal** [comment]
Please refer to #173 and see if that fixes your problem.

**Comment by antonispgs** [comment]
Thanks Pannal, and thanks for all the hard work on this awesome plugin by the way.
Is there a way to give write access without having root? Nvidia Shield does not allow it.

**Comment by pannal** [comment]
It does seem like a limitation of the PMS on Android devices.

You can only store subtitles in the internal metadata storage, not as sidecar/physical storage subtitles.
