### ISSUE TITLE
SubZero stopped downloading subtitles

### ISSUE THREAD

**Issue by ireun** [pannal/Sub-Zero.bundle#177]
Hello, for some reason subzero on my PMS won't download subtitles, i have them categorized via "TV Shows/Name_of_TV_show/Season XX" plex is recognizing  everything just fine, but i cannot get any subtitles. It was working some time ago though.

This is how agents look like:
![chrome_2016-07-01_01-05-10](https://cloud.githubusercontent.com/assets/695818/16507153/00f8b912-3f28-11e6-9b61-e6baad604a75.png)

Any help?

Edit: I've reinstalled whole plex, deleted all subtitles. SubZero downloades subtitles only for some TV Shows, but it won't download anything for: "The Blacklist", "House of Cards" also for example, for "The Wire" it has downloaded subtitles only for 5 episodes out of 13..

**Comment by pannal** [comment]
Logs please.

**Comment by ireun** [comment]
You mean plex logs? Or some subzero-specific logs?

**Comment by pannal** [comment]
Hey,

You've reached the download limit of OpenSubtitles:
```
2016-07-01 10:59:14,799 (b10) :  ERROR (logkit:22) - subliminal_patch.patch_provider_pool: Invalid subtitle
2016-07-01 10:59:14,868 (b10) :  ERROR (logkit:22) - subliminal_patch.patch_provider_pool: Unexpected error in provider u'opensubtitles', Traceback: Traceback (most recent call last):
  File "C:\Users\Michal\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\patch_provider_pool.py", line 214, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "C:\Users\Michal\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\opensubtitles.py", line 185, in download_subtitle
    response = checked(self.server.DownloadSubtitles(self.token, [str(subtitle.subtitle_id)]))
  File "C:\Users\Michal\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\opensubtitles.py", line 243, in checked
    raise DownloadLimitReached
DownloadLimitReached
```

Wait a day, then it should be good again. You can also create an account for more free API hits I guess.

**Comment by ireun** [comment]
Oh, thank You! Though i have an account, and I have given subzero credentials for it in the settings. Also why it doesn't use Addic7ed account? 

Also maybe subzero should display an error visible to user via web-ui ?

**Comment by pannal** [comment]
Error display would definitely be a good addition, but it's hard to integrate with the limited options you have as a Plex channel.

I'm closing this for now!

**Comment by ireun** [comment]
Sure, thank You for your help!

**Comment by ireun** [comment]
@pannal, once again I need some help, now I'm not getting the "DownloadLimitReached" error, just "Invalid Subtitle" can I do anything to fix that?

Logs: http://pastebin.com/UeQiRXMW

**Comment by pannal** [comment]
Hmm. Can't really help with that - those subtitles couldn't be parsed by either pySRT nor pysubs2. Nothing I can do about it, sorry.

**Comment by ireun** [comment]
Thanks, wouldn't it be good to automatically blacklist these subtitles, and try to download some others? Or maybe that's what SubZero will do now?

**Comment by pannal** [comment]
Yeah that's a feature that's still missing. It will come :)

**Comment by pannal** [comment]
Hm. I've just checked the code. It displays the error but it should continue to the next subtitle and try to download that one. Can you check?

**Comment by pannal** [comment]
Nope it doesn't. Found the issue I hope.

**Comment by ireun** [comment]
I'm sorry, I had a busy day today. And yes, You're right - It doesn't ;)
