### ISSUE TITLE
Missing subtitles, but plugin doesn't know about it

### ISSUE THREAD

**Issue by benjick** [pannal/Sub-Zero.bundle#178]
Hey

Been using this plugin (it's amazing) for a while now, but I have some problems lately, no new subtitles seem to get downloaded. 

If I click "on deck-items" it shows me an empty list, same with "Items with missing subtitles" (even though I have shows with missing subtitles).

If I click "Search for missing subtitles" it finishes with "last runtime: 0:00:00".

I've tried restarting the plugin/plex, but that doesn't change anything.

**Version 1.3.46.606**

Where can I find logs for subzero?

**Comment by ukdtom** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/Support

Or use the WebTools PlugIn

**Comment by pannal** [comment]
Please follow @ukdtom 's suggestion and reopen this, when you've posted your logs

**Comment by benjick** [comment]
```
2016-10-04 23:57:58,686 (1e94) :  DEBUG (logkit:13) - Skipping section: Movies
2016-10-04 23:57:58,687 (1e94) :  DEBUG (logkit:13) - Skipping section: TV Shows
```

Can't see anywhere in the settings these are set to be ignored. I tried uninstalling the plugin and deleting the whole folder from `Plug-in Support\Caches` and then reinstalling, but it didn't help.
