### ISSUE TITLE
[Request] Overview page of downloaded subtitles

### ISSUE THREAD

**Issue by mbnn** [pannal/Sub-Zero.bundle#179]
Hello,

First of all, love Sub-Zero, one of the best plugins for Plex out there. I do however have one request: What I would love to see is an overview page with latest downloaded subtitles and an option next to them to re-download (or download next) (in case of wrong subs).

Thank you :)

**Comment by pannal** [comment]
I've added a History menu to 1.4.0, which shows the last X (configurable) subtitles downloaded. When entering an item there, you can use the new manual selection feature afterwards.

Closing this for now, or isn't this enough?
