### ISSUE TITLE
Sub-Zero not showing up in the Channels section.

### ISSUE THREAD

**Issue by bjay1404** [pannal/Sub-Zero.bundle#180]
I installed Sub-Zero a couple of weeks ago and tweaked all of the settings, but now I can't see it in the channels section. My Plex server checks daily for updates.. I even removed the plugin and I still don't see anything. 

ug 05, 2016 15:07:43.324 [0x7f72047fd700] WARN - Request for plug-in [com.plexapp.agents.subzero] but it doesn't exist.

Aug 05, 2016 15:09:22.556 [0x7f721cfff700] ERROR - Error received reading configuration for com.plexapp.agents.subzero

Any suggestions?

**Comment by ukdtom** [comment]
OS?
How did you install it?
(Via the Plex Online directory, or manually)

**Comment by ukdtom** [comment]
If so, we need logs in debug mode, and since it's not showing, we want Sub-Zero logs, system.bundle logs and the PMS logs, preferred zipped 10 min after a restart of PMS

**Comment by pannal** [comment]
Sounds weird, please follow @ukdtom's suggestion to post debug logs.

**Comment by bjay1404** [comment]
Where are the Sub-Zero and System.bundle logs located? Ubuntu 14.04 btw not 16

**Comment by ukdtom** [comment]
Wiki time
https://github.com/pannal/Sub-Zero.bundle/wiki/Support

**Comment by bjay1404** [comment]
Thanks.

This stuck out immediately 

2016-08-06 16:42:47,297 (7fcb41382740) :  ERROR (__init__:57) - Insufficient permissions on library Movies, folder: /media/movies
and I see this line for all of my library folders... 


Looks like there is a permission issue.... The plugin is run by the same user which runs PMS right? That user should have full access to those folders.

In the mean ime I need to clean up my logs, I will post them later. Thanks so far.

**Comment by ukdtom** [comment]
You are correct in assuming, that all plugin's in Plex run under the same user as PMS itself, since they are child processes

/T

**Comment by pannal** [comment]
Yeah, the media folders itself have to have the correct permission for SZ to be able to write subtitles to the filesystem (and create subfolders if necessary). Check the ownership and/or the permissions of your library folders, please.

**Comment by ukdtom** [comment]
And make sure it's recursive from top of the library, and all the way down

**Comment by pannal** [comment]
I haven't tested this, but it should chown `/path/to/library` to your plex user:
```
chown -R `ps aux |grep -m1 com.plexapp.system |cut -f1 -d " "` /path/to/library
```

**Comment by ferllings** [comment]
I have the same issue: 

I installed with the Channel method.
- The plugin is visible as installed in Channels>Install Channels>More...>Installed Plug-ins (But no icon)
- I can Uninstall/Restart/Reset without any issue
- The plugin itself works fine
- I don't have any Errors or Warnings in the logs

But still not visible in the main channels browsing page.

**Comment by ukdtom** [comment]
@ferllings Check first item mentioned here:
https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration

**Comment by ferllings** [comment]
@ukdtom Thanks, that was so obvious...sorry

**Comment by ukdtom** [comment]
ping @bjay1404 Any news here?

**Comment by bjay1404** [comment]
Looks like it came back into my channels. I have no idea why though!
