### ISSUE TITLE
Sub-Zero not download the most updated File from addic7ed

### ISSUE THREAD

**Issue by eender** [pannal/Sub-Zero.bundle#181]
Looks like Sub-Zero always downloads the "original" Subtitle instead of the most updated one.
(5 Out of 20 Episodes had wrong Subtitles, where Sub-Zero just didnt download the most updated one.)

So maybe try this url first
http://www.addic7ed.com/updated/x/xxxxx/x

and if there is no "most updated" one just this path
http://www.addic7ed.com/original/xxxxx/x

Anyway thanks for this **awesome** tool =)

**Comment by pannal** [comment]
Will look into it, thanks!

**Comment by pannal** [comment]
I think you're wrong. Subliminal uses [this view](http://www.addic7ed.com/show/4658), for example, for parsing subtitles, which will always get the newest ones. I guess you've been "too early" in the game for your particular episode.

What you're really up to here is some sort of check-again-later-feature.
