### ISSUE TITLE
Sub-Zero automatically adds folders to the ignore list

### ISSUE THREAD

**Issue by Hespen** [pannal/Sub-Zero.bundle#182]
There is an issue which is really annoying me. Sub-Zero automatically fills the ignore list with random files or folders. 
The files already have embedded subtitles, so I don't really care about those. But the folders are the root folders of my movies and tv shows. 
Why are the root folders added to the ignore list (automatically)? I've been removing them from the list every day.

**Comment by pannal** [comment]
That's very weird. Did you try reinstalling SZ? It has no control of its own over its ignore list.

**Comment by Hespen** [comment]
Yes I did, multiple times. At the moment it has put 14 items in this ignore list. 3 sections and 11 items

**Comment by pannal** [comment]
Please clear the internal storages of SZ to see whether that fixes your problem. The functions can be found in the advanced menu of the SZ channel.

**Comment by pannal** [comment]
Did this fix your problem?

**Comment by Hespen** [comment]
I wanted to wait a bit to see if the list got filled again. But I totally forgot about it, sorry!
But yes, I think it is fixed. The ignore list is empty, so I guess that's good :)
