### ISSUE TITLE
Only download subtitle if language is foreign

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#186]
We should have an option that determines whether to download any subtitle at all, based on the audio language of the video file. Something like this:

`Download subtitles`
- always
- if primary audio stream language differs from lang1 setting

Any other options you guys might need?

**Comment by pannal** [comment]
We should have an option something like this:

`Download subtitles`
* always
* if primary audio stream language differs from lang

Any other options you guys might need?

**Comment by pannal** [comment]
#209

**Comment by cvium** [comment]
I know it's not directly related, so I'll open another issue if you prefer.

Anyway, it'd be nice if there was an option to only download subtitles if _none_ exist. Sometimes embedded subtitles have no language tag and in that case I just want Sub-Zero to assume it is lang1.

**Comment by pannal** [comment]
That's #239, unrelated.

**Comment by pannal** [comment]
That's been implemented.
