### ISSUE TITLE
Issue with (many) Greek subtitles

### ISSUE THREAD

**Issue by lnslevin** [pannal/Sub-Zero.bundle#187]
hello everyone,

I have an issue with many of the greek subtitles that are downloaded by SZ.
Some are OK but there are some other greek subtitles which appear as gibberish. I tried opening them in Notepad++ and changing the encoding (from UTF-8 to ISO8859-7, OEM 737, OEM 869, Windows-1253) but nothing really happens, all the characters are still gibberish. This problem has never happened to the english subs that are also downloaded by SZ.
Please take a look at the sample files and let me know if there is anything I can do.

Thanks for all your help in advance!

[Blindspot.S01E23.HDTV.x264-LOL-Obfuscated.el.txt](https://github.com/pannal/Sub-Zero.bundle/files/478615/Blindspot.S01E23.HDTV.x264-LOL-Obfuscated.el.txt)
[Blindspot.S01E19.HDTV.x264-LOL-Obfuscated.el.txt](https://github.com/pannal/Sub-Zero.bundle/files/478616/Blindspot.S01E19.HDTV.x264-LOL-Obfuscated.el.txt)
[Blindspot.S01E20.HDTV.x264-LOL-Obfuscated.el.txt](https://github.com/pannal/Sub-Zero.bundle/files/478614/Blindspot.S01E20.HDTV.x264-LOL-Obfuscated.el.txt)

**Comment by pannal** [comment]
That's weird. I'll try adding the other encodings you mentioned, that are known for Greek, to SZ. I wasn't able to successfully convert the example files you posted, though, either.

Where did it download these subs? Does the download source perhaps say something about their encoding?

**Comment by ukdtom** [comment]
Bad subs, IMHO

Blindspot.S01E23.HDTV.x264-LOL-Obfuscated.el.txt was already UTF-8 encoded, so uploader to the sub site broke it, IMHO

**Comment by lnslevin** [comment]
Thank you both for answering!

I don't really think that the subs are broken, at least the original uploads are not. 
Please take a look at the new samples below. The first one (1.) is the sub that was downloaded by SZ, the second one (2.) is the exactly same sub I found from the site that was originally uploaded (http://www.subztv.gr). 
[1. Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.el.txt](https://github.com/pannal/Sub-Zero.bundle/files/480499/1.Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.el.txt)
[2. Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.txt](https://github.com/pannal/Sub-Zero.bundle/files/480500/2.Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.txt)
Of course I can't be certain from which site exactly the sub was downloaded by SZ (can I?) but this show that the original upload is not broken. 
If we can assume that the sub was downloaded from opensubtitles.org then the file is also not corrupted (see below 3.)
[3. Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.txt](https://github.com/pannal/Sub-Zero.bundle/files/480560/3.Game.of.Thrones.S06E09.720p.HDTV.x264-AVS.txt)


Also another thing I noticed, all the subs I download from the web by myself have a structured form, on the other hand all the subs that are downloaded by SZ have not. You can see this by opening the sample files with the plain notepad. I don't know if this means something, I'm just mentioning it.

I don't know if these observations help you, I hope they are.
Is there anything I should try?
thanks again!

**Comment by pannal** [comment]
Please [follow this](https://github.com/pannal/Sub-Zero.bundle/wiki/Support#logging) and attach the log files here after deleting the subtitle and refreshing the item so we can investigate.

**Comment by lnslevin** [comment]
hey pannal,

attached is the log file you requested. I deleted the subtitles which I send you before as samples and they all got downloaded again with the same problem.

[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/483155/com.plexapp.agents.subzero.zip)

thanks again!

**Comment by pannal** [comment]
In your logfile there's nothing to observe, mate. Only a possibly broken library.

**Comment by lnslevin** [comment]
hey pannal,

yes, you are right. I didn't send them correctly.
Please check the full logs
[PMS Plugin Logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/494003/PMS.Plugin.Logs.zip)

I tried to play a little bit with different providers to understand from which site does the SZ downloads the "gibberish" subs.  They are all downloaded from Opensubtitles, if I uncheck the Opensubtitles.org as a provider, no greek subtitle is downloaded for these episodes. Maybe this observation helps..

**Comment by mcde731** [comment]
Dear Pannal, thank you for this excellent plugin. I can also confirm that greek subtitles downloaded by SZ from opensubtitles.org have the problem with encoding that lnslevin is reporting. I can also confirm that the same subtitle is ok when downloaded directly from the opensubtitles.org site. Plex/SZ is installed on a pc with Win10.

**Comment by eltismerino** [comment]
@lnslevin it seems like you need to create a new library from scratch, as your logs seem to be really messed up. I can't make too much out of those.

I'll try, though.

**Comment by pannal** [comment]
@lnslevin it seems like you need to create a new library from scratch, as your logs seem to be really messed up. I can't make too much out of those.

I'll try, though.

Edit: I think I've got it.

**Comment by pannal** [comment]
Could you try the [develop-1.4 branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip) and see if that fixes your problem? You need to use parts of [these instructions ](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)to do so.

**Comment by pannal** [comment]
Or try the newest release (should auto-update); I've backported the language fixes from the develop-1.4 branch to the current 1.3 release.

**Comment by pannal** [comment]
Poke?

**Comment by mcde731** [comment]
Hello Pannal, thank you for the replies and all the work you are doing. Unfortunately the pc that plex is installed on sustained a hard disk failure and I'm now trying to repair it. Once everything is back in order I will try to update SZ and see what happens.

**Comment by lnslevin** [comment]
Hi pannal, 
Thank you for the time you spent on this, I will try to do what you suggest during the weekend and I will let you know immediately. 

Thanks again!

**Comment by pannal** [comment]
Yeah just try the currently available release from the channel repository.

**Comment by lnslevin** [comment]
Hey pannal,
I had the time to check the new release of SZ (1.3.49.630).
You did an amazing job! So far I have force-refreshed more than 20 "gibberish" subs and they were all downloaded correctly this time. I will spent more time on it during the weekend to re-download all the problematic subs i can find but it seems that the issue is resolved.

Thanks again for your time and effort!

**Comment by pannal** [comment]
Great, closing the issue!
