### ISSUE TITLE
Missing sub-zero from channel overview

### ISSUE THREAD

**Issue by vildning** [pannal/Sub-Zero.bundle#188]
I disabled the plugin from the sub-zero setting page, but how to I get it back?

It's listed under installed plugins.

![image](https://cloud.githubusercontent.com/assets/18198878/19041855/18d9b99e-898a-11e6-8ded-39559756fdb2.png)

**Comment by ukdtom** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ
