### ISSUE TITLE
Cannot determine whether Sub-Zero is downloading Subtitles?

### ISSUE THREAD

**Issue by bjay1404** [pannal/Sub-Zero.bundle#189]
Hello, I'm having trouble determining if Sub Zero is actually working. It's added to agents and I'm pretty sure it's configured properly, but I have yet to see it download a subtitle. I've looked at the logs and they aren't very helpful. Any tips to determine or pinpoint specific .srts that Sub Zero snatched? I'm convinced that something is wrong.

**Comment by pannal** [comment]
Not yet, same as #179
