### ISSUE TITLE
Ignore VobSub (.idx/.sub) subtitles while scanning external subtitles.

### ISSUE THREAD

**Issue by RobinHoutevelts** [pannal/Sub-Zero.bundle#192]
Is it possible to exclude VobSub subtitles while scanning for external subtitles?

I have this option turned on:
`Scan: include external subtitles (metadata/filesystem, don't download if existing)`

But i'd still prefer .srt's over VobSub

**Comment by pannal** [comment]
I could build you a branch of SZ which doesn't add VobSub subtitles. Would you be willing to test that?

**Comment by pannal** [comment]
@RobinHoutevelts ping?

**Comment by RobinHoutevelts** [comment]
Yeah I'm sorry for the delay.

I'd be happy to test. Although I'm also thinking of tackling this problem
myself in order to get to know the project...

I think I'll have some time Sunday to try and create a PR for this.

I'll update this issue Sunday ;-)

Op 18-nov.-2016 10:27 PM schreef "pannal" <notifications@github.com>:

**Comment by pannal** [comment]
Just have a look in https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Code/support/localmedia.py

**Comment by pannal** [comment]
Where are we with this?

**Comment by RobinHoutevelts** [comment]
Lost my plex due to me being a dumbass ( trusted the onboard NAS encryption and after a reboot it doesn't recognize my drives.).

I probably won't be spending time on this for another month. Especially with the upcoming holidays.

I'm fine with this issue being closed for now as I won't even be able to test until I figure out a way to restore my drives.

**Comment by pannal** [comment]
I can add that feature instead, so you don't have to worry :)

**Comment by pannal** [comment]
This will still display any found vobsub subtitles in the Plex GUI, but they'll be ignored by SZ while determining whether to look for a subtitle or not.
