### ISSUE TITLE
SubZero Stopped downloading subtitles

### ISSUE THREAD

**Issue by DanielSBFranco** [pannal/Sub-Zero.bundle#194]
Hello, a few days ago Subzero stopped downloading subtitles when TV Show episode is just added to the Library, or when scheduled.

Logger says Episode 5 not found, but I don't know where it is not found, and another TV Show says
"No show id found" 

(7fd57b8f5700) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for u'The Flash' ({u'year': 2014})

Both TV Shows worked flawlessly a few days ago

Exception thrown when scheduled is this

2016-10-26 12:04:48,367 (7fd5793bb700) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: Episode 5 not found
2016-10-26 12:04:51,799 (7fd5793bb700) :  CRITICAL (agentkit:1067) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.3.49.636)', called with guid 'com.plexapp.agents.thetvdb://263365/4/5?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/media/8a625a54-a1d7-4931-baf3-5e2b85f3433a/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 265, in update
    scheduler.signal("updated_metadata", item_id)
  File "/media/8a625a54-a1d7-4931-baf3-5e2b85f3433a/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/background.py", line 93, in signal
    status = task.signal(name, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/media/8a625a54-a1d7-4931-baf3-5e2b85f3433a/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 74, in signal
    return handler(*args, **kwargs) if handler else None
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/media/8a625a54-a1d7-4931-baf3-5e2b85f3433a/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 79, in signal_updated_metadata
    if item_id in self.items_searching_ids:
TypeError: argument of type 'NoneType' is not iterable

**Comment by pannal** [comment]
Looks like a bug, I'll have a look. Thank you!

**Comment by pannal** [comment]
Could you please *attach* all of the SZ logs?

**Comment by DanielSBFranco** [comment]
Sure, the whole com.plexapp.agents.subzero.log file is pasted here: [http://pastebin.com/xsQ0HUXG](http://pastebin.com/xsQ0HUXG)

But I had debug only at the end,

**Comment by pannal** [comment]
For Episode 5: the tvsubtitles provider hasn't got the Episode 5, that's all right.

SZ downloads `/media/ed626575-0592-4986-9a9d-2cced3c72a14/media/TV Shows/Lethal Weapon/Season 01/Lethal Weapon - S01E05 - Spilt Milk.pt-BR.srt` - isn't it there?

The rest of the log looks quite OK, but I doubt that's all of it, as your Exception isn't in there. Please attach all of the SZ logs (also the ones with a number at the end) to this ticket.

**Comment by DanielSBFranco** [comment]
Pastebin won't accept files larger than 512k, so I zipped them all together, and upload at [http://s000.tinyupload.com/?file_id=07687780959479431484](http://s000.tinyupload.com/?file_id=07687780959479431484)

To try and contextualize, here's what I've noticed about the issue: Most of the episodes are downloaded during the night/morning after its release, and they had their subtitles downloaded correctly at the next evening, but since a few days ago, even 2, 3 days after the episode is downloaded and added to plex, it has no subtitles until I go and refresh the episode in Plex Web (I've setup subzero to look for subtitles every 6 hours). Also, I've setup subzero to store subtitle files in the same folder as the episode, and before refreshing I'd go and look if the subtitle was downloaded before refreshing (suspecting it was a problem with plex refreshing the episode), but there are no subtitles.

Then I looked in the logfiles and saw the exceptions, enabled debug logging, and refreshed one episode that still didn't have the subtitles.

Also, after reading that the exception wasn't in the log I sent, I checked the files, and since I enabled debug information, and forgot it on, I only have debug info from this afternoon, and I don't think any of them will have the Exceptions (including those I uploaded right now), since I haven't downloaded anything this afternoon. Please excuse me for wasting your time with these logs.

Is it ok if I send logs with the exception tomorrow, after new downloads are finished? And if it is, what is the prefered level? debug, info, warning?

**Comment by pannal** [comment]
Always DEBUG and always all of them (because they get rotated). And is there a reason why you can't simply attach them to a comment here? (Look at the text below: "Attach files by dragging & dropping,  Dateien auswählen selecting them, or pasting from the clipboard.")

**Comment by DanielSBFranco** [comment]
Okay, I'll switch to debug and try to refresh

I can't attach here because github only accepts images and PDFs, no .log files

**Comment by pannal** [comment]
By the way: is the scheduler function still enabled in SZ (`Scheduler: Periodically search for recent items with missing subtitles`) and did you try restarting the PMS? From what you're saying it seems like the automatic task isn't running.

**Comment by DanielSBFranco** [comment]
Yes, Scheduler is enabled to run every 6 hours, and I restarted PMS today. I haven't sent any more logs yet because I haven't seen any exceptions on the logs today.

I'll check the logs and if the new episodes have subtitles later tonight

**Comment by pannal** [comment]
You don't have to use DEBUG for your PMS, though. Setting the log level of Sub-Zero to DEBUG is the right way.

**Comment by DanielSBFranco** [comment]
Yes, that's what I did, changed only SZ's logs to debug, but in doing that, all 6 files (com.plexapp.agents.subzero.log and com.plexapp.agents.subzero.log.1 through com.plexapp.agents.subzero.log.5) span about 15 minutes

I looked at all of them again, searching for terms like 'CRITICAL' and 'Exception' but found only an permission denied one, no other exceptions.

I guess I have screwed something up, and restarting PMS fixed it or something. If you like, I could close this and reopen if find the exception again

In any case, thanks for the help, please excuse me for wasting your time, and thanks a lot for such a great job with SubZero!

**Comment by pannal** [comment]
Sounds good, just reopen this if it happens again :)
