### ISSUE TITLE
Insufficient permissions

### ISSUE THREAD

**Issue by Drance144** [pannal/Sub-Zero.bundle#195]
I've been reading about this a lot and I can't seem to figure it out. Sub-Zero 1.3.46.606 is giving me Insufficient permissions on library. Reading through other issues I have added the user plex with rw access..

I am running this on a NVIDIA Shield with a DS214 synology as external storage. I've tried enabling debugging to try and figure out what user is accessing what but no luck...

Can anyone help me out?

**Comment by ukdtom** [comment]
This is a limitation with NVIDIA Shield
[https://support.plex.tv/hc/en-us/articles/221099648-Limitations-When-Running-Plex-Media-Server-on-NVIDIA-SHIELD](url)

Not sure here, but guess you should be able to set SZ to not store subs next to your media

**Comment by Drance144** [comment]
Hey ukdtom,

Actually Sub-Zero is trying to access the NAS that I have mounted on the shield but it says insufficient rights.

![image](https://cloud.githubusercontent.com/assets/20655458/19835629/029c2708-9e8d-11e6-855a-2b070136c8f9.png)

**Comment by ukdtom** [comment]
Yes, and that will according to the link I provided you with not work
In the link, search for "Storage Limitations"

**Comment by Drance144** [comment]
Ah I am so sorry, you are right. Thank you for this information! I will try and figure out if I can have it so that it saves the subtitles on the local drive or something. Thank you!
