### ISSUE TITLE
Upper limit of TV-score-setting is too low

### ISSUE THREAD

**Issue by eleonrk** [pannal/Sub-Zero.bundle#197]
Sub-Zero is showing very high computing scores for the subtitles retrieved from Addic7ed provider.

```
319  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'series', u'year', u'episode', u'hearing_impaired', u'season']) and <Episode [u'South Park', 20x6]>
319  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 111
321  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'series', u'year', u'episode', u'hearing_impaired', u'season']) and <Episode [u'South Park', 20x6]>
321  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 111
322  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'series', u'year', u'episode', u'season']) and <Episode [u'South Park', 20x6]>
322  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 110
323  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'episode', u'series', u'season', u'hearing_impaired', u'year', u'release_group']) and <Episode [u'South Park', 20x6]>
323  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 122
325  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'series', u'year', u'episode', u'release_group', u'season']) and <Episode [u'South Park', 20x6]>
325  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 121
332  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'episode', u'series', u'season', u'year', u'video_codec', u'resolution', u'hearing_impaired']) and <Episode [u'South Park', 20x6]>
332  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 119
334  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computing score for matches set([u'episode', u'series', u'season', u'hearing_impaired', u'year', u'release_group']) and <Episode [u'South Park', 20x6]>
334  INFO (logkit:16) - subliminal_patch.patch_subtitle: Computed score 122
```
It's bothering me because in the agent settings, the 'Minimum score for TV subtitles to download' parameter can not go higher then 100.

I recently switched from bramwalet/Subliminal.bundle to Sub-Zero, and back then, the computing score was relevant (between 55 and 66 for the right subtitles).

**Comment by pannal** [comment]
Which version are you using? The one from the Plex repository or a manual installation?

**Comment by Diaoul** [comment]
Previous versions of subliminal used to have a score between 0 and 100. This is not the case anymore.

**Comment by Diaoul** [comment]
https://github.com/Diaoul/subliminal/blob/1.0/subliminal/cli.py#L149-L150

**Comment by pannal** [comment]
Yeah but SZ is still using 1.0.1 and he was complaining about 0.8.0-dev - nothing in terms of the scores itself has changed since then.

**Comment by eleonrk** [comment]
Actually I installed SZ from the Plex repository

**Comment by pannal** [comment]
@eleonrk OK. Still, the scoring itself hasn't changed since Subliminal.bundle, which used subliminal 0.8.0-dev. Sub-Zero uses 1.0.1.

You could be mixing up movie scores with TV scores (movie scores are substantially lower). And where exactly is the problem? The scoring you get it perfectly fine, anything above 100 is a good but not perfect match and SZ will pick the best available.

I may add a more fine-grained score setting to 1.4.

**Comment by eleonrk** [comment]
@pannal 
Actually, I didn't enable the SZ agent for the movies, just tv shows.
I'm only using the Addi7ed provider without any bonus score.
In the settings the parameter's label is "Minimum score for TV subtitles to download ".

The thing is, in the example I gave you, SZ downloaded a subtitle of FLEET release from Addic7ed when my episode was AVS.
With scores like this, SZ will grab anything, no matter the release group, quality..

Just for my information, maybe I missed something in the configuration, how could I be missing up movie scores with TV scores?

**Comment by pannal** [comment]
I'm talking about this:

> I recently switched from bramwalet/Subliminal.bundle to Sub-Zero, and back then, the computing score > was relevant (between 55 and 66 for the right subtitles).

That can't be, scores were never that low. Only for movies (which is why I suspected you're remembering movie scores from Subliminal.bundle).

**Comment by pannal** [comment]
Can you set SZ to DEBUG and post your log after refreshing that episode? It should download the subtitle with score 122 (which has a release_group match).

**Comment by eleonrk** [comment]
I switched like 4 days ago so I still have some logs, I'll try to find them.
I was never using Subliminal.bundle for movies.
When my tv episode matched the exact year, title, episode, release group and some more stuffs, I was always getting 66, never more.

Diaoul was saying that in the previous versions of Subliminal the scores were between 0-100.

For example, I found this in my logs of subliminal.bundle:

```
2016-11-05 14:24:40,223 (118c) :  DEBUG (logkit:13) - guessit.matchtree: Final result: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "episodeNumber": 16, 
    [1.00] "container": "mkv", 
    [1.00] "format": "HDTV", 
    [0.76] "series": "The Walking Dead", 
    [0.70] "releaseGroup": "KILLERS", 
    [1.00] "screenSize": "720p", 
    [1.00] "season": 6, 
    [1.00] "type": "episode"
}
2016-11-05 14:24:40,224 (118c) :  DEBUG (logkit:13) - subliminal.video: Size is 3355861632
2016-11-05 14:24:40,236 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEB-DL (WEB-DL) (confidence=1.00)
2016-11-05 14:24:40,237 (2534) :  INFO (logkit:16) - subliminal.subtitle: Computed score 60 with matches set([u'series', u'year', u'episode', u'season'])
2016-11-05 14:24:40,253 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEBRip (WEBrip) (confidence=1.00)
2016-11-05 14:24:40,269 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEBRip (WEBrip) (confidence=1.00)
2016-11-05 14:24:40,270 (2534) :  INFO (logkit:16) - subliminal.subtitle: Computed score 60 with matches set([u'series', u'year', u'episode', u'season'])
2016-11-05 14:24:40,286 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEBRip (WEBrip) (confidence=1.00)
2016-11-05 14:24:40,303 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEBRip (WEBrip) (confidence=1.00)
2016-11-05 14:24:40,305 (2534) :  INFO (logkit:16) - subliminal.subtitle: Computed score 60 with matches set([u'series', u'year', u'episode', u'season'])
2016-11-05 14:24:40,322 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEB-DL (WEB-DL) (confidence=1.00)
2016-11-05 14:24:40,338 (2534) :  DEBUG (logkit:13) - guessit.matcher: Property found: format=WEB-DL (WEB-DL) (confidence=1.00)
2016-11-05 14:24:40,338 (2534) :  INFO (logkit:16) - subliminal.subtitle: Computed score 60 with matches set([u'series', u'year', u'episode', u'season'])
2016-11-05 14:24:40,338 (2534) :  INFO (logkit:16) - subliminal.api: Downloading subtitle <Addic7edSubtitle [en]> with score 66
```

**Comment by eleonrk** [comment]
Ok I'll do that/

**Comment by pannal** [comment]
That's weird. @Diaoul any idea why he was getting subtitles with a score of 60 for `matches set([u'series', u'year', u'episode', u'season'])`? @eleonrk do you remember which version of Subliminal.bundle you had?

**Comment by pannal** [comment]
Oh yeah, I see. You must have used an older version of Subliminal.bundle: https://github.com/Diaoul/subliminal/blob/0.7.5/subliminal/video.py#L91

**Comment by pannal** [comment]
@eleonrk how would SZ grab "just any" subtitle available? It still grabs the best one found. In this case the one with the best matches: `[u'episode', u'series', u'season', u'hearing_impaired', u'year', u'release_group']`

**Comment by eleonrk** [comment]
You are probably right about the old 0.7.5 version.

I set the DEBUG level and refreshed.
https://gist.github.com/eleonrk/5250e52d33482cb7e0664f2843b3daeb

To be more precise:
I've this episode
South Park - S20E07 (720p.HDTV - AVS).mkv

and I've set English and French in the SZ settings.

This morning, on Addic7ed, the subtitles available were :
HD AVS english
Fleet English
Fleet French

HD AVS French was/is still in processing.

My goal is to download the exact release group subtitle, not the best available.
That's why I was hoping playing with the score parameter to adjust my need.

The thing is the 3 of available subtitle were computed with the score 110 or higher.
So it downloaded the right English AVS HD and the French Fleet.

**Comment by eleonrk** [comment]
The fact that the score is higher than 110 is not an issue for me, it's the fact that I cannot go higher than 100 in the settings.

**Comment by pannal** [comment]
OK. 121 is the score you want, by the way, for a good release group match. 126 when including format (WEB-DL/HDTV).

Scores are here: https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/subliminal/video.py#L141

When we update to the new subliminal 2.X versions, though, we'll have to adjust again, massively.

**Comment by eleonrk** [comment]
@pannal  Thank you for you time and information.
