### ISSUE TITLE
Add subtitle modification menu

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#201]
* adjust offset (+XXXms/-XXXms)
* fix FPS issues (convert from 23.9 to 25 for example)
* remove hearing impaired events

any more ideas?

**Comment by Ruvetuve** [comment]
Where will this menu placed? In a playback video, or in the channel menu?

**Comment by pannal** [comment]
Channel menu. I have no power over any other menu.

**Comment by meganugen** [comment]
If it's possible to add a preffered text size (i.e. 12, 24, 36px) and placement then that would be awesome. I don't like the subtitle to be "inside" the letterbox.

**Comment by machadoit** [comment]
I would love these, I was thinking about running a script with some regexes to "remove hearing impaired events", but having this option by default would be great!

**Comment by pannal** [comment]
@meganugen no, that is only adjustable from the client itself

@machadoit great, it'll be implemented after 2.0 is released.

**Comment by pannal** [comment]
Currently implementing automatic hearing impaired cleanup inspired by SubtitleEdit.

**Comment by pannal** [comment]
@machadoit remove hearing impaired has been integrated into 2.0 beta. [You can try it](https://forums.plex.tv/discussion/268339/sub-zero-v2-beta-inquiry/p1) if you'd like to beta test.

**Comment by machadoit** [comment]
Amazing! I will check it out @pannal Thanks

**Comment by spopinski** [comment]
Having the ability to change sub color to yellow would be great

**Comment by pannal** [comment]
@spopinski Interesting idea. Usually that's the client's task though.

**Comment by spopinski** [comment]
@pannal yes, the thing is it's been asked for years but plex never touch it.

**Comment by pannal** [comment]
@spopinski color modification is implemented in 2.0 RC4. Please try :)

**Comment by spopinski** [comment]
Woohoo!! I will report after I try

**Comment by pannal** [comment]
It's currently only implemented as an automatic modification; you set your color code in the preferences and it gets applied to every subtitle downloaded.

I'm still trying to figure out how to realize a manual color mod via the menu. Should I supply a list of colors? Which would that be?
Or some kind of cumbersome nested menu to pick your own color code?

**Comment by spopinski** [comment]
Well Netflix and Hulj only do white and yellow :)

**Comment by pannal** [comment]
I guess I'll do these: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by pannal** [comment]
The CMD colors look well. I'll do the normal and the bright ones.

**Comment by spopinski** [comment]
Well yes please, but with that many colors I guess you should also include the sub window/background? Maybe

**Comment by pannal** [comment]
Background isn't possible with SRT.

**Comment by spopinski** [comment]
Understood

**Comment by pannal** [comment]
Any success with RC4?

**Comment by spopinski** [comment]
DO I input the HEX code, RGB, or what number for yellow?

**Comment by pannal** [comment]
Yellow is #ffff00

**Comment by spopinski** [comment]
Is it only applied to new download?

**Comment by pannal** [comment]
Yes, but you can apply to previous subtitles in the advanced menu: `Apply configured default subtitle mods to all (active) stored subtitles` - it will take some time, though.

**Comment by pannal** [comment]
I'd test it first, though :)

**Comment by spopinski** [comment]
Still not changing color in newly downloaded movie, I also test to refresh one old movie and still came up white.

**Comment by pannal** [comment]
Can you check the subtitle content? It should have font info in every line. 

Are you sure your client supports colored subtitles?

**Comment by spopinski** [comment]
`100:00:02,560 --> 00:00:04,562
<font color="#ffff00">(ROCK MUSIC PLAYING)</font>

200:00:06,000 --> 00:00:12,074
<font color="#ffff00">Advertise your product or brand here
contact www.OpenSubtitles.org today</font>

300:00:24,120 --> 00:00:25,849
<font color="#ffff00">- (lNDISTINCT CHATTERING)
- (STUDENTS WHOOPING)</font>

400:00:52,760 --> 00:00:54,489
<font color="#ffff00">- (TIRES SCREECH)
- CAMPBELLI Whoa!</font>

500:00:55,640 --> 00:00:57,847
<font color="#ffff00">Hey! Buddy, excuse me.
I'm sorry, you're parking in my spot...</font>

600:00:58,000 --> 00:00:59,490
<font color="#ffff00">Senior prank day.</font>

700:01:00,120 --> 00:01:01,201
<font color="#ffff00">Yeah, but it's not a prank.</font>

800:01:01,360 --> 00:01:04,011
<font color="#ffff00">You're just parking it in a`

Tryin the force refresh method, media failed to play in plex web and plex for android

**Comment by pannal** [comment]
Can you remove the modifications using the menu, then attach the subtitle file here, also your log files with submod Debug enabled (preferences)?

**Comment by pannal** [comment]
I'll be back in a couple of hours, pub time

**Comment by spopinski** [comment]
SRT after removing mods:
[https://drive.google.com/file/d/0B_90pJXoQFtkUlZzZktsRU5QVUU/view?usp=sharing](url)

Logs:
[https://drive.google.com/file/d/0B_90pJXoQFtkLTZpeUJHVWVhQW8/view?usp=sharing](url)

**Comment by spopinski** [comment]
Sleep time, diff time zone

**Comment by pannal** [comment]
The SRT you posted has the font color modifications inside. But it somehow really messed up the timeline. Investigating.

**Comment by pannal** [comment]
Wow, you have upgraded from a really old release. Are you storing the subtitles internally or besides the media? For the next log I'll need logging to be set to DEBUG before you try stuff, as well as the modification debug setting (both in SZ preferences).

**Comment by pannal** [comment]
Yep. Found it. Was a stupid bug in RC4. RC5 will have that fixed.

**Comment by pannal** [comment]
All fixed in RC5.

**Comment by pannal** [comment]
You can either set your colors globally in preferences, or in the subtitle modification menu in the channel,

**Comment by spopinski** [comment]
Tried force refresh a movie (GOLD), apply mod from the channel (color yellow)

Results : playback crashed with subtitle on.

Tried to remove mod from srt using the channel

Result : srt in metadata folder still contains color mod.

Link to logs [https://drive.google.com/file/d/0B_90pJXoQFtkZ0tqSXpiT3FIam8/view?usp=sharing](url)

**Comment by pannal** [comment]
I don't see any indication of you requesting a subtitle in those logs. Also I think you still haven't enabled DEBUG in SZ's preferences.

**Comment by spopinski** [comment]
Maybe I missed a step. Will try ahain later

**Comment by spopinski** [comment]
Ticked all the debug checkboxes, try on a new movie (FIST FIGHT)

Results: Indonesian sub works, English sub crashed playback.

Files: [https://drive.google.com/drive/folders/0B_90pJXoQFtkaC1POERXUDJhZlk?usp=sharing](url)

**Comment by pannal** [comment]
The important part is not a checkbox, but the Debug level. 

I'll take a look tomorrow. The setting I'm talking about is in sub zeros channel or agent preferences, not the Plex settings.

**Comment by pannal** [comment]
Did you restart the PMS after upgrading SZ?

**Comment by spopinski** [comment]
Restart pms and restart channel

**Comment by pannal** [comment]
Ok, only one of those is necessary :) 

Again, will have a look at your logs tomorrow. Thank you for debugging with me!

**Comment by spopinski** [comment]
Here is the screenshot for the channel settings [https://drive.google.com/file/d/0B_90pJXoQFtkckZPTXlvTC1SRms/view?usp=sharing](url)


The latest log
[https://drive.google.com/file/d/0B_90pJXoQFtkLXFMZFJQTXFLWjQ/view?usp=sharing](url)

A movie previously failed the playback now played successfully. I removed all modifications from the channel to the particular movie, and re apply only the color mod.

**Comment by pannal** [comment]
Thanks. Are you using the bleeding edge, not RC5? I'm seeing stuff inside the logs that indicates that.

**Comment by spopinski** [comment]
Hmm, I think I use the bleeding edge. Should I replace it?

**Comment by pannal** [comment]
No, you can update to the newest commit - it's called "develop" for a reason :D
I've completely redone the internal subtitle storage yesterday, but had some bugs inside. You should upgrade.

As for the submod:
- First of all I'm seeing buggy lines like: `Processor <MultipleWordReProcessor SE_replace_beginline>: u'-(CAMPBELL GROANS)\\N- ALLI Oh!' -> u'-(CAMPBELI GROANS)\\N- ALLI Oh!'` - it replaces `LL` with `LI`. I'll look into that.

I can't see anything else wrong, though. After upgrading to newest develop, could you try reproducing the unplayable subtitle issue? And if you still get it, send me the modified ones that work and that don't work?

**Comment by pannal** [comment]
OK. That submod fix is also pushed.

**Comment by pannal** [comment]
If you updated in the last 30 minutes, please update again, there was a major whoopsie in the channel menu item details.

**Comment by spopinski** [comment]
Planned to do it later 😀. I'll keep you updated

**Comment by pannal** [comment]
Sure. Latest develop should result in RC6 later today.

**Comment by spopinski** [comment]
With the latest dev it appears to be working, I change the color mod to an already modded srt to yellow, previously showing color=#fff000. 
Now the playback is fine. 

DO you need the logs?

**Comment by pannal** [comment]
Yeah it may be that things broke because the parameters of color changed.

Before the mod signature was: `color(color=#xxxxxx)`, now it's `color(name=color-name)`.
You can just remove the color mod on those items and re-add it. That should fix it.

Also you can make the color mod automatic in the preferences.

**Comment by spopinski** [comment]
I think then I'll just wait for the final release and the mod. Thanks for implementing this!

**Comment by pannal** [comment]
You're welcome. I've also found some new bugs in your recent logs with the OCR fixes. Thanks!

**Comment by spopinski** [comment]
My pleasure. Hit me up if you want more debugging work

**Comment by spopinski** [comment]
Is it possible to add border mod to the sub?

**Comment by pannal** [comment]
Hm no, I can't control anything besides the font color itself.

**Comment by spopinski** [comment]
Got it

**Comment by Ninjouz** [comment]
Hey @pannal, what do you think of this (taken from SubtitleEdit) : 
- Point sync via other subtitle: If you have another subtitle in sync (perhaps in another language - it helps if you can understand it a bit) you can match one of the first lines, match one of the last lines, sync, and then all lines should be in sync.  

Most of the releases nowadays include english SRT, so it should be easy to try and match first lines to deted the offset to apply (and pray that work ie ok with movies, and for tv shows depending on the cut from ads if there is any)

**Comment by pannal** [comment]
@Ninjouz Essentially a good idea.

The problem normally isn't the offset sync, but that people use HDTV subtitles for BluRay releases, or for WEB-DL (different cut times because of commercials = different offsets throughout the video). A common problem is mismatching framerate of the video the subtitle was intended for - although SZ 2.0 handles that pretty well.

I'm not sure how to achieve point sync automatically. Manual point sync via the menu may be an option, but with the very limited menu API Plex gives me, that may be impossible until they change their channel infrastructure.
