### ISSUE TITLE
Change default file permission

### ISSUE THREAD

**Issue by fdbgbgsf** [pannal/Sub-Zero.bundle#203]
Is it possible to set the file and folder permissions of the subtitles? (Like you can in the advanced settings of CouchPotato.)

Current problem: subtitles are created as 755 with SZ (=plex) as owner, which means only the plex user can delete them. When downloading better versions SickRage fails due to not being able to delete the subtitles. Other users in the same group only have read permission.

I had a the reverse problem with CP, SZ couldn't create the subtitles because the folders where 755 with CP as owner, I changed the permissions to be 775 in CP. Since SZ and CP are in the same group they both have write privileges.

Thanks. (and thanks for the great plugin!)

**Comment by pannal** [comment]
Yep, good one.

**Comment by fdbgbgsf** [comment]
Sweet! Thanks.
