### ISSUE TITLE
"This channel is not responding." Error

### ISSUE THREAD

**Issue by HenrySia** [pannal/Sub-Zero.bundle#204]
Looking at the log file (/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log), I see

> 2016-11-22 23:21:22,956 (7f80097fa700) :  CRITICAL (runtime:889) - Exception (most recent call last):
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
>     result = f(**d)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/menu.py", line 45, in fatality
>     config.refresh_permissions_status()
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/config.py", line 69, in refresh_permissions_status
>     self.permissions_ok = self.check_permissions()
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/config.py", line 78, in check_permissions
>     for section in self.sections:
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 107, in <lambda>
>     _getiter_           = lambda x: x.__iter__(),
> AttributeError: 'NoneType' object has no attribute '__iter__'
> 
> 2016-11-22 23:21:22,957 (7f80097fa700) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
> 2016-11-22 23:21:22,957 (7f80097fa700) :  DEBUG (runtime:924) - Response: [500] 1313 bytes

I'm not exactly sure what happened. It was working fine before.

**Comment by pannal** [comment]
Have you tried restarting the PMS? Which SZ version is this?

**Comment by HenrySia** [comment]
Hi @pannal, it says I'm running version 1.4.10.768. I tried restarting plex
> sudo systemctl stop plexmediaserver.service
> sudo systemctl start plexmediaserver.service
It didn't work. I even restarted my ubuntu box and it's still showing the same error.

**Comment by pannal** [comment]
Can you attach the full log file with SZ's log level set to DEBUG, please?

**Comment by pannal** [comment]
Do you by chance have not any library added?

**Comment by HenrySia** [comment]
Logs attached.
[com.plexapp.agents.subzero.logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/609548/com.plexapp.agents.subzero.logs.zip)

I have stuff on my library. Sub-zero was working fine and had been for months. Sub-zero worked great, so I rarely manually go into the channel but last I did a force-refresh on an item was Saturday (Nov 19) and it was still working.

Yesterday, I noticed that some of my items didn't get new subtitles, so I opened the channel and I saw it's broken. Thanks for looking into this, @pannal!

**Comment by pannal** [comment]
I think I've got it, pushing hotfix release. Let's hope @sander1 is still available.

**Comment by HenrySia** [comment]
Aww yiss. Beers incoming! Thank you.

**Comment by pannal** [comment]
If you're on the official channel version, you'll have to wait until it gets updated.

**Comment by pannal** [comment]
It's official now. Is the bug gone?

**Comment by HenrySia** [comment]
Hi @pannal, thanks for checking on this. I'm still not seeing the update. I went to channel, tap "Check for updates" and it says everything is up-to-date.

I then removed the channel and re-install it from the plex store but I got the same version 1.4.10.768.

I'll try again later and will let you know.

**Comment by pannal** [comment]
I've seen other users on 1.4.11 now. Did SZ update?

**Comment by HenrySia** [comment]
@pannal sorry I was on a holiday. I just got back and everything works fine now. Thank you very much!
