### ISSUE TITLE
The Channel is not reponding 

### ISSUE THREAD

**Issue by flixajki** [pannal/Sub-Zero.bundle#207]
I installed latest version ( before i completely removed all one, including database ) 
When i go to browse mode and most of time I receive **This channel is not responding** , if I stick with refreshes eventually i manage to get in. However I can not force refresh on an item as every time i receive not reponding error. 

This if what I found in log 
` ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/1/e843a574f0faba637670d8556140bcfd194610e.bundle/Contents/com.plexapp.agents.subzero

p.s. All my media in on AmazonDrive  trough encfs encryption and that does make performance impact eg longer scaning/loading times. 
`

**Comment by pannal** [comment]
Can you attach a full log in SZ DEBUG mode please?

**Comment by flixajki** [comment]
Bellow are the logs. 
I enabled debug, deleted all existing logs, restarted plex server:
1. Browse all items 
2. Series 
3. Braindead 
4. Channel not responding 

Sometimes I get channel not responding before choosing library. 




[ON_PLEX_RETSRAT_com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/612921/ON_PLEX_RETSRAT_com.plexapp.agents.subzero.log.txt)
[browser_series_braindead_com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/612923/browser_series_braindead_com.plexapp.agents.subzero.log.txt)
[browser_series_braindead_com.plexapp.agents.subzero.log.1.txt](https://github.com/pannal/Sub-Zero.bundle/files/612924/browser_series_braindead_com.plexapp.agents.subzero.log.1.txt)

[NOT_RESPONDING_WHEN_CLICKING_ON_SUBZERO_CHANNELcom.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/612940/NOT_RESPONDING_WHEN_CLICKING_ON_SUBZERO_CHANNELcom.plexapp.agents.subzero.log.txt)

**Comment by pannal** [comment]
Please zip up all of your logs in the subzero log folder. Crucial parts are missing.

**Comment by pannal** [comment]
I also see you still have 1.4.10.768. 1.4.10.769 was merged yesterday and 1.4.11 today.

@dane22 do you know why he doesn't receive the auto update? [He isn't either](https://github.com/pannal/Sub-Zero.bundle/issues/204#issuecomment-262800624).

**Comment by flixajki** [comment]
This is all subzero logs in : 
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs`
http://www.filedropper.com/sublogs (could not upload zip for some reason )
https://puu.sh/stRfZ/0caa583e95.png

If there is another location where logs are kept let me know.

**Comment by pannal** [comment]
And you are using the official channel version, right?

**Comment by pannal** [comment]
In all of those logs there isn't a single error concerning the channel menu. Please disable the recently added missing task (set it to "never"), and the find better subtitles task (the same). Then clear the logs, restart the PMS, and try to get into the Sub-Zero channel menu. Then re-post the logs, please.

**Comment by flixajki** [comment]
Find better subtitles was disabled, did disabled recently added eg set it to never, deleted logs and restarted server, tried to click on each and every menu and never got channel not responding message. 

Then i set back search for missing subtitles every 24h ( 6 weeks ), did the browsing part and it worked then manually triggered search for missing subtitles and got channel not responding error. 

All logs bellow:
[com.plexapp.agents.subzero.log.1.txt](https://github.com/pannal/Sub-Zero.bundle/files/613109/com.plexapp.agents.subzero.log.1.txt)
[com.plexapp.agents.subzero.log.2.txt](https://github.com/pannal/Sub-Zero.bundle/files/613113/com.plexapp.agents.subzero.log.2.txt)
[com.plexapp.agents.subzero.log.3.txt](https://github.com/pannal/Sub-Zero.bundle/files/613114/com.plexapp.agents.subzero.log.3.txt)
[com.plexapp.agents.subzero.log.4.txt](https://github.com/pannal/Sub-Zero.bundle/files/613111/com.plexapp.agents.subzero.log.4.txt)
[com.plexapp.agents.subzero.log.5.txt](https://github.com/pannal/Sub-Zero.bundle/files/613110/com.plexapp.agents.subzero.log.5.txt)
[com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/613112/com.plexapp.agents.subzero.log.txt)

**Comment by pannal** [comment]
You got the channel not responding after triggering the search. After that the menu doesn't work at all anymore? Even after re-entering it?

How many items are considered recent in your setup? 2000?

**Comment by flixajki** [comment]
No the subzero channel works I can access it again, but it will fail when I repeat same procedure 
As for recent I have it at 5000 / atm i have around 10.000 video files in my library.

**Comment by pannal** [comment]
OK, that may explain it. I can try triggering the task differently for one of the next releases, but for now I wouldn't necessarily consider this a bug.

I wouldn't do the 5000 by the way, 2000 is more than enough and normally 500 should be, too. Does it usually take that long for your items to receive subtitles? You should perhaps consider then force-refreshing the full library from the Plex interface once a month and lowering the limit to 500, because your current setup puts a lot of load on your PMS.

**Comment by ukdtom** [comment]
@pannal 

When Auto update is triggered, a request containing info about platform etc. is requested, and logged in the system.bundle log.

So maybe the Repo isn't in sync for all platforms?

Sample req. below for a QNAP x86

`https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=e30440dca8c9caa54XXXXXXX52a0442068e5&os=Linux&osVersion=3.12.6%20%28%231%20SMP%20Tue%20Aug%2023%2001%3A24%3A50%20CST%202016%29&cpu=i386&serverVersion=1.3.0.3059-6277334&systemRevision=6277334`

**Comment by pannal** [comment]
Seems up to date...
Why would it separate the versions depending on platform?

**Comment by ukdtom** [comment]
No idea, but seems like that though, since it's handing over all that info, but guess it maybe has something to do with server version, where it checks for Plex own bundles that might have to match those

**Comment by flixajki** [comment]
Thanks for help @pannal , your plex bundle is the life saver.

**Comment by pannal** [comment]
What now? Did I change anything?
