### ISSUE TITLE
Sub-Zero has started to download subtitles that already exist on my server

### ISSUE THREAD

**Issue by SvenErik1968** [pannal/Sub-Zero.bundle#208]
Norwegian language has 2 different forms, [_bokmål_](https://en.wikipedia.org/wiki/Bokm%C3%A5l) and [_nynorsk_](https://en.wikipedia.org/wiki/Nynorsk). And when I add movies to my server, I use the _bokmål_ language code NB/NOB instead of the inclusive language code NO/NOR to be able to distinguish from nynorsk subtitles (not many of them around, but still).
Sub-Zero is set to download subtitles in Norwegian and to not download if already existing internally or externally, and until recently, it has worked as expected. But recently, it has started to download Norwegian subtitles where there already exists with the NOB language code. Looks like it started around November 20/21.

**Comment by pannal** [comment]
That may be the find better subtitles feature. Which version are you on?

**Comment by SvenErik1968** [comment]
I am currently on version 1.4.11.781.
OK, I will turn off that feature. For movies, I usually hand-pick and re-sync if necessary my subtitles.

**Comment by pannal** [comment]
You could try cheating the ietf codes. Try using no-XX or nb-XX as your subtitle filename language code and refresh the item. SZ should detect it, but I'd have to have a closer look whether that can work or not. 

If you're not interested in automatic better subtitles at all, just set the task execution period to never.

**Comment by pannal** [comment]
Yes it should, I've just had a look at the code. If you use the default settings, SZ will parse the ietf codes correctly. It won't save its own subtitles with ietf codes so your manually added ones should be safe.

**Comment by SvenErik1968** [comment]
I use Matroska files with the subtitles muxed into them, and Matroska only use ISO-639-2 language codes...
But that is OK, I can live with this now that I know why and how to turn it of. :)

**Comment by pannal** [comment]
Ah I misunderstood, I thought it was overwriting your manually downloaded external subs. 

You're wondering why it downloads external subs because you already got internals. Got it.

**Comment by SvenErik1968** [comment]
Yes, I thought it was seeing the subtitles with NB/NOB language codes as not the same as those with NO/NOR.

**Comment by Ruvetuve** [comment]
Subzero Will stay off the manual subs in root of movie when you tell it to automatic find better ones and safe on filesystem in specifiek subdirectory?

**Comment by pannal** [comment]
@Ruvetuve yes, it should.
