### ISSUE TITLE
"Custom Subtitle folder" is being ignored

### ISSUE THREAD

**Issue by Ruvetuve** [pannal/Sub-Zero.bundle#211]
Now the subtitles are being downloaded next to the media item. 

Option Subtitle Folder is enabled
Option Custom Subtitle folder holds: subtitles-subzero

Something iam missing? It always worked, seems like it didn't since the newest version with a re-check on the subtitle quality (seperate process).

**Comment by pannal** [comment]
Yep, I broke it. Will be fixed in next version (or develop-1.4 branch)

**Comment by Ruvetuve** [comment]
Confirmed fix. Thanks man
