### ISSUE TITLE
Computing score for movies with OpenSubtitles are incoherent

### ISSUE THREAD

**Issue by hbfs-misc** [pannal/Sub-Zero.bundle#212]
I've the following release:

Jason Bourne (2016) (Blu-ray 1080p H264 SPARKS).mkv

I'm using SZ (1.4.16.822) with OpenSubtitles configured to grab subtitles with minimum score of 60. But SZ (or more precisely subliminal) seems to grab the wrong subtitle release.
Here are the currently available subtitles releases on OpenSubtitles (the ones corresponding to my release) and the computed score I'm getting for them :
- Jason.Bourne.2016.1080p.BluRay.x264-SPARKS ---> 61
- Jason.Bourne.2016.720p.BluRay.x264-SPARKS ---> 56
- Jason.Bourne.2016.720p.BluRay.x264-SPARKS (HI) ---> **first 63 then 57**

So the downloaded one is Jason.Bourne.2016.720p.BluRay.x264-SPARKS (HI).
I was wondering why the first one wasn't the one with the highest score?
The third one seems to be analyzed twice (first with hash, then without it).

Logs (cut):
https://gist.github.com/hbfs-misc/42d62b456e6e0175accd1e8a7a05eb2e

**Comment by pannal** [comment]
The `Jason.Bourne.2016.720p.BluRay.x264-SPARKS (HI)` subtitle gets 63 because it has a matching hash, which is the highest of scores.

Apparently someone added the hash of the 1080p file to their 720p subtitle on OpenSubtitles. Nothing we can do about that, to be honest.

**Comment by eleonrk** [comment]
Ok, thank you @pannal for the answer.

I was wondering if the possibility to disable the search by hash in the settings is something you thought about for some future release?

**Comment by hbfs-misc** [comment]
Ok, thank you @pannal for your answer!

I was wondering the the possibility to disable the search by hash is something you thought about for the future releases?

**Comment by pannal** [comment]
We could do that, but that doesn't change the fact that this is a user error on the opensubtitles provider side, and this can happen with any meta information posted there. Hash is very valuable, even if it gives your 720p for your 1080p release (which is always the same if it's the same release group).

**Comment by hbfs-misc** [comment]
@pannal  Ok, thank you again.
