### ISSUE TITLE
Sub-zero installed, but it doesn't appear under channels list

### ISSUE THREAD

**Issue by lamaledetta** [pannal/Sub-Zero.bundle#213]
Hello, 
sorry to bother you guys, I have installed subzero in plex (I'm a Synology user).
I can see it under Channels > Installed Channels > More 
but it doesn't show up in channels main page, so I can't configure it.

Moreover there is no disk activity, so I can't say if it is actually working properly.

Thanks in advance and regards,

**Comment by ukdtom** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ

**Comment by lamaledetta** [comment]
Ok then, how can I re-enable channel mode?

**Comment by ukdtom** [comment]
Huh...I pointed you to the FAQ, and first entry has a link in it....

https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#basic-configuration

**Comment by lamaledetta** [comment]
I obviously clicked on the first link. I'm saying I have no chance to enter that config menu.

It says: "Enable Sub-Zero channel.this will disable manual operation, but still allows Sub-Zero to work automatically". How can enable the manual operation again and have this config menu back?

**Comment by ukdtom** [comment]
Heh....Think I understand what you mean now....

Go back to: https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ
I've updated the FAQ

**Comment by lamaledetta** [comment]
Found it. I'm OK with this, but can you confirm there is no way to have the channel back?

**Comment by ukdtom** [comment]
Huh again ;-)

Go to settings/Agent....Look in movies/Plex movies, and click on the little gear icon for Sub-Zero agent....

That should bring up it's settings, where you can make sure, that channel mode is enabled.

If already so, then restart your PMS
