### ISSUE TITLE
 Ignore folders (with "subzero.ignore/.subzero.ignore/.nosz" files in them) is being ignored

### ISSUE THREAD

**Issue by Ruvetuve** [pannal/Sub-Zero.bundle#214]
Last time the custom subfolder for subtitles was ignored (fixed in latest release), now this option is broken:

 Ignore folders (with "subzero.ignore/.subzero.ignore/.nosz" files in them)

I have a TV episode with burned in subtitles and an empty file named ".subzero.ignore". Still the subtitles are being downloaded in the custom subtitle folder.

Please advice. Kind regards

**Comment by pannal** [comment]
May be the same issue (some weird boolean preference handling). If you want to, you can try the current develop-1.4 branch to see if that issue is fixed.

**Comment by Ruvetuve** [comment]
Will try and get back to you.

**Comment by Ruvetuve** [comment]
Works in dev-1.4 indeed. Thanks

2016-12-07 16:10:14,336 (494fc) :  INFO (logkit:16) - Ignoring "DIR\The.Walking.Dead*" because ".subzero.ignore" exists
2016-12-07 16:10:14,336 (494fc) :  DEBUG (logkit:13) - An ignore file exists in either the items or its parent folders

fixed in dev-1.4
