### ISSUE TITLE
ERROR (model:205) and (logger:38)

### ISSUE THREAD

**Issue by flixajki** [pannal/Sub-Zero.bundle#217]
Last version ( downloaded today, I removed all old subzero files .. from databases, cashe etc.. )

>  ERROR (logger:38) - subliminal_patch.patch_subtitle: PySRT-parsing failed: (389, u'\x96Led se topi. \x96Tako je.\n'), trying pysubs2
> 2016-12-15 18:24:32,880 (7fe638c7a700) :  ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/8/8e33d7ba2569dd918fcc80e9196b60eaa2ddfa3.bundle/Contents/com.plexapp.agents.subzero

**Comment by pannal** [comment]
Seems OK, though. If it didn't fail trying pysubs2, it should have worked. Otherwise you can enable SZ DEBUG logging and attach the full log file for me to have a look at.

**Comment by pannal** [comment]
What language is that subtitle in?

**Comment by flixajki** [comment]
slovenian

**Comment by pannal** [comment]
Is the encoding correct? It detected latin-1, I think that's wrong for slovenian.
