### ISSUE TITLE
[REQ] Search for subtitles with bookmarklet

### ISSUE THREAD

**Issue by flixajki** [pannal/Sub-Zero.bundle#218]
Is there a way to trigger subtitle search & refresh with URL command ?
For my user I made simple bookmarklet that calls a php file which triggers URL command (with my token) to ANALyze the video, and I wonder if it would be possible to do the same with sub search.

The key would be just to send URL command with ID parameter.
So instead of:

`http://***/channel//video/subzero/section/contents?previous_item_type=movie&base_title=Sections > Movies > #&title=10 Cloverfield Lane&previous_rating_key=1&display_items=0&rating_key=23409//video/subzero/item/23409?item_title=10 Cloverfield Lane&timeout=30000&randomize=1481823099
`
**New feature URL command**
`http://***/channel//video/subzero/refresh?rating_key=23409
`
and 
`http://***/channel//video/subzero/force?rating_key=23409
`
So users could refresh/force movie with one click.

This is for analyze: http://puu.sh/sQzGF/bbc6fbf214.jpg 

Bookmarklet java that calls analyze.php with video id 

`"javascript:(function(){if(/(^|\.)plex\.tv$/.test(window.location.hostname)||/(^|\.)plex\.yourserver\.net$/.test(window.location.hostname)){window.open('http://webserver/analyze.php?id=' encodeURIComponent(window.location.href.split('%2F').pop()) '&u=' encodeURIComponent(window.location.href),'_self')}else{window.location.href='http://plex.tv'}})()"`

and php is just CURL call ( PUT or GET ) with command + owner token.

**Comment by pannal** [comment]
This is already implemented for the route: `/item/{rating_key}`, so the URL should be `http://***/channel//video/subzero/item/23409` for refreshing and `?force=True` for force-refreshing.

**Comment by flixajki** [comment]
Great, I assume i need add token as well since iam not doing it from same machine

**Comment by flixajki** [comment]
I assume that ?force=true does refresh as well.

**Comment by flixajki** [comment]
It opens in Plex : You must be Lost, this page does not exist 
(with or without token)
URL 
http://myserver.net/web/index.html#!/server/ba6******824//channel//video/subzero/item/23409

**Comment by flixajki** [comment]
Checked in logs and nothing happens. 
If i do it trough channel then i can see 

> 016-12-15 21:47:58,197 (7fe63a5bc700) :  INFO (items:278) - Forced-refreshing item 23409
> 2016-12-15 21:47:59,516 (7fe652ffe700) :  INFO (agentkit:946) - Searching for matches for {'id': '23409', 'guid': 'com.plexapp.agents.themoviedb://333371?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.themoviedb', 'parentID': None}

btw I just notice its forcing only one language can it be set for more ?

**Comment by pannal** [comment]
That message shouldn't be sub zero related. 
For the correct URL you'll have to tinker around, as I'm not at the pc right now.

**Comment by flixajki** [comment]
I tired tons of different ones and could not figure it out.

**Comment by pannal** [comment]
Please try querying the PMS api without going through plexweb, have a look here: https://github.com/pannal/Sub-Zero.bundle/wiki/Advanced-usage

**Comment by flixajki** [comment]
Those queries work.

**Comment by flixajki** [comment]
my bad, this is the correct url  webtoken:32400/video/subzero/item/23409?X-Plex-Token=

**Comment by pannal** [comment]
Yeah I thought so. Not sure why the plexweb queries don't work.

**Comment by flixajki** [comment]
So is there a way to force download for multiple languages ?

**Comment by pannal** [comment]
As I said, it always searches for all configured languages.

**Comment by flixajki** [comment]
Its not shown in logs: 
`2016-12-15 23:06:05,222 (7fe63bfff700) :  INFO (agentkit:946) - Searching for matches for {'id': '25622', 'guid': 'com.plexapp.agents.imdb://tt2084989?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.imdb', 'parentID': None}
`

**Comment by flixajki** [comment]
Btw could you add option that with force refresh if subtitle .en.srt exisit to add .eng.srt and same for other languages.

**Comment by pannal** [comment]
That's another thing. Closing.
