### ISSUE TITLE
Only on demand download

### ISSUE THREAD

**Issue by BHMath** [pannal/Sub-Zero.bundle#220]
Hi,

Thanks for this amazing tool ! 

I can't find anywhere if there is a way to use this add-on as a On-Demand subtitle downloader.

What I'd like to do is to have the plug-in alway started and configure but it does not download automaticaly subtitle bt only if I ask explicitly to do it.

If this feature exists how can I configure it ? Because I don't want to create a .subignore in every folder of my 123 tv shows and so many seasons.
Or would it be posible to create it ?

Thanks ahead !

**Comment by pannal** [comment]
This feature doesn't exist yet, no. But the implementation shouldn't be too hard.

**Comment by pannal** [comment]
Will be fixed in the next release.

**Comment by leram84** [comment]
was this the addition of the new SZ "mode" option? im trying to understand what that does... (agent, channel, or both)

My guess is that channel only would only allow manual subs inside the channel that get stored in the plex media file system, and Agent only would only allow automatic downloading of subs... that get stored in a subzero folder? Is that right? or am i way off?

**Comment by pannal** [comment]
You guessed correctly, sir :) 

The agent is a Metadata agent, which downloads subtitles automatically, the channel is the manual and management part. Both can work alone.

**Comment by pannal** [comment]
Although, I believe this wasn't tested thoroughly by anyone but me,  or it simply works for those who use it.

**Comment by pannal** [comment]
Both use the same configuration, though. If you set it to store subtitles externally, both will honor that setting.

**Comment by leram84** [comment]
ok great! i guess i was confused by the agent only part... like why would anyone want that and not want the ui

**Comment by pannal** [comment]
Because they share their library and don't want others to have the power to mess with ignore lists or something? I don't know. 

Also there's the pin feature to lock down the channel now. I guess the option is just there to be there :D
