### ISSUE TITLE
Subtitles not downloading

### ISSUE THREAD

**Issue by OwsleyJr** [pannal/Sub-Zero.bundle#221]
Hi, Sub-zero has never found any subtitles since it has been installed. Works on my other server but not on my main. Not entirely sure why but would love some help on solving this. Here is the most recent log  
http://pastebin.com/E2nFu5v2

**Comment by pannal** [comment]
This seems like a Windows path issue. Please delete your local guessit version from your local Python installation.

**Comment by pannal** [comment]
[This could help you.](https://forums.plex.tv/discussion/209304/suggestion-debian-packages-and-pythonpath)

**Comment by pannal** [comment]
Please reopen if still relevant
