### ISSUE TITLE
Incorrect srt filename encoding

### ISSUE THREAD

**Issue by AeonLucid** [pannal/Sub-Zero.bundle#223]
Hi,

Sub-Zero has a bug where it downloads an .srt, places it under an incorrect name and then removes the .srt file when `Automatically delete leftover/unused (externally saved) subtitles` is checked.

The media file is called "Hannibal - S01E01 - Apéritif Bluray-1080p.mkv".
Sub-Zero places it under "Hannibal - S01E01 - ApĂŠritif Bluray-1080p.en.srt".

If you need more information, please let me know.

OS: Ubuntu 16.04
PMS: 1.3.3.3148

**Comment by HLFH** [comment]
Yes I confirm there is now some filename encoding issue. I'm no longer able to download TV Shows because the name of TV Shows folder is "Séries" (French translation of "TV Shows"). So, I could get 

> IOError: [Errno 2] No such file or directory: '/srv/http/data/HLFH/files/S\xc4\x82\xc5\xa0ries/Vikings/Season 04/Vikings - S04E16 - Crossings.fr.srt'

**Comment by ukdtom** [comment]
Please state what OS your PMS is running on

**Comment by HLFH** [comment]
OS: ArchLinux
PMS version: Version 1.3.3.3148

**Comment by AeonLucid** [comment]
OS: Ubuntu 16.04
PMS: 1.3.3.3148

**Comment by HLFH** [comment]
EDIT: [SickRage ](https://github.com/SickRage/SickRage) can download TV Shows automatically AND subtitles. Until now, I didn't know that their subtitles feature was working flawlessly.

**Comment by pannal** [comment]
Looking into it.
