### ISSUE TITLE
persian subtitle bug

### ISSUE THREAD

**Issue by imanedr** [pannal/Sub-Zero.bundle#224]
hi
sub-zero have an issue regarding to Persian subtitle.
the main issue is the some specific character (ی) is missing from subtitle file.
for example in movie Zootopia : 
00:00:56,737 --> 00:01:00,737
<font color="#80ff80">زوتوپا</font>
3
00:01:00,920 --> 00:01:06,370
<i>ترس, خانت, شهوت به خون</i>
it actually should be like this : 
00:00:56,737 --> 00:01:00,737
<font color="#80ff80">زوتوپیا</font>

3
00:01:00,920 --> 00:01:06,370
<i>ترس, خیانت, شهوت به خون</i> 
its just like this for every persian subtitle than sub-zero downloading. its seems subzero doing some format conversion that cause this specific character disappear from subtitle file.
im using plex in windows 10
plex ver : 1.3.3.3148
sub-zero ver : Sub-Zero Subtitles (Movies, 1.4.17.836)
at the end thanks for your grate work. and sorry for my poor English.

**Comment by pannal** [comment]
Why did you close this? Has this been resolved?

**Comment by imanedr** [comment]
hi
because i realized the problem is not from sub-zero, is coming from podnapisi.net. seems that website doing some kind of subtitle normalizing that cause this problem.

**Comment by pannal** [comment]
Thank you for reporting back :)
