### ISSUE TITLE
Subtitles not downloading because of site tag

### ISSUE THREAD

**Issue by X-static** [pannal/Sub-Zero.bundle#226]
Hi. I have some subtitles that aren't downloading and I'm almost sure it's because of the tag the torrent site puts on the fine name. As an example, for this file the release group is searched as 'AVS[rartv]' and, once I remove the tag, the subtitle downloads.

Can you exclude this type of patterns from search? If not I'll need to create a bash file to renamed all files on my folders.

Thank you.

**Comment by chopeta** [comment]
Interesting... I could swear I am also getting this error for OS site. It could be the same problem reported by @X-static but at the same time I could also swear that GuessIt would take care of cases like this... or not? Maybe some logs?

**Comment by pannal** [comment]
It should. Please attach logs.

**Comment by X-static** [comment]
I attached the channel log. Tell me if you need other log file.

I also attached the screenshot of the List English Subtitles option for the file I can't get subtitles. On another episode from other show I added into my library this week, that as a similar pattern in the file name, the subtitles was downloaded. So, it may not be the reason I said on the first post. 

Thank you.


![screenshot_20170119-214933](https://cloud.githubusercontent.com/assets/3238301/22127280/37c2e00c-de93-11e6-82f4-0400c23f8664.png)




[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/717887/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
What's your TV series min score set to? Also the log file is truncated, I'll need a bigger one.

Indeed guessit misses on the releaseGroup detection, it detects `AVS[rarbg]`. I guess this behaviour [is fixed in the newest guessit](https://github.com/guessit-io/guessit/blob/develop/guessit/rules/properties/release_group.py#L38). It will be incorporated in SZ 1.5.

**Comment by pannal** [comment]
Closed for now. Should be fixed in 1.5.
