### ISSUE TITLE
[REQ] Having Forced English and English as two separate languages

### ISSUE THREAD

**Issue by julestop** [pannal/Sub-Zero.bundle#230]
Would it be possible to have both the forced and full english subtitles... For example, one of my plex users may want to watch with all subtitles on and I personally only want to watch with forced on.

**Comment by pannal** [comment]
You mean for SZ to download both? Because the file handling already is there (you can add a .forced.srt separately)

**Comment by julestop** [comment]
Yeah, if possible to have SZ download both.
If the movie has forced subs, it'll find the forced ones and the full subs.

**Comment by pannal** [comment]
Yeah that's a good feature.

**Comment by kmlucy** [comment]
This would be fantastic!

**Comment by KBlixt** [comment]
is there anyone working on this feature currently or is there any plans for it?

**Comment by pannal** [comment]
Yep, working on it.

**Comment by pannal** [comment]
To make configuration easier, I'd remove the "Only download foreign/forced" option and add a dropdown instead, with the old option inside and "Also download foreign/forced for all languages"/"Also download foreign/forced for Language X".

Would that be OK?

**Comment by marcel5454** [comment]
any news on this?

**Comment by crafty35a** [comment]
That sounds perfect, @pannal 

Can't wait to see this!

**Comment by pannal** [comment]
Still on track for this, development is slow because I've focused on other things besides SZ in the last weeks (massive development on my daily driver, Plex4Kodi).

**Comment by PieMistake** [comment]
Sorry to ask a daft question, but would this allow me to just download only the forced English subtitles? For me, I'm not interested in any of the other types of subtitle or language.

**Comment by oliverzp** [comment]
I too would love to see this feature!

**Comment by pannal** [comment]
That's been implemented.

**Comment by oliverzp** [comment]
Oh yeah, I discovered afterwards how to use it, forgot to come back and reply here. Great job and thanks for implementing it!
