### ISSUE TITLE
Exception in the update function of agent

### ISSUE THREAD

**Issue by diligiant** [pannal/Sub-Zero.bundle#232]

**Comment by diligiant** [comment]
thank you for fixing #222 but the process still doesn't go through for the same files. Here is a debug log. Let me know if you need anything.

[subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/753160/subzero.txt)

**Comment by pannal** [comment]
Oh that's my fault. Releasing a fix

**Comment by diligiant** [comment]
I guessed ;) thanx
(is this normal for the plex store to be slow to show your new versions ?)

**Comment by pannal** [comment]
Could you please test https://github.com/pannal/Sub-Zero.bundle/archive/master.zip and see if that fixes the issue?

Yes it's normal, they have to manually merge my pull request. After that it's in the channel repo.

**Comment by diligiant** [comment]
I managed before to ride around this problem but this time no) do you know why plex systematically overwrites your plug-in with the version it has at hand although I first deleted the channel properly. Difficult to test… ;(

**Comment by pannal** [comment]
Yes. Unpack the zip file and edit `Contents/Info.plist`, set `PlexPluginDevMode` to `1`.

**Comment by diligiant** [comment]
Let's just say that I'm glad for both the trick and the fix ;)

**Comment by pannal** [comment]
OK so this issue is resolved?

**Comment by diligiant** [comment]
yep
