### ISSUE TITLE
Subtitle history makes Dict huge

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#233]
Stop storing actual Subtitle instances in Dict.

**Comment by ukdtom** [comment]
No idea why you wanted that, but as an alternative, maybe:

`6.1.7 Data storage and caching
It is often useful for developers to be able to store data for use by the plug-in later on. To
assist with this, the framework provides three methods of data storage, enabling the developer
to choose the method most suitable for their requirements.
6.1. Standard API
77Plex Plug-in Framework Documentation, Release 2.1.1
Data
The Data API provides methods for storing and retrieving arbitrary data. Plug-ins are generally
not allowed to access the user’s file system directly, but can use these methods to load and save
files in a single directory assigned by the framework.
The data storage locations are unique for each plug-in, preventing one plug-in from modifying
data stored by another.
Note: The actual location of data files stored by these methods may vary between platforms.
Data.Load(item)
Loads a previously stored binary data item.
Parameters item (str (http://docs.python.org/library/functions.html#str)) –
The name of the data item to load.
Returns The contents of the data item stored on disk.
Return type str
Data.Save(item, data)
Stores binary data as a data item with the given name.
Parameters
• item (str (http://docs.python.org/library/functions.html#str)) – The
name of the data item to store.
• data (str (http://docs.python.org/library/functions.html#str)) – The
binary data to store.
Data.LoadObject(item)
Loads a Python object previously stored as a data item.
Parameters item (str (http://docs.python.org/library/functions.html#str)) –
The name of the data item to load.
Returns The contents of the data item stored on disk.
Return type object
Data.SaveObject(item, obj)
Stores a Python object as a data item with the given name.
Parameters
• item (str (http://docs.python.org/library/functions.html#str)) – The
name of the data item to store.
• data (object (http://docs.python.org/library/functions.html#object))
– The Python object to store.
Data.Exists(item)
Checks for the presence of a data item with the given name
78
Chapter 6. API ReferencePlex Plug-in Framework Documentation, Release 2.1.1
Parameters item (str (http://docs.python.org/library/functions.html#str)) –
The name of the data item to check for.
Returns The existence of the item.
Return type bool
Data.Remove(item)
Removes a previously stored data item with the given name.
Parameters item (str (http://docs.python.org/library/functions.html#str)) –
The name of the data item to remove.`

**Comment by pannal** [comment]
Hm yeah, that's actually quite a good idea. The whole SubtitleHistory storage could be separated from Dict, because it's only used in one place it doesn't need to be "generally available".

The fact that SZ is currently storing the full subtitle content in Dict (of a 100 history items) is actually due to a lazy oversight by myself. Nevertheless, the Data idea is quite good, thank you!
