### ISSUE TITLE
SubZero is considering subtitles as leftover (and removes them) when they are not when "Custom Subtitle folder" is set

### ISSUE THREAD

**Issue by pfoo** [pannal/Sub-Zero.bundle#234]
It seems like every time the scheduler is triggered, I lose every subtitles for every show stored in my "Custom Subtitle folder" excepted the subtitles that were just downloaded by the scheduler itself.
Subtitles files are removed, but plex still tries to read them when trying to play an episode.

Here is an example of SZ downloading subtitles for "The Expanse" : 
> 2017-02-06 23:21:41,730 (7f7f84f9d700) :  INFO (subtitlehelpers:168) - Found subtitle file: /var/lib/plexmediaserver/subs/The.Expanse.S02E01-E02.720p.HDTV.x264-FLEET.en.srt language: en codec: srt format: srt default:  forced: 
2017-02-06 23:21:41,731 (7f7f84f9d700) :  INFO (subtitlehelpers:168) - Found subtitle file: /var/lib/plexmediaserver/subs/The.Expanse.S02E01-E02.720p.HDTV.x264-FLEET.fr.srt language: fr codec: srt format: srt default:  forced: 
2017-02-06 23:21:41,780 (7f7f84f9d700) :  INFO (datakit:131) - Saved the dictionary file

And this is after triggering SZ "autofind" function for "Chance" but removing "The Expanse" subtiltes that were downloaded a few minutes ago : 
[subzero-after-autofind.txt](https://github.com/pannal/Sub-Zero.bundle/files/757989/subzero-after-autofind.txt)

SubZero version : 1.4.19.866
Plex Version : 1.3.4.3285

**Comment by pannal** [comment]
OK, for now you can simply [set the automatic leftover subtitle cleanup to off](https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#subtitles-storage-configuration).

And please refrain from posting big log snippets directly, attach them or add them as code, please.

I'll check on that.

**Comment by pannal** [comment]
Yep, it's a bug. Will be fixed in the upcoming bugfix release.

**Comment by pfoo** [comment]
As far as I can tell, this issue still exists in 1.4.22.908

I just launched a manual refresh for a show, and SZ deleted another one from SZ custom subtitle folder (but the subtitle was still referenced in plex database, causing plex to fail when trying to read the subtitle)

**Comment by pannal** [comment]
Uh, which version are you using?

**Comment by pfoo** [comment]
[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/826168/com.plexapp.agents.subzero.txt)

**Comment by pannal** [comment]
Can you also paste your custom subtitle folder setting please? May it by chance be relative?

**Comment by pfoo** [comment]
Nope, using /var/lib/plexmediaserver/subs/
<subtitles.save.subFolder.Custom>/var/lib/plexmediaserver/subs/</subtitles.save.subFolder.Custom>

**Comment by pannal** [comment]
Ok, thank you. Something is up with my path comparison, then. 

Stay tuned and sorry for the issue.

**Comment by pannal** [comment]
I will check with you before releasing a fix for this, if you want to manually verify it. I'd appreciate that. There are very few users who use this feature, so it isn't really battle tested.

**Comment by pfoo** [comment]
No problem. I can provide more logs if needed as I can reproduce this quite easily now

**Comment by pannal** [comment]
So it finds any existing subtitle besides the one currently in scan and tries to remove it? I see that you have some kind of countermeasure in place by denying the removal, or was that something else I just saw in your log?

**Comment by pannal** [comment]
Ah no, that was it trying to remove something in the media folder, not the custom path.

**Comment by pfoo** [comment]
SZ is actually also trying to remove a text file that is sitting near the mkv file. The whole video folder (/home/pfoo/p2p/) directory is mounted read only which explains the "Removing failed" (and why I'm using the custom subtitle folder option)

In the log provided, I had a (working) subtitle stored in /var/lib/plexmediaserver/subs/The.Expanse.S02E06.720p.HDTV.x264-AVS[PRiME].en.srt (that was the only subtilte in the folder at this time) which got removed when I triggered a refresh for Taken

**Comment by pannal** [comment]
Ok. Those are two different things. One is the wrong removal of stuff inside the custom subtitle folder. 

The other is the attempted cleanup inside the media file's folder itself. When a custom folder is set, would you expect that behavior or should SZ skip any cleanup at all?

**Comment by pfoo** [comment]
I think SZ should only be allowed to touch file created by SZ itself, so in this case, it might be better for SZ to avoid cleaning up the media folder (what if a text subtitle is provided with the media file ?)

**Comment by pannal** [comment]
Yeah that's the ultimate way. The current implementation is pretty stupid and the new subtitle storage implementation will help with that. 

But that's for later. I'll fix your custom folder issue for now and tackle a proper cleanup later.

**Comment by pannal** [comment]
OK, [this should fix your issue](https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip).
Please [see here](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation) on how to do a manual installation.

The problem was, that your custom folder hat a trailing slash. It should be fixed now.

Please report back, thank you!

**Comment by pfoo** [comment]
It seems to be working for now. I'll keep in touch / reopen if anything comes up again
thanks !

**Comment by pfoo** [comment]
Ok, found a probably related thing : every subtitles in the custom subtitle folder are added to every media managed by SZ.

Just updated one episode of a show using SZ channel, every subtitles currently stored in /var/lib/plexmediaserver/subs/ were linked to the episode on plex side.

**Comment by pannal** [comment]
Oh that's about equally bad. Looking into it!

**Comment by pannal** [comment]
Current develop-1.4 has a fix for that. Can you try it out?

**Comment by pfoo** [comment]
Both issues seem to be resolved

**Comment by pannal** [comment]
Awesome!
