### ISSUE TITLE
"Last Runtime" shown as "none"

### ISSUE THREAD

**Issue by JurgendW** [pannal/Sub-Zero.bundle#242]
I am running sub-zero version 1.4.19.866.

In the main menu the item "Search For Missing Subtitles..." shows "Last runtime" always as "none".

It appears to be a cosmetic issue only as all works without any issues. I have attempted to reinstall from the menu, repair permissions as described in the various FAQ's. No effect. I also remember that this used to work correctly a few versions ago.

Let me know what further details you require so I will post them.

**Comment by pannal** [comment]
Yep it's a known bug which will be fixed in the next update. Thank you :)
