### ISSUE TITLE
Erros in log 

### ISSUE THREAD

**Issue by ajkis** [pannal/Sub-Zero.bundle#248]
Latest version sub-zero and plex media server plex pass

> 2017-03-04 21:19:28,524 (7f0070ff9700) :  ERROR (missing_subtitles:67) - Something went wrong when getting the state of item 17887: Traceback (most recent call last):
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/missing_subtitles.py", line 61, in items_get_all_missing_subs
>     external=cast_bool(Prefs["subtitles.scan.external"])
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/missing_subtitles.py", line 14, in item_discover_missing_subs
>     item = get_item(rating_key)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/items.py", line 21, in get_item
>     item_container = Plex["library"].metadata(item_id)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/library/__init__.py", line 9, in metadata
>     response = self.http.get('metadata', rating_key)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 95, in get
>     return self.request('GET', path, params, query, data, **kwargs)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 87, in request
>     response = request.request.send()
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/lib.py", line 31, in send
>     data = HTTP.Request(self.url, headers=self.headers, immediate=True, method=self.method)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
>     method=method,
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
>     req = self._core.networking.http_request(url, *args, **kwargs)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
>     return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
>     self.load()
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
>     f = self._opener.open(req, timeout=self._timeout)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
>     response = self._open(req, data)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
>     '_open', req)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
>     result = func(*args)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
>     raise URLError(err)
> URLError: <urlopen error timed out>

**Comment by pannal** [comment]
Please attach all your SZ logs zipped.

**Comment by ajkis** [comment]
https://drive.google.com/file/d/0B89x0Pnx4k71TUhSd1hody0yRmc/view?usp=sharing

**Comment by pannal** [comment]
Uh that looks bad.

Your PMS doesn't answer any of the API calls as it seems. @ukdtom is this perhaps related to [the other issue](https://github.com/pannal/Sub-Zero.bundle/issues/244)?

@ajkis could you zip up your PMS system log files also? And the rest of the SZ logs, please.

**Comment by ukdtom** [comment]
Don't think so.

@ajkis 
Please try and browse to: 
`http://**IP-Of-PMS**:32400/library/metadata/18063?X-Plex-Token=**INSERT_TOKEN_HERE**`

To find your token, look here:
https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

Then grab the XML from the browser, and upload here as a txt file

/T

**Comment by pannal** [comment]
Please reopen if this still happens; please also comment if you fixed this by yourself.
