### ISSUE TITLE
Version 1.4.22.898 - Channel not responding

### ISSUE THREAD

**Issue by cesalo** [pannal/Sub-Zero.bundle#250]
I just realized subtitles were not being downloaded. Tried to check the settings of the channel and got a "Channel not responding" msg. It seems few people have the same issue as reported in the Plex forum.

**Comment by Royal2000H** [comment]
Experiencing this as well

**Comment by Joost1991** [comment]
I'm having this issue as well. Already reinstalled Sub-Zero, but still not responding.

**Comment by cesalo** [comment]
I had to reinstall the previous version. All good so far. I used the
instructions from the Plex forum.

**Comment by pannal** [comment]
Please [try this](https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip) to see if that fixes the isue.

**Comment by Joost1991** [comment]
Tried the fix but still got the error "The Channel is not responding". Just to be sure, the steps I took:

1. Stop plex service
2. Remove old content from SubZero bundle
3. Upload new content
4. Start plex service

**Comment by pannal** [comment]
Then please attach the logs zipped so I can see what's wrong there :)

**Comment by Joost1991** [comment]
At least the log file gives a clear sign where it went wrong.


[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/821321/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
Good, download again, please.

**Comment by pannal** [comment]
@Joost1991 did DEV 2 fix that?

**Comment by Joost1991** [comment]
I tried it out and it stills produces the error and still with the same error in the logs.

`2017-03-06 15:28:15,167 (7ff806ffd700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/menu.py", line 118, in fatality
    if task.ready_for_display:
AttributeError: 'NoneType' object has no attribute 'ready_for_display'
`

**Comment by pannal** [comment]
That's only a result of the error itself. I'll need the full log again, please, attached.

**Comment by Joost1991** [comment]
[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/821558/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
Ah OK, now we're in different territory. The bug is gone, now your PMS times out answering the metadata request when migrating item 71070. Could you try restarting the PMS again? It may just migrate fine this time.

**Comment by pannal** [comment]
I've uploaded DEV 3, which shouldn't keep the plugin from starting when the migrations fail.

**Comment by Joost1991** [comment]
Currently migrating a lot of data which causes the plugin not to show up yet.

Will update you when this migration is finished.

**Comment by Joost1991** [comment]
Doesn't seem to work. Not sure what its migrating, but after a few minutes it looks like it gets stuck. Because of that it does not show up in Channels.

[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/821725/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
Are you sure it stopped? It could just hang again on the PMS request timeout. No updates to the log after the ones you sent me?

**Comment by Joost1991** [comment]
No I'm not sure, but the logs are not being update anymore. Last update is from 16:59.

**Comment by pannal** [comment]
OK. Please make a backup of your Dict file in the Sub-Zero data folder (`Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.subzero`), then stop your PMS, delete the Dict file and start it again.

You'll most likely lose some stored subtitle info, which is used internally by SZ, but you'll be able to use it again. The storage format has completely changed, so this will only happen once.

**Comment by Joost1991** [comment]
After deleting the Dict file it is working once again running DEV 3.

**Comment by pannal** [comment]
Have you backed up your Dict file? You can try the newest production version and copy back the old Dict file for migration, plus a restart of the PMS.

**Comment by ejmichel** [comment]
the fix two posts above worked.. have a question about this 

You'll most likely lose some stored subtitle info, which is used internally by SZ,

hope this doesnt mean all the subtitles that were already downloaded have to be synched again?

**Comment by pannal** [comment]
No, you won't lose any subtitles. Just SZ loses the info about them so it won't be able to find better ones for those particular files.

Still, read my post above yours, you don't need the fix I've posted, actually it's worse than the current stable version 908.

**Comment by ejmichel** [comment]
thanks i used the latest version.  
i copied the file and then stopped PMS and then deleted DICT and then restarted PMS. 
saw that DICT was recreated
went to channels in PMS
and at first SZ didnt show up but then i did 'check for updates'
and then it showed up ... i still asked it to check for updates and it said it was current version
so then i opened it and its working ... 
at least it was letting me see the menus and search for recent added files (catastrophe s03e02) i didnt check from last night to see if the SRT file is there - the ep was just aired yesterday so it may be a day or so before its available.
