### ISSUE TITLE
Subscene support

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#26]
Considering adding https://github.com/kronenthaler/plex-subscene as a subliminal provider

**Comment by chopeta** [comment]
This would be a very nice addition. I was thinking about it the other day.

**Comment by Roelie** [comment]
Or even better: http://subtitleseeker.com! Support for dutch providers sounds good as well.

Pannal, i scraped subscene before (in PHP), let me know what i can do.

**Comment by zatchmok** [comment]
I agree that adding subscene as option for subtitle seeking would be an awesome feature.

**Comment by pannal** [comment]
Roeli: Thanks for the offer, I'll first try to incorporate kronenthaler's approach as he seems to have a working library.

**Comment by pannal** [comment]
This should be a major feature.

**Comment by thongdong7** [comment]
@pannal please take a look at https://github.com/thongdong7/subfind if you has chance. Let me know what I could help

**Comment by pannal** [comment]
@thongdong7 I'm seeing specific code for movies only, do you cover series also?

**Comment by thongdong7** [comment]
@pannal Currently, only movies is supported. But I could start to implement for the series. Do you have any "series" sample name, so I could use for testing? Thanks.

**Comment by pannal** [comment]
@thongdong7 well, it's not that easy. You can try adding generic queries such as "Boardwalk Empire S01E01", which may result in a list. Support for direct media names such as http://subscene.com/subtitles/release?q=Boardwalk.Empire.S01E01.720p.HDTV.x264-IMMERSE&l= would also be needed. Additionally we'd need some sort of intelligent parsing for the result for the query http://subscene.com/subtitles/title?q=Boardwalk%2bEmpire, so that a matching subtitle could be picked.

That's the hard part of this. Multi-tier querying for several media info Sub-Zero receives.

**Comment by MadzDK** [comment]
No progress with the subscene support ? 
The Kodi subscene add-on can it be modified so it can be used here ?

**Comment by brandurFO** [comment]
Is this still in the pipeline or has it been abandoned?
This would be a great addition to this awesome plugin.

**Comment by pannal** [comment]
This has been abandoned. I've tried properly parsing subscene with the features I need for SZ.
It's too much of a hassle and puts heavy strain on the website itself to get it right.

It will be implemented with the SubtitleSeeker API, they parse subscene as well.

**Comment by pablonchox** [comment]
add tusubtitulo.com and subtitulamos.tv for spanish subs

**Comment by pannal** [comment]
I've taken another shot at SubScene in 2.1. [Please join the SZ beta](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes)!

**Comment by pannal** [comment]
Implemented.
