### ISSUE TITLE
plugin doesnt download any subtitle

### ISSUE THREAD

**Issue by aahmyu** [pannal/Sub-Zero.bundle#262]
Hello, I'm having a problem with using this plugin. I think i have everything configured right but it is not downloading any subtitle. my plex server is installed on ubunto server and have my nas mounted to it. im not sure if i need to set permissions or something.

[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/912428/com.plexapp.agents.subzero.txt)

**Comment by pannal** [comment]
I've answered [your post in the forums already](https://forums.plex.tv/discussion/comment/1418219/#Comment_1418219). Please check your permissions.
