### ISSUE TITLE
[BUG]  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Sub-Zero Subtitles (Movies, 1.4.27.973)', called with guid 'com.plexapp.agents.themoviedb://390054?lang=en' (most recent call last):

### ISSUE THREAD

**Issue by ajkis** [pannal/Sub-Zero.bundle#269]
Version latest ( Plex version, latest plex pass )

> 2017-04-24 13:49:48,881 (7f6feb7fe700) :  INFO (localmedia:165) - Looking for subtitle media in 1 paths with 1 media files.
> 2017-04-24 13:49:48,881 (7f6feb7fe700) :  INFO (localmedia:165) - Paths: /mnt/cloud/movies/Sand Castle (2017)
> 2017-04-24 13:49:48,883 (7f6feb7fe700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Sub-Zero Subtitles (Movies, 1.4.27.973)', called with guid 'com.plexapp.agents.themoviedb://390054?lang=en' (most recent call last):
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
>     agent.update(obj, media, lang, **kwargs)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 238, in update
>     scheduler.signal("updated_metadata", item_id)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/background.py", line 144, in signal
>     status = task.signal(name, *args, **kwargs)
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
>     return apply(f, args, kwargs)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 115, in signal
>     return handler(*args, **kwargs) if handler else None
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
>     return apply(f, args, kwargs)
>   File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 120, in signal_updated_metadata
>     if item_id in self.items_searching_ids:
> TypeError: argument of type 'NoneType' is not iterable
> 
> 2017-04-24 13:49:53,887 (7f6fc09fd700) :  INFO (datakit:131) - Saved the dictionary file

Full logs: https://drive.google.com/drive/folders/0B89x0Pnx4k71VEV6Rm5tZWx5bTQ?usp=sharing

**Comment by pannal** [comment]
Hmm, shouldn't have an effect on your user experience. The error will be fixed, though. Thank you

**Comment by pannal** [comment]
Is fixed in 2.0, which is currently in beta.
