### ISSUE TITLE
Typo on Settings Page

### ISSUE THREAD

**Issue by kanine** [pannal/Sub-Zero.bundle#274]
Search enabled providers **simuntaneously** (multithreading)

Correction: simultaneously

If I knew where to fix such typos I'd be happy to help.

**Comment by pannal** [comment]
Thanks, fixed

**Comment by pannal** [comment]
The preferences are here: https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/DefaultPrefs.json if you want to hunt for more typos 🗡
