### ISSUE TITLE
[Feature Request] Download subtitles only if you don't already have one

### ISSUE THREAD

**Issue by Nottt** [pannal/Sub-Zero.bundle#275]
It would be nice if I could set it not keep downloading subtitles for media files I already have

**Comment by pannal** [comment]
That's precisely what it does if configured correctly. What exactly happens and how is your [scanning configuration](https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#scanning-configuration)?

**Comment by pannal** [comment]
Please reopen if still an issue
