### ISSUE TITLE
Deleted subtitle sticks in PMS

### ISSUE THREAD

**Issue by zin105** [pannal/Sub-Zero.bundle#276]
Let's say Sub-Zero downloads a subtitle and I decide I don't want any subtitle at all, when I remove it from my HDD it sticks in PMS, even when refreshing the movie.

**Comment by pannal** [comment]
It may get redownloaded by SZ when you refresh the movie. You can either put that movie on the ignore list, or disable SZ.

**Comment by zin105** [comment]
It's on ignore and the subtitle is not re-downloading. After removing the subtitle, refreshing the media, then trying to play the video it errors out because obviously the subtitle isn't on the disk anymore.

**Comment by pannal** [comment]
Hm, that's new, never heard of that behaviour. Which client are you testing this with? Does the same happen in Plex Web?

**Comment by zin105** [comment]
Plex Media Player on Windows, Android app and Plex Web.

**Comment by pannal** [comment]
And you delete the subtitle, then refresh the movie, and Plex Web still sees that exact subtitle? Can you get me the XML for that? (PlexWeb > movie > three dots > Get Info > View XML)

**Comment by zin105** [comment]
Exactly. Here's the XML: https://pastebin.com/8HTCmFED

**Comment by pannal** [comment]
Thanks. What's your subtitle storage set to in SZ? Subfolder?

**Comment by zin105** [comment]
Current folder. I updated the pastebin link because I had not deleted the subtitle yet there. The one I deleted is "Suomi".

**Comment by pannal** [comment]
What's the filename of the subtitle file in question?

**Comment by pannal** [comment]
It's weird. Do you have the Local Media Assets agent disabled?

**Comment by zin105** [comment]
[](https://imgur.com/a/ioIO0)

**Comment by zin105** [comment]
Just FIY it was exactly the same problem in 1.4.27.974

**Comment by pannal** [comment]
Oh you're using RC1. Great, more beta testers :)

I might have an idea about that. Let me see.

**Comment by pannal** [comment]
Can you try the bleeding edge? https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip

You'll need to rename the extracted folder to Sub-Zero.bundle.

**Comment by zin105** [comment]
Seems that I have to restart Plex for it to get loaded (yes I renamed it to Sub-Zero.bundle), and I have multiple users streaming atm that I don't wanna interupt. I will get back to you as soon as I can.

**Comment by pannal** [comment]
You can replace the old folder, go to SZ's advanced menu, and hit restart there.

**Comment by zin105** [comment]
I deleted the old folder first (stupid me) so Sub-Zero menu is gone for now.

**Comment by pannal** [comment]
Ah, OK :D I'll wait

**Comment by pannal** [comment]
BTW you don't need to drop physical ignore files wherever you don't want SZ to process. You can just add it to the soft ignore list via the channel menu.

**Comment by zin105** [comment]
Allright thanks, didn't know that.

Anyway the problem persists with the cutting edge release. As I mentioned earlier I had the same problem on 1.4 aswell.

**Comment by pannal** [comment]
Hmm, I was pretty certain that the bleeding edge fixed the issue. Can you do the whole deleting-subtitle-refreshing-item thing again with DEBUG enabled in Sub-Zero's settings, then zip up the logs after that and attach them here?

**Comment by zin105** [comment]
[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/983985/com.plexapp.agents.subzero.log.zip)

There you go. I tried it with the movie City of God around 17:32, it was the swedish subtitle track that I removed. I added a subzero.ignore file before deleting it.

**Comment by pannal** [comment]
Hm, you're somehow not using the newest version. Still looks like RC1.

I'm releasing RC3, please try that.

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/releases/download/2.0.15.1216/Sub-Zero.bundle-2.0.15.1216.zip

**Comment by pannal** [comment]
There's also an option now in the channel menu to find the locally available subtitles without refreshing the item itself.

**Comment by pannal** [comment]
Your log indicates you're using Sub-Zero 2.0.12.1180 DEV

**Comment by zin105** [comment]
You're right, sorry about that. The latest RC3 fixes the problem! Only thing is that I need to manually press Refresh Metadata, afaik usually it's enough just to open the movie. Good enough for me though.

**Comment by pannal** [comment]
As I said, you can go to the item in the channel menu and trigger find local subtitles instead of refreshing it.

**Comment by leelouch** [comment]
Hi, it seems I have the same problem in Sub-Zero 2.5.4.2527
xml info before deleting the SRT is https://pastebin.com/QWZ2K197
xml info after deleting the SRT is https://pastebin.com/2MWmEwrs
any idea please ? 
thanks
