### ISSUE TITLE
add delay between downloads

### ISSUE THREAD

**Issue by opensubtitles** [pannal/Sub-Zero.bundle#277]
Hi

opensubtitles developer here. I saw your script is doing retries on downloads when user doesn't have quota making unnecessary load - I can send download log if needed. Please check:

http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC

specially:
* when downloading subtitles using standard HTTP we added HTTP RESPONSE HEADER: Download-Quota: %d, where %d is number how many subtitles can user still download.

* API Request limit: 40 HTTP requests per 10 seconds per IP address, read here more ​https://forum.opensubtitles.org/viewtopic.php?f=8&t=16072

http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst#Implementingopensubtitles.orgsupport

* I dont see any link to opensubtitles - thats basically all what we got from API users...

please fix it, thanks.

**Comment by pannal** [comment]
I've put links to the used subtitle providers into the README.md.

You might want to head over to the subliminal library, which is what Sub-Zero uses to query OpenSubtitles.

As for the retrying of downloads after quota exceeded: I'll try to fix that in one of the next releases.

**Comment by pannal** [comment]
The current release candidate of Sub-Zero 2.0 will only retry downloading when network exceptions occur.

**Comment by opensubtitles** [comment]
ok great, thanks

**Comment by pannal** [comment]
I will fast track a separate 1.4 release tomorrow with changes to the retry behavior, as 2.0 will take a couple of days to be released. 

Preferably with the user agent change.

**Comment by pannal** [comment]
Implemented.

**Comment by pannal** [comment]
@opensubtitles pinging here for #336
