### ISSUE TITLE
sub-zero does not download subs automatically

### ISSUE THREAD

**Issue by artibo** [pannal/Sub-Zero.bundle#285]
Hello all,

I installed sub-zero and enabled it on the agents tab. Sub-zero works perfectly when I manually search for subtitles by using the sub-zero app that is on my channels directory. However, when I add new content to my library, Sub-zero does not find subtitles automatically. During metadata downloading, I expect sub-zero to download the subs, but it does not. these are my settings; http://imgur.com/a/U6U4X

I enabled log to console but it did not log anything yet. I checked my logs folder, but nothing sub-zero related there. :(

**Comment by pannal** [comment]
Don't log to console, set the log level of SZ to DEBUG, please.

**Comment by artibo** [comment]
I just did, now I am going to download something for logging purposes. After plex scans the new content, I am going to post my logs here :)

**Comment by pannal** [comment]
Great. You can also just refresh a video file from PlexWeb, that will trigger SZ.

**Comment by baglio** [comment]
I also have encountered this issue, not only: in my case, I'm not able to download any subtitle even using the *Auto Scan* feature. The problems started after I've recently update Plex to version 1.5.5.3634 on my Synology NAS. Here's [the log](https://pastebin.com/4EnZJvty) provided by Sub Zero.

**Comment by artibo** [comment]
I solved my issue 10 minutes ago, going to post what I did in an hour. Since you have a similar issue maYbe you can try what I did. I deleted sub-zero from the plugins folder manually. Restarted my machine. Redownloaded subzero and it worked. I don't know how and why but it now works. :)

**Comment by baglio** [comment]
Thanks, @artibo , I'll give it a try.

**Comment by baglio** [comment]
Nope. I've uninstalled Sub Zero by removing the plugin .bundel file, restarted my NAS, re-installed Sub Zero but nothing has changed.

**Comment by pannal** [comment]
Are you both using the manual installation method, or do you install via the channel repository?

@baglio there is nothing in that log. Please set the logging of Sub-Zero to DEBUG, refresh an item in your particular library, zip all your SZ logs, and attach them here. (just drop the zip in this text field or click "selecting them".

**Comment by pannal** [comment]
@artibo it may well be that you didn't have any issue at all. The default TV series score it set in a way that you get subtitles for new releases fast enough, but with a guaranteed level of quality. It can just be that the file(s) you were looking at didn't have well-enough scoring subtitles at the time of adding and that the Sub-Zero background scheduler simply picked them up later that day.

**Comment by artibo** [comment]
@pannal yeah maybe, I am happy that now it works without a flaw. Thanks for the replies :). @baglio I hope you can solve this issue asap. :)

**Comment by baglio** [comment]
Thank you for your support. Here are Sub-Zero logs after refreshing an item with missing subs.

I should add that after my previous comment on this issue I've completely removed my Plex installation from my Synology NAS, including the Shared Folder in which 'Application Support' is stored. Then I've re-installed Plex from the Synology official repo and then manually updated it to the latest version.  
After that I've installed and configured Sub-Zero, which is ordered as first agent in my *shows* agent list.

Unfortunately I'm still not able to download any subtitle. Also, even in my previous installation, the plugin was installed **non manually**. 





[szlogs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1022210/szlogs.zip)

**Comment by pannal** [comment]
Yes @baglio, you've got a different issue. Your files have very few info in their names. The default score for TV shows to match good subtitles against is 116. Especially the format (HDTV, WEB-DL, BluRay) or the release group (you know) is crucial to finding good subtitles for your media.

If you want to take a chance of getting subtitles, but they may be out of sync: set the TV minimum score to 110 or lower (I'd start with 110). [More info on scores](http://v.ht/szscores) (Look for the v1 values).

**Comment by pannal** [comment]
It will get better with version 2.0, which is due soon. It'll detect most of the data (except for format and release group) by itself.

**Comment by baglio** [comment]
Thank you @pannal , I can see why mantaining the *scene* details in the filename is important to get the correct subs. Now, setting the score to 110 did the trick. My media storage/organization is handled by Sonarr, I should ask to the community if there's a way to keep both *scene* and *quality* in the filename.

It's curious, though, how this problem never occured before. Did Sub-Zero raise the quality standard in the latest release?

**Comment by pannal** [comment]
Yes, in March. The TV score was raised from 110 to 116.

**Comment by pannal** [comment]
Closing, thank you for reporting!

**Comment by pannal** [comment]
Ah, and look in the advanced settings of Sonarr. You can add the release group and/or format to the renamed files.

**Comment by pannal** [comment]
{Quality.Full} and {Release_Group}

**Comment by pannal** [comment]
This is a pretty good format: `{Series.CleanTitle}.S{season:00}E{episode:00}.[{Quality.Full}]-{Release_Group}`, you can remove the dots if you want.

**Comment by pannal** [comment]
I'm currently using {Original Title}, though as the only variable. Doesn't change the release name at all.

**Comment by ukdtom** [comment]
Thus getting incorrect subs ;-)

**Comment by pannal** [comment]
Nah, as long as you keep the release group and/or the format in the filename and not totally mess up the order, you'll be fine.

**Comment by baglio** [comment]
For now I'm happy with my current settings, but sure I'm going to edit them as soon as I encounter any additional problem. I don't know if this is the right place to talk about this, but I'm a *translator* for an italian subs community. Is there any chance to add it to Sub-Zero?

Thanks again.

**Comment by pannal** [comment]
We can talk about that in another issue, or join us on https://szslack.fragstore.net
