### ISSUE TITLE
name-recognition somewhat weird

### ISSUE THREAD

**Issue by iham** [pannal/Sub-Zero.bundle#286]
my movie library is organized using subfolders for movies with multiple parts like star wars, star trek, thor, and so on.

movies -> Avengers -> 01 - The Avengers (2012).mkv
this naming is not recognized and i needed to rename it to:
movies -> Avengers -> Avengers 1 - The Avengers (2012).mkv

in order to keep my sorting done right (just for readability on the file system) and get the title recognized correct, so the subtitle gets downloaded.

**Comment by pannal** [comment]
I'd need debug logs on that, but I'm guessing guessit gets confused by the leading numbers. That file naming scheme is *very* odd, though. It's hard to be told apart from Episode/Season pack parsing.

May be fixed with 2.0 and the new guessit version. Calling it a wontfix for now, though.
