### ISSUE TITLE
IETF as ISO 639-1 (pt-BR)

### ISSUE THREAD

**Issue by brenosabino** [pannal/Sub-Zero.bundle#287]
The option "Treat IETF language tags as ISO 639-1 (e.g. pt-BR = pt)" work as expected but only after i manually refresh metada of the movie, before that it shows up as unknown or as duplicate (unkown and portuguese).
Is there any workaround for that?

**Comment by pannal** [comment]
Not sure, try moving the position of Sub-Zero before or after Local Media in the agents list, to see if that fixes the issue.

**Comment by brenosabino** [comment]
Manually changing the Local Media agent fixed it for me, used this fix:
https://github.com/plexinc-agents/LocalMedia.bundle/pull/58
File was in : /usr/lib/plexmediaserver/Resources/Plug-ins-4613ce077/LocalMedia.bundle/Contents/Code/subtitlehelpers.py

**Comment by pannal** [comment]
OK. We'll have to wait for Plex to support IETF language tags. Nothing I can do plugin-wise.

Thank you for reporting the workaround!

**Comment by chopeta** [comment]
After installing and enabling SZ is very recommended you do a full refresh of your libraries. You can backup your previous subs if you want.

That would make sure you have the bests subs available today and there will be no Unknown subs and no LocalMedia hack required (which you can probably you loose after a PMS update). 

If your library is very big considering going VIP on OS to higher your download limits.

**Comment by brenosabino** [comment]
@chopeta That would work but after adding new files the problem would return, at least for me.

**Comment by pannal** [comment]
Was that test done with 2.0 as well?

**Comment by chopeta** [comment]
@brenosabino I don't have that problem. New subs are always displayed as "Portuguese" for me.
