### ISSUE TITLE
Legendas.tv not automatically downloading

### ISSUE THREAD

**Issue by brenosabino** [pannal/Sub-Zero.bundle#289]
Using the latest develop-2.0 build (2.0.20.1341 DEV) with opensubtitles disabled, legendas.tv enabled and manually refreshing metadata no portuguese subtitles are downloaded. But manually selecting a subtitle in the Sub-Zero channel's "Actions for Portuguese Subtitle" works fine.

**Comment by pannal** [comment]
Well is the score of those subtitles which you can manually select higher than the default configured minimum TV score? If not, that's intended behaviour.

**Comment by pannal** [comment]
[Read up on scores](http://v.ht/szscores) to understand, why. Look for the v2 scores.

**Comment by brenosabino** [comment]
Minimum score for movies it set to 60. Subtitle score as 97 (matches format title year and imdb_id)

**Comment by pannal** [comment]
Ah we're talking movies, OK. Then I'll need your logs. Please use the advanced menu -> get my logs feature and attach the zip file here (don't get annoyed by the disappearing popup, the link is also in the title bar).

**Comment by brenosabino** [comment]
I enabled debug so theres lots of stuff but i tried to filter to only the time i refreshed metadata and manually downloaded.

https://pastebin.com/j5a6TPsJ

**Comment by pannal** [comment]
Yeah most likely. You don't need that anymore, set it to prefer non-HI and use my new automatic hearing impaired modification.

That'll be a good way to debug that, as well :D

**Comment by pannal** [comment]
BTW you're welcome to join the beta team on slack (https://szslack.fragstore.net)

**Comment by pannal** [comment]
Oh wait I just got what you told me. The setting doesn't work correctly with legendas, let me check.

**Comment by pannal** [comment]
OK, should work now, please try 2.0.20.1355 DEV

**Comment by pannal** [comment]
Good catch, mate!
