### ISSUE TITLE
Converting to other formats

### ISSUE THREAD

**Issue by ignaszewski** [pannal/Sub-Zero.bundle#292]
Since srt is not supported by chromecast (plex is transcoding video) it will be good to have vtt convertion made by subzero on the fly.

Right now I have it done it by node script in cronetab, but it will be much better if sub zero will do it.

**Comment by pannal** [comment]
Yep, WebVTT is nearly the same as SRT. I'll write a converter for it and add an option. Will be implemented after 2.0 hits the public.

**Comment by pannal** [comment]
Actually. @ignaszewski, please give me some insight about your setup.

You use Plex as the media organizer, then play the actual video files via chromecast? Using a Plex client (which can burn in the SRT) is no option for you?

**Comment by ignaszewski** [comment]
My setup.

PMS: on Rasperry PI3
Watching on Chromecast: thrue www or mobile app

When I use VTT - no transcoding is needed (so I can watch easly fullHD). 
With SRT transcoding is necessary and fullHD films are lagged.

BTW thx for fast answer and implementing that future.

**Comment by pannal** [comment]
Great. I've just had a hunch about how easy the implementation would be.

Care to try it out? You'd have to switch to manual/dev installation mode and install the current develop-2.0 branch. There's a new setting called `Subtitle formats to save`.

**Comment by ukdtom** [comment]
Heh, I should have seen that coming :)

**Comment by ignaszewski** [comment]
It seems to work :) thx

**Comment by pannal** [comment]
Awesome!
