### ISSUE TITLE
Problem with Serbian subtitles

### ISSUE THREAD

**Issue by viking1304** [pannal/Sub-Zero.bundle#294]
Serbian language allow use of both Latin and Cyrillic alphabets. Latin subtitles use CP1250 and Cyrillic ones use CP1251. I am aware that this might be something completely new for you, since this is very rare situation.

Addic7ed and Podnapisi use opposite logic which one is default. For Podnapisi sr is Cyrillic and sr-latn is Latin. For Addic7ed default one is Latin and for Cyrillic you need to add Cyrillic as parameter.

To make things worse, there is only one 639-1 code for Serbian language sr.

About 90% of available Serbain subtitles are in Latin alphabet.

Logs clearly shows that SubZero tries to fetch Cyrillic subtitles from podnapisi sL=sr.

Maybe I could try to add sr-latn in additional subtitle language field, but I am not sure what I will get as a result.

**Comment by pannal** [comment]
Currently SZ tries decoding a serbian subtitle with 'iso-8859-5' or 'windows-1251' (in-order).

What encoding would you like to have added to that list?

**Comment by pannal** [comment]
['iso-8859-5', 'iso-8859-2', 'windows-1250', 'windows-1251'] should be better than the current implementation.

**Comment by pannal** [comment]
The current develop-2.0 branch has the changes implemented. Care to try it out?

**Comment by pannal** [comment]
BTW did you actually see errors in the log? Like couldn't decode and stuff?

**Comment by viking1304** [comment]
That's indeed looks good, but encoding of subtitles is not my problem. Maybe I wasn't clear enough.

There is a problem with the way how most sites handles searching for Serbian subtitles. There is usually separate search for Serbian Latin and Serbian Cyrillic subtitles. You can't get both with one search.

In order to get Serbian Latin subtitles from podnapisi.net you need to send sL=**sr-latn** as parameter to search. If you send sL=**sr** you will get only Serbian Cyrillic subtitles.

Some other sites, use opposite logic. Titlovi.com for example use **srpski** for Latin and **cirilica** for Cyrillic.

I hope I was more clear now.

btw. I am on 2.0.20.1364

**Comment by pannal** [comment]
Ah. So you need SZ to search for a different language tag? You *want* serbian latin?

**Comment by pannal** [comment]
Care to join our slack? Then we don't need to discuss this here. https://szslack.fragstore.net
