### ISSUE TITLE
Not downloading subs / sub-zero not showing in logs

### ISSUE THREAD

**Issue by ministryofsillywalks** [pannal/Sub-Zero.bundle#297]
I'm probably doing something fundamentally wrong.
I have Sub-Zero installed on my server, have it enabled in the Agents, have the right Agents selected.
I can access Sub-Zero from the channels and from there I can trigger a refresh of a file.
This refresh happens and is shown in Sub-Zero and in Plex.
However no subtitles are being downloaded.

So I go ahead and enable debug logging, do another refresh and grab the logs.
However in the log file from Plex there is no trace of Sub-Zero.
It goes from:
com.plexapp.agens.plexthememusic.log
to
com.plexapp.agents.themoviedb.log
and there is no
com.plexapp.agents.subzero.log

What am I doing wrong?

**Comment by pannal** [comment]
Are the permissions of your Logs folder correct? Also which version of SZ are you using?
And: Which debug logging did you enable? The `log_level=DEBUG` in SZ's preferences?

**Comment by ministryofsillywalks** [comment]
The permissions of the folder should be correct, as other logs are being written. (I'm on windows btw)
Version: Sub-Zero 1.4.27.980 (the one from the plex store)
In the Sub-Zero settings:
How verbose should the logging be? DEBUG (I hope thats the correct place to set the logging)

**Comment by pannal** [comment]
What the heck, I'm somewhat lost here.

**Comment by ministryofsillywalks** [comment]
Thanks! me too!

**Comment by pannal** [comment]
Which server version?

**Comment by ministryofsillywalks** [comment]
Latest stable: Version 1.5.5.3634

**Comment by ministryofsillywalks** [comment]
Will uninstall Sub-Zero and manually install the 2.0 beta just to see if it makes a difference...

**Comment by pannal** [comment]
Be sure to use RC10.1, not develop, it's unstable.

**Comment by ministryofsillywalks** [comment]
2.0.23.1464 RC10.1

**Comment by ministryofsillywalks** [comment]
Ok installed the beta however its not showing up in my channels...
When I go to settings and select installed plugins it shows however I can't access its settings or launch it...

**Comment by pannal** [comment]
And you did restart the PMS?

**Comment by pannal** [comment]
Did you delete any leftovers of Sub-Zero.bundle?

**Comment by ministryofsillywalks** [comment]
Yeah I deleted everything, but im reinstalling the beta once again now. (hadn't deleted the preferences file)

**Comment by pannal** [comment]
Also delete the Data directory of SZ. just to be sure: `Library/Application Support/Plex Media\ Server/Plug-in Support/Data/com.plexapp.agents.subzero`

**Comment by ministryofsillywalks** [comment]
yeah I deleted that aswell this time and now its showing. will check if subtitles download now...

**Comment by ministryofsillywalks** [comment]
Ok still  no subs being downloaded here come the logs (only from the advanced menu of the plugin not from plex itself...)
Plugin:
https://pastebin.com/8AXzeJq9
Server:
https://pastebin.com/QLT7Uhdc (had to cut this one short as it exceeded the max filesize oO)

**Comment by pannal** [comment]
The log is there: `C:\Users\david\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.agents.subzero.log` (at least that's what the Log tells me)

**Comment by ministryofsillywalks** [comment]
Ok yeah there it is.
I just triggered a refresh of my library and it seems to be loading subtitles now.

**Comment by ministryofsillywalks** [comment]
Heres the log
https://pastebin.com/mLZ4wDas
Had to cut it short again due to size limitations...

**Comment by pannal** [comment]
Yes, but not for everything. (Some of) your media files don't have any format info (WEB-DL, HDTV, BluRay) in them (such as `Archer - S07E03 - Deadly Prep.mkv`). The default score for TV series is 337, which implies it found at least a matching format or (341 with matching release_group). 

Without format info, it can't be guaranteed that you'll get proper subtitles because of the framerate differences.

For now you can lower the TV score to 330, but in the long term I strongly advise to keep more meta info in your file names. Format and ReleaseGroup are the only data items that can't be guessed automatically, but they're the most important ones for finding sync subtitles.

**Comment by ministryofsillywalks** [comment]
Yeah newer stuff is keeping the format it's just some older stuff where I left it out.
Lowered the rating though and now its grabbing subtitles!

**Comment by pannal** [comment]
Yep, but sadly with a high chance of them being async.

**Comment by ministryofsillywalks** [comment]
Most of my older stuff was subbed already so I'm not too worried. The new stuff will def. keep the formats.
Thanks a lot!!!

**Comment by pannal** [comment]
Ah BTW, feel free to join our slack: https://szslack.fragstore.net
