### ISSUE TITLE
"Channel not responding error" when trying to open history

### ISSUE THREAD

**Issue by Darkside-** [pannal/Sub-Zero.bundle#299]
I'm getting a "This channel is not responding." error when attempting to load the history page in subzero.

The log file reveals the following error:

2017-06-03 10:08:02,134 (1b68) :  CRITICAL (core:574) - Exception (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4b377d295\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
  File "R:\Plex\plexmediaserver\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\interface\menu.py", line 520, in HistoryMenu
    key=Callback(ItemDetailsMenu, title=item.title, item_title=item.item_title,
AttributeError: 'str' object has no attribute 'item_title

**Comment by Darkside-** [comment]
1.4.27.980

**Comment by pannal** [comment]
OK. I'll not try fixing this in 1.4, as 2.0 is due for release.

Please stop your PMS and delete `Application Support/Plex Media Server/Plug-In Support/Data/com.plexapp.agents.subzero/DataItems/subtitle_history`, then start your PMS again.

**Comment by Darkside-** [comment]
Hmm, I don't appear to have that folder available. Maybe that's the problem.

![image](https://cloud.githubusercontent.com/assets/89964/26765366/525782de-4940-11e7-9333-0901441b52c7.png)

**Comment by pannal** [comment]
Hmm. Can you try reinstalling SZ via the plex channel repository? The folder has to be there, normally.

**Comment by Darkside-** [comment]
I've uninstalled/reinstalled several times and that folder still isn't present.

**Comment by pannal** [comment]
Oh. Can you tell me where you looked instead? May be good for the wiki

**Comment by ukdtom** [comment]
Considering the datetime stamps in the screenshot, OP most likely redirected his Plug-in Support folder to another location, and forgot about it ;-)

**Comment by pannal** [comment]
OK :D
