### ISSUE TITLE
Black list subtitle file

### ISSUE THREAD

**Issue by lzinga** [pannal/Sub-Zero.bundle#300]
So for the Fear the Walking Dead the subtitles are completely off from the show. I have tried to force refresh subtitle but it constantly downloads the same file, there should be a way to black list a subtitle. Then it just keeps looking for one until it gets one that isn't on black list.

**Comment by vBm** [comment]
More than once i've got busted, oos, computer translated subs from OS.org as part of "Find better subtitles".

I'd expand this option into "Ignore list of providers when searching for better subs" or simply "Only get better subs from XXX"

**Comment by pannal** [comment]
Which SZ version are you guys using?

**Comment by vBm** [comment]
I'm on 2.0.24.1503 -> d5253f130c9bb657bb64064232b77b0b84516790

**Comment by pannal** [comment]
OK. The solution for now is to disable `Scheduler: Overwrite manually selected subtitles when better found` and select them manually when it happens.

I'll implement something to mitigate this issue after 2.0 final hits.

**Comment by pannal** [comment]
Will come with the next 2.0 release.
