### ISSUE TITLE
ignore list - how does it work?

### ISSUE THREAD

**Issue by jeff15110168** [pannal/Sub-Zero.bundle#301]
Hi there, i added a few japanese anime movies to my ignore list as they had hardcoded english subs in them already. I was wondering how do i trigger to erase the EXT subtitle files in them so that they dont show up for any of my plex users - otherwise it default turns them on and shows two overlaying subtitles which isn't ideal.

Do i need to add the "subzero.ignore" blank file to each of the folders for the external subtitles to be actually removed?

Thank you in advance for such an incredible plugin!

**Comment by pannal** [comment]
The ignore list can either be managed from the channel menu, per-item, per-series or per-library.
The hard ignore works by dropping subzero.ignore files wherever you want (dropping it inside a library will instruct SZ to ignore the whole library).

That does not affect the already existing SRT files and those ignored items will be completely be exempted from any handling SZ does. The ignore functionality is just for new SRTs.

**Comment by jeff15110168** [comment]
hmm okay, that makes sense. i guess the issue then is, if import files subzero will automatically add subtitles quicker than i can add them to ignore list.

Regardless, how would i go about removing EXT subtitles from such files manually (they are also on the ignore list so that future scrubs wont add subtitles)?

Thank you Pannal!

**Comment by pannal** [comment]
I don't fully understand your question. To remove external subtitles you'll have to delete them (and possibly refresh the item(s) afterwards).
If you want certain movies, series or libraries without subtitles added by SZ, use the ignore list and organize your libraries accordingly.

You might want to add a separate library where the full library is on SZs ignore list, for all your non-subtitle items.

**Comment by jeff15110168** [comment]
Sorry for being unclear - my question is how do i go about deleting those said external subtitles (where do i delete them from?). I don't know where they reside physically, but i understand i can go into channels and refresh after i have deleted/removed them.

**Comment by pannal** [comment]
Ah, are you using Metadata as storage in Sub-Zero? That's a whole different story then and I'd advise your to see whether the Plex Wiki helps you with that, or post on the Plex forums.

If you use SZ in default configuration, the SRT files will be saved alongside the actual media files on disk.

**Comment by jeff15110168** [comment]
I think I am using metadata storage. Would you recommend changing back to storage alongside media files? I thought to be cleaner and faster, integrating into metadata would be a good option :)

On Jun 27, 2017, at 10:58 AM, pannal <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, are you using Metadata as storage in Sub-Zero? That's a whole different story then and I'd advise your to see whether the Plex Wiki helps you with that, or post on the Plex forums.

If you use SZ in default configuration, the SRT files will be saved alongside the actual media files on disk.

**Comment by pannal** [comment]
I always suggest using the external storage option in SZ (that's why it's the default). You see now why.
Plex has a complex data structure when it comes to Metadata. You can find all your metadata info in the plex app data folder, but actually finding specific items in there is hard to do.

It might be a tad cleaner, but that's why the subfolder option exists, which puts all subtitles into a seperate folder, or even into a global subtitle folder (not so much recommended).

**Comment by pannal** [comment]
If you want to go back to external only, you can delete existing SRT files in the `Plex Media Server/Application Support` folder recursively by searching for `*.srt`.

**Comment by jeff15110168** [comment]
hmm, i looked into %LOCALAPPDATA%\Plex Media Server\ and searched for *.srt and it didn't show up with anything.

**Comment by pannal** [comment]
I think there's another folder like this on Windows. The Plex Wiki should know that.

**Comment by ukdtom** [comment]
Try WebTools.

**Comment by jeff15110168** [comment]
@ukdtom wow amazing, didn't know webtools had a built in subtitle manager. this is super useful for getting rid of subtitles on a case-by-case basis.

@pannal with this built in subtitle manager, is there any reason to prefer to use storing subtitles next to the media files versus being built into plex?

**Comment by pannal** [comment]
Not necessarily, if you don't need the additional freedom you have when managing external subtitle files, or not use your media on any other player than a Plex-based one.

**Comment by ukdtom** [comment]
Also not related to Sub-Zero ( Sorry @pannal  ;-) )

But to export a list of items, that might need a touch, lookup [ExportTools](https://github.com/ukdtom/ExportTools.bundle/wiki)

**Comment by ukdtom** [comment]
Sadly though, the dev of that did not make a fancy wiki as Sub-Zero has :-1:

**Comment by jeff15110168** [comment]
thanks @ukdtom and @pannal for all the help. I did install export tools and use it to correct those pesky unknown audio language files. Now only if i could have a tool that would automatically change the language of unknown files to english, except for the anime torrents...

**Comment by pannal** [comment]
Closing!
