### ISSUE TITLE
Matched by Hash, but incorrect subtitle is downloaded (OpenSubtitles)

### ISSUE THREAD

**Issue by kohanyirobert** [pannal/Sub-Zero.bundle#303]
Summary: wrong subtitle is downloaded for an episode even though SZ reports that the match is based on hash.

I've noticed that SZ downloaded incorrect subs for an episode. I then went to SZ's Channel and tried to use _Actions for Hungarian subtitle_, then _List Hungarian subtitles_, then _Search for Hungarian subtitles (BluRay by demand)_. It then listed a few subtitles the top match being this

```
Current: opensubtitles, score: 360
Release:  mr.robot.s01e01.720p.bluray.x264-demand, Matches: hash, hearing_impaired
```

I picked this, however the subtitle didn't match. I went to check the logs after this. [Here are my logs](https://pastebin.com/raw/afwCktLq). I can see that SZ calculates this hash for OpenSubtitles.org: _a67fbdf9a1b23499_. I used this in OpenSubtitles.org's _very advanced search_ in my browser and I've found a subtitle which matches the episode.

I've dug in the logs a bit more and I can see SZ downloading the correct subtitle downloaded by SZ.

```
2017-07-02 16:35:53,204 (7fd9abfff700) :  DEBUG (scheduler:169) - Dispatching single task: ('DownloadSubtitleForItem',), {'subtitle': <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/6444977/sid-nqP92DtwhQpfZ-pU4noMrDD9v,2/mr-robot-eps1-0-hellofriend-mov-hu' [hu:None]>, 'rating_key': u'412'}
```

This sub is indeed matches the episode, unfortunately however _another sub is placed beside the video file_. Please see the attached ZIP ([subs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1117949/subs.zip))

- _Incorrect - mr.robot.s01e01.720p.bluray.x264-demand.hu.srt_ - this is the file that'll end up beside the video file.
- _Correct - mr.robot.s01e01.720p.bluray.x264-demand.srt_ - I've downloaded this manually, this is correct. SZ reported downloaded the same in the logs.

I'm using the latest release (Sub-Zero.bundle-2.0.24.1558). I've installed the plugin by deleting my old bundle.

Why is this happening?

Some more info about my settings:
 - _I keep the exact (release-) filename of my media files_ is _checked_. (I've tried re-downloading the subtitles while unchecked, but it didn't have any influence.)
 - _Scan: which external subtitles should be picked up?_ is set to _loose: filename contains media filename_.

**Comment by pannal** [comment]
That's weird. Do you have other subtitle agents enabled by chance? Like the original OpenSubtitles agent?

Could you set the download location for subtitles to the subfolder "subs" in SZ's settings and re-download the subtitle using the channel menu? Does that download the same bad subtitle?

**Comment by kohanyirobert** [comment]
> Do you have other subtitle agents enabled by chance? Like the original OpenSubtitles agent?

Nah. Here's my config.

### Shows > TheTVDB Scanner
![image](https://user-images.githubusercontent.com/1104829/27839412-510bf2ca-60f1-11e7-9e7e-40bb57ffc4e4.png)

### Shows > The Moive Database Scanner
![image](https://user-images.githubusercontent.com/1104829/27839451-975c8992-60f1-11e7-9f49-57a0ffe76d96.png)

I'm using the latter scanner configured in my "shows with subtitles" library. I'm using the first one for another library. The first one is configured to "use localized titles" while the latter isn't. Not sure if this matter at all.

Trying `subs` folder now ...

OK, unexpected results. Searching for Hungarian subtitles now results in matches with way lower scores: around ~115 instead of the previous 360. [Here's the log](https://pastebin.com/raw/jvhDLmWM). Best match:

```
Available: opensubtitles, score: 138
Release:  mr.robot.s01e01.720p.bluray.x264-demand, Matches: episode, format, season, year, release_group, series, video_codec, resolution, hash, hearing_impaired
```

Downloading it ... [here's the log of it](https://pastebin.com/raw/Y6anXLMJ). 

The actual file that was downloaded still didn't match the audio, it wasn't the one I've attached earlier. :/

**Comment by kohanyirobert** [comment]
Errr, hey wait. Sub-Zero 1.4? Just noticed it, earlier it was definitely the latest version as I have mentioned ... Plex is auto-downgrading my plugins? :D I'll fiddle with it and try again.

**Comment by pannal** [comment]
Please read the instructions on how to install SZ manually and do that, before we continue debugging this. 

Clean install, no symlinking: https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner

**Comment by kohanyirobert** [comment]
Well, I did it. Know the the channel icon's text overlay has the word 'dev' and I can see the 'dev' keyword added to the end of the name of the agent in the agent configure view.

Still to no avail. Tested it again and now it downloads a third totally unrelated Hungarian subtitle. I'm not sure at this point what Mr.Robot is about, but in very first few sentences in the sub there's mention of the Red Army, Berlin and 16 April 1945. In the English subtitle there is no mention of this. I don't have to say that the sub doesn't match the audio.

The log: [logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1123708/logs.zip)

Can you point me in the code where the actual download, the GET request happens that fetches the subtitles? I'll insert some debug code or I don't know. This frustrates the hell out of me.

**Comment by pannal** [comment]
Can you find out the rating key for that item? Click the three dots in plex web, when at the item's page, click `Get Info` -> `View XML`, you should see its `rating_key` parameter in the URL.

Then go to `Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.subzero\DataItems` and find the `subs_RATING_KEY.json.gz`, where RATING_KEY is the one you just found. Please attach that file.

**Comment by kohanyirobert** [comment]
Here it is.

[subs_412.json.gz](https://github.com/pannal/Sub-Zero.bundle/files/1124087/subs_412.json.gz)

**Comment by pannal** [comment]
OK, seeing some strange behaviour. The subtitle storage says `"current": "opensubtitles__1955027189"`, which begins with:

```
"1\n00:00:14,778 --> 00:00:17,278\nAnonyma\n\n2\n00:00:24,447 --> 00:00:28,338\nEgy berlini asszony\n\n3\n00:00:33,181 --> 00:00:36,014\nKi gondolt volna erre?\n\n4\n00:00:37,021 --> 00:00:40,651\n1945. \u00e1prilis 16-\u00e1n elj\u00f6tt az id\u0151.\n\n5\n00:00:42,221 --> 00:00:45,118\nA V\u00f6r\u00f6shadsereg k\u00f6rbez\u00e1rta Berlint\n\n6\n00:00:45,119 --> 00:00:49,900\n\u00e9s most h\u00e1zr\u00f3l-h\u00e1zra\nk\u00f6zel\u00edtettek a Reichstag fel\u00e9.\n\n7\n00:00:49,901 --> 00:00:54,140\nEzen a napon a nap elb\u00fajt a felh\u0151k m\u00f6g\u00e9,\n\n8\n00:00:54,141 --> 00:00:58,721\nde az orgon\u00e1k illata\nminden f\u00fcst\u00f6n \u00e1t\u00fct\u00f6tt.\n\n9\n00:01:02,181 --> 00:01:04,741\nHogyan kezdjem?\n\n10\n00:01:04,861 --> 00:01:08,771\nHogyan tal\u00e1ljak r\u00e1 megfelel\u0151 szavakat?\n\n11\n00:01:09,981 --> 00:01:13,140\nKor\u00e1bban \u00fajs\u00e1g\u00edr\u00f3 voltam,\n\u00e9s tizenk\u00e9t orsz\u00e1gban j\u00e1rtam.\n\n12\n00:01:13,141 --> 00:01:15,356\n\u00c9ltem m\u00e1r Moszkv\u00e1ban,\nP\u00e1rizsban \u00e9s Londonban is.\n\n13\n00:01:15,357 --> 00:01:19,220\nT\u00e9nyleg szerettem P\u00e1rizsban\n\u00e9s Londonban is \u00e9lni.\n\n14\n00:01:19,221 --> 00:01:21,792\nDe \u00fagy hat\u00e1roztam, hogy visszat\u00e9rek,\n\n15\n00:01:21,793 --> 00:01:25,221\nmert a sz\u00fcletend\u0151 dolgok\nr\u00e9szese akartam lenni.\n\n16\n00:01:28,181 --> 00:01:31,180\nEgy\u00e1ltal\u00e1ban nem sz\u00e1m\u00edt a nevem.\n\n17\n00:01:31,181 --> 00:01:35,940
```

Is that matching with the video file?

**Comment by kohanyirobert** [comment]
Nope that is not the one. Based on the hash value I've found in the logs this should be it: https://www.opensubtitles.org/en/search/sublanguageid-hun/moviehash-a67fbdf9a1b23499. Two subs are listed, both of them are fine and matches. The one downloaded by SZ (the one in the JSON file) is incorrect. Not sure how that got in there. I think it is for a completely different movie, series.

**Comment by pannal** [comment]
Yes but does the part that I quited match the episode? It doesn't matter whether it's the one in your link. I'm trying to find out where the data comes from.

**Comment by pannal** [comment]
OK I've just manually used the OpenSubtitles API  and got a subtitle starting with: 
```
1
00:00:02,980 --> 00:00:04,190
<i>�dv, bar�tom!</i>
2
00:00:04,980 --> 00:00:07,330
<i>"�dv, bar�tom!".
Ez el�g b�na.</i>
3
00:00:07,640 --> 00:00:11,330
<i>Tal�n adhatn�k neked nevet,
de az el�g g�z lenne.</i>
```

Which looks like the correct one you want. I'm not sure what's happening here - could you delete the subs.json.gz file you got me (or move it somewhere) and try again?

**Comment by pannal** [comment]
As I'm receiving the correct subs, could you delete the gz file you attached here, restart your PMS and try again? Maybe there was some hickup in OSS services or so.

**Comment by kohanyirobert** [comment]
>  does the part that I quoted match the episode?

Nope, that's what I meant with _Nope that is not the one_, sorry about that.

I'll try removing the GZIP later today and get back to you. Thanks!

**Comment by pannal** [comment]
Yes, I've just tested it locally, it downloads the correct one.

**Comment by pannal** [comment]
Actually, don't delete the gz file yet. Try again without deleting. Are there other files inside the folder containing the gz file, apart from history and all the subs_*.json.gz files? Perhaps "subs_XXXX"?

**Comment by kohanyirobert** [comment]
> Are there other files inside the folder containing the gz file, apart from history and all the subs_*.json.gz files? Perhaps "subs_XXXX"?

Yep there are.

```
subs_476
subs_483
subs_300
subs_325
subtitle_history
```

No `subs_412`.

I've moved back the GZip to it's original place. Moved the `subs_XXXX` files out of there. Searched for Hungarian subtitles again. Didn't work :( A "new" wrong subtitle is downloaded now.

After this I've deleted the GZip again and tried refreshing the subs. The new GZip generated is here:[subs_412.json.gz](https://github.com/pannal/Sub-Zero.bundle/files/1125245/subs_412.json.gz)

By the way [the sub you've included in your comment earlier is the right one](https://github.com/pannal/Sub-Zero.bundle/issues/303#issuecomment-313109686). Just confirming.

Well, I'm not sure what to do now. I'd try a pristine install of the plug-in. Is there a "right way" to remove the plugin? Is it enough to delete the plugin's "Plug-ins Support" directory and remove the plugin? Or is there anything special I need to do?

One thing worth mentioning is that my Plex version is: 1.5.6.3790. I'm not controlling the installation of it, it's on a seedbox. Does SZ require a version more recent than this? It works for English subs ... so I thought it's okay.

**Comment by kohanyirobert** [comment]
Huh, didn't work. I completely removed Plex's files from `$HOME/.apps/plex`. Still downloads rubbish subtitles from OpenSubtitles.org.

**Comment by kohanyirobert** [comment]
I've tried using subliminal directly. Latest version. Same thing happens. I'll report this there.

**Comment by kohanyirobert** [comment]
[Created a new issue for Subliminal](https://github.com/Diaoul/subliminal/issues/784).

**Comment by kohanyirobert** [comment]
Quote from my seedbox provider.

> Yes, opensubtitles has blacklisted many of our ips, and serves in purpose wrong subtitles to these IPs. We have contacted their support many times about this, but the refuse to even respond to our requests. I am not quite sure why they do this. It is our understanding, that they do this in purpose to other seedbox providers as well, to blackmail for "VIP"opensubtitles accounts in order to lift the ip ban.

So yeah, it's a proper ass move. Returning 404 instead of downloading crap subs would be way nicer.

**Comment by pannal** [comment]
@opensubtitles can you give some insight to that issue? This sounds like there was a war between you and the seedbox provider.

**Comment by opensubtitles** [comment]
Hi, well, if for somebody is downloaded correct subtitle, and for somebody else not, then I need IP address of user who get wrong subtitles. Sometimes, we put in some special group IPs and serving random subs.

**Comment by pannal** [comment]
Yes, that's the case for him. Why do you put people in special group IPs and serve random subs (instead of 404)? What did they do? (Curious)

**Comment by kohanyirobert** [comment]
@opensubtitles I can give you the IP in question. Where can I send it/post it?

> yes, and returning 404 would've saved us a lot of time.
Yep :( I've spent two days on this. I can understand this if an IP range is banned because of hammering the API.

**Comment by pannal** [comment]
Or rather 403 I guess. I think you can drop him an E-Mail at admin@opensubtitles.org with the IP in question.

**Comment by opensubtitles** [comment]
@pannal those users are usually proxy, vpn, tor - IPs who abuse our services in some kind

**Comment by pannal** [comment]
@opensubtitles I understand. Although it would make life much easier for libraries like subliminal or sub-zero, if you could just return 403 instead of random subtitles.

**Comment by kohanyirobert** [comment]
@opensubtitles I've sent the IP in question to the address mentioned by @pannal. It'd be nice to know why is this particular IP is banned.  Thanks.

**Comment by opensubtitles** [comment]
@pannal if 403 is returned, hackers could easily detect it.

**Comment by opensubtitles** [comment]
@kohanyirobert where did you send it ? you can use my email: admin [at] opensubtitles dot org

**Comment by kohanyirobert** [comment]
@opensubtitles I've sent it there and I believe you or somebody else already replied. Twice actually. The ban is still in effect tho' - patiently waiting :) Thanks!

**Comment by opensubtitles** [comment]
Right, now it should be solved. Try in hour or so (cache...)

**Comment by kohanyirobert** [comment]
@opensubtitles Well, still no good. I've checked the page where I can see the stats for my IP. Still banned. 2 subtitles downloaded in 24 hours (I've downloaded subs to see what happens).

**Comment by opensubtitles** [comment]
@kohanyirobert solved :)

**Comment by kohanyirobert** [comment]
@opensubtitles Yes, thank you!
