### ISSUE TITLE
Doubt about how Sub-Zero matches movies/tv shows with subtitles

### ISSUE THREAD

**Issue by chmercesmoreira** [pannal/Sub-Zero.bundle#305]
Hello, I don't know if this is the properly place to ask this but I can't find any forum for this purpose so I'm going to ask here.

Currently I'm using a application "filebot" to automate the renaming of my movies and tv shows to the Plex Naming Scheme: https://support.plex.tv/hc/en-us/categories/200028098-Media-Preparation

If I do that, does Sub-Zero plugin still search for perfectly matches for my renamed media using "hash comparison"? Or should I keep the original name of the files?

I read here: https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration
That there is already an option to deal with this problem:

> **I keep the exact (release-) filename of my media files:**
>If you don't rename your media files automatically or manually and keep the original release's file names, >enabling this option may help finding suitable subtitles for your media. Otherwise: disable this.

Does this mean that if I rename the files I will lose precision in the file matching pattern  (using hash comparison).

Thank you.

**Comment by ukdtom** [comment]
If you strip a lot of info from the filename, then there's less for SZ to check against, when searching.

So let's say you have an episode like:
`myShow.S01E01.WebDL.720.x264.TorrentGroup.mkv`
Then SZ will start with an exact match, and gradually strips the different parts when searching

So all in all, Plex has a mandatory naming for `myShow.S01E01`
But the rest helps SZ to determine the correct match for you

**Comment by pannal** [comment]
Hash won't be affected as long as your don't physically change the contents of your media files. Renaming is not really problematic anymore, you just won't get any tag-based (exact filenames) matches from OpenSubtitles.

Be sure to keep the format (HDTV, WEB-DL, BluRay, etc.) in the filename, everything else doesn't matter anymore since Sub-Zero 2.0.

**Comment by pannal** [comment]
I've updated [the related Wiki page](https://github.com/pannal/Sub-Zero.bundle/wiki/How-Matching-Works) to reflect the major changes in this regard, in Sub-Zero 2.0.

**Comment by chmercesmoreira** [comment]
I'm currently using this script to do the renaming:
https://www.filebot.net/forums/viewtopic.php?t=215

> Movies will be sorted into {output}/Movies/Name (Year)/Name (Year) [CD123].ext
> TV Shows will be sorted into {output}/TV Shows/Name/Season N/Name - S00E00 - Title.ext

This script doesn't keep format information... Do you recommend some alternative for filebot?

**Comment by ukdtom** [comment]
Not a Filebot dude, and not related to SZ, but take a peak here:
https://www.filebot.net/naming.html

**Comment by pannal** [comment]
I'd keep `{source}` in the file format.

**Comment by pannal** [comment]
But be sure to be using Sub-Zero 2.0, 1.4 has different filename matching implications.

**Comment by chmercesmoreira** [comment]
I created a topic in their forums asking for a new feature:
https://www.filebot.net/forums/viewtopic.php?f=4&t=5181

Keeps the original file name appended at the end of the generated filename.
This way the new filename will attend both Plex name convention and the informations needed by Sub Zero Plugin.
Do you guys think this could be a good solution?

**Comment by chmercesmoreira** [comment]
Hey! I just discovered how to rename the filename keeping the original filename appended at the end between (), the command argument:
--def movieFormat="{movie}({fn})"
do this.

**Comment by viking1304** [comment]
@chmercesmoreira There is really no need to make a complete mess of your filenames in order to get good results with SZ. All my movies and series and automatically renamed with Flexget tasks.

**Good movie filename examples:**

```
The Fate of the Furious (2017) - [1080P BLURAY H264].mp4
```

**Good series filename examples:**
```
Killjoys (2015) s03e01 - Boondoggie - [720P HDTV H264].mkv
iZombie (2015) s03e10 - Return of the Dead Guy - [720P WEBDL H264].mkv
```
Those are settings from my sorting tasks:

**For movies:**
```
    move: 
      to: '/{? paths.movies ?}/{{ tmdb_name|replace(":", " -") }} ({{ tmdb_year }})'
      rename: "{{ tmdb_name|replace(':', ' -') }} ({{ tmdb_year }}){% if quality|default(False) %} - [{{quality|upper}}]{% endif %}{{location | pathext}}" 

```
**For series**
```
    move:
      to: '/{? paths.series ?}/{{ trakt_series_name }} ({{trakt_series_year}})/Season {{ trakt_season|pad(2) }}'
      rename: "{{ trakt_series_name }} ({{trakt_series_year}}) s{{ trakt_season|pad(2) }}e{{ trakt_episode|pad(2) }}{% if trakt_ep_name|default(False) %} - {{ trakt_ep_name|replace(':', ' -') }}{% endif %}{% if quality|default(False) %} - [{{quality|upper}}]{% endif %}{{location | pathext}}" 
```

If you compare original filename like `Orphan.Black.S05E04.720p.HDTV.x264-AVS[eztv].mkv` and new filename like `Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [720P HDTV H264].mkv`  you will notice that only missing part is release group. In SZ 2.x this info is really not so important. Default scores in settings are those that you will get when release group is not matched.

I suggest to read this:
https://github.com/pannal/Sub-Zero.bundle/wiki/How-Matching-Works
https://github.com/pannal/Sub-Zero.bundle/wiki/Media-Score
@pannal and @ukdtom made two great articles about matching and scoring

This is (just a part of) what SZ knows about a file  `Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [720P HDTV H264].mkv`  
```
{
    "title": "Dark Matter", 
    "year": 2015, 
    "season": 3, 
    "episode": 4, 
    "episode_title": "All the Time in the World", 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
Size is 765355043
Computed hashes 
'thesubdb': 'ddaa84f016a1e50bab8999e725dacc7a',
'opensubtitles': 'f4c3e9d3e0cdc0c1'
'napiprojekt': '10258f28a2ca77bb3777a8145a461445'
```

**Comment by chmercesmoreira** [comment]
I'm using this script on filebot:
**For Movies:**
`filebot -script fn:amc --def movieFormat="Movies/{movie}/{movie} - ({fn})" --action move -non-strict Filebot/ --output . --def ut_label=movie --mode interactive`
**For TV Shows:**
`filebot -script fn:amc --def seriesFormat="TV Shows/{n}/Season {s}/{episode} - ({fn})" --action move -non-strict Filebot/ --output . --def ut_label=tv --mode 
interactive`

Now I'm getting the expected behavior, SZ found all the subtitles it was not finding before I made these changes.

Do you prefer to use [] instead of () to limit source file informations? What is the usual default for this?

**Comment by ukdtom** [comment]
() are ignored by native Plex scanners, and are as such preferred, to make overall scanning faster

**Comment by chmercesmoreira** [comment]
Cool, so my bet was right, prefer () against [].

**Comment by viking1304** [comment]
I am simply using [] to add data that is useless to Plex, but still might be useful for SZ. I cant remember why I decided to use [] instead of (), but I would probably change it to () after I read what @ukdtom wrote.

Btw. based on http://www.filebot.net/naming.html I would use something like this:

**For series filename**
`{n} ({y}) {s00e00} - {t} (vf source vc group)`

**For movies filename**
`{n} ({y}) (vf source vc group)`

**Comment by chmercesmoreira** [comment]
He edited his comment, the right choice is []. You don't need to change anything, you are right.

**Comment by chmercesmoreira** [comment]
Following what is said here:
https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows

> **To name series/episode based shows:**
> TV Shows/ShowName/Season XX/ShowName - sXXeYY - Optional_Info.ext

Optional_Info is located at the end after a - character, is it recommended to put a - like that?
My final script will be:
**With -**
`--def movieFormat="Movies/{movie}/{movie} - [{fn}]"`
`--def seriesFormat="TV Shows/{n}/Season {s}/{episode} - [{fn}]"`
**or without -**
`--def movieFormat="Movies/{movie}/{movie} [{fn}]"`
`--def seriesFormat="TV Shows/{n}/Season {s}/{episode} [{fn}]"`

What should I choose?

**Comment by ukdtom** [comment]
Sorry about the confusion here, and late here as well, so bare with me...

[] is the way to go

**Comment by viking1304** [comment]
If that was my system I would probably go with those:

**For series**
`--def seriesFormat="TV Shows/{n}/Season {s}/{n} ({y}) {s00e00} - {t} - [vf source vc group]`

**For movies filename**
`--def movieFormat="Movies/{n} ({y})/{n} ({y}) - [vf source vc group]`

This way you will have all info from original file name, but it would be more clean :)

**Comment by chmercesmoreira** [comment]
@viking1304 
Yes, you are right, using `[vf source vc group]` I will keep only the main information needed by SZ, but I'll keep using {fn} (original file name), so that I'll bring "all" the metadata information, even keeping the filename ugly, I think this is a price I can deal with.

**Comment by viking1304** [comment]
I am trying to explain that you will get same results with SZ in both cases.

Those two files are basically same for SZ:
```
Orphan.Black.S05E04.720p.HDTV.x264-AVS[eztv].mkv 
Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [720P HDTV H264 AVS].mkv 
```

Check this:
```
Sane: 337 and above (default)
series 180 + season 30 + episode 30 + year 90 + format 7 = 337

Ideal: 352 and above
series 180 + season 30 + episode 30 + year 90 + release_group 15 + format 7 = 352
```

or in filebot terms

```
Sane: 337 and above (default)
n 180 + s 30 + e 30 + y 90 + vf 7 = 352

Ideal: 352 and above
n 180 + s 30 + e 30 + y 90 + group 15 + vf 7 = 352
```

Default score for TV is 337. You will get more than that in most cases.

**Comment by chmercesmoreira** [comment]
Yes, I know, but I'm using Plex and I need to follow Plex naming conventions.
This: `Orphan.Black.S05E04.720p.HDTV.x264-AVS[eztv].mkv ` is far from the Plex naming convention.
This: `Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [720P HDTV H264 AVS].mkv` is following Plex naming convention and at the same time is SZ compliant.

**Comment by viking1304** [comment]
I am just saying that for SZ both of those are same. Even something like this (what you will probably get with your settings is exactly the same for SZ:
`Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [Orphan.Black.S05E04.720p.HDTV.x264-AVS[eztv].mkv].mkv`

2017-07-05 01:23:36,762 INFO <PodnapisiSubtitle 'http://www.podnapisi.net/subtitles/en-orphan-black-2013-S05E04/Z4hE' [en:None]>: Computed score 357 with final matches set(['episode', 'format', 'series', 'year', 'hearing_impaired', 'season', 'video_codec', 'resolution', 'release_group'])

**Comment by chmercesmoreira** [comment]
Ok, I understand, but before I was using the default script called amc: https://www.filebot.net/forums/viewtopic.php?t=215

And this script renamed files without keeping any metadata information, this reason was why SZ was not finding any matching subtitle before.
Now I'm getting matching subtitles to all my media.

**Comment by viking1304** [comment]
Your system, your rules.

I am just trying to explain that you will get exactly same results without having ugly filename like this `Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [Orphan.Black.S05E04.720p.HDTV.x264-AVS[eztv].mkv].mkv` if you simply use something like this `Orphan Black (2013) s05e04 - Let the Children & the Childbearers Toil - [720P HDTV H264 AVS].mkv `. You can always try both yourself.

Final decision is only yours.

**Comment by chmercesmoreira** [comment]
Did you read what I wrote here: https://github.com/pannal/Sub-Zero.bundle/issues/305#issuecomment-312963788
I already changed my mind, I'm following your suggestion already =)

**Comment by viking1304** [comment]
@chmercesmoreira I read your original message, but haven't seen your edit until now. I though you are still insist on using fn in your script :)

**Comment by chmercesmoreira** [comment]
No no, your suggestion is much better! I have to thank you!

**Comment by viking1304** [comment]
btw. if you have any more question, feel free to ask on Plex forum. Here is the link (since I guess you haven't found it):
https://forums.plex.tv/discussion/186575/release-sub-zero-2-0-24-1558-subtitles-done-right/p1

**Comment by chmercesmoreira** [comment]
I just found this official forum topic after creating this issue, thank you.
