### ISSUE TITLE
Character and spacing problems with é è ë and punctuation marks

### ISSUE THREAD

**Issue by rourke** [pannal/Sub-Zero.bundle#307]
I use v2.0.24.1565 (currently the latest) and still occasionally see some weird characters in my dutch subtitles. I know the subs are probably to blame but is this fixable through mods? Default mods are applied: Common and OCR.

`ט` should be `è`
`י` should be `é`
`כ` should be `ë`

There are probably more, but at the moment this is all I could find.

Also I was wondering if it would be able to fix some spacing issues. I see `<space>?` and  `<space>!` at the end of sentences sometimes. Could you remove that space in a mod?

**Comment by pannal** [comment]
Spaces before punctuation is possible, although not generally applicable to every language out there.

Please compile a list of search/replace strings for Dutch, I'll add them to the custom OCR fixes dictionary then.

**Comment by rourke** [comment]
I made a quick script to scan all my subtitles (113) for OCR issues and this is what I got:

`ט` should be `è`
`י` should be `é`
`כ` should be `ë`
`צ` should be `ë`
`ן` should be `ï`
`ף` should be `ó`
`א` should be `à`

Characters I encountered but of which I'm not entirely sure what the exact replacement should be. The following makes the most sense:
`פ` should be `o`
`ם` should be `i`

1 subtitle file had `Iֻ` (notice the weird line underneath) which should be `I`.
1 subtitle file had a lot of `č` in it. This should be `è` in all those cases. The `č` is hardly ever used in the Dutch language.

Is this the format you want them in?

```
<PartialWords>
    <WordPart from="ט" to="è" />
    <WordPart from="י" to="é" />
    <WordPart from="כ" to="ë" />
    <WordPart from="צ" to="ë" />
    <WordPart from="ן" to="ï" />
    <WordPart from="ף" to="ó" />
    <WordPart from="א" to="à" />
    <WordPart from="פ" to="o" />
    <WordPart from="ם" to="i" />
    <!-- Not sure if you want these in -->
    <WordPart from="Iֻ" to="I" />
    <WordPart from="č" to="è" />
</PartialWords>
```

**Comment by pannal** [comment]
I think it should be PartialWordsAlways, but no, I don't need it in that format as I add the custom replacements directly in Python.

I can extract them, or you could post them as a Python dictionary:
```
asdf = {
    "search": "replace",
    ....
}
```

**Comment by pannal** [comment]
But wait, you scanned all your subtitle files for OCR errors? Have they been downloaded by Sub-Zero 2.0+? If not you should re-download them and see whether all those fixes are still valid.

**Comment by rourke** [comment]
All subtitles have been downloaded through Sub-Zero 2.0+. I just read them through a PHP script and got rid of the characters that are familiar, leaving these strange characters. I only displayed them on-screen. I did no alterations.

If you could extract them, then please go ahead. I'm not sure what the format of a Python dictionary should look like.

**Comment by pannal** [comment]
I just posted the format above :D

But no worries, I'll convert it.

**Comment by rourke** [comment]
Ah right, I misinterpreted that. Sorry haha. Thanks! :)

**Comment by pannal** [comment]
@rourke Want to test develop-2.0 branch? I've adapted the changes you've requested.

**Comment by rourke** [comment]
I'll be able to test it tomorrow! Will let you know as soon as possible.

**Comment by rourke** [comment]
Confirmed working. 👍 

Can I just use `Advanced` > `Apply configured default subtitle mods to all (active) stored subtitles` to fix all my subtitles?

**Comment by pannal** [comment]
Yeah, I'd use Reapply Mods instead, though.
