### ISSUE TITLE
UNRAR_Tool - Unrar not installed

### ISSUE THREAD

**Issue by BrutuZ** [pannal/Sub-Zero.bundle#311]
Python library doesn't seem to be handling RAR files properly. 
Version 2.0.24.1565
```
2017-07-06 23:30:42,042 (3bc) :  INFO (logkit:16) - subliminal.providers.legendastv: Downloading archive 58cc427f4157d  
2017-07-06 23:30:43,941 (29c0) :  INFO (datakit:131) - Saved the dictionary file  
2017-07-06 23:30:43,947 (29c0) :  INFO (datakit:131) - Saved the dictionary file  
2017-07-06 23:30:43,953 (29c0) :  INFO (datakit:131) - Saved the dictionary file  
2017-07-06 23:30:43,953 (29c0) :  INFO (logkit:16) - Task: ran: SearchAllRecentlyAddedMissing  
2017-07-06 23:30:43,956 (29c0) :  INFO (datakit:131) - Saved the dictionary file  
2017-07-06 23:30:48,345 (3bc) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 120, in list_subtitles_provider  
    ret = self[provider].list_subtitles(video, provider_languages)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 477, in list_subtitles  
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 437, in query  
    self.download_archive(a)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 356, in download_archive  
    archive.content = RarFile(archive_stream)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 666, in __init__  
    self._parse()  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 858, in _parse  
    self._file_parser.parse()  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 973, in parse  
    self._parse_real()  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 1047, in _parse_real  
    self.process_entry(fd, h)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 1460, in process_entry  
    cmt = self._read_comment_v3(item, self._password)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 1414, in _read_comment_v3  
    inf.file_size, inf.flags, inf.CRC, psw, inf.salt)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 2747, in rar3_decompress  
    p = custom_popen(cmd)  
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\rarfile.py", line 2816, in custom_popen  
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)  
RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')  
2017-07-06 23:30:48,346 (1c10) :  INFO (logkit:16) - subliminal_patch.core: Discarding provider legendastv  
```

**Comment by viking1304** [comment]
You need to install unrar command line utility first and it has to be added to your path.

More info here:
https://rarfile.readthedocs.io/en/latest/faq.html

**Comment by pannal** [comment]
Damn, I wanted to add "unrar needed!" to legendas in settings.

**Comment by ukdtom** [comment]
Instead, maybe consider this?
https://pypi.python.org/pypi/rarfile/

/T

**Comment by pannal** [comment]
`Compressed files are extracted by executing external tool: either unrar from RARLAB or bsdtar from libarchive.`

**Comment by viking1304** [comment]
@ukdtom Please pay attention at class. That one is used. I sent link to their FAQ. :)

**Comment by BrutuZ** [comment]
Okay, seems to work fine after editing line 190 of rarfile.py with the full path to rarfile.exe .
However that will surely break after an update, so what would Plex's relative path to root be in Windows? Tried the Data folder but no luck there.

Method 3 (according to FAQ list) would be the best since the other either require admin privileges or will break upon update.

**Comment by pannal** [comment]
Did you add the folder containing unrar.exe to your windows PATH? I sadly can't test on Windows right now.

**Comment by BrutuZ** [comment]
Copying into %windir% falls under the "Require admin privilege" category.
Personally I can do it, don't think that would be the case for every user.

Then again, my Plex is not installed under the default Program Files folder either, not sure this concern is that valid since you'd usually need admin privilege to put unrar.exe there anyway.

**Comment by viking1304** [comment]
Just add folder with unrar.exe to your path. If you do not know how to do that, you can find more info here.

https://www.google.rs/amp/s/www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/amp/

**Comment by BrutuZ** [comment]
```
1. Add location of unrar.exe to PATH.
2. Set rarfile.UNRAR_TOOL to full path of unrar.exe.
3. Copy unrar.exe to your program directory.
4. Copy unrar.exe to system directory that is in PATH, eg. C:\Windows.
```
1, 4 and potentially 3 (unless the folder is not protected) require admin privileges
2 would break on updates, unless it was integrated in the (already crowded) agent settings

Maybe there is no easy universal UAC-friendly way.

**Comment by viking1304** [comment]
It is written "It can be solved several ways:"

You don't need to do all of that. Choose one that suits you best.

**Comment by BrutuZ** [comment]
I tested a couple just to be sure they required elevation.
Like said before, any of the options will work for me (in fact, already do), I was just trying to figure out one that would be applicable to anyone, regardless of admin privilege to be as compatible as possible :)

**Comment by pannal** [comment]
Well, the other option is to ship a version of unrar with Sub-Zero for every platform combination out there.

Doable, but out of scope right now. I'm leaving this open for a week so people see it easily.

**Comment by pannal** [comment]
@BrutuZ develop-2,0 branch has a Windows-specific possible-fix for this. Can you check?

**Comment by BrutuZ** [comment]
That change worked flawlessly @pannal 👍

**Comment by pannal** [comment]
Awesome!

**Comment by BrutuZ** [comment]
For the record: so did manually placing unrar.exe on Plex install folder (beside "Plex Media Server.exe"), which _in my case_ doesn't require elevation since it's a non-default path. I had it also work previously by changing the code to point the absolute path for unrar.exe.
Needless to say that everything was cleaned up between the tests.

**Comment by pannal** [comment]
So you can use this now without *any* changes?

**Comment by BrutuZ** [comment]
Yes, didn't have to do anything with the latest commit, it all worked out of the box. All my previously placed unrar files had been cleared so it was all on the fix.

**Comment by pannal** [comment]
Great. Thank you for testing!

**Comment by mimed** [comment]
Guys, can someone please help me install Unrar on my Plex media server? I'm using a Mac Mini, so these tips for Windows doesn't work for me.

**Comment by pannal** [comment]
@andremacola SZ relies on `unrar` being inside the environment. Did you try restarting your PMS or even the Mac after installing unrar? It might not be visible for it until you do that.

@mimed this pops up on google: http://macappstore.org/unrar/

**Comment by mimed** [comment]
@pannal Lovely, I'll try that as soon as I get home. Thanks for the tip!

**Comment by andremacola** [comment]
@pannal what to you mean about "inside the environment"? Yes I did restart the Plex and OSX (High Sierra). Using external drive for media files.

![captura de tela 2018-03-01 as 13 12 26](https://user-images.githubusercontent.com/3408809/36855457-4596e12a-1d52-11e8-90c0-44034962203e.png)
![captura de tela 2018-03-01 as 13 12 34](https://user-images.githubusercontent.com/3408809/36855458-45bec988-1d52-11e8-9095-07a7cbe9f486.png)
`2018-03-01 13:07:33,231 (7000108a9000) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "/Users/andremacola/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 147, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/Users/andremacola/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 88, in __getitem__
    provider = provider_registry[name](**self.provider_configs.get(name, {}))
  File "/Users/andremacola/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 175, in __init__
    raise ConfigurationError('UNRAR tool not available')
ConfigurationError: UNRAR tool not available`

**Comment by pannal** [comment]
@andremacola does the PMS have access to execute the binary?

**Comment by andremacola** [comment]
@pannal I solved the problem. I had to disable High Sierra SIP (System Integrity Protection) with `csrutil enable –without fs` and create a symlink from /usr/local/bin to /usr/bin

**Comment by mimed** [comment]
Hi @andremacola, I'm so glad you figured this out. If you don't mind me asking, could you please write the steps you took to make this work? I've been trying to download Legendas.tv subtitles on Subzero for months without success. I'm not super tech savvy, but I'm curious and I would love to know how this works. You can write in Portuguese if you want to, since I'm guessing we're both Brazilians. Thank you so much!

**Comment by andremacola** [comment]
@mimed In english is better for the community

1 - Reboot your Mac into Recovery Mode by restarting your computer and holding down `Command+R` until the Apple logo appears on your screen.
2 - Click Utilities > Terminal.
3 - In the Terminal window, type in `csrutil disable -without fs` and press Enter. ( There will be a message like "unsupported blablabla".
4 - Restart your Mac.
5 - Install unrar from brew or from https://www.rarlab.com/rar_add.htm
6 - Open terminal and write `sudo ln -s /usr/local/bin/unrar /usr/bin/unrar` (check your paths)
7 - Start Plex and configure Sub Zero properly

**Comment by pannal** [comment]
Why is that necessary?

**Comment by andremacola** [comment]
@pannal Honestly? Have no Idea. I had several problems with SIP and local bins on OSX before, so I did that and worked.

**Comment by pannal** [comment]
@brunoluzsousa please keep this in English.

I'm experimenting with pre-shipped UNRAR for several platforms currently, for the next release perhaps.

**Comment by brunoluzsousa** [comment]
@pannal OMG, if you do this... we will really appreciate!
--------
Translating what I previously commented:

Hi, @andremacola. Do you know if it's still necessary to disable SIP in the newest macOS version (High Sierra - 10.13.4)? I would like to test it first without disabling SIP.

Already installed UNRAR on Mac through this tutorial: http://geekussion.com/mac-os-x/install-use-winrar-mac-37/. Homebrew isn't necessary. Just the rar files from RARLab website. (I think you will appreciate this tutorial, @mimed).

After installing UNRAR on Mac, what's the next step?

**Comment by pannal** [comment]
@brunoluzsousa could you try the [current develop-2.5 branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.5.zip) with a [manual installation](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)?

**Comment by brunoluzsousa** [comment]
Just tested, @pannal 

It does appear "Using UnRAR from" but it also appears an error "ERROR (logger:34) - subliminal_patch.core: Malformed RAR file from provider 'legendastv', skipping subtitle."

Here is the logs:

[Logs_180401_19-49-08.zip](https://github.com/pannal/Sub-Zero.bundle/files/1866772/Logs_180401_19-49-08.zip)

**Comment by pannal** [comment]
@brunoluzsousa care to join the [SZ slack](http://szslack.fragstore.net) beta team to further debug this?

**Comment by brunoluzsousa** [comment]
Absolutely! @pannal

**Comment by mimed** [comment]
I'm still unable to download subtitles from the agent Legendas.tv 

It doesn't even show options from Legendas.tv when manually searching on Subzero.

**Comment by pannal** [comment]
@mimed that seems like a different issue, please create a new ticket for that

**Comment by mimed** [comment]
@pannal Do I have to enable multithreading? Because everything seems to be configured correctly here. I took the steps @brunoluzsousa mentioned to install Unrar on my Mac and when manually searching for subtitles on Subzero, it doesn't show subs from Legendas.tv, only from OpenSubtitles and Addic7ed. 
<img width="573" alt="screenshot 2018-04-02 12 11 21" src="https://user-images.githubusercontent.com/6992776/38201528-0440046e-366f-11e8-823b-6b84aa9ea472.png">
<img width="565" alt="screenshot 2018-04-02 12 11 03" src="https://user-images.githubusercontent.com/6992776/38201529-04708f76-366f-11e8-9eea-473b7c854d22.png">

**Comment by pannal** [comment]
@mimed again, please open a separate issue, this is not UnRAR related.

**Comment by mimed** [comment]
Sorry @pannal. Moved this discussion to [here](https://github.com/pannal/Sub-Zero.bundle/issues/487).
