### ISSUE TITLE
SubsCenter broken

### ISSUE THREAD

**Issue by rotem925** [pannal/Sub-Zero.bundle#316]
Hi,
When trying to search via SubsCenter I can see an error log with  line 102 of SubsCenter provider, where it sets the session .
Currently I'm not able to use SubsCenter at all.

Thanks
Rotem

**Comment by rotem925** [comment]
I thinks the site url has change to .info instead of .org

**Comment by rotem925** [comment]
I've changed the server_url to the new url, it works for some of the movies/shows, for some of the videos it logs error 404 when downloading...

> HTTPError: 404 Client Error: NOT FOUND for url: http://www.subscenter.info/he/subtitle/download/he/285819/?key=db52518b1ff0f007a1fa3c886cbaa772&v=57657374776f726c642e5330314530352e343830702e783236342d6d5344

**Comment by pannal** [comment]
Hmm, interesting. @diaoul

@rotem925 is the org address down universally?

**Comment by rotem925** [comment]
@pannal 
It is not down. If you go to the org site, you will see that the login page is at .info.
Some of the links are still directing to the .org and some to the .info. It think they are moving the site to a new domain...

**Comment by pannal** [comment]
Hm, so what's the plan here? I'd say we wait until they've fully moved their site.

Any other fix would be just temporary and quickly obsolete.

**Comment by Diaoul** [comment]
Ping me when they're done.

**Comment by rotem925** [comment]
I think they moved it completely. I joined their telegram group... Some download links are still with error 500.
I've asked on the chat. .info is the right domain and not .org

**Comment by pannal** [comment]
OK, will be updated in the upcoming release.

**Comment by Diaoul** [comment]
See https://github.com/Diaoul/subliminal/pull/796

**Comment by pannal** [comment]
Damn.

**Comment by pannal** [comment]
SubsCenter currently likes to impose CAPTCHAs. Consider this provider broken for the time being.

**Comment by pannal** [comment]
SubsCenter will be removed in the next version.
