### ISSUE TITLE
Pulling pre-rename file name from Sonarr/Radarr history for search

### ISSUE THREAD

**Issue by mattmac24** [pannal/Sub-Zero.bundle#319]
I'd like to suggest a new feature where Sub-Zero will query Sonarr & Radarr for the original file name of the file. This would give more information about the file allowing for a better match. 
The information is available in the history part of the api as shown [here](https://github.com/Sonarr/Sonarr/wiki/History)(Sonarr) and [here](https://github.com/Radarr/Radarr/wiki/API:History)(Radarr).

Every single one of my files comes from Radarr/Sonarr and is renamed on import so my library looks nice and organised, but this hinders correct subtitle lookup.

Is this something the developers of Sub-Zero could implement?

**Comment by pannal** [comment]
What an amazing idea.

This will definitely be implemented if possible.

**Comment by mattmac24** [comment]
Glad you like the idea! Can't wait for this to happen :)

**Comment by Diaoul** [comment]
Maybe as a refiner?

**Comment by gabbe222** [comment]
gr8 idea

**Comment by pannal** [comment]
@diaoul Yeah, thought of that, too. That feature is high on my list right now.

**Comment by pannal** [comment]
Hmm. Do you have any more info on the history API than what's available [here](https://github.com/Sonarr/Sonarr/wiki/History)?

As far as I understand, there's no way of searching the history, so it'd need to be scraped and/or archived to be searchable.

**Comment by pannal** [comment]
Tracked over there: https://github.com/Sonarr/Sonarr/issues/2265

**Comment by pannal** [comment]
Radarr tracked over here: https://github.com/Radarr/Radarr/issues/2245

**Comment by vrokolos** [comment]
What about couchpotato?

**Comment by pannal** [comment]
@vrokolos does it have an API that contains that information?

**Comment by vrokolos** [comment]
HTTP manager manages to access its history but I'm not sure what kind of details you'd need for it

**Comment by pannal** [comment]
https://github.com/Radarr/Radarr/issues/2345 https://github.com/Sonarr/Sonarr/issues/2336 https://github.com/Sonarr/Sonarr/issues/2335 https://github.com/Radarr/Radarr/issues/2344

**Comment by pannal** [comment]
The first WIP implementation of this is inside the develop-2.1 branch.

**Comment by Mirabis** [comment]
Yay; will try the dev branch this weekend to see if it helps :) my file names were pretty matchable.. but every improvement is a improvement
