### ISSUE TITLE
Subtitles for optimized versions

### ISSUE THREAD

**Issue by Cooad** [pannal/Sub-Zero.bundle#321]
Hello.
I store the subtitles along my videos in the filesystem.
When subzero downloads subtitles after an optimized version is created by plex, the subtitles are unavaible while playing the optimized version. This is a common scenario for me, as I optimize new content as soon as it's available, and the subtitles come a few hours later.
From my understanding, the solution is as simple as just copying the subtitle files to plex version directory.
Could this be supported in the next release?

**Comment by ukdtom** [comment]
Unsure if putting subs in Plex Metadata library might be the solution, but regardless, check the Wiki here:
https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#subtitles-storage-configuration

**Comment by Cooad** [comment]
I tested it, it unfortunately doesn't work

**Comment by pannal** [comment]
Is the added srt file besides the optimized media file? Where exactly is the optimized file placed and how is it named compared to the original file name?

This sounds fixable.

**Comment by ukdtom** [comment]
Random number sounds like track number, and should not be there, IMHO. 
Sounds instead like a PMS bug

**Comment by pannal** [comment]
@Cooad ? Want to answer my question? :)

**Comment by Cooad** [comment]
The files may be placed in a subfolder of the original file, or a folder in the root of the library called "Plex versions". Let's say you want "original quality" of "Series A" season 2, episode 3 placed in library root - the optimized file will be placed in library root -> Plex versions -> Original -> Series A -> S02E03.mp4 . If you want the file in a subfolder, the "Plex versions" folder is placed in the media file folder.
I think the "random" number in subtitle filename is there for some reason.

**Comment by pannal** [comment]
OK @Cooad I'll investigate.

**Comment by pannal** [comment]
If you put the SRT file SZ downloaded into that folder, without the random number, does it get recognized?

**Comment by Cooad** [comment]
Yes, it does, after a subzero refresh :)

**Comment by pannal** [comment]
Ok. I think I can support this natively. Stay tuned.

**Comment by pannal** [comment]
What are the possible folder names, can you find out?

**Comment by Cooad** [comment]
What folders are you asking about exactly?
If you are asking about the folder that indicates the optimized viersion quality ("original" in the example above), then well... anything. There are a few presets in Plex (Original, Optimized for mobile, Optimized for TV), but allows the user to create a custom quality and name it anything the user wants. In that case it also adds a number ad the end. My use case as example:
I optimize everything to a custom quality setting of 1,5 Mbps 480p, and I name it "SD" each time. I always save optimized versions in root library folder, so I have a folder structure like:
root
-Plex Versions
--SD 1120
---Series A
--SD 1145
---Series B
--SD 1182
---Series C

I have created a feature request at plex forums to save the quality setting, which would probably help with the number of the Quality folders. But I wouldn't count on it being implemented :).
I hope this answers your question.

**Comment by pannal** [comment]
So the `root` in this case is the path to the episode file and below that is that possible structure?

**Comment by Cooad** [comment]
Yes

**Comment by pannal** [comment]
OK. SZ could check for those folders upon refresh and place subtitle items in every folder. Would that suffice?

**Comment by Cooad** [comment]
That's exactly what i had in mind. Can this happen every time the SZ subtitles change? For example, when changing subtitle color via SZ?
(off-topic)
Also, I'm not familiar how SZ updates happen. I have installed SZ using official plex repository - how often is it updated?

**Comment by pannal** [comment]
Yes, that can happen everytime SZ *saves* a subtitle, which is right after it downloaded one, as well as after you modify it from the channel menu.

Updates happen automatically if you've installed it the official way - I release a version, create a pull request on Plex Inc.'s fork of Sub-Zero. When they merge the fork and the repositories update, you will update automatically. They happen as often as I pull request (release).

Back to the functionality again: When are those versions created? May it happen that a file gets added, SZ downloads a subtitle immediately, and the folders don't exist?

**Comment by Cooad** [comment]
The folders are created as soon as optimization task starts. The file isn't there yet, but the folders are.

**Comment by pannal** [comment]
But I guess it starts after the metadata has been added?

**Comment by Cooad** [comment]
The wild file appears -> the metadata about a new file appears -> the optimization task starts -> the folders are created -> metadata about the optimized file is added when the optimization stops.
This is the order in which thinks happen as far as I can tell
