### ISSUE TITLE
bug on all substitles with bad utf-8 encoding but Subliminal is working.

### ISSUE THREAD

**Issue by ialexandru** [pannal/Sub-Zero.bundle#322]
The problem occur on all downloaded subtitles. 
Context: Default sub zero instalation, and only one language set as language 1.

All subtitles are downloaded under the .ro.srt extension but the file is using a forced conversion to utf-8 and all the characters are converted. The plex opensubtitles and subliminal plugin are working correctly bringing the same subtitles but they preserve the correct characters.

Bad encoding....
- Da, aºa cred.
- Miºto.
Câinele i-a fãcut ferfeniþã

Good encoding using Subliminal
așa
Mișto.
gândești
ferfeniță

**Comment by pannal** [comment]
Thanks, I'll look into it. Can you give me a subtitle example of opensubtitles? With link? Also I'll need logs of subzero in log level DEBUG. Right after you download a subtitle where that happens.

**Comment by pannal** [comment]
In fact, just attach the logs, I'll get the necessary info from them.

**Comment by baadnewz** [comment]
Same subtitle from opensubtitles .

Downloaded manually - as you can see the special chars are displayed correctly:
![manual-download](https://user-images.githubusercontent.com/661635/28713780-3e18ae1e-7399-11e7-8d4b-2606f9bad6d9.png)

Sub-zero download:
![subzero-download](https://user-images.githubusercontent.com/661635/28713781-3e348314-7399-11e7-9a6e-e3b78e79462c.png)


Here is the link for the subtitle:
https://www.opensubtitles.org/en/subtitles/7045969/queen-of-the-south-el-precio-de-la-fe-ro

Also I feel like i need to mention this. For the manual downloaded subtitle the encoding is ANSI while the Sub-Zero download is encoded in UTF. Suspect this is where the actually problem is. most Romanian subtitles uploaded on opensubtitles are ANSI and Sub-Zero assumes they are UTF-8

**Comment by pannal** [comment]
Sub-Zero doesn't *assume* anything. It tries to transcode the subtitle to UTF-8 and fails, because apparently I've used the wrong encoding for Romanian :)

Still, can you send me your logs please so I can verify?

**Comment by baadnewz** [comment]
ok my bad, its clear i haven't checked how Sub-Zero works just made a guess :) 
here are the logs you asked

[Logs_170728_14-32-38.zip](https://github.com/pannal/Sub-Zero.bundle/files/1182864/Logs_170728_14-32-38.zip)

**Comment by pannal** [comment]
There's nothing in the logs.

Please make sure to set log_level to DEBUG in SZ's settings, then download a subtitle for an item that has that problem. Then attach the logs again (including all the .log.X ones).

**Comment by baadnewz** [comment]
let's try again.  Queen of the South is the one with the problems and now it seems is all logged
[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/1182927/com.plexapp.agents.subzero.zip)

**Comment by pannal** [comment]
That's better. Can you disable multithreading in SZ's settings and do that again, please?

It's hard to exactly see what's happening with all that log clutter, sorry.

**Comment by pannal** [comment]
Ah, I've just spotted something.

It downloaded https://www.opensubtitles.org/en/subtitles/7045979/queen-of-the-south-el-precio-de-la-fe-ro

It contains: `Voi aºtepta primã platã într-o` - I guess that's already wrong from the get-go, isn't it?
Do you have an example where the subtitle on OpenSubtitles actually is correct, but Sub-Zero fails to encode it properly, with a log?

**Comment by baadnewz** [comment]
in my 1st post i showed you a VS screen. The correct one from that post is by downloading the srt from the same link as you. Only difference that i think makes mine look good is that i have regional settings to Romania in Windows. Try this, assuming you are on Windows, change your regional to Romanian reboot and load subtitle again. I remember I had this issue and that changing regional in windows fixed it

**Comment by pannal** [comment]
OK. I've updated the character encoding stuff for eastern european in the develop-2.0 branch.

Could you re-do what you did without multi threading enabled so I can double check?

You could also try the [develop-2.0 branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip) in [manual installation](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation) to see if the issue has been fixed.

**Comment by baadnewz** [comment]
all right I load dev2 branch with disabled multithreading and post the results and log

**Comment by baadnewz** [comment]
develop-2.0 branch  works! Attached logs with only Opensubtitles as provider and disabled multi-threading 
[com.plexapp.agents.subzero-dev2.zip](https://github.com/pannal/Sub-Zero.bundle/files/1183066/com.plexapp.agents.subzero-dev2.zip)

**Comment by pannal** [comment]
Awesome. It'll be in the next release. Thank you for debugging with me!

**Comment by baadnewz** [comment]
No problem, glad to be able to help with something :). Thanks for the great support you offer
