### ISSUE TITLE
Sub-Zero 2.0.25.1635 doesn't work with Nvidia shield Plex

### ISSUE THREAD

**Issue by valkhyr1** [pannal/Sub-Zero.bundle#323]
Sub-Zero 2.0.25.1635 doesn't work with a nvidia shield plex server.
After deleting the 2.0.24.1581 dev version and installing the official channel version Sub-Zero doesn't appear in the channel list.

[com.plexapp.agents.opensubtitles.txt](https://github.com/pannal/Sub-Zero.bundle/files/1184165/com.plexapp.agents.opensubtitles.txt)

**Comment by pannal** [comment]
It's not synced yet to the official channel repository.

**Comment by pannal** [comment]
https://forums.plex.tv/discussion/comment/1486589/#Comment_1486589

**Comment by pannal** [comment]
It's synced now. It should update over time (out of my control).

**Comment by valkhyr1** [comment]
It's synced now, I have now Sub-Zero 2.0.25.1635.
Thanks Pannel.
