### ISSUE TITLE
[Feature Request] Remove junk and adverts from subtitles

### ISSUE THREAD

**Issue by kitsuneDEV** [pannal/Sub-Zero.bundle#324]
Is there any idea for a future release to include say a user defined list that will remove advertisement from subtitle files? Say ["Sync & corrections by","www.Addic7ed.com","Advertise your product or brand here contact www.OpenSubtitles.org today"] And so on..

**Comment by pannal** [comment]
Never going to happen. Subtitle providers do this for free.

**Comment by kitsuneDEV** [comment]
I can't find a single site that can do this for me. Also Sub-Zero is all about automation? If I have to find and upload .srt files to whatever site that can do this, that is more work than just opening the .srt file and removing said lines. And if Sub-Zero were to do this, it would bring it back to automation.

**Comment by ukdtom** [comment]
It would kill the eco system, aka providers

**Comment by pannal** [comment]
There is a way to do it automatically. Set SZ's subtitle download notification executable to your script and remove the content you don't want, yourself.

SZ itself will never incorporate such a feature by default.
