### ISSUE TITLE
Download not working?

### ISSUE THREAD

**Issue by LaMpiR** [pannal/Sub-Zero.bundle#326]
Installed it, tried it, went for the search option, found it, clicked it, saying it is downloading it but nothing after that?

Can I choose which websites to download, what is the interval for the autosearch?

**Comment by pannal** [comment]
What is "The search option"?

Also: Look at the Wiki first. If there's really something wrong, please *attach* your log zip.

**Comment by LaMpiR** [comment]
So, everything should work according to my settings but nothing happens. No Auto-download nor when I force it.

[Logs_170801_11-08-30.zip](https://github.com/pannal/Sub-Zero.bundle/files/1190062/Logs_170801_11-08-30.zip)

**Comment by pannal** [comment]
`IOError: [Errno 13] Permission denied: u'/home/vuka/torrents/rtorrent/Serije/Preacher/Season 2/Preacher.S02E04.720p.HDTV.x264-AVS.sr.srt'`

```DEBUG (menu:211) - config.permissions_ok: False
DEBUG (menu:211) - config.missing_permissions: [('TV Shows', '/home/vuka/torrents/rtorrent/Serije')]```

Please fix your permissions.

**Comment by LaMpiR** [comment]
How do I do that? Thank you.

**Comment by pannal** [comment]
The FAQ in the Wiki gives you the basic idea. Other than that, I can't help you. The user the PMS runs as should be the same the downloader runs as, or should have full access to the files.

**Comment by viking1304** [comment]
Hello @LaMpiR 

If you need more help, maybe it would be easier if you came to chat with us on Slack 
https://szslack.fragstore.net/
