### ISSUE TITLE
Problems with Addic7ed not returning results

### ISSUE THREAD

**Issue by djcath** [pannal/Sub-Zero.bundle#327]
can someone advise if there are issues with results being returned from Addic7ed subtitles?
i just migrated onto new HW for my plex server. 
I have 100 files that havent been downloading subtitles.
i have attached a portion of the log file for review, as you will see there are subtitles found for opensubtitles etc,  but none found for addic7ed.  the same thing occurs for all my new files.
should i just reduce the score for downloading to 330 OR is there a setting i need to change to get addic7ed to work again?
[subzero addic7ed.txt](https://github.com/pannal/Sub-Zero.bundle/files/1192128/subzero.addic7ed.txt)

**Comment by ferllings** [comment]
Same issue.

**Comment by pannal** [comment]
Addic7ed *needs* the release group information to be accurate. Without that, it doesn't hit.

**Comment by pannal** [comment]
It's a cantfix for now, until #319 is implemented.

**Comment by djcath** [comment]
Thanks pannal,
Has this always been the case? It always used to work no problem except for the latest 100 files.
The files have come from superchillin, so I'm not even sure if 319 will rectify the issue.

Anyway I will reduce the score to 330 so at least I'll get some downloads.

**Comment by pannal** [comment]
Not always, but it was already the case back when 1.4 was current.

**Comment by ferllings** [comment]
Strange, it only started few days ago for me.
I'll try a previous version to see if that fix it.

**Comment by ferllings** [comment]
Ok, same result with previous versions.
I don't understand why it's not working anymore.
As @pannal said, the only way to get some downloads, is to reduce the score to 330

**Comment by djcath** [comment]
I found the same thing. Worked previously.  Have dropped the score to 330 and everything has started again perfectly fine
