### ISSUE TITLE
Refresh subtitles when starting movie.

### ISSUE THREAD

**Issue by eilandert** [pannal/Sub-Zero.bundle#33]
I dont really know the internals of plex and it's possibilities, but if it is at all possible:

It might be neat to refresh the subtitles when someone starts a movie. If there is a wrong sub the user can restart the movie and watch again with refreshed subtitles.

Or scrape the watched movies from the logs and refresh them later during maintainance.

Also, if this works correctly, we don't have to scrape thousands subtitles at once and get blocked. Just get the subs when needed.

**Comment by miniop** [comment]
that will be perfect idea !

**Comment by pannal** [comment]
May be added, but please tell me if this is still needed with the new 1.3.0 features. (You can force-search for subtitles via the channel menu)

**Comment by eilandert** [comment]
Not really needed, but I still think it's a nice feature to wield out the bad subs, and if we do "subtitles on demand" instead of "refresh all" we won't overload the subtitle providers.

for example: 
- refresh subs if subs with higher score are found.
- refresh subs if sub-zero has not refreshed them before.
- refresh subs if there are no subs.

**Comment by pannal** [comment]
Well currently the "refresh all" feature 1.3.0 has actually isn't "refresh all". It looks through all recently added items and actually checks for missing subtitles. Then issues searches for those with missing subs.

"refresh subs if subs with higher score are found." wouldn't change anything, still querys the providers, just skips the download part.

I get what you mean, though. You can still refresh the single item you've just tried playing, via the on deck list of Sub-Zero's channel feature, you know that, right?

**Comment by comrade1** [comment]
Does it check for missing subtitles for each language? For example, I have mine set for German first, French second, and English third. A lot of shows have English and French right away but the German usually comes later. Will it pick the German subtitles up later even if it already downloaded the French and English?

Rob

**Comment by chopeta** [comment]
@comrade1 I could swear it doest exactly that for me.

I also have 3 langs (English, Spanish and Brazilian-Portuguese) with PT-BR almost always delayed, but now with autom. refresh they are getting downloaded automatically few ours later (depending on my settings) - all that without re-downloading English and Spanish once again which means a lot for not getting banned.

**Comment by comrade1** [comment]
That’s great. I wasn’t reporting a bug - just was wondering if it would pick up new German.

Rob

**Comment by eilandert** [comment]
"You can still refresh the single item you've just tried playing, via the on deck list of Sub-Zero's channel feature, you know that, right? Still, you would prefer automatic searching for missing subtitles just after a playback has started as an option?"

Well, if it is obvious that there are bad or no subs, there is a big fat change the user goes to the SZ channel anyway (if the client supports it) to refresh it manually, so I see no the harm to automate that part as the user has to restart the movie anyway.

Besides that, we have some very serious disabled people with no affection with modern technology., it's easier to explain to "wait 30 seconds and restart the movie" than to explain to go to the channels menu and refresh things and go back to the deck and start over. With their disabilities that would take forever. 

But as said, it's not really needed. I like it how it is anyway :)

**Comment by pannal** [comment]
No biggie, I'll add this feature to post-1.3.0-stable. Using plex_activity I can also add an option to search for missing subs on pause and stop, besides play.

**Comment by Royal2000H** [comment]
+1 this would be very convenient to not have to go into the Channel menu.

**Comment by pannal** [comment]
Are you sure this is convenient enough? Starting a subtitle search on play/pause would mean some overhead on the server and the subtitle would only be accessible after a short amount of time, together with a stop+subtitle-select+start.

**Comment by Royal2000H** [comment]
Sorry I never responded. Yes, for me at least, it would be great. I'm aware I'd need to leave the video and restart, but the time it takes out of viewing and having to traverse menus (especially when I have guests) is worth it to me.

**Comment by helmonder** [comment]
Great idea... I would love this !

**Comment by chopeta** [comment]
It could trigger the function that only download missing languages and subs with higher scores ('Auto-Search'?)... anyway, I still think it's a no biggie if you have auto. schedule in place.

**Comment by pannal** [comment]
Auto-Search actually is force-refresh. I could perhaps bind the find-better-subtitles task to the play action.

**Comment by helmonder** [comment]
Every kind of auto-search is really nice but it does not solve the manual option... Thing is that there are allways multiple subtitles available and it is not always apparent which one is the best.. So a lot of times I have to try a few to see which one is best. This is easiest done while whatching.. An auto-refresh option will always pick the best option in the opinion of the tool... I would like it the best if I could make that selection myself... -while watching- (since I have to watch to see if a subtitle is actually correct)

**Comment by pannal** [comment]
@helmonder impossible, sorry. It's outside the capabilities of a Plex plugin.

**Comment by pannal** [comment]
@Royal2000H is this still something that you'd like to see? SZ has an automatic find-better-subtitles feature now, as well as manual subtitle selection.

**Comment by Ruvetuve** [comment]
How do you select manual a subtitle. Through the Channel menu right. I don't see any user going  through the Channel menu, too much of a hasle.

**Comment by pannal** [comment]
@Ruvetuve and how does that relate to this ticket? Would auto-searching for a subtitle when playing a video help then, in any way? SZ already is auto-searching your subtitles periodically and even tries to find better ones over time. Do you really think this would still be a useful option? Manual subtitle selection on the start of a video is not possible.

**Comment by Ruvetuve** [comment]
I think the auto search is enough. Just checking.

**Comment by Royal2000H** [comment]
@pannal Absoultely, it would still be useful.
I just ran into the issue the other day where the subtitles weren't matched well (I had replaced a previous poor release with another release of the same movie so the subs probably matched the old release). Despite any and all auto functionality that may exist in Sub-Zero, I had to go into the Sub-Zero channel, go to the movie, and click "Refresh" or "Auto-Search" (I don't remember which I clicked? and frankly I don't know the difference). Then I went back to the movie after waiting under a minute and just like that, I had good subs.

That's not a terrible experience. But a BETTER experience would be if, upon starting the movie, Sub-Zero would run the same command that I manually ran by going to the channel. When I realize the subtitles don't match well, I back out of the video playback to the movie info screen (stop playback), and immediately press play again on the movie and the new subtitles are available to be cycled through.

**Comment by pannal** [comment]
OK. We'd need some sort of timeout then, after the playback, to ensure it doesn't get spammed too often. I'd recon a 5 minute cooldown after a playback, with an auto-search on an item.

**Comment by pannal** [comment]
Should be done in 1.4.27.957

**Comment by pannal** [comment]
It's only refreshing the item, though, not force-refreshing. Please report back if you still need that.

**Comment by Royal2000H** [comment]
Hi @pannal 

First off, thanks for implementing! I'm under the belief it was working for the most part for a while.

Today, I was just watching a TV show for ~8-10 minutes. No subtitles. I exited out of it and came back in to play it. Still no subs. I tried playing it from both OpenPHT and PMP (in case that matters), but it never refreshed subs. I went into sub-zero and selected "Refresh" (not "Force-find") and it found subtitles immediately.

I just checked my setting for searching on play, it is: "hybrid: current item or next episode"
This must be newer than when I last set it because I don't remember that option, but it's cool. Shouldn't that have searched for it? It also happens to be the most recent episode of the series. (As an aside, how does it choose the current item "or" next episode?)

**Comment by pannal** [comment]
Which version of SZ are you running?

hybrid mode refreshes either the current movie or the next episode.
I think you might want to enable hybrid-plus, which refreshes the current item and the next episode (if it's a TV series and there is a next episode).

**Comment by Royal2000H** [comment]
I'm on Version 2.0.26.1695. With Hybrid mode.
I can confirm it still does not download/refresh any subtitles when I play. But if I go click refresh on the episode in the SZ channel, it gets it without a problem.

I just changed to Hybrid plus to see if it'll make a difference (though I doubt it).

**Comment by pannal** [comment]
Sorry for the long response time.

Can you provide logs after you play an item? This feature has been working for what feels like ages now.
I can only imagine that some core functionality is broken, that causes this to happen.

**Comment by Royal2000H** [comment]
Absolutely. I'm away from the server and connection for the next 3-5 weeks though. I'll update once I'm back. Thank you!

**Comment by pannal** [comment]
Great, I'll await your logs :)
