### ISSUE TITLE
Add option to automatically convert subtitles' framerate based on the video file

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#331]

**Comment by ukdtom** [comment]
Ref: #290

**Comment by pannal** [comment]
Why? I already have the FPS information for both.

**Comment by ukdtom** [comment]
Heh, and correct, you got it from PMS, so no need to extract the same info twice ;)

**Comment by pannal** [comment]
This is not very feasible, as the FPS information provided by the providers is often wrong.
