### ISSUE TITLE
Polish encoding wrong after last release

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#333]

**Comment by pannal** [comment]
There may be a regression in the last release. iso-8859-2 is tried before windows-1250.

**Comment by pannal** [comment]
Please try https://github.com/pannal/Sub-Zero.bundle/archive/polish_encoding.zip

**Comment by burzka** [comment]
This version works excellent. No more encoding issues.

**Comment by havran** [comment]
I have same problem (with czech or slovak subtitles). polish_encoding.zip version work but with high CPU usage. Then i install latest version and change only one file and now all work as expected. Thanks.

**Comment by pannal** [comment]
@havran The high CPU usage can occur after upgrading to a development release after having installed the official release, as it's running the find missing subtitles task on boot. Installing latest version and replacing one file doesn't change anything.

**Comment by burzka** [comment]
@pannal 24h after fresh install of polish_encoding I still have a high CPU usage too. PlexScriptHost process consume ~20-30% of my CPU. SZ shows "idle" status. When I turn off SZ, CPU usage go down.

**Comment by pannal** [comment]
Yep, fixes in #337, current develop-2.0 has the changes.
