### ISSUE TITLE
[Enhancement Request] Increase "List $language subtitles" timeout

### ISSUE THREAD

**Issue by chmercesmoreira** [pannal/Sub-Zero.bundle#334]
Hello, I'm trying to use the option "List $language subtitles" to manually select a subtitle from the list but as my files are located on a remotely mounted disk it tooks more than 15 seconds to read the file and I think that 15 seconds is the timeout configured to show the message: This channel is not responding. I want to know if it is possible to increase this timeout to 60 seconds or more.

**Comment by pannal** [comment]
Hmm. Can you provide DEBUG logs for that?

**Comment by chmercesmoreira** [comment]
Should I enable some verbose logging before? Or the default log preset if enough?

**Comment by pannal** [comment]
Yes, in SZ's settings set the log level to DEBUG. No changes needed in PMS itself.

**Comment by chmercesmoreira** [comment]
Log didn't produced any errors, only commun debug and warning messages. I think my bug is actually related with the fact that I'm running Plex behind a reverse proxy and Cloudflare. This has nothing to do with your plugin, thank you.

**Comment by pannal** [comment]
In current develop-2.0 pre-release (2.0.26.1689 DEV) there is an option to increase the timeout for PMS API requests to a maximum of 45 seconds. I don't know if your issue is related, but you might want to try the new release.

**Comment by chmercesmoreira** [comment]
The bug is not related with the timeout default time as I was thinking, it is related with this weird bug that I wrote above.

**Comment by pannal** [comment]
Yes, it may be, that the webgui times out quicker than SZ does when requesting stuff. Nothing I can do about that, unfortunately.

**Comment by pannal** [comment]
try `large_client_header_buffers 4 32k;` in NGINX.

**Comment by chmercesmoreira** [comment]
I think this solved the problem with the larger header request, but know I'm back with the timeout problem, I will give a try to this pre-release version, Is it possible to install it from inside the plugin itself? Or should I manually install it?

**Comment by pannal** [comment]
You have to manually install it. Download [this](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip), then follow [this](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation).

**Comment by pannal** [comment]
When installed, you'll notice it immediately. Then you can set the timeout in SZ's preferences (to 45 max).

**Comment by pannal** [comment]
If that doesn't resolve the issue, I can add an option to skip file scanning inside that particular menu item. That'll remove some of the information displayed, but will most likely fix your problem.

I'd call that "Low impact mode (for remote filesystems)" and might use that for other optimizations for people with remotely mounted filesystems.

**Comment by chmercesmoreira** [comment]
I'm doing the tests right now, I'll update here with the results.

**Comment by pannal** [comment]
You might want to join [the Slack of Sub-Zero](https://szslack.fragstore.net) so we can investigate this more quickly.

**Comment by pannal** [comment]
OK, issue resolved by using the new low impact mode.

**Comment by chmercesmoreira** [comment]
Thank you @pannal , everything working properly now.
