### ISSUE TITLE
Massive OpenSubtitles errors in the last days

### ISSUE THREAD

**Issue by edgibba** [pannal/Sub-Zero.bundle#336]
Plesa, I need some help ! I ´d installed subzero agent , but it seems not working properly.
I send my log where there are multiples Errors messages. Could you help me ?

[com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/1234489/com.plexapp.agents.subzero.log.txt)

**Comment by pannal** [comment]
@opensubtitles I'm getting reports of dozens of users who have this problem recently.

Most of them get: `ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Not Available>`

@edgibba the other "decompose" error will be fixed in the next version.

**Comment by opensubtitles** [comment]
recently we got problems with one of the API server (it is on 2 webservers). It should be OK now.

**Comment by pannal** [comment]
OK thank you @opensubtitles I'll report back.

**Comment by pannal** [comment]
Please reopen if this still happens
