### ISSUE TITLE
Languages reset to English only

### ISSUE THREAD

**Issue by ppucci** [pannal/Sub-Zero.bundle#338]
Hiya!

Sometime these past few days I noticed my subzero wasn't pulling subtitles in Portuguese (Brazil) anymore, so I went checking the configs and noticed it was not selected anymore. It can only have been changed after an update.

**Comment by cre8ivejp** [comment]
After the update I had the same issue.
I had to set the languages again.

**Comment by pannal** [comment]
Yes, that was intended, as there were problems with the language selection after the 2.0 release for a bunch of people. A clean reset was necessary. [I mentioned that in the forums](https://forums.plex.tv/discussion/comment/1500773/#Comment_1500773), but forgot to mention it in the changelog itself.
