### ISSUE TITLE
Unable to download subs

### ISSUE THREAD

**Issue by hofwing** [pannal/Sub-Zero.bundle#341]
So, I installed the sub-Zero.bundle on my PMS a few weeks ago and tried to refresh metadata on some shows and movies but it doesn't download any subs (despite being a opensubtitles.org VIP) from the logs I'm guessing it may have something to do with my metadata 

ERROR (model:205) - Cannot read model from /Users/Filip/Library/Application Support/Plex Media Server/Metadata/Movies/b/a9d98c50c2dceb0815e3dc938f1710b8b022b31.bundle/Contents/com.plexapp.agents.subzero

I have tried to delete the subzero cache and also cleared metadata from Plex, but still no luck

For the sake of it, I installed a completely fresh version of PMS on another computer and tried the Sub-Zero.bundle to retrieve metadata but got the same error message

What can I do?
[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/1274666/com.plexapp.agents.subzero.txt)

**Comment by pannal** [comment]
Why is this closed?

**Comment by hofwing** [comment]
Sorry, I'm sort of a n00b at this so I closed the issue when it, after countless retries all of a sudden started working

Now I have another issue, regarding loging towards opensubtitles.org.
Should I create a new issue?
