### ISSUE TITLE
English - SRT Forced is chosen before english sub

### ISSUE THREAD

**Issue by minihessel** [pannal/Sub-Zero.bundle#344]
I dont want to use FORCED subitltes at all, still, it get's chosen if there exists a forced sub in the movie file. Have tried around with all settings. Is this an issue?
<img width="258" alt="screen shot 2017-09-07 at 18 47 00" src="https://user-images.githubusercontent.com/5398823/30174976-34837710-93fd-11e7-9f60-b7da124453f8.png">

In the logging I can see that sub-zero downloads a subtitle, but still, the english FORCED one is the one being chosen? Is there an option for sub-zero to ALWAYS ignore forced subtitles? If not, it would be wonderful to have that feature. Many not native english speakers want english subs.

Ignoring all the subs in the MKV file could also be an option

Edit: if I uncheck this box 
<img width="492" alt="screen shot 2017-09-07 at 19 07 15" src="https://user-images.githubusercontent.com/5398823/30175686-d6be2780-93ff-11e7-98fb-3719c0880359.png">

It seems to do the job correctly. Is that the way it's supposed to be?

**Comment by pannal** [comment]
Seems like. It's definitely out of SZ's hands.

You might want to talk to the Plex guys about this.
