### ISSUE TITLE
Modified subs get redownloaded over and over

### ISSUE THREAD

**Issue by DDRobo7** [pannal/Sub-Zero.bundle#346]
I only use Subtitles.org as a SZ source but I have noticed that some subs ALWAYS get updated.

As I have a VIP account on Subtitles.org I sometimes get the VIP sub but then I get the non-VIP subs and the update seems to be an alternation between these 2 subs when I compare the 2 files.

Example: (Snippet from sub file for "Castlevania.S01E01.720p.WEBRip.x264-STRiFE.en.srt")

File.1
---
1172: Please rate this subtitle at www.osdb.link/*****
1173: Help other users to choose the best subtitles
---

File.2.
---
1172: Support us and become VIP member
1173: to remove all ads from www.OpenSubtitles.org
---
Now sometimes a new download has contained modified timing on some lines so some updates are needed but a function to prevent "round-robin" download of two versions of the same file would be nice.

**Comment by pannal** [comment]
Sorry for the answering delay. Can you provide SZ DEBUG logs after that happens? (See the wiki for that, please)

**Comment by DDRobo7** [comment]
Hello.

I hope These are the files you asked for.

I have noted the file “The.Tick.S01E02.720p.WEBRip.x264-STRiFE.en.srt” doing this thing at the time 14:59:04 (File create time) and during the time I was copying the files a new create date was set to 15:12:05.

The file that was created at 14:59:04 has been copied out as well as a previous file and two modified (by timestamp) following files, 4 in total where the oldest one ends with an .1 in the filename and the newest with .4.

Thanks for a wonderful program =)





Från: pannal<mailto:notifications@github.com>
Skickat: den 11 oktober 2017 02:34
Till: pannal/Sub-Zero.bundle<mailto:Sub-Zero.bundle@noreply.github.com>
Kopia: DDRobo7<mailto:kk37gu@hotmail.com>; Author<mailto:author@noreply.github.com>
Ämne: Re: [pannal/Sub-Zero.bundle] Modified subs get redownloaded over and over (#346)


Sorry for the answering delay. Can you provide SZ DEBUG logs after that happens? (See the wiki for that, please)

**Comment by pannal** [comment]
Hey, I think you can't attach stuff to the github response email. Please attach them here.

**Comment by DDRobo7** [comment]
I’ll try again =)

Från: pannal<mailto:notifications@github.com>
Skickat: den 12 oktober 2017 02:01
Till: pannal/Sub-Zero.bundle<mailto:Sub-Zero.bundle@noreply.github.com>
Kopia: DDRobo7<mailto:kk37gu@hotmail.com>; Author<mailto:author@noreply.github.com>
Ämne: Re: [pannal/Sub-Zero.bundle] Modified subs get redownloaded over and over (#346)


Hey, I think you can't attach stuff to the github response email. Please attach them here.

**Comment by DDRobo7** [comment]
Trying again

[Logs_171011_15-19-53.zip](https://github.com/pannal/Sub-Zero.bundle/files/1378275/Logs_171011_15-19-53.zip)


[The.Tick.S01E02.720p.WEBRip.x264-STRiFE.en.srt.zip](https://github.com/pannal/Sub-Zero.bundle/files/1378276/The.Tick.S01E02.720p.WEBRip.x264-STRiFE.en.srt.zip)

**Comment by pannal** [comment]
Please set SZ's log level to DEBUG (it's currently on WARNING).

**Comment by DDRobo7** [comment]
Will do,

**Comment by DDRobo7** [comment]
Here we go, this time it is our old friend Castlevania.S01E02.720p.WEBRip.x264-STRiFE.en.srt that changed.
[Logs_171016_18-36-53.zip](https://github.com/pannal/Sub-Zero.bundle/files/1388323/Logs_171016_18-36-53.zip)

**Comment by pannal** [comment]
I think you have that setting off: `Scan: include external subtitles (metadata/filesystem, don't download if existing)`. Please enable it, then SZ will honor existing subtitles on disk and not re-search for them.

**Comment by DDRobo7** [comment]
Ok but will that not also stop the downloading of subs in other languages ?

**Comment by pannal** [comment]
No, that's specific per language. If a language is missing, it tries to find it always. That setting is just to tell SZ that it should honor what it locally found for the next missing subtitles scan.

**Comment by DDRobo7** [comment]
OK, Thanks =)

Keep up the good work!
