### ISSUE TITLE
[REQ] Force a language on 'Unknown - SRT/VTT'

### ISSUE THREAD

**Issue by Mirabis** [pannal/Sub-Zero.bundle#349]
I'm using mp4automator to extract the embedded subs to .vtt, which imports through Sonarr.

However, doing this in plex it shows language 'unknown'  - after which Sub-Zero downloads both English & Dutch (as configured). But could you make a setting that changes/allows Unknown subs to default to English?

**Comment by pannal** [comment]
You can circumvent this behaviour by adding arbitrary attributes to your subtitle file. Try `filename.en.custom.srt`, it should be picked up by SZ as English.

**Comment by Mirabis** [comment]
Hi @pannal ,

Thanks, not really the solution i was looking for - but i'll just modify the mp4automator script to always append .en. To the subtitle. Quick and dirty fix

**Comment by pannal** [comment]
You can try adding "en.embedded", that way you can have a version from SZ, which downloads as "en.", and your extracted subtitle at the same time.
