### ISSUE TITLE
Cannot read model from /var/lib/plexmediaserver/....

### ISSUE THREAD

**Issue by tknikolov** [pannal/Sub-Zero.bundle#350]
Hello,

I've had a storage crash and I had to restore all my media from backup. I decided to go the clean route and installed a brand new Plex Media Server - just in order to avoid issues with restored Plex from my old machine.

After I installed Plex, added all my Media files, created the Libraries, etc, I decided it's finally time to install Sub-Zero again. However, I don't think it is working, and here's the error I am getting every time I hit refresh metadata on an item:

`2017-09-27 10:55:55,784 (7f7ab18d9700) :  ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/Movies/e/03e0c5be44dfd354bc9ec16c6ecf5023633274c.bundle/Contents/com.plexapp.agents.subzero
`

`2017-09-27 10:04:01,189 (7f7ab18d9700) :  ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/8/02e33041ba72d4ebea568c279570535b4d58ff7.bundle/Contents/com.plexapp.agents.subzero`

I read somewhere that this is due to Library f**k up, but I don't think it's the case with me, since it's a brand new PMS with a brand new library. Any help would be appreciated!

**Comment by pannal** [comment]
That error is common and shouldn't affect SZ as far as I know.

Can you please attach DEBUG logs?
