### ISSUE TITLE
Support Legendei.com

### ISSUE THREAD

**Issue by Ack0** [pannal/Sub-Zero.bundle#351]
I am a big fan and admirer of Legendas.TV, but in recent days they are taking too long to release the subtitles, around 7 to 10 days for some TV series. They were faster.

However, Legendei.com releases the subtitles the next day, or a maximum of four days.

I would love to know how to code and just send a pull request to you, but as I do not know, here is my request.

Regardless of the answer (whether positive or negative), thank you for this wonderful tool.

**Comment by pannal** [comment]
Do they have an open API? If not, it might be out of scope for Sub-Zero itself, as it's only maintained by one person (me). You might have better luck proposing that feature to the underlying library, [subliminal](https://github.com/Diaoul/subliminal).

**Comment by Ack0** [comment]
I think they don't have an API, unfortunately.
I'll try proposing this to subliminal then.
Anyway, thank you, pannal.
