### ISSUE TITLE
Not downloading any Subtitles

### ISSUE THREAD

**Issue by antigravity83** [pannal/Sub-Zero.bundle#352]
Hi

I'm new to Sub-Zero so apologies if this is a simple issue- but I can't seem to get any subtitles to download?

Logs attached. 

Any help would be great

Thanks

David
[Logs_171001_11-56-11.zip](https://github.com/pannal/Sub-Zero.bundle/files/1346867/Logs_171001_11-56-11.zip)

**Comment by antigravity83** [comment]
Any help would be great. Have gone through the readme and completed all the settings fields.

**Comment by pannal** [comment]
Sorry for the answering delay. You seem to have problems connecting to OpenSubtitles.

@opensubtitles can you check on that? He/she's getting `SSLError: ('The read operation timed out',)` when trying to log in via the XMLRPC.

**Comment by opensubtitles** [comment]
Hi, I tried now, and it works ok. Uptime is 98%, so try again

**Comment by antigravity83** [comment]
Thanks, I think it is working now. Cheers
