### ISSUE TITLE
No subtitles downloaded at all

### ISSUE THREAD

**Issue by ThatFatPat** [pannal/Sub-Zero.bundle#353]
Sub-Zero worked on other computers.
Never worked on current computer.
I don't know what the problem is...
I completely uninstalled Plex and deleted all data and still no dice.
Here are my logs: (Plex Media Server log first. Search page for "Subliminal Logs" for subzero logs)
https://pastebin.com/NpkGX3Q7
Thanks!

**Comment by ThatFatPat** [comment]
I went to all the trouble to install linux, as it might change something. Anything.
No dice.

**Comment by pannal** [comment]
Sorry for the answering delay. Please read up on the [wiki](https://github.com/pannal/Sub-Zero.bundle/wiki) on how to post Sub-Zero specific logs, then attach them here.

**Comment by ThatFatPat** [comment]
I did get those logs. I'll try to find them
