### ISSUE TITLE
[REQ] Small changes to options concerning recent items

### ISSUE THREAD

**Issue by mbnn** [pannal/Sub-Zero.bundle#354]
As discussed on Slack: Can i request to change/add two options in Sub-zero: 1) Item age to considered as recent can now be set to max 6 weeks (maybe make that max 12 so its 3 months? sometimes subs come out way later), 2) Periodically search for is now either 1 or 3 hours, could you pls add 2 hours to that? :grinning: I think that’s a decent middle mode in most cases.

**Comment by pannal** [comment]
1) yes
2) yep

Will do in the next release.
