### ISSUE TITLE
Dont Download Automaticly

### ISSUE THREAD

**Issue by filoor** [pannal/Sub-Zero.bundle#356]
Hi,

Is thear also a way to select only specific movies or tv-shows to download subs for
and not every movie and tv-show

**Comment by Ruvetuve** [comment]
You can put in a sub ignore file in the directory for which you don't want to download subs. Upper directories will count for all sub directories. Have a look at

**Comment by filoor** [comment]
Hi @Ruvetuve 

Thank you for Fast response.
So lets say if i ignore my hole tv-shows library and then go to a specific 
Tv-show season in "browse all function of sub-zero"  and go the a tv-show that is in that same library
and click on auto-find subtitles for season 3 will it search for it 
or will it not because i selected ignore my hole library ?

**Comment by Ruvetuve** [comment]
I think it would be ignored, can you test? I can only test this in a few days.

**Comment by pannal** [comment]
The auto-find functions will not work as they will honor the ignore file/soft menu ignore. The manual subtitle search will work.
