### ISSUE TITLE
Subtitles stop working after 3-4 lines

### ISSUE THREAD

**Issue by QuintenJustus** [pannal/Sub-Zero.bundle#357]
I'm not sure if this issue is entirely related to Sub-Zero or not, but I highly suspect it.

**Comment by ukdtom** [comment]
It's not, but a PMS issue

**Comment by pannal** [comment]
Can you attach a subtitle where this happens and specify the line when it happens at? I want to rule out any encoding issues.

**Comment by QuintenJustus** [comment]
It happens with every subtitle downloaded by Sub-Zero, I disabled OpenSubtitles so that can be ruled out. I noticed when I tried to delete and add the "Series" library again that subs aren't downloading now. Or not saving, however I double checked all the settings. Subs should be directly next to the media.

**Comment by pannal** [comment]
So it doesn't happen with subtitles downloaded by the OpenSubtitles addon?

Again: please attach one of those subtitles here and tell me which line it stops working at.

**Comment by QuintenJustus** [comment]
When I was only using the OpenSubtitles addon some time ago, I never experienced it. 
Attached is the subtitle you requested, but it stops working after a few lines. Regardless of where I start the movie, I can go to 1/2 of the movie, then it will work, then stop again, then go to 3/4 of the movie and then the same story. It should also be noted that this is the case when I select another subtitle file/language (downloaded via Sub-Zero).

I can't add a .srt file so I'll zip it.
[Subtitle sample.zip](https://github.com/pannal/Sub-Zero.bundle/files/1376006/Subtitle.sample.zip)

**Comment by QuintenJustus** [comment]
Update: 
I tried the subs with the original video file with VLC player. Another subtitle file was already there, in the video itself. I think atleast since there are no other subtitle files in the folder except for the ones downloaded via SZ.

**Comment by ukdtom** [comment]
@QuintenJustus 

If you are a PlexPass user, then try https://forums.plex.tv/discussion/comment/1535240/#Comment_1535240

It's a known issue!

If not a PlexPass user, then downgrade, but unsure to what version sadly :(

**Comment by QuintenJustus** [comment]
Ah, that's unfortunate... Oh well, glad to know it isn't due to Sub-Zero.
Keep up the good work you all!
