### ISSUE TITLE
HUGE list of subtitles for one EP of a TV show

### ISSUE THREAD

**Issue by lgromb** [pannal/Sub-Zero.bundle#358]
Beside all that can be said under this, thanks to the dev team for that awesome addon with seamless integration with Plex.

Here's the issue I face : I completly trust Sub-Zero for finding my subtitles. It works as expected but I noticed a strange behavior.

Take the exemple of TBBT. When I want to watch S07E10, in the subtitles selection menu of plex, i can select all of the subtitles for the entire season ! The files are named correctly as you can see here :

![2017-10-11 10_40_16-season 7](https://user-images.githubusercontent.com/7590118/31430254-ad9a75d0-ae70-11e7-8c2e-c2f6a2a2ad2e.png)

And in Plex, on the episode selection menu :

![image](https://user-images.githubusercontent.com/7590118/31430297-c1a33ddc-ae70-11e7-9edb-6bde176f73d0.png)

Each subtitle matches an episode, and you can't see it in Plex as they're all named "English" but in Kodi they refer as "subtitle00, subtitle01", etc.

What settings do I need to tinker with in order to have the right subs for the right EP ? It happens on all of my TV shows...

Thanks a lot in advance !

**Comment by pannal** [comment]
Can you try the current develop-2.0 branch?

Also what's your `Scan: which external subtitles should be picked up?` set to? If it's `any`, it will pick up other subtitles in the current folder. I'd recommend `strict`.

**Comment by lgromb** [comment]
Hi and thanks for the advice, I just changed that setting but I'm not sure how to apply it to the TV Library. I restarted all and hope it'll trigger itself haha, do you have a way to trigger it directly ? Thanks !

**Comment by pannal** [comment]
You can refresh the metadata of the whole library, then SZ should pick up the correct subtitles from disk.

**Comment by lgromb** [comment]
Yes that made the trick !!! At least on TBBT the issue is gone, will have to check back on other media as well but that was that simple, thanks a lot !!
