### ISSUE TITLE
nordic letter 'å' is turned into the letter 'ĺ'.

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#361]
big Å also turns to big Ĺ

it's not for all downloaded subtitles but for a significant portion for it to be very noticeable.

I've temporarily fixed it by having a script that manually replace these characters but a longterm fix would be nice?

~~can the "Call this executable upon successful subtitle download (see Wiki for det)" box be used in any way? I can't find anything about this on the wiki.~~

found out how to use a script on the just added subtitles and I now run all my subtitles through a sed script.

**Comment by pannal** [comment]
Can you check the original subtitles from the provider? Usually the error is in the original file and I can add an automatic replacement to SZ's modification framework.

Which language are we talking about?

**Comment by pannal** [comment]
@KBlixt ?

**Comment by KBlixt** [comment]
swedish. and i have not confirmed against the source but it's a significant portion of all of the downloads, and when doing downloads manually for a while have given me 0 of these issues.

**Comment by pannal** [comment]
OK. Please try to confirm if it's SZ adding those character issues or if that's from the original subtitle.

Nevertheless, if you enable `Fix common OCR errors in downloaded subtitles`, or you go to the subtitle modification menu and apply it manually, at least the `ĺ` should turn into `å`. I've added the uppercase versions of this for the next SZ version into the Swedish OCR fixes dictionary.

Do you see any other character issues I can fix for Swedish?

**Comment by KBlixt** [comment]
Fix common OCR errors in downloaded subtitles is already enabled. and manually fixing this for all affected movies is not an alternative. there are 100s, luckily I managed to find out how to execute a script on the downloaded subtitles so for me personally this isn't an issue any longer.

everything else seems fine in Swedish.

**Comment by pannal** [comment]
That's weird. If that's already enabled, it should at least fix the lowercase `ĺ`. Are you running the current version? Can you attach one of those subtitles so I can manually check?

Of course manually fixing them via the menu all the time is not what I meant, this has to work automatically (as it does for other languages).

**Comment by KBlixt** [comment]
the Swedish subtitle for minions had this error, that was the movie I noticed it on before I added the script and re downloaded all my subtitles. I'm don't have time to find any more for now I have a big test on Tuesday, but then I might be able to find more examples.

I should be running the latest version, plex says it can't find any updates anyway.

**Comment by pannal** [comment]
There's a new version out. `Å = Ĺ` shouldn't happen anymore, either.
