### ISSUE TITLE
Items with missing subtitles show Portuguese, even though they're not missing

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#366]
Likely related to `Treat IETF language tags as ISO 639-1 (e.g. pt-BR = pt)`

**Comment by beachfork** [comment]
I have this issue running the latest Sub-Zero 2.0.33.1871, I have a whole season with subtitles already downloaded by Sub-Zero, but it seems that the pt-BR subtitles are not detected as present.

**Comment by pannal** [comment]
Can you provide logs (log level in SZ's settings set to DEBUG) after hitting refresh on one of those episodes?
