### ISSUE TITLE
Correctly skip searching for subtitle if already existing

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#373]
Even with both "Scan: " options disabled, SZ should skip downloading a new subtitle if it already has one in its local storage (and the file exists?)

**Comment by Nottt** [comment]
Also take in consideration that subtitles may be named .por. instead of .pt-BR. or similar for other languages.. 

Also would be cool if subzero were smart enough to know about .forced.lang.* subtitles and if it's the only present then search for non-forced subtitles.

Plex does recognize this format .forced.lang.*

**Comment by Nottt** [comment]
Including the forced subs part ? :P

**Comment by pannal** [comment]
You want to use lang.forced not forced.lang. That may be the cause of the issue of the other ticket.

**Comment by pannal** [comment]
Updated develop-2.0. It now ignores forced subtitles in its local assessment and treats them as non existant if the `Only download foreign/forced subtitles` option isn't enabled, thus searching for new subtitles.

You can just re-download the develop-2.0.zip to get that change.

**Comment by pannal** [comment]
Updated develop-2.0 to 1753 DEV. IETF handling has been separated into two settings. One controls how IETF (pt-BR) languages are displayed in Plex, the other controls how SZ should handle them.

**Comment by Nottt** [comment]
@pannal I don't really mind either of them, it's just that sometimes current existing subtitles and ones that come from internet aren't IETF but in ISO code, but either way I don't mind. I actually prefer to keep them in IETF. 

Also I have changed my subs to long.forced already. Thanks !!

**Comment by pannal** [comment]
Yeah that's why I've changed the IETF settings and split them up into two separate ones.
If you keep the first one off, it'll download pt-BR if por already exists. If you turn it on, it won't.

Can this be closed?

**Comment by Nottt** [comment]
@pannal  Yes it can, it seems to be working on Sub-Zero 2.0.29.1756. Thanks and sorry for the delay.
