### ISSUE TITLE
When using a custom domain, the log url is broken

### ISSUE THREAD

**Issue by Nottt** [pannal/Sub-Zero.bundle#377]
This is really a small bug, but just FYI when you use a custom domain the logs url looks like :

`https://domain.com:None/video/subzero/logs?X-Plex-Token=xxxx`

To access the logs you have to go remove `:None` and it will works fine. 

Really small bug, but just letting you guys know..maybe it doesn't even worth the effort to fix it lol :p

**Comment by pannal** [comment]
Great find!

That URL works without any port?

**Comment by pannal** [comment]
I've pushed a fix to develop-2.0. Can you try?

**Comment by Nottt** [comment]
Yes that URL works without any port, I'm going to test this tomorrow and edit this answer

**Comment by Nottt** [comment]
It's working now in the latest master release. Thanks and sorry for the delay!
