### ISSUE TITLE
Donwload same subtitle all the time

### ISSUE THREAD

**Issue by rjulie95** [pannal/Sub-Zero.bundle#378]
Hi,

See in Addic7ed, subzero download the same subtitle all time : 
![image](https://user-images.githubusercontent.com/8410772/32373538-01dd15fe-c09a-11e7-81b7-4128241c66ce.png)

In sub sero option, i have this :  

![image](https://user-images.githubusercontent.com/8410772/32373563-243d4bc8-c09a-11e7-9fb3-81735ad3924f.png)

And in my file system : 

![image](https://user-images.githubusercontent.com/8410772/32373607-554733f0-c09a-11e7-8a6b-5e9125037fc8.png)

I dont undestand wath is wgrong in my option -:(

Do you have idea ?

I use the last version of sub zero 

Thank

**Comment by pannal** [comment]
Can you attach your log zip?

**Comment by rjulie95** [comment]
The log file

[Logs_171103_17-55-55.zip](https://github.com/pannal/Sub-Zero.bundle/files/1441850/Logs_171103_17-55-55.zip)

**Comment by pannal** [comment]
Can you go to the Advanced menu in the Sub-Zero channel, click on "restart", then post the logs again, please?

**Comment by rjulie95** [comment]
Yes, new log file
[Logs_171103_19-51-39.zip](https://github.com/pannal/Sub-Zero.bundle/files/1442200/Logs_171103_19-51-39.zip)

**Comment by pannal** [comment]
Weird, looks fine. Can you now refresh a media item you want subtitles for and post the logs again?

**Comment by rjulie95** [comment]
I activacte option : Search for missing subtitles

New log

[Logs_171103_20-18-40.zip](https://github.com/pannal/Sub-Zero.bundle/files/1442249/Logs_171103_20-18-40.zip)

**Comment by rjulie95** [comment]
Same issue again

![image](https://user-images.githubusercontent.com/8410772/32392253-2a45188a-c0d5-11e7-9942-5476c47a5860.png)

**Comment by rjulie95** [comment]
New log

[Logs_171103_20-36-12.zip](https://github.com/pannal/Sub-Zero.bundle/files/1442293/Logs_171103_20-36-12.zip)

**Comment by pannal** [comment]
I can't really make anything out of those logs. I can see an authentication error for addic7ed, though: 
`AuthenticationError: rjulie`

**Comment by pannal** [comment]
It also seems like you're locked out of the providers currently. You might want to disable SZ for 24 hours.

Then please *refresh* *one* media item from the PlexWeb interface ("refresh metadata").

The logs are too full of connection errors, I can't find anything helping in there right now.

Also make sure your addic7ed login is correct.

**Comment by rjulie95** [comment]
I just removed The Bold type and now all it's ok

Very strange

**Comment by pannal** [comment]
What did you do?

**Comment by rjulie95** [comment]
All the time the same problem with the same file Bold Type, i just removed this file and i don't any problem

**Comment by pannal** [comment]
Interesting. Can you re-add the Bold Type media file and post your logs? Otherwise, please close this issue.
