### ISSUE TITLE
Sub-zero not downloading subtitles

### ISSUE THREAD

**Issue by neepz** [pannal/Sub-Zero.bundle#381]
Any help? I'm looking at the logs but can't find what's wrong with it.

https://pastebin.com/vUsLFHQV

**Comment by pannal** [comment]
- Your authentication with legendas.tv fails, please check your credentials
- you've got permission errors: `IOError: [Errno 13] Permission denied: u'/home/micmacs/torrents/rtorrent/Movies/Still Walking (2008)/Still.Walking.2008.720p.BluRay.x264-EbP.en.srt'`

**Comment by neepz** [comment]
changed the credentials although they were checking.
About the permission errors I did a sudo chmod a+rwx /home/ so I could access everything and still nothing.

**Comment by pannal** [comment]
Then I'll need new logs :)

It's generally a good idea to add the Plex user to your directory owner group and chmod 775.

**Comment by neepz** [comment]
Thanks for your help, pannal!
I installed it through the quickbox script because I'm pretty new to all this. Do you know how I add the user to my directory owner group?

**Comment by pannal** [comment]
`adduser plex micmacs` I guess. You'll also need to instruct your download program to use chmod 775.

**Comment by pannal** [comment]
Ah and you need to do that recursively: `chmod -R 775 /home/micmacs/torrents/rtorrent`.

**Comment by neepz** [comment]
tried what you said:
with legendas.tv active (I did check the credentials twice, created a new account but took a quick look at the log and saw that it still says wrong credentials) 
https://pastebin.com/GSehVyJy


without legendas.tv: 
https://pastebin.com/G9iR2Fkh


Thanks again, pannal!

**Comment by neepz** [comment]
plex       985  0.0  0.0   4512   760 ?        Ss   Nov05   0:00 /bin/sh -c /usr/lib/plexmediaserver/Plex\ Media\ Server
plex       986  0.4  0.3 777580 54352 ?        Sl   Nov05   8:14 /usr/lib/plexmediaserver/Plex Media Server
plex      1174  0.1  0.6 1854488 108116 ?      SNl  Nov05   2:16 Plex Plug-in [com.plexapp.system] /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.9.4.4325-1bf240a65 /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/System.bundle
plex      1575  0.0  0.0 294088  9876 ?        Sl   Nov05   0:36 /usr/lib/plexmediaserver/Plex DLNA Server
plex      1579  0.0  0.0 233620  4664 ?        Sl   Nov05   0:02 /usr/lib/plexmediaserver/Plex Tuner Service /usr/lib/plexmediaserver/Resources/Tuner/Private /usr/lib/plexmediaserver/Resources/Tuner/Shared 1.9.4.4325-1bf240a65 32600 /waitmutex
plex      3567  0.8  1.2 2226720 206204 ?      Sl   12:56   1:54 Plex Plug-in [com.plexapp.agents.subzero] /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.9.4.4325-1bf240a65 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle
plex     12235  0.3  0.2 959668 48140 ?        Sl   16:16   0:02 Plex Plug-in [com.plexapp.agents.imdb] /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.9.4.4325-1bf240a65 /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/PlexMovie.bundle
plex     12288  0.2  0.2 952080 44300 ?        Sl   16:17   0:01 Plex Plug-in [com.plexapp.agents.localmedia] /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version 1.9.4.4325-1bf240a65 /usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/LocalMedia.bundle
root     12943  0.0  0.0  14232   980 pts/2    S+   16:30   0:00 grep Plex



AND

4.0K drwxrwxr-x   2 micmacs micmacs 4.0K Nov  6 12:54 .
 12K drwxrwxr-x 246 micmacs micmacs  12K Nov  6 13:17 ..
4.4G -rwxrwxr-x   2 micmacs micmacs 4.4G Nov  6 12:53 Still.Walking.2008.720p.BluRay.x264-EbP.mkv

**Comment by pannal** [comment]
Hmm, as far as I can tell, that should work. What does `groups plex` say?

**Comment by neepz** [comment]
plex : plex video micmacs

**Comment by pannal** [comment]
OK, then I'm not sure what's wrong. Looks fine to me. Perhaps restart the PMS? Otherwise I can't help you - as long as Plex doesn't have the permission to write a file there, it's out of my hands.

**Comment by neepz** [comment]
Ashamed to say that I did a reboot on the server and it worked. 
Thank you so much for your help and your work, pannal. 
Closing the issue.

**Comment by pannal** [comment]
Please ensure, that newly created directories/files get created with chmod 775. Your downloader(s) (rutorrent?) should have an option for that.

**Comment by pannal** [comment]
`chmod -R g+s /home/micmacs/torrents/rtorrent` should do the trick I think.

**Comment by neepz** [comment]
Thanks mate!

**Comment by neepz** [comment]
pannal, somehow I did what you said, rebooted the server and the weird thing is: plex is able to download subtitles for the old movies but the new ones it won't. Here is the new log (by the way, do you have any ideia why it's saying my credentials are not valid for legendas.tv, i'm pretty sure they are, I even created a new account for it):

https://pastebin.com/DSUc0PTN

**Comment by neepz** [comment]
If I do a  chmod -R 775 /home/micmacs/torrents/rtorrent
it starts downloading again.

**Comment by pguizeline** [comment]
Watch out with recursive chmod, you should differentiate directories from files. Try something like this:

```
# fix directories
$ find /PATH/PATH/ -type d -exec chmod 2775 {} \;

# fix files
$ find /PATH/PATH/ -type f -exec chmod 0664 {} \;
```

Then add your user to plex group and change the directory structure to group plex.

```
$ adduser USER plex

# fix ownership
$ chown USER:plex /PATH/PATH/ -R
```

What this will accomplish is that your user will be part of Plex group, will have R/W rights over you Media and directories and files will have the right permissions, using 2777 (setgid bit) will inherit USER:plex ownership for new files and folders

Hope that helps! And please try it on a disposable system before using on your production server, it's never a good idea to just copy & paste commands!

**Comment by neepz** [comment]
Thanks, @pguizeline! I did try that (this is a new server, I only use it for plex as my streaming platform, so it's ok to mess with it as long as I get it going, and sub-zero is a must have for me). 

I tried what you said, rebooted the server, but still nothing. I'm trying to refresh the following movie: "The Earrings of Madame De..."

https://pastebin.com/cGtcJrTK


One thing though, I'm using Radarr to download them all, don't really know if that could be an issue.
Although I tried adding it through Radarr and directly through rutorrent and nothing changed.

**Comment by pannal** [comment]
You still have the same permissions problem. 

I would contact Quickbox for help as this is quite out of scope for Sub-Zero.

Sonarr and Radarr have permission settings btw, for directories and files. Also they support chown. `Media Management` with `Advanced Settings` shown.

**Comment by pannal** [comment]
Are you guys even serious? https://quickbox.io/ufaqs/plex-cannot-readwrite-my-media-directory/

**Comment by pannal** [comment]
#391

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#Q3
