### ISSUE TITLE
Subtitles disappearing

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#382]

**Comment by pannal** [comment]
OK, from your logs I see that SZ finds external subtitles for hu and en for S06E04.
It doesn't see any metadata ones, though.

Are you sure that your downloader didn't simply download a better release, thus discarding your old release including its subtitles in the process?

**Comment by pannal** [comment]
In the meantime you can switch back to externally stored subtitles - that feature is well tested.

**Comment by manfreed** [comment]
Sorry, I forgot to mention that I have already switched back to store subtitles externally. So the subtitles SZ finds are the ones it put there when I triggered a metadata refresh. 

> Are you sure that your downloader didn't simply download a better release, thus discarding your old release including its subtitles in the process?
 
I'm not sure what you mean by my downloader. I don't use anything to find subtitles except SZ (well, as far as I know).

**Comment by pannal** [comment]
The subtitle disappears where exactly? The file on disk? The subtitle entry in the Plex Web menu? Or the subtitle itself, when playing a media file, on screen disappears?

**Comment by manfreed** [comment]
The srt files stay on the disk, they aren't deleted, but the entry disappears from the subtitle selector.
When this happens and I'm watching the show, the player reloads the video and the subtitle disappears from there too.

**Comment by pannal** [comment]
And this happens with external subtitles? Is that something new or has that happened for a while?

**Comment by manfreed** [comment]
Actually I figured out what was wrong, and it's lame :) It was a configuration error on my end: For some reason the folder where I store tv series was added twice to my library. I don't remember adding it twice though.

**Comment by pannal** [comment]
Hmm, I'd still consider this a bug. Adding folders to multiple libraries shouldn't break things. I doubt SZ has anything to do with it, though.

**Comment by manfreed** [comment]
I don't think so either.

**Comment by pannal** [comment]
Closing!
