### ISSUE TITLE
Add option to download more than one subtitle at once.

### ISSUE THREAD

**Issue by dyorgio** [pannal/Sub-Zero.bundle#383]
Hi, nice plugin!

Currently it works to me almost 90%, when not, I force to download another sub.

I would like to suggest to include the option to download more than one sub at once ( maybe 3 :) ).

The idea:
1) Do search like it does today.
2) CHANGE: Rank result to select one (here select top N [N=number of options]).
3) Save file(s) with another suffix ${releaseName}.${N}.${lang}.${extension} (tested on VLC and Plex, all are recognized)

**Comment by pannal** [comment]
I don't know if I can implement this. SZ is hard enough on providers as is - perhaps for OpenSubtitles VIP users in the future.

**Comment by dyorgio** [comment]
The users will be restrict like today: after daily download cota exhaust no more downloads.
Option can be used only in specific cases (like rank value of top are equals/almost).

**Comment by pannal** [comment]
The quota doesn't change the fact, that downloading 3 subtitles at the same time poses more stress on the servers generally.

**Comment by dyorgio** [comment]
Please @pannal, maybe this can be implemented without impact providers, ex:

Download first as today, second 1-6 hour later.

Normally people consume downloaded subtitles in another time/date.
