### ISSUE TITLE
Permissions problem?

### ISSUE THREAD

**Issue by LaMpiR** [pannal/Sub-Zero.bundle#385]
Hi.

Can somebody help me with this problem?

> IOError: [Errno 13] Permission denied: u'/home/vuka/torrents/rtorrent/Serije/Me, MYSELF & I/Season 1/Me.Myself.and.I.S01E06.720p.HDTV.X264-DIMENSION.en.srt'.

[Logs_171107_14-45-14.zip](https://github.com/pannal/Sub-Zero.bundle/files/1450166/Logs_171107_14-45-14.zip)

**Comment by pannal** [comment]
Ideally the user the Plex server and the rtorrent Downloader run as, are the same. Then you won't have to deal with those problems.

**Comment by pannal** [comment]
#381

**Comment by LaMpiR** [comment]
I got that part, but I have no idea how to pull that off? Would it be possible to guide me through it?

**Comment by pannal** [comment]
I can't help you with that more than I have in the other ticket I linked to above. 

You want plex to have write access to the whole rtorrent folder. 

Sorry

**Comment by pannal** [comment]
Are you using some pre built seedbox script for your machine?

**Comment by LaMpiR** [comment]
Hi.

Yes, quickbox. I will check out the link tomorrow and try to make some sense from it.

Thank you :)

**Comment by pannal** [comment]
I'd suggest talking to the quickbox guys, as their setup should allow plex write permissions on the download folders by default.

**Comment by pannal** [comment]
@LaMpiR did you talk to the Quickbox guys?

**Comment by LaMpiR** [comment]
Yes and so far no reply from them...

**Comment by pannal** [comment]
Can you do a `ls - als` on both the folder and the folder above the one regarding the error from your first post? 

Also do you use radarr/sonarr?

**Comment by LaMpiR** [comment]
ls-als Season 1 folder:
4.0K drwxr-xr-x  2 vuka vuka 4.0K Oct 31 00:08 Season 1
ns329388:/home/vuka/torrents/rtorrent/Serije/Me, MYSELF & I#

ls -als: Serije folder:
4.0K drwxr-xr-x  3 vuka vuka 4.0K Sep 26 13:53 Me, MYSELF & I

Yes, I do use sonarr.

**Comment by pannal** [comment]
OK, let's try something:
`adduser vuka plex`
`chown -R vuka:plex /home/vuka/torrents`
`chmod -R 775 /home/vuka/torrents`
`chmod g+s /home/vuka/torrents`
`setfacl -R -m g::rwx /home/vuka/torrents`
`setfacl -R -m o::x /home/vuka/torrents`
`setfacl -R -d -m g::rwx /home/vuka/torrents`
`setfacl -R -d -m o::--- /home/vuka/torrents`

This sets the default group of newly created files/directories under the torrents folder to `plex` and the permissions to rwx for the group.

**Comment by pannal** [comment]
Then please post the output of:
`getfacl /home/vuka/torrents`
`getfacl "/home/vuka/torrents/rtorrent/Serije/Me, MYSELF & I/Season 1/"`

**Comment by LaMpiR** [comment]
Hi.

Here is is:

xxx:/home/vuka# adduser vuka plex
Adding user `vuka' to group `plex' ...
Adding user vuka to group plex
Done.
xxx:/home/vuka# chown -R vuka:plex /home/vuka/torrents
xxx/home/vuka# chmod -R 775 /home/vuka/torrents
xxx/home/vuka# chmod g+s /home/vuka/torrents
xxx:/home/vuka# setfacl -R -m g::rwx /home/vuka/torrents
bash: setfacl: command not found
xxx:/home/vuka#

What do I do? Thank you.

**Comment by pannal** [comment]
umn: https://quickbox.io/ufaqs/plex-cannot-readwrite-my-media-directory/

**Comment by pannal** [comment]
`apt-get install acl`

**Comment by LaMpiR** [comment]
Amazin!

Here it is:

xxx:/home/vuka# getfacl /home/vuka/torrents
getfacl: Removing leading '/' from absolute path names
# file: home/vuka/torrents
# owner: vuka
# group: plex
# flags: -s-
user::rwx
group::rwx
other::--x
default:user::rwx
default:group::rwx
default:other::---


xxx:/home/vuka# getfacl "/home/vuka/torrents/rtorrent/Serije/Me, MYSELF & I/Season 1/"
getfacl: Removing leading '/' from absolute path names
# file: home/vuka/torrents/rtorrent/Serije/Me, MYSELF & I/Season 1/
# owner: vuka
# group: plex
user::rwx
group::rwx
other::--x
default:user::rwx
default:group::rwx
default:other::---

Should I try it now?

**Comment by pannal** [comment]
No, use their FAQ please: https://quickbox.io/ufaqs/plex-cannot-readwrite-my-media-directory/

**Comment by LaMpiR** [comment]
I've already did yours :) How do I undoit?

**Comment by pannal** [comment]
Shouldn't matter, follow theirs.

**Comment by LaMpiR** [comment]
Done everything.
Works like a charm!
Sent you a beer! Will do in the next month as well.

Thank you!

sorry I was searching for the solution, but I didn't think it was connected to the plex, but the channel/plugin directly.

Best regards

**Comment by pannal** [comment]
Great, glad you fixed it!
