### ISSUE TITLE
Scrubbing Font Formatting

### ISSUE THREAD

**Issue by Smalfinn** [pannal/Sub-Zero.bundle#386]
It would be so useful for me to have an option to remove all HTML tags/font formatting in a sub file, to only leave the bare minimum.

Like integrating: https://subtitletools.com/srt-cleaner into sub-zero

E.g. converting:
`1
00:00:03,080 --> 00:00:05,780
<font face="Angie" size="68" color="#efecf4"><b>Huh? That's strange.</b></font>`

into: 
`1
00:00:03,080 --> 00:00:05,780
Huh? That's strange.`

**Comment by pannal** [comment]
Apart from <b> <i> and <u> this is already done by the SZ subtitle modification framework.

A new default modification will be added in the next release, though: "remove_tags".
This modification will remove any tags at all.

**Comment by Smalfinn** [comment]
I appreciate it :D

**Comment by Smalfinn** [comment]
Will this feature remove tags from subtitles not downloaded via SubZero?

**Comment by pannal** [comment]
No it won't. SubtitleMods are currently only available for SZ's own downloaded subtitles.

**Comment by Smalfinn** [comment]
Would it be a possibility for SZ to scrub thirdparty subs in the future?

**Comment by pannal** [comment]
Yes, handling of pre-existing subtitles is planned for 2.1, which is not too far away :)

**Comment by Smalfinn** [comment]
Is this now implemented?

I did have a read of the release notes but couldn't find it.

**Comment by pannal** [comment]
Not for 3rd party subs, no. Only for subtitles extracted or downloaded by Sub-Zero. The existing subtitle management feature didn't make it into the last version, unfortunately, but is still planned.

**Comment by Smalfinn** [comment]
Okay thanks for the info.

Keep up the great work :)

**Comment by pannal** [comment]
#376 is the ticket that tracks that specific feature.

Closing this.
