### ISSUE TITLE
Only channel mode doesn't working anymore

### ISSUE THREAD

**Issue by BHMath** [pannal/Sub-Zero.bundle#387]
My mode is set to only channel but everytime I create a new folder SubZero will download subtitles even if the mode is set to only channel.

**Comment by pannal** [comment]
Hmm, that can't really be the case. Is perhaps the OpenSubtitles agent enabled for your library?

Otherwise please set SZ's log verbosity to "DEBUG", refresh a media item from PlexWeb, then attach the log zip from SZ's advanced menu here.

**Comment by BHMath** [comment]
[Logs_171110_13-55-48.zip](https://github.com/pannal/Sub-Zero.bundle/files/1461365/Logs_171110_13-55-48.zip)
Here my log.
I removed all srt in the folder. 
Tried to refresh the library but nothing happened.
But one hour later new srt were here.

I think if there is no srt SZ will download but if there is already one, no new srt are downloaded.

I'll try this later.

**Comment by pannal** [comment]
Ah, so it's the automatic tasks in the background who add the SRTs, not the agent when adding the media file. That makes sense. Investigating.

**Comment by BHMath** [comment]
I ran a new test but until now I still have no new srt maybe in 12h hour. I'll keep you in touch.

13h58 : Delete srt except for 3 files (15 actually in the folder)
13h59 : Refresh library
14h00 : Analyse
14h01 : Refresh metadata

**Comment by pannal** [comment]
Yes, the agent (which is triggered after adding a media file) is disabled, but the "search for missing subtitles" and "search for better subtitles" tasks aren't.

You found a bug, I'll fix it.

**Comment by BHMath** [comment]
I'm glad I did. 

I make use of this post to thank you very much for your work ! It is wonderful

**Comment by pannal** [comment]
I had a look at the code. Actually it's not a bug, it's a configuration issue.

Please change the following in SZ's preferences:
`On media playback: search for missing subtitles (refresh item)` = never
`Scheduler: Periodically search for recent items with missing subtitles` = never
`Scheduler: Periodically search for better subtitles` = never

**Comment by BHMath** [comment]
right I changed my configuration.

This is quiet a tricky one and thank you for your time ;)
