### ISSUE TITLE
Plex Cloud

### ISSUE THREAD

**Issue by jarboloide** [pannal/Sub-Zero.bundle#388]
Can I configure sub zero in PlexCloud?

**Comment by pannal** [comment]
Nope, sorry!

**Comment by jdat82** [comment]
Do you plan on supporting it? If so, would you mind updating us in this thread? Thx.

**Comment by pannal** [comment]
As far as I know it is impossible for SZ to support Plex Cloud as it stands right now.
It might come in the future.
