### ISSUE TITLE
Another provider - subscene, is it possible?

### ISSUE THREAD

**Issue by minihessel** [pannal/Sub-Zero.bundle#389]
Subscene sometimes has subtitles that some providers do not, is it possible to add it? For example https://github.com/andy-pham/subscene-api

**Comment by pannal** [comment]
Duplicate of #26 

Sorry.

**Comment by minihessel** [comment]
I should be the one saying sorry, I should've searched.

**Comment by pannal** [comment]
#268 might interest you. though.

**Comment by pannal** [comment]
I've taken another shot at SubScene in 2.1. [Please join the SZ beta](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes)!
