### ISSUE TITLE
Subtitles aren't downloading

### ISSUE THREAD

**Issue by Vitorvlv** [pannal/Sub-Zero.bundle#390]
[Logs_171117_00-36-20.zip](https://github.com/pannal/Sub-Zero.bundle/files/1481044/Logs_171117_00-36-20.zip)

I am using linux mint 18.2.

**Comment by pannal** [comment]
`RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')` please install unrar for podnapisi

**Comment by Vitorvlv** [comment]
Installed unrar and I had another issues with permission. Everything is working now, thanks!
