### ISSUE TITLE
USING QUICKBOX? PERMISSION ERRORS? LOOK HERE

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#391]
`apt-get install acl`

Follow their FAQ:
https://quickbox.io/ufaqs/plex-cannot-readwrite-my-media-directory/

**Comment by ukdtom** [comment]
Documented here:

https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#Q3

Homepage updated as well

And you forgot to assign me ;)

**Comment by pannal** [comment]
<3
