### ISSUE TITLE
Force-find subtitles not working

### ISSUE THREAD

**Issue by BHMath** [pannal/Sub-Zero.bundle#393]
Hi, 

I noticed that force-find subtitle is not working for me.
I use SZ as channel only.

When I went to an episode without any subtitles on the drive in the channel I can see menu like this
[...]
-Force-find subtitle: [myepisode]
-List French subtitles: No current subtitle in storage
-List English subtitles: No current subtitle in storage
[...]

If I click on Force-find. the current state is "triggering Force-Refresh for [MyEpisode]" then the state goes to idle but no subtitle is available in my storage nor in the menu "List XXX subtitles" in the SZ menu of the episode.

But if I use "List English subtitles" wait for SZ to find some subtitle online then select one available : The file is downloaded in my storage.

Here my debug [Logs_171120_23-22-45.zip](https://github.com/pannal/Sub-Zero.bundle/files/1489330/Logs_171120_23-22-45.zip) for easier investigation.

Thanks ahead

**Comment by pannal** [comment]
Force-find doesn't work with channel-only, sorry. The force-find method requires the agent to be enabled.

Other than that, FYI: You've got permission errors: `IOError: [Errno 13] Permission denied: u'/mnt/MyBookLive/NightWatch/Future.Man.S01E06.720p.WEBRip.x264-TBS.en.srt'`

**Comment by pannal** [comment]
#394

**Comment by BHMath** [comment]
Thank you for your warning about my permissions error. I fixed it not so long ago maybe it was old logs.
At first, I thought that was my problem with Force-find but then it was not.

Can't wait for the 2.1 version with this enhancement.

Again, thank you for your work this is amazing !
