### ISSUE TITLE
Empty channel window

### ISSUE THREAD

**Issue by beachfork** [pannal/Sub-Zero.bundle#395]
Hi! I installed Sub-Zero main release using the Plex channels menu, Sub-Zero is working and fetching subtitles, but when I click on the Channel menu and Sub-Zero icon to access the app I get an empty menu.

![2017-11-22 16_09_30-plex](https://user-images.githubusercontent.com/33908726/33143673-bd09b664-cfa1-11e7-8b50-6cb836f0bd71.png)

I've already re-installed Plex, my Libraries and Sub-Zero. Thank you!

**Comment by pannal** [comment]
Please consult the [Wiki on how to obtain your logs](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs#sub-zero-channel-is-not-showing), then attach them here.

**Comment by beachfork** [comment]
Hi! There you go!

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1497202/com.plexapp.agents.subzero.log)

**Comment by Cooad** [comment]
I have the same problem.
Logs here: https://www.dropbox.com/s/nnnnil0k457njhe/subzero-logs.zip?dl=0

**Comment by ukdtom** [comment]
Sadly a plex issue, affecting all channels.
Seems like if not going via plex.tv, but instead browse directly towards the PMS, that it then works.
Plex has been notified about this
