### ISSUE TITLE
[BUG] Not all options from "Periodically search for recent items with missing subtitles" available

### ISSUE THREAD

**Issue by jippo015** [pannal/Sub-Zero.bundle#396]
Ever since (2.0.29.1756) the option "every 2 hours" (from issue #354 ) was added to the "Periodically search for recent items with missing subtitles" setting, I can't see the options: every 1,2 and 3 hours.

It looks as if the dropdown box fills itself with the values from "Periodically search for better subtitles".

I've tried to reinstall sub-zero, before reinstalling I cleared all setting of sub-zero, but it didn't help.

I think this is a bug.

**Comment by pannal** [comment]
Those options have been removed in the last release, due to over-stressing of subtitle providers. SZ was using over 40% of the global OpenSubtitles API in total.
