### ISSUE TITLE
Question about subzero.ignore

### ISSUE THREAD

**Issue by BHMath** [pannal/Sub-Zero.bundle#399]
Is subzero.ignore will prevent Subzero to look fr subtitle in the current folder and all of the subfolder ?

example : For /TVShow/subzero.ignore and /TVShow/MyShow is MyShow automatically skipped ?

**Comment by pannal** [comment]
Yes.

**Comment by BHMath** [comment]
Perfect thanks !

**Comment by pannal** [comment]
Wait, a specific explanation is in order:

For movie libraries it checks the current media file folder for existence of the ignore files, as well as the folder above it.

For tv show libraries, it walks up one more folder, to accomodate Season subfolders..

**Comment by BHMath** [comment]
Ok so if my folders are organized like this.

/TvShows/TvShow1/Season1/
/TvShows/TvShow1/Season2/
/TvShows/TvShow2/Season1/
/TvShows/TvShow2/Season2/
/TvShows/subzero.ignore 

If i understand what you wrote. My files inside each season will be analyzed even if I got a subzero ignore file at the root of my folder ?

So in order to ignore the whole folder I have to go to the channel, Browse all items, select one library and ignore the section. That's right ?

Then new question how about a new library creation with these folders how long do I have to ignore it before subzera start downloading subtitles ?

Thank you very much for your support !

**Comment by pannal** [comment]
No, I was wrong, it'll ignore that library folder as well.
