### ISSUE TITLE
Some menu items don't work right on Android Plex

### ISSUE THREAD

**Issue by dny238** [pannal/Sub-Zero.bundle#400]
Navigating the menu structure of Sub-Zero on my phone doesn't work like it does on the web. 
In some cased it dead-ends when the web loops back up a level. 
Example; When I pick Force-Find, on the phone I get the below 'dead end' blank screenshot. On the computer it takes me to a 'Working... refresh here' menu item. 

In some cases, items on the phone are blank when they contain contents on the web. 
Example: "List English Subtitles" is always blank, but the web has items for me. 

Can this be fixed? 
Rob

![screenshot_20171127-120211](https://user-images.githubusercontent.com/127399/33284246-a585ab4c-d36b-11e7-9f4b-baf18e9eaea7.jpg)
![screenshot_20171127-120358](https://user-images.githubusercontent.com/127399/33284247-a59d8438-d36b-11e7-8345-8bdaef537aae.jpg)

**Comment by pannal** [comment]
Sadly the support for many (documented) menu features has gone haywire with the last couple of updates to the native apps on many devices.

The biggest gripe I have with the implementation is that list items don't seem to exist anymore, as they do on PlexWeb and everything is a big "box" not containing enough information.

There's currently nothing I can do, except to ask you to make Plex Inc. aware of the issues.
