### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by vrokolos** [pannal/Sub-Zero.bundle#401]
2017-11-30 21:50:58,114 (711ff460) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.0.29.1767)', called with guid 'com.plexapp.agents.thetvdb://260449?lang=en' (most recent call last):
--
#118 | File "/usr/lib/plexmediaserver/Resources/Plug-ins-a39b25852/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
#119 | agent.update(obj, media, lang, **kwargs)
#120 | File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 158, in update
#121 | videos = media_to_videos(media, kind=self.agent_type)
#122 | File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/plex_media.py", line 123, in media_to_videos
#123 | imdb_id = media.guid[len(imdb_guid_identifier):].split("?")[0]

**Comment by vrokolos** [comment]
[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/1519804/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
The log you posted doesn't contain what you posted originally.

From the errors I can see (but those are most likely unrelated to your initial problem):
The requests to your PMS time out. That's not SZ's fault and I can't do much about it.

You might want to look inside the Plex Media Server logs, it may have problems with reading your database in time.

**Comment by pannal** [comment]
Closing for now
