### ISSUE TITLE
[Feature request] Add http proxy support

### ISSUE THREAD

**Issue by materemias** [pannal/Sub-Zero.bundle#402]
since opensubtitles blacklists some seedbox server ips it would be great to have the option to manually set a http proxy for fetching subtitles

**Comment by pannal** [comment]
Valid point, I'll investigate.

**Comment by pannal** [comment]
https://gist.github.com/nathforge/980961
http://docs.python-requests.org/en/master/user/advanced/#proxies

This is definitely possible.

**Comment by pannal** [comment]
Would setting an environment variable be enough for you, or would you need a new option in SZ's settings?

**Comment by materemias** [comment]
Since Plex server is not controlled by me having an option would be great!

**Comment by pannal** [comment]
Can you join the [SZ Slack and beta 2.1](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes) so we can test this?

**Comment by materemias** [comment]
sorry, I cannot :(
