### ISSUE TITLE
Subtitles are still being downloaded even though they already exist emebeded

### ISSUE THREAD

**Issue by Tamburra** [pannal/Sub-Zero.bundle#403]
I have the most recent version sub-zero installed and the "Don't search for subtitles if there are embedded subtitles inside the media file (MKV/MP4)?" enabled.  I am still experiencing English subtitles being downloaded even though they are embedded in the MP4 with English named subtitles.  What am i doing wrong?

**Comment by pannal** [comment]
Are you sure those embedded subtitles have the correct language tag set?

**Comment by guice** [comment]
This happens to me with English - VOBSUB embeds

"English - VOBSUB" is what Plex shows, which I assume means it's tagged correctly as English.

**Comment by pannal** [comment]
Do you have `Include "exotic" subtitle formats (anything else than .srt/.ssa/.ass/.vtt; embedded or external) in the above?` enabled?

**Comment by guice** [comment]
Nope. I didn't. I wasn't aware that was associated with this. "exotic" subtitle formats throw me off, since VOBSUB and PGS seem to be pretty common in my movies.

**Comment by pannal** [comment]
OK, I should rename that to `non-text` subtitles. Would that make it more clear? :)

**Comment by guice** [comment]
How about `other "third party" formats (embedded or external)`? Covers all your bases, and gets rid of the added wordy `"(anything else than .....)"`

**Comment by pannal** [comment]
Well "third party" formats isn't accurate, they're as first-party as any other subtitle format. Just not text-based :)
