### ISSUE TITLE
issue with applying a color to a line that contains ":[a letter]"

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#408]
in my SZ configuration I have stated that I want all my texts to be forced into plain white text. and it works well for the most part. the exception is when there is a acronym of some agency or country followed by a ":s" that something weird happens. see the below examples:

from opensubtitles Salt (2010):

```
652
01:28:26,018 --> 01:28:29,174
Jag vill ha henne ensam i ett rum.
Ifall det finns fler KGB:are-
```

gets converted into:

```
652
01:28:26,018 --> 01:28:29,174
<font color="#FFFFFF">Jag vill ha henne ensam i ett rum.</font>
are-</font>

```
from opensubtitles Bridge of spies (2015)

```
622
00:43:42,246 --> 00:43:48,418
Jag tror att det ligger i USA:s intresse -
```

gets converted into:

```
622
00:43:42,246 --> 00:43:48,418
s intresse -</font>
```

the bridge of spies have plenty of examples since they refer to USA a few times. they also refer to the KGB once. interestingly the bridge of spies movie also have one instance where it isn't converted erroneously:
```

1747
02:10:34,828 --> 02:10:38,248
<i>Nyligen har USA:s regering</i> -
```

into 

```
1747
02:10:34,828 --> 02:10:38,248
<i>Nyligen har USA:s regering</i> -  
```

but here SZ didn't put it into white because it was already in some kind of html tag.

I've spotted these issues across plenty of movies but haven't realized what the issue have been. I've though it have been random until I saw bridge of spies last night.

I'm not sure if it matters but this is in Swedish. I'm not sure if this is an issue in other languages. also there isn't an issue with following numbers. I'm certain of that ":a" and ":s" is converted wrongly, but there could be other combination that causes this behavior.

**Comment by pannal** [comment]
Hmm, I think this may be related to hearing impaired stuff. Do you have the HI mod active?

**Comment by KBlixt** [comment]
yupp.

**Comment by pannal** [comment]
Can you give me the original, unmodified subtitle file so I can debug this? Just remove all mods using the modify menu, then attach the subtitle file here.

**Comment by KBlixt** [comment]
[bridge of spies original.zip](https://github.com/pannal/Sub-Zero.bundle/files/1561242/bridge.of.spies.original.zip)

here it is.

**Comment by pannal** [comment]
I think I found the issue. Do you have the means to install develop-2.0?

**Comment by KBlixt** [comment]
I think so, will I have to reconfigure SZ?

**Comment by pannal** [comment]
Nope, just follow the instructions here: https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation

Instead of downloading a release you download https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip

The dev mode flag is already set.

**Comment by KBlixt** [comment]
aright, done. what now?

**Comment by pannal** [comment]
See my edit above.

**Comment by KBlixt** [comment]
I can't find the sub-zero channel. I can access the settings through agents in the settings but nothing under channels.

**Comment by pannal** [comment]
Woot, did you restart your PMS?

**Comment by KBlixt** [comment]
yepp, service plexmediaserver stop and then start when i was finished

**Comment by KBlixt** [comment]
and i just restarted again, still nothing.

**Comment by pannal** [comment]
Humm. The folder is named as "Sub-Zero.bundle" and not "Sub-Zero.bundle-develop-2.0"?

**Comment by KBlixt** [comment]
Sub-Zero.bundle with plex:plex 755 permissions

**Comment by KBlixt** [comment]
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle

is the exact copy pasta

**Comment by pannal** [comment]
Hmm. You can access the agent settings but not the channel itself? Can you attach the newest SZ log files?

**Comment by KBlixt** [comment]
Sub-Zero Subtitles (Movies, 2.0.33.1871) inställning is the settings info i get.

**Comment by KBlixt** [comment]
where do i find those specifically ?

**Comment by pannal** [comment]
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log` and the .log.* files

**Comment by KBlixt** [comment]
[logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1561375/logs.zip)

**Comment by pannal** [comment]
`CRITICAL (sandbox:298) - Function named 'Start' couldn't be found in the current environment` - the package seems broken, can you re-download?

**Comment by KBlixt** [comment]
oh, right i forgot to say. I got some kind of error when I unpacked the package. i tried to do it twice it to different folders but still the same error. hang on

**Comment by KBlixt** [comment]
"an error occurred while unpacking the files"

**Comment by KBlixt** [comment]
no details

**Comment by pannal** [comment]
Seems like some kind of corruption issue. Try lynx or wget?

**Comment by KBlixt** [comment]
please, be specific I'm not complexity used with linux. I'm trying to unpack it in my windows machine and transfer it to my server.

**Comment by pannal** [comment]
Ah OK. You can try `wget https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip` on your linux machine, then `unzip develop-2.0.zip` and rename the folder afterwards.

**Comment by KBlixt** [comment]
aright, now it works. in what order do you want me to reapply the mod in ?

**Comment by pannal** [comment]
Doesn't matter, they all get applied on the fly.

**Comment by KBlixt** [comment]
excellent. it's all fixed. I also tried with re downloading the salt subtitle and it worked out of the gate.

**Comment by pannal** [comment]
Awesome. Now you can re-apply all applied mods to all of your subtitles via the advanced menu if you want to.

**Comment by KBlixt** [comment]
can i do that in batch? cause I have a quite a few... hehe. I might just delete all subtitles I have and update metadata for the entire library.

**Comment by pannal** [comment]
Yes, just as I've told you. Go to [the advanced menu ](https://github.com/pannal/Sub-Zero.bundle/wiki/Advanced-usage) and hit Re-Apply mods of all stored subtitles

**Comment by KBlixt** [comment]
Brilliant. Thank you for your fast help :) big kudoz. 

now that I have the dev version. is there anything I can enable to help development?

**Comment by pannal** [comment]
Sure, there's been a big callout on Reddit today, for 2.1 beta testers: https://www.reddit.com/r/PleX/comments/7jsqy9/subzero_21_announcement_subtitle_master_race/

**Comment by KBlixt** [comment]
aright, I'll have a look into that in the morning. right now it's really late :)

**Comment by pannal** [comment]
Have a good one!
