### ISSUE TITLE
RTL languages subtitles show punctuation marks in reverse

### ISSUE THREAD

**Issue by dorsharon** [pannal/Sub-Zero.bundle#409]
On the AndroidTV version of Plex, RTL subtitles (Hebrew, Arabic and more..) show punctuation marks at the start of sentences instead of at the end.

It'd be great if there was a setting to auto-reverse all downloaded RTL subtitles.

**Comment by pannal** [comment]
Wouldn't that normally be something the subtitle creator should be doing?

I'm not at all familiar with RTL languages, so cut me some slack here please :)

Can you give me an example? Is the error inside the subtitle itself or does the Plex client behave wrong?

**Comment by dorsharon** [comment]
No, the subtitle creator is doing what he should do, creating a sentence like this:

> שלום לך.

However, the Plex decodes it as:

> .שלום לך

which puts the period on the start instead of the end.
Other players will play Heb subs just fine. It's only Plex that doesn't.

**Comment by dorsharon** [comment]
If you'd like an example, you can download SubtitleEdit 3.5, where there's a feature under Tools for Reverse RTL:

![image](https://user-images.githubusercontent.com/23096334/34047073-bd44b250-e1b7-11e7-827c-537f59cb5187.png)

**Comment by pannal** [comment]
So the order of the characters in `שלום לך.` is already correct, and in `.שלום לך` it is as well, just the full stop should be at the end?

If you read from right to left, why wouldn't the full stop be on the left?

**Comment by dorsharon** [comment]
The characters are in the right order, it's only punctuation marks that are supposed to appear at the end of sentences that are not right.

Most players usually recognize RTL languages and simply render the subtitles so that the period, commas etc. appear correctly.
Plex considers the heb subs as LTR and so doesn't reverses the punctuation.

**Comment by dorsharon** [comment]
> So the order of the characters in שלום לך. is already correct, and in .שלום לך it is as well, just the full stop should be at the end?
That's correct

**Comment by pannal** [comment]
Let me get this straight: ש is the first word/character you'd read in this example?

**Comment by pannal** [comment]
Ah, you write/read from right to left, but the punctuation still occurs at the right, not the left?

**Comment by dorsharon** [comment]
ש us the first character I'd read.
We read right to left, Punctuation occurs on the left.

**Comment by pannal** [comment]
Wait, when punctuation occurs on the left, then `.שלום לך` is correct if I understood you fine.

**Comment by dorsharon** [comment]
Yeah. Github actually also reversed my punctuation for my examples.
Bottom line is that period should occur on the left, Plex shows it on the right on AndroidTV

**Comment by pannal** [comment]
OK. Is that the case with SZ subtitles only? I'm doing quite a bit of cleanup so I might kill the RTL marker in the process. Can you try downloading a subtitle manually from OpenSubtitles and see whether it really is Android TV which does that?

**Comment by dorsharon** [comment]
I downloaded from OpenSubtitles and the subtitles there are fine.
Furthermore, on other platforms Plex plays the subtitles fine, It's the Android TV version that doesn't.

This issue isn't exclusive to SZ, I never said that it was.
I was simply asking for a feature of a setting to auto-reverse these punctuation marks, so that Israeli users can finally fully enjoy SZ, as well as arabic and others.

**Comment by pannal** [comment]
> This issue isn't exclusive to SZ, I never said that it was.

And I didn't say you did. I wanted to have as much information about the issue as possible, before I try and fix things :)

**Comment by dorsharon** [comment]
[Vikings.S05E03.720p.HDTV.x264-KILLERS.B291968.msg1.zip](https://github.com/pannal/Sub-Zero.bundle/files/1584245/Vikings.S05E03.720p.HDTV.x264-KILLERS.B291968.msg1.zip)

**Comment by pannal** [comment]
Please try the attached srt file. I've added an explicit [RTL mark](http://www.fileformat.info/info/unicode/char/200f/index.htm) right after the first dot on:
```
4
00:00:08,230 --> 00:00:09,940
נראה שאתה לא מתייעץ איתנו
.‏בשום דבר
```

Does that work? If so, this modification could be very easy.

[testout.zip](https://github.com/pannal/Sub-Zero.bundle/files/1584531/testout.zip)

**Comment by dorsharon** [comment]
I'll check later today

**Comment by pannal** [comment]
Any news?

**Comment by dorsharon** [comment]
Sorry about the delay, been crazy busy.
Unfortunately this still doesn't change anything. The problem persists.

**Comment by pannal** [comment]
Damn. I'm not sure on how to approach this to be honest.
Your client seems to put the dot to the right side of the sentence explicitly, while the dot already being in the correct place inside the subtitle. I currently have no idea on how to circumvent that - have you actually had success in manually modifying a subtitle so it gets played correctly on your TV client?

**Comment by dorsharon** [comment]
Yes, SubtitleEdit's feature does the job.
Just annoying having to do it every single time...

**Comment by pannal** [comment]
OK I'm still not 100% sure why the SubtitleEdit approach works, simply because I have no experience with RTL languages. I think what it does it actually just putting the punctuation to the end of the sentence, explicitly, while keeping the rest intact.

Why that fixes things for you I still don't know, but if that's what you need, I can integrate it into SZ.

**Comment by dorsharon** [comment]
Great! Looking forward to testing it out :)

**Comment by pannal** [comment]
I think it'd be good if I separate the logic of the common modification for RTL and LTR languages, as they're currently only tested on LTR and probably won't work correctly on LTR. What do you think?

**Comment by dorsharon** [comment]
Sounds about right

**Comment by dorsharon** [comment]
However, I do believe you should add this as a setting (perhaps one thats enabled by default) to allow users to avoid this modification (if there's ever a reason)

**Comment by pannal** [comment]
I've added a test branch based off of the 2.1 beta with a RTL-reverse test modification: https://github.com/pannal/Sub-Zero.bundle/tree/heb_test

Can you try it out? It doesn't modify automatically yet, it's another modification in the menu.

**Comment by dorsharon** [comment]
Well, this fix only partially works.
While punctuations are now correctly displayed, there's the case where there's the '-' mark (when other people are talking in the same subtitle).
The '-' mark is displayed on the wrong side.

In other words, just like your fix moved all punctuation from end to the start of the sentence, if a '-' mark is at the beginning of a sentence, it must be moved to the end  of it for it to display correctly.

That should fix the problem entirely.

**Comment by pannal** [comment]
So `.peter, this is not right - yes I know` should be `peter, this is not right. yes i know -`?

Can you give me an example I can base my regex off of?
Currently I'm using this: `ur"(?u)((?=(?<=\b|^)|(?<=\s))([.!?-]+)([^.!?-]+)(?=\b|$|\s))")` and replace it with `r"\3\2"`. It takes punctuation from the start of a sentence and puts it at the end.

The dash that'd need to be swapped around would be at the end of it?

**Comment by dorsharon** [comment]
Really simple:
'-' at the start of a sentence - goes to the end.
'-' mid sentence - leave untouched.

I'm afraid my regex ain't strong enough to give you an example.

**Comment by pannal** [comment]
Weird, OK. But the current punctuation swap is correct? I'm swapping all punctuation, even when there's two sentences in one line, both ending with punctuation.

I'd just need to not do the mid-line-swap with dashes, and we're good? Because I am currently also swapping dashes.

Or are we talking about different start/end?

**Comment by dorsharon** [comment]
I think mid-sentence not touching goes for punctation as well. sorry if I hadn't mentioned that so far.
Just swap any dashes and punctuation you see on the start/end of the sentence to the other end.

**Comment by pannal** [comment]
Hm, OK, but if I don't swap mid-sentence, why would that work?

Did you see my edit above?

**Comment by pannal** [comment]
> I think mid-sentence not touching goes for punctation as well. sorry if I hadn't mentioned that so far.
> Just swap any dashes and punctuation you see on the start/end of the sentence to the other end.

Weird. Wouldn't that result in mid-sentence punctuation with spaces at the wrong side?

**Comment by pannal** [comment]
Would you mind hitting me up on the [SZ Slack](https://szslack.fragstore.net)? I need to understand this, otherwise I can't support it in the future.

**Comment by pannal** [comment]
Pushed another version which just swaps punctuation and dashes vice-versa, trying to keep the correct spaces, without touching mid-sentence.

**Comment by pannal** [comment]
Please check for the correct spaces after swapping the punctuation (not the dash). Currently it does:
`. this is a .test -` -> `- this is a .test. `

**Comment by pannal** [comment]
Any update?

**Comment by dorsharon** [comment]
Hi, sorry that I've been away. Life got in the way big time.
Anyway, I want to revisit this issue for a possible fix.
What do you need from me to continue?

**Comment by pannal** [comment]
Can you re-download https://github.com/pannal/Sub-Zero.bundle/tree/heb_test? It should swap the dashes now, as well.

**Comment by pannal** [comment]
News?

**Comment by dorsharon** [comment]
How do I mod the subs with your heb-fix?
I've installed your version.

**Comment by pannal** [comment]
The same as before, go to an item in question using the SZ plugin menu, modify subtitle, `Reverse punctuation in RTL languages`.

**Comment by dorsharon** [comment]
Yeah that solves the dashes as well :)

**Comment by pannal** [comment]
Oh so that fix is working? 

Do you want this to be a configurable default mod, that always gets applied to new subtitles, if enabled, or should I keep it manual?

**Comment by dorsharon** [comment]
Enabled by default, can be disabled manually

**Comment by pannal** [comment]
Well you will be able to enable it in SZ's settings, so it's applied by default. Then you can remove it for a specific item by going to the same menu you just went, and remove the mod.

**Comment by dorsharon** [comment]
Fantastic

**Comment by pannal** [comment]
I'll only enable this mod for Hebrew right now. If there are other languages where this applies, please give me a list.

**Comment by dorsharon** [comment]
Alright

**Comment by pannal** [comment]
This is properly implemented in this branch right now: https://github.com/pannal/Sub-Zero.bundle/tree/develop-2.5

And will be in the upcoming release. You can switch to that branch, it has the option to enable the modification by default (via SZ's settings).

**Comment by doopler** [comment]
Hi this is a great add on to already great plugin. but i have noticed that not all punctuation marks are reversed. Can you add comma (,) and other marks like (") to this?
thank you

**Comment by AWaheedi** [comment]
Hello there,

Please note that Arabic suffer from the same issue as well. It will be great if you could fix Arabic subtitles.

The below languages are RTL but I cannot confirm if those languages suffer from the same issue:
- Aramaic
- Azeri
- Dhivehi/Maldivian
- Kurdish (Sorani)
- Persian/Farsi
- Urdu

Thanks

**Comment by krahma9990** [comment]
> Please try the attached srt file. I've added an explicit [RTL mark](http://www.fileformat.info/info/unicode/char/200f/index.htm) right after the first dot on:
> 
> ```
> 4
> 00:00:08,230 --> 00:00:09,940
> נראה שאתה לא מתייעץ איתנו
> .‏בשום דבר
> ```
> 
> Does that work? If so, this modification could be very easy.
> 
> [testout.zip](https://github.com/pannal/Sub-Zero.bundle/files/1584531/testout.zip)
> 
> Edit: If not, the modifcation may be a bit more complex.

Hi Pannal ,And Thank You For Your Help.
For Arabic It Work's ,Take A Look Your-Self

**Before**
![Before](https://user-images.githubusercontent.com/42889595/57582531-c1c40200-74bd-11e9-8608-f3938a8506e4.png)


**After**
![After](https://user-images.githubusercontent.com/42889595/57582523-b4a71300-74bd-11e9-992a-7d4d46d26f3d.png)


But Am Really NOOB At This Stuff
Can You Please Teach Me How To Do It

And What I Did In The Subtitle In The Photos Is I Paste The Subtitle In The File You Put In You Reply

**Comment by adirt4289** [comment]
any updates on this?

**Comment by pannal** [comment]
No, this plugin is discontinued.

**Comment by adirt4289** [comment]
> No, this plugin is discontinued.

so no sulotion for this problem?

**Comment by pannal** [comment]
No, maybe try bazarr.
