### ISSUE TITLE
Keeps saying "I'm not enabled!"

### ISSUE THREAD

**Issue by robross0606** [pannal/Sub-Zero.bundle#413]
The channel continues to report "I'm not enabled" even though I have followed all steps to check the box on the Agent and move it to the top of the list for Movies.  
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1581435/com.plexapp.agents.subzero.log)
![screenshot-media-server-32400-2017-12-21-23-45-07-246](https://user-images.githubusercontent.com/2965467/34285655-1c5dc5ce-e6a9-11e7-933b-2eff117897b7.png)
![screenshot-media-server-32400-2017-12-21-23-46-36-638](https://user-images.githubusercontent.com/2965467/34285667-38d5bb08-e6a9-11e7-83f1-e6c837ee5733.png)

**Comment by pannal** [comment]
Do you have `Plex Movie` set as the primary agent for your movie library? (See the library settings' advanced tab)

**Comment by robross0606** [comment]
Yes, just made sure of it:
![screenshot-media-server-32400-2017-12-22-15-00-23-457](https://user-images.githubusercontent.com/2965467/34311040-df49a092-e728-11e7-885a-3a7cbf1b1a73.png)

**Comment by pannal** [comment]
OK, that's weird. Can you join the [SZ slack](https://szslack.fragstore.net) so we can debug this together?

**Comment by pannal** [comment]
You still there?

**Comment by robross0606** [comment]
Yes.  I joined the SZ Slack but never heard back.  In the meantime, I fiddled a little more with my setup and rebooted my server.  At some point in that process, it started working.  Unfortunately, I'm not quite sure what I did that made it work.

**Comment by pannal** [comment]
Well, you could've just highlighted me and I would've answered :)

**Comment by robross0606** [comment]
Apologies. Never used slack before.
