### ISSUE TITLE
Download forced subtitles in one language, but normal in another? 

### ISSUE THREAD

**Issue by Dixbee** [pannal/Sub-Zero.bundle#415]
Is it possible to download forced subtitles in one language, but normal in another? For example, the ability to download forced subtitles in a user's native language (English, in my case) but full subs in other languages could be useful (French and Japanese for me).

Also, sorry if this isn't formatted correctly or isn't posted in the right place. I think this is my first time posting on GitHub.

**Comment by pannal** [comment]
Not right now, no.

Advanced configuration is planned for 2.2, which will try to cover exactly those specific use cases.

**Comment by Dixbee** [comment]
Alright, thanks.
