### ISSUE TITLE
Sub-zero will not download subs anymore

### ISSUE THREAD

**Issue by superkvx** [pannal/Sub-Zero.bundle#416]
sub zero not download subtitles any more, it worked before.
I need to refresh metadata manually, then i get subtitles.

Here is my log:
[Logs_171230_01-33-00.zip](https://github.com/pannal/Sub-Zero.bundle/files/1594074/Logs_171230_01-33-00.zip)

**Comment by pannal** [comment]
OK, one: your external subtitles have `dk` as language tag, which is wrong and should be `da`. It'll be correctly parsed in Sub-Zero 2.1.

Second: You're completely blocked off by the providers at the moment. Have you been downloading many subtitles recently or using a seedbox?

**Comment by superkvx** [comment]
Ok, how do i fix that ? i have Subtitle Language (1) English Subtitle Language (2) Norwegian..

Not using seed box, i have refreshed manually metadata sometimes..

**Comment by pannal** [comment]
> Ok, how do i fix that ?

What of the two?

For the second: You wait a day or become OpenSubtitles VIP :)

**Comment by superkvx** [comment]
the dk\da tags...
okey ill can pay for vip :)

**Comment by superkvx** [comment]
Now iam vip member and did a refresh..
here is the log:
[Logs_171230_18-54-25.zip](https://github.com/pannal/Sub-Zero.bundle/files/1594624/Logs_171230_18-54-25.zip)

**Comment by pannal** [comment]
Doesn't look too bad. Did you enter the credentials and ticked the VIP box?

Set SZ's log level to DEBUG please and refresh something.

**Comment by superkvx** [comment]
okei, yes i did that.
here the new log
[Logs_171230_23-06-34.zip](https://github.com/pannal/Sub-Zero.bundle/files/1594806/Logs_171230_23-06-34.zip)

**Comment by pannal** [comment]
Looks good - Addic7ed has still banned you, that may be gone in a day. Can't see anything wrong right now.

**Comment by superkvx** [comment]
Okey, but i refreshed blindspot s03e08, but when i go to opensubtitles.org, there is 6 subtitles there..

**Comment by pannal** [comment]
Nope there isn't: https://www.opensubtitles.org/en/search/sublanguageid-nor/season-3/episode-8/moviename-blindspot

**Comment by superkvx** [comment]
not norwegian, i know that.. i mean english

**Comment by pannal** [comment]
You already have the english subtitle for that, so it doesn't search for a new one.

**Comment by superkvx** [comment]
i know that, i tought it downloaded more, it has done that with other shows

**Comment by pannal** [comment]
Can this be closed?

**Comment by superkvx** [comment]
Yes you can do  that
