### ISSUE TITLE
Subtitles not downloading

### ISSUE THREAD

**Issue by metrize** [pannal/Sub-Zero.bundle#418]
[Logs_180102_07-43-22.zip](https://github.com/pannal/Sub-Zero.bundle/files/1597010/Logs_180102_07-43-22.zip)

I have attached the logs, I see in places it says "raise unauthorised", i don't know, it has admin access? the disk space is low could that be a reason? my python version is 3.6, do I need some other version?

**Comment by metrize** [comment]
I tried a reinstall here's more logs 
[Logs_180102_07-55-06.zip](https://github.com/pannal/Sub-Zero.bundle/files/1597022/Logs_180102_07-55-06.zip)

**Comment by metrize** [comment]
movies seem to be working, just did it for casino royale and the dark knight and it found subtitles, attaching logs again

[Logs_180102_08-22-53.zip](https://github.com/pannal/Sub-Zero.bundle/files/1597049/Logs_180102_08-22-53.zip)

seems tv show isnt working for some reason

**Comment by pannal** [comment]
OpenSubtitles says it's Unauthorized. Are you sure you've put in your credentials correctly?

**Comment by metrize** [comment]
My login is right I check again

**Comment by metrize** [comment]
[Logs_180123_21-33-54.zip](https://github.com/pannal/Sub-Zero.bundle/files/1657699/Logs_180123_21-33-54.zip)

**Comment by pannal** [comment]
Sorry for replying so late.

No more worrying errors inside your latest log. You don't receive subtitles because of your episode naming scheme, though. 

Do you use any software for renaming your media files?

**Comment by metrize** [comment]
I don't rename at all, it just doesn't show up on history of the plugin section of sub zero (but I think it might be downloading so I'll delete subtitles for a file and see if it works)

**Comment by pannal** [comment]
Well your media files don't have enough information inside their filenames for SZ to match subtitles for you: https://github.com/pannal/Sub-Zero.bundle/wiki#attention
