### ISSUE TITLE
ERROR (model:205) - Cannot read model

### ISSUE THREAD

**Issue by cmacnevin** [pannal/Sub-Zero.bundle#422]
It looks like no amount of refreshing or forcing results in downloaded subtitles. I looked at the logs and I'm seeing this: 

2018-01-07 20:28:52,948 (7f55ae16e700) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/TV Shows/0/dd872be2dd02a1b21cf1da010e9d8e74490092a.bundle/Contents/com.plexapp.agents.subzero

I just looked at that folder, and the Plex user does have Full Control. 

I'm not sure where to upload my logs, but they're here if needed. I tried restarting PMS and it didn't make a difference.

Thanks

**Comment by pannal** [comment]
That error is unrelated and doesn't really matter.

Just attach the zipped log files here, by dropping the file into the comment box.

**Comment by cmacnevin** [comment]
[Logs_180107_20-35-46.zip](https://github.com/pannal/Sub-Zero.bundle/files/1619689/Logs_180107_20-35-46.zip)

**Comment by pannal** [comment]
Looks well - there are a couple of OpenSubtitles connection errors in there, which aren't SZ's fault.

What I can see is stuff like this:
`OSError: [Errno 2] No such file or directory: '/volume1/PLEX_MEDIA/tv/Game.of.Thrones.S05E01.The.Wars.to.Come.1080p.BluRay.x264-DON-Scrambled'`

Do you have detachable storage?
