### ISSUE TITLE
Can only find subs from podnapisi

### ISSUE THREAD

**Issue by leram84** [pannal/Sub-Zero.bundle#423]
Not sure what im missing since it seems like podnapisi is actually fully working (I was able to dl that one w the 102 score and it worked... it just wasn't the right sub) But none of the other sites are populating results. (i am only trying to use SZ manually)

https://cdn.discordapp.com/attachments/374674280300019712/399596533995012096/Screenshot_2018-01-07_at_11.10.16_AM.png

**Comment by leram84** [comment]
sorry, should probably have added some background:

win10
manual plugin installation
v2.0.33.1871

lemme know if you need anything else :)

**Comment by pannal** [comment]
Please attach a DEBUG log zip (see the wiki)

**Comment by leram84** [comment]
ahhhh sorry! didn't realize channels could have logs. Here ya go: https://pastebin.com/ycKnPb31

**Comment by pannal** [comment]
Yeah, a slightly bigger log. Please set SZ log level to DEBUG (in the settings), then [follow this](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs) to get your log zip, then attach that zip here.

**Comment by leram84** [comment]
sorry... too early for reading comp lol

https://pastebin.com/7A0SCk5v

**Comment by pannal** [comment]
OK, that's better, but you still ignored about 50% of my instructions :D
Just drop the log zip into this comment box, don't use pastebin, please.

**Comment by leram84** [comment]
i feel like im about to fuck up again... but there is no zip file. I'm pulling it manually from the log dir. HOPEFULLY you just need the complete file? *fingers crossed* lol
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1619539/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Well, LOL :D
I guess that's enough, yeah. It would've been much easier if you'd just followed my link to the how-to-get-my-log-zip wiki page from above: https://github.com/pannal/Sub-Zero.bundle/wiki/Logs

**Comment by leram84** [comment]
.. but I DID! lol... i used the "manual" option at the bottom since i didn't have that webtools module. That option had a way to grab a zip directly from pms settings but that didn't include 3rd party channels (subzero). lmao, sorry dude! really not trying to be a pita here

**Comment by pannal** [comment]
But your Sub-Zero channel is accessible, isn't it? Why didn't you follow the first option? https://github.com/pannal/Sub-Zero.bundle/wiki/Logs#sub-zero-channel-is-accessible

**Comment by leram84** [comment]
smh... well... ok, fine, im an idiot lol. I THOUGHT that that was the same as pulling it form the pms and that it wasn't going to show 3rd party logs without that log plugin. SORRY SORRY SORRY lol. 

Ok, but now.. do u still need that? i just pulled it, and it looks like basically the same log i just gave u (plus the older copies), but it also has the plex media server log. I assume that is what you were also looking for? i can share that, but id rather not post it here since it has some personal info.

**Comment by pannal** [comment]
Nah all good, I'll take a look at what you've posted.

**Comment by pannal** [comment]
Also, if you can, [join the 2.1 beta](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes). I've fixed some opensubtitles bad credentials handling.

**Comment by pannal** [comment]
Closing this for now. Please reopen if the issue persists.
