### ISSUE TITLE
[Feature Request] Integrate Subspedia and Italiansubs into SZ (Italian Optional Providers)

### ISSUE THREAD

**Issue by Coggi** [pannal/Sub-Zero.bundle#424]
I've seen that Subspedia and Italiansubs (the 2 most active italian subtitles makers) offer APIs to access their subs. 

Subspedia is already available ( http://www.subspedia.tv/api.php ) 
Requests return JSON UTF-8 values.
First request is to http://www.subspedia.tv/API/getAllSeries.php 
which for every series return an ID ( "id_serie") then 2nd request to http://www.subspedia.tv/API/getBySerie.php?serie= \<id_serie\>
which returns the subtitles info and link. 
Subs are provided in .zip files and afaik the same Zips get updated with new subtitles added in them for various releases of the same sub.

To access Italiansubs API permission must be asked, if this is needed I can reach to them and get details.

**Comment by pannal** [comment]
Will take a look, thank you!

**Comment by Coggi** [comment]
Hi,
this can now be marked as closed as both websites have been shut down from copyright holders and no longer provide subtitles :(
