### ISSUE TITLE
Shooter.cn

### ISSUE THREAD

**Issue by saishowaguu2** [pannal/Sub-Zero.bundle#425]
Hello. 
It doesn't look like shooter.cn is available anymore.
Can it be changed to the new site, which is  https://secure.assrt.net ?

Also, is there a way to auto select between different Chinese subs? (Mandarin vs. Cantonese)

**Comment by pannal** [comment]
Yes, will be updated in 2.1 which is currently in beta.

**Comment by pannal** [comment]
Actually no, their API seems completely different. Shooter will be disabled for the time being until someone implements the new API. Sorry.

**Comment by dimotsai** [comment]
@saishowaguu2 Maybe you can took a look the pull request I just created. I have implemented assrt provider for Chinese subtitles.
