### ISSUE TITLE
Multiple copies of the same subtitles listed in last episodes

### ISSUE THREAD

**Issue by cesalo** [pannal/Sub-Zero.bundle#426]
I have version: Sub-Zero 2.0.33.1871
Not sure if this is related with Subzero but since yesterday or today I'm having duplicated subtitles.
![image](https://user-images.githubusercontent.com/16859916/35078252-5d02c3be-fbcf-11e7-938d-0ed1af8cb0ac.png)
There is just 1 english subtitle. I have done a refresh metadata but it doesn't make any difference.
Any ideas?

**Comment by cesalo** [comment]
Found the issue. I changed: How strict should these subtitles existing on the filesystem be detected? to Any.
Used loose and did a refresh metadata on the episodes affected.

**Comment by pannal** [comment]
Great that you figured it out on your own!
