### ISSUE TITLE
[Feature Request] Consider subtitle descriptions for "works with" statements

### ISSUE THREAD

**Issue by D3nn3** [pannal/Sub-Zero.bundle#427]
Hi,

Sub-Zero sometimes misses subtitles because "works with" statements in the subtitle description aren't considered.

See this addic7ed page for example: http://www.addic7ed.com/serie/Modern_Family/9/12/Dear_Beloved_Family

On the right side it says "Works with AVS". It would be nice if Sub-Zero would check for such statements not only on addic7ed as some other sites have similar descriptions mentioning other versions the subtitle works with.

Sorry if it was suggested before but I could find anything.

**Comment by pannal** [comment]
Well yeah, that would be helpful, but we only look at the Multi-Download pages (http://www.addic7ed.com/show/620 for example).

Looking at every individual page would hammer Addic7ed too much. Maybe you can convince them to either include that comment section inside the Multi-Download pages?

**Comment by D3nn3** [comment]
When I wrote a subtitle scraper back in the day I had the same concerns. There're multiple ways to not increase the http requests to much.

First of all most of the time only one episode of a show is searched so it doesn't matter if you look up the individual episode page or the multi-download page. Just check the search queue if that is the case.

If the search queue contains multiple episodes of the same tv show and season then you run into the problem that you would need way more http requests. I solved it by only requesting the individual episode page if no match was found for that episode on the multi-download page.
Caching results from the multi-download pages for this scenario and having a list of common "works with cases" (like AVS and SVA) is also nice.

You're totally right that one should do as much as possible to not stress the servers too much but if done right I think the http requests wouldn't be much more.

Thanks for the reply and the great work you've done is much appreciated!

**Comment by pannal** [comment]
Hmm, I'm not sure why the Addic7ed provider scrapes the Multi-Download page and not the episode page.

You might want to create an issue with [subliminal](https://github.com/Diaoul/subliminal) and ask there. I don't have the time right now to revisit this.

**Comment by vBm** [comment]
Maybe basic pairing would suffice in this case. There are known groups that do things separately for SD and HD.
For example:
`LOL`, `SYS` and `DIMENSION`
or
`XII`, `ASAP` and `IMMERSE`
or
`SVA` and `AVS`

**Comment by D3nn3** [comment]
I just checked and subliminal has this feature (basic pairing) already and in the develop branch SVA/AVS made it to the list ;) The master branch is ages behind though.

I also looked at the code from subliminal and their isn't anything (at least I didn't find anything) that would do what I suggested. Implementing such a feature would mean many changes. Seems like it won't make it but that's okay :)

Maybe consider to merge the develop branch of subliminal into this project if not done already.

**Comment by pannal** [comment]
Yeah it'd mean rewriting parts of the addic7ed provider in subliminal (which is the basis for addic7ed in Sub-Zero).

The similar release groups thing is already in the code, but I think it's unused.

Can you compile a list of SD/HD release groups that use the same source?

**Comment by D3nn3** [comment]
You sure that it's not being used? Looking through it seems that everything is there.

Check here:

https://github.com/pannal/Sub-Zero.bundle/blob/ef044e49379386e5f2c4d0f57a812bbc631105dd/Contents/Libraries/Shared/subliminal/score.py#L47

https://github.com/pannal/Sub-Zero.bundle/blob/ef044e49379386e5f2c4d0f57a812bbc631105dd/Contents/Libraries/Shared/subliminal/providers/tvsubtitles.py#L62


As for the list, check the one the current subliminal dev branch is using:
https://github.com/Diaoul/subliminal/blob/4c0bcbfd68728241324f509317afdf6beb681f99/subliminal/score.py#L47

**Comment by pannal** [comment]
Yeah, SZ is on subliminal-develop@June 2017. I'll update to the latest develop for 2.1, but the equivalent release group stuff is in there. Just not AVS/SVA.

**Comment by D3nn3** [comment]
Yeah just adding the AVS/SVA to the current code should solve most of the issues I stated in the entry post.

**Comment by pannal** [comment]
@D3nn3 the current 2.1 beta has the newest subliminal changes merged. If you want to try them out before release, [please follow this](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes).

**Comment by D3nn3** [comment]
Good news. Is there any way to keep the config? Maybe a config file I can copy/paste?

**Comment by pannal** [comment]
The config isn't touched :)

**Comment by D3nn3** [comment]
That's even better. I'll try it sometime soon :)

**Comment by pannal** [comment]
That is, if you follow the beta instructions and don't uninstall from the web interface.

**Comment by ukdtom** [comment]
Actually....When you uninstall an official bundle, PMS doesn't do a proper house cleaning AFAIK ;)
