### ISSUE TITLE
Not finding Legendas but its there

### ISSUE THREAD

**Issue by wlmfa** [pannal/Sub-Zero.bundle#428]
Hello!
I found out that legendas.tv its not working for me. It eventually download from opensubtitles, but i prefer legendas.

`2018-01-25 23:00:41,649 (6863f460) :  INFO (logger:38) - subliminal_patch.core: Scanning video 'Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BRRip.x264.AAC-ETRG.mp4'`
`2018-01-25 23:00:44,325 (6b3c7460) :  DEBUG (logger:28) - subliminal.providers.legendastv: Found 0 titles`

It's there with the exact same name...

![legendas](https://user-images.githubusercontent.com/20801553/35420593-90429478-0225-11e8-9db1-5540950b590e.JPG)

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1666257/com.plexapp.agents.subzero.log)

PS: Dont mind the permission problem, it's fixed already.

**Comment by pannal** [comment]
This is what's used for searching on legendas: `http://legendas.tv/legenda/sugestao/star%20wars%20the%20force%20awakens` - which returns zero results. I'll have to investigate.

**Comment by pannal** [comment]
This actually returns the desired result: `http://legendas.tv/legenda/sugestao/force%20awakens`

**Comment by pannal** [comment]
This as well: `http://legendas.tv/legenda/sugestao/star%20wars%20episode%20vii%20the%20force%20awakens`

**Comment by pannal** [comment]
This will be fixed in the upcoming 2.1 release. It is currently in beta, you can try it out if you'd like: https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes

**Comment by wlmfa** [comment]
Thanks man. Looking forward to the update.

Congrats, you're doing a great job. This app is awesome.
