### ISSUE TITLE
Subtitles not downloading in PMS on Nvidia Shield TV

### ISSUE THREAD

**Issue by Kenzitron** [pannal/Sub-Zero.bundle#429]
First of all, I would like to thank you all for the work and second I have seen few issues in order to find the solution to mine. But I did not see anything that worked for me.

I run PMS on Nvidia Shield TV and I have problems downloading subtitles only in TV Shows. My folder structure is TV Shows/[SUITS]/[EPISODES] 

I run PMS using external storage from Nvidia Shield

I attach the zip with logs.
[Logs_180203_21-55-25.zip](https://github.com/pannal/Sub-Zero.bundle/files/1692188/Logs_180203_21-55-25.zip)

I see there hoe subtitles are found but I do not see if they are donwloaded or not.

Thanks in advance!

**Comment by pannal** [comment]
Sorry for the late answer, I've somehow missed this ticket. I don't see any errors in your logs.

Is this still an issue? If so, please configure SZ's log level to DEBUG instead of INFO and refresh the metadata of a video file in Plex Web. Then post the log zip please.

**Comment by Kenzitron** [comment]
There we go!
[Logs_180309_23-07-30.zip](https://github.com/pannal/Sub-Zero.bundle/files/1798618/Logs_180309_23-07-30.zip)

Thanks :)

**Comment by pannal** [comment]
This should have been fixed with the latest update, which you should already have. #441
