### ISSUE TITLE
Subzero not downloading subtitles

### ISSUE THREAD

**Issue by battlezone100** [pannal/Sub-Zero.bundle#431]
Subzero is rarely downloading any subtitles. It has worked flawlessly previously on a different system and I have set it up the same as before. What is going wrong here?
[Logs_180204_20-02-40.zip](https://github.com/pannal/Sub-Zero.bundle/files/1693207/Logs_180204_20-02-40.zip)

**Comment by eltismerino** [comment]
Is this still an issue even with the newest version?

**Comment by pannal** [comment]
Is this still an issue even with the newest version?

**Comment by pannal** [comment]
Closing this for now. Please reopen if issue persists.
