### ISSUE TITLE
issues finding subs at subscene

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#437]
I've added the subscene provider under options. but when searching for subtitles it does not find swedish subtitles that is available on the website.

Not sure what log files to send and what level of logging that is required.

**Comment by KBlixt** [comment]
aright, I made a subtitle search for the movie "Coherence". language: swedish, no-HI. I know for a fact that subscene have a subtitle for that movie in swedish. it's even the same release group although I'm not sure I've managed to get it to fetch the original file name from radarr. maybe that's somwhere in there in the log file as well. 

I took the log file immediately after searching and not finding anything at subscene.

[com.plexapp.agents.subzero.log.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/1728848/com.plexapp.agents.subzero.log.tar.gz)

**Comment by pannal** [comment]
Your log shows that your api connection isn't correctly configured.

How's your radarr connection configured?

**Comment by pannal** [comment]
Ah, you have '192.168.0.100:7878' as base url. please add http:// in front.

**Comment by pannal** [comment]
#438

**Comment by pannal** [comment]
The next release will automatically add `http://` to radarr/sonarr

**Comment by KBlixt** [comment]
I still can't find any subscene subtitles though.

doesn't even show up in the subzero plug-in menu after having searched for available swedish subtitles.

**Comment by KBlixt** [comment]
[com.plexapp.agents.subzero.log.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/1728923/com.plexapp.agents.subzero.log.tar.gz)

here is the new log. it now says that connection is ok for radarr, but I can't see any information about not finding subscene subtitles.

**Comment by KBlixt** [comment]
[com.plexapp.agents.subzero.log.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/1728953/com.plexapp.agents.subzero.log.tar.gz)

here is the same but having added INFO level logging for one search. I can see where it logs into opensubtitles and correctly locates the two available subtitles there but I don't see anything regarding searching at subscene.

**Comment by pannal** [comment]
Ah sorry it's for a movie. Subscene isn't enabled for movies by default, as it yielded bad results in beta testing. 

You can enable it by using advanced settings. I don't know if there's already a wiki entry for it. If not: look at the 2.5 changelog, there's a hint on how you set up the advanced settings.

**Comment by pannal** [comment]
This needs to be documented.

**Comment by KBlixt** [comment]
"This needs to be documented."

pfff, documentation is for the weak. ;)

**Comment by pannal** [comment]
I've asked around, in beta we decided to disable it for movies, because of false positive, Google translated subs and so on.

**Comment by ukdtom** [comment]
Normally, it's to be found in the changelog, but :-)
