### ISSUE TITLE
Sub-zero worked before - but after changing IP on Plex it only gets from POPnapsi

### ISSUE THREAD

**Issue by MoellerClaus** [pannal/Sub-Zero.bundle#440]
Normally for Films opensubtitles is the preferred site to donwload from. But Sub-zero only gets from popnapsi.
I am using Netgear 9000 as server for Plex.

Any ideas where to look?

**Comment by pannal** [comment]
Yeah, look at the wiki on how to obtain your log zip, then attach it here, please.

**Comment by MoellerClaus** [comment]
Hope this helps. Thanks Claus
[Logs_180221_19-16-00.zip](https://github.com/pannal/Sub-Zero.bundle/files/1745408/Logs_180221_19-16-00.zip)

**Comment by eltismerino** [comment]
Are there special characters inside the file names of `/tmp/mnt/sda2/data/film/`? It seems like it fails on a "ä".

What's your system locale set to? Please show me the output of `locale`.

For OpenSubtitles: It seems to refuse connecting to you: `error: [Errno 111] Connection refused`. It may have just been a temporary hickup.

**Comment by pannal** [comment]
Are there special characters inside the file names of `/tmp/mnt/sda2/data/film/`? It seems like it fails on a "ä".

What's your system locale set to? Please show me the output of `locale`.

For OpenSubtitles: It seems to refuse connecting to you: `error: [Errno 111] Connection refused`. It may have just been a temporary hickup.

**Comment by MoellerClaus** [comment]
/tmp/mnt/sda2/data/film/ where is this?

[Locale.zip](https://github.com/pannal/Sub-Zero.bundle/files/1752743/Locale.zip)

From the opensubtitles log. I read communication error due to protocol? It worked all very well until I changed IP and changed back?
I have tried to delete all zub-zero folders. Deleting it via plug-ins only deletes some but not the settings o.a.

**Comment by pannal** [comment]
> /tmp/mnt/sda2/data/film/ where is this?
On your system. I'm only reading what's inside the logs.

> I have tried to delete all zub-zero folders. Deleting it via plug-ins only deletes some but not the settings o.a.
Why are you trying to delete it? How did you install it?

> Locale.zip
That's a zip file containing a python file. I need the output of `locale` when entered in your console on your server.

**Comment by MoellerClaus** [comment]
I have tried several things but still not working.
As I see it subzero only runs when I trigger it via plugins, subzero
My locale is danish. I have tried to change to english - no difference.
Plex-server is running NetgearR9000
Hope you can help - it used to work so fine, but lastest updates of Plex it does not.

Thansk in advance for any guidance. I attach in zips all settings and logs.

[Logs_180304_10-36-46.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778338/Logs_180304_10-36-46.zip)
[subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778339/subzero.zip)

**Comment by MoellerClaus** [comment]
After becomming a member at Opensubtitles it wotks for me.
But only if I force updates via SZ menu.
