### ISSUE TITLE
This plugin is not responding error message when clicking on Plugin within Plex

### ISSUE THREAD

**Issue by astrodad** [pannal/Sub-Zero.bundle#442]
Just installed the plugin from the Plex directory and after configuring, when I click on the Plugin I get the following: 

This plugin is not responding

I can click on the settings and see the settings, and the logs seem to indicate it can download subs. Here are the logs:

https://drive.google.com/open?id=1NfLx4IHiJKpHrbkao_eaYEstEnjv60hL

**Comment by pannal** [comment]
From the one small subzero log file in there, everything looks fine.

Can you set SZ to DEBUG in its settings, open the channel, stop your PMS, then upload the latest logs?

**Comment by astrodad** [comment]
This happens all the time, I have never been able to get this to work.

https://drive.google.com/open?id=1FAvtjK02oc0UE37f6Rrbud36F2aBEwTC

Thanks!

**Comment by pannal** [comment]
Weird. I can't see anything suspicious in your log files. Can you be more specific about your setup? I guess OSX?

**Comment by pannal** [comment]
@ukdtom any ideas? The plugin seems to work fine, I can't make out anything wrong.

**Comment by astrodad** [comment]
PMS is running within a Docker container on a Ubuntu Linux host. The Plex library, configuration, and all media files are mounted on the host and mapped to the Docker container.

**Comment by astrodad** [comment]
I’ll also add that the media folder is entirely read only and that I store all subs in metadata and not in th media folders themselves.

**Comment by ukdtom** [comment]
Sadly not seen anything wrong here, except a none related error where PMS complains about missing rights to create a transcoder directory..

When said, you picked only the current logs, and they do roll over very fast, so suggest that you reproduce, and then zip ALL the logs.

And.....

Since you said that you are running read-only for medias, and can't access the channel setup, maybe manually alter the conf for a short test, to make sure it saves in the internal library, and then restart PMS
Setting "<subtitles.save.filesystem>false</subtitles.save.filesystem>"

**Comment by pannal** [comment]
@ukdtom he is able to change the plugin settings via the agent configuration.
Also the plugin itself works, just not the channel. I'm pretty much out of ideas.

**Comment by astrodad** [comment]
I’ll clear logs and run for a few minut a longer and then zip up all the logs. I’ll also try your suggestion about the conf. Thanks for your help!

**Comment by astrodad** [comment]
Interestingly l, I do get an error saving prefs in the browser but the all f

**Comment by astrodad** [comment]
Ugh can’t edit on mobile. I was saying that I get an error saving the prefs but the file does get updated. I don’t think it’s related but I’ll send a screen shot nonetheless.

**Comment by ukdtom** [comment]
If I dig the logs correctly, you are using the hosted WebClient.

Any difference when using the client bundled with PMS instead?

**Comment by astrodad** [comment]
@ukdtom I looked at the xml file and it's currently set to `<subtitles.save.filesystem>false</subtitles.save.filesystem>`

When you say to use the client bundled with PMS, do you mean go to the host directly? I did that and this time instead of Plugins it says Channels. But I get "Channel Not Responding" instead of "Plugin Not Responding". 

https://drive.google.com/open?id=13JVpoywtI-G23YYZbU7QSx6huNA-dmyJ

**Comment by ukdtom** [comment]
Ack, and simply a desperate attempt here, since we in the past have seen strange errors with the hosted WebClient

Also note:

`Feb 24, 2018 15:54:12.197 [0x7f181e0c1800] ERROR - Error creating directory "/home/plex/plextranscode": boost::filesystem::create_directories: Permission denied: "/home/plex"`

**Comment by astrodad** [comment]
I can fix that transcode issue. I'll work on that now.

**Comment by pannal** [comment]
Definitely try using your local plex web, not plex.tv.

**Comment by astrodad** [comment]
@pannal I did try to use the host directly. It's not local either, the Docker container runs on dedicated co-located server, but I did use the IP directly. That's what I was trying to convey in my comment above. https://github.com/pannal/Sub-Zero.bundle/issues/442#issuecomment-368259886 

I fixed the problem of the transcoder folder and am getting the same results.

**Comment by pannal** [comment]
That's so weird, I can see from your latest logs that SZ runs perfectly and throws no errors. It doesn't even seem like its channel functions are being called by the PMS when you try accessing it.

This might be out of scope, can you create a thread on the Plex forums about this?

**Comment by astrodad** [comment]
Ok I will see what they have to say over there. I’ll close this for now, then. Thanks for looking at it!
