### ISSUE TITLE
SubZero doesn't automatically download subtitles

### ISSUE THREAD

**Issue by kgout3** [pannal/Sub-Zero.bundle#444]
Hello,

I've updated to the latest version and I'm having issues where the majority of my library doesn't automatically download subtitles. I've followed the wiki documentation and when I go to the plugin, browse all items and select a movie that doesn't have a subtities and perform a refresh, it works great. The issue is it doesn't search and download the subtitles automatically, which I think is the main selling point of this plugin. I have to be missing something obvious?  

Logs attached.  Thanks for the help!
[Logs_180225_14-58-52.zip](https://github.com/pannal/Sub-Zero.bundle/files/1756642/Logs_180225_14-58-52.zip)

**Comment by pannal** [comment]
Hey,

You need to fix your file/folder permissions: `IOError: [Errno 13] Permission denied: u'\\\\?\\E:\\Media\\Movies\\Murder on the Orient Express (2017)\\Murder on the Orient Express (2017).mkv'`
