### ISSUE TITLE
Subtitles duplicating

### ISSUE THREAD

**Issue by javernp** [pannal/Sub-Zero.bundle#447]
So when a new show gets added it adds over 7 subtitles to it, none being the actual subtitle, it never use to do this now it just happens
![plex subs](https://user-images.githubusercontent.com/36919031/36783236-549a6028-1c73-11e8-9d55-00edfaa52e38.png)

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#scanning-configuration

You most likely changed `Scan: Which external subtitles should be picked up` to any. Why does everyone do that all of a sudden?

**Comment by javernp** [comment]
Thanks for that, it must have gotten changed by accident
