### ISSUE TITLE
Throttled Providers : Addic7ed

### ISSUE THREAD

**Issue by FlorianFranconi** [pannal/Sub-Zero.bundle#448]
Hello,

Sub-Zero version: 2.5.0.2287

In the parameters of subzero I have the following message:"Throttled providers: addic7ed - addic7ed until 18/03/01 17:45 (TooManyRequest).

As a result I have several French subtitles that the plugin can't find when they are well available on addic7ed. My minimum search score is 337.

Attached are my logs.

Thank you for your help.
[Logs_180301_16-44-15.zip](https://github.com/pannal/Sub-Zero.bundle/files/1771816/Logs_180301_16-44-15.zip)
<img width="484" alt="capture d ecran 2018-03-01 a 16 53 15" src="https://user-images.githubusercontent.com/23030829/36854465-5eaf0f92-1d71-11e8-85b7-510d451d4516.png">

**Comment by pannal** [comment]
Please enable `Addic7ed: Use random user agent: Randomizes the user agent`. This will be the default in the next version.

**Comment by tudor131313** [comment]
Hello! I also have this problem at the moment. I do not know why. Could someone perhaps help me?

**Comment by ukdtom** [comment]
@tudor131313 

https://github.com/pannal/Sub-Zero.bundle/wiki/Provider

Look at item 9

**Comment by pannal** [comment]
@ukdtom this is the default now.

**Comment by tudor131313** [comment]
it is checked. i would not have posted here if it was not, but still shows the aforementioned error

**Comment by pannal** [comment]
You might just have hit the limits - normally they don't throttle for no reason. Do you use a seedbox or a shared IP?

**Comment by tudor131313** [comment]
i do use a seedbox but what i'm running on that doesn't use that provider. i refreshed my entire library recently. maybe that is the reason? can i contact them to 'unthrottle' my ip?

**Comment by M0rr1s0n** [comment]
I do have this issue as well, my logs show, that after the throttling ends or a restart there is immediately another "TooManyRequests" throttle starting:

> 2018-05-11 16:29:25,357 (22ac) :  DEBUG (logkit:13) - subliminal.providers.addic7ed: Logged in
> 2018-05-11 16:29:25,358 (22ac) :  DEBUG (logkit:13) - subliminal_patch.providers.addic7ed: addic7ed: using random user agents
> 2018-05-11 16:29:25,391 (22ac) :  DEBUG (logkit:13) - subliminal.providers.addic7ed: Getting show id with year
> 2018-05-11 16:29:25,392 (22ac) :  DEBUG (logkit:13) - subliminal.providers.addic7ed: Getting show id
> 2018-05-11 16:29:25,392 (22ac) :  INFO (logkit:16) - subliminal_patch.providers.addic7ed: Getting the page of show id 2951, season 6
> 2018-05-11 16:29:25,507 (22ac) :  INFO (logkit:16) - Throttling addic7ed for 1 hour, until 18/05/11 17:29, because of: TooManyRequests

Log: [com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1995669/com.plexapp.agents.subzero.log)
