### ISSUE TITLE
future autoupdate

### ISSUE THREAD

**Issue by miniop** [pannal/Sub-Zero.bundle#45]
Do you think you can add update future ?

Example: https://github.com/coder-alpha/ChannelUpdater.bundle

**Comment by pannal** [comment]
Yeah, considering it. Have to look into it, though - the plugin you've just linked to requires root access and I don't want that.

**Comment by eilandert** [comment]
If you do the development/cutting edge in the masterbranche, and make a new branch each time when you do a release, we can easily auto-update with git clone/checkout.

**Comment by pannal** [comment]
Yeah I will move to develop in the master branch again, after 1.3.0
For release branches: I automatically create tags for a release, that should be enough?

**Comment by ledge74** [comment]
@pannal Why don't you ask the Plex team to distribute Sub-Zero through their "channel store"? I see there is already some metadata agents there, and you would benefit of their upgrade feature as well as a great exposure within the Plex community.

**Comment by pannal** [comment]
Oh I never thought about that. I'll see what it takes to be in there.

**Comment by ledge74** [comment]
Here are the requirements: https://support.plex.tv/hc/en-us/articles/201199096-Submitting-your-channel-for-the-Channel-Directory

**Comment by pannal** [comment]
I've just sent them a mail to submit SZ into the channel directory. Thank you for the hint!

**Comment by eilandert** [comment]
@pannal to come back about branches, you should tag 1.3.5-stable or something. 
That way you can develop 1.3.6 with new features/cutting edge in master while maintaining a stable tree in 1.3.5-stable for fixes and/or backports from master.

That way we can easily git checkout bleeding edge for testing new stuff, and return to -stable if neccesarry. 

Thanks for your hard work, you've accomplished a lot in a relative short time.

**Comment by pannal** [comment]
Yep, good idea.

**Comment by pannal** [comment]
I didn't receive any reply to my channel directory inquiry. Does anyone have further information?

**Comment by ledge74** [comment]
Maybe you should try to contact directly someone from Plex inc.?

**Comment by pannal** [comment]
That's what I did: "Send an email to (sander at plex dot tv), with a link to your channel on GitHub"

**Comment by ledge74** [comment]
Maybe trying to ask directly to a moderator on the forum would be more effective?

**Comment by pannal** [comment]
This is pretty interesting: https://github.com/sharkone/BitTorrent.bundle/blob/master/Contents/Code/updater.py

**Comment by sharkone** [comment]
I actually coded that because of the Unsupported App Store got banned from GitHub and I needed a way to allow my users to be aware of new version and allow them to trigger an update.

The ChannelUpdater.bundle you linked in the first post here, was actually inspired by my code.

**Comment by pannal** [comment]
Finally Sub-Zero has been accepted as one of the few official plugins. Closing this :)
