### ISSUE TITLE
Error when trying to select active subtitle

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#450]
https://github.com/pannal/Sub-Zero.bundle/issues/441#issuecomment-370029861

It's an oversight. It happens once you've added anything to the blacklist for that particular item. Fixed in develop-2.1 branch.

**Comment by jbreuer95** [comment]
Fixed :)

**Comment by pannal** [comment]
Awesome, this'll be in the next release then. Thank you for testing.
