### ISSUE TITLE
Cannot get logs

### ISSUE THREAD

**Issue by cbernet** [pannal/Sub-Zero.bundle#452]
Hello, I'm not getting any subtitles from subzero, so I'd like to get my logs. 
I followed these instructions: https://github.com/pannal/Sub-Zero.bundle/wiki/Logs
And copied the following link to my browser: 
https://88.175.213.86:32400/video/subzero/logs?X-Plex-Token=cNXXXXXXXXXXXZq3

But after a while I'm getting a timeout error saying that maybe the website is unavailable or overloaded.
My internet connection does work at the moment. 
Is there a temporary issue or can you please help me getting logs in some other way?

**Comment by ukdtom** [comment]
I've updated above, and scrambled the token

NEVER EVER post your token in a public place!

**Comment by cbernet** [comment]
Thank you, sorry.

**Comment by ukdtom** [comment]
NP, and you can get the logs manually

https://github.com/pannal/Sub-Zero.bundle/wiki/Logs#sub-zero-channel-is-not-showing

**Comment by cbernet** [comment]
Thank you I was able to get the logs from my shield, the instructions are very clear. Closing this issue, I will open another one concerning the exception I see.
