### ISSUE TITLE
Embedded subtitles extraction and usage discussion

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#455]
Fire away!

**Comment by pannal** [comment]
Continued:

Automatically extracted subs get assigned a score of 0 and are set as current, if there's no current subtitle set. That way they'll be superseded by any other subtitle downloaded by the find better subtitles task if the setting `Scheduler: Overwrite manually selected subtitles when better found` is left on. They are valid subtitles, though, and are treated as such.

I don't know whether that answers your question. The problem with PGS subs is that they're image based and we'd need some sort of OCR mechanism to extract those to a usable text format. I guess that's way out of scope right now.

**Comment by kjac3585** [comment]
So I would need to delete the downloaded subs in order for the embedded subs to be extracted? 

I'm trying to think of how I can best preserve any extracted subs over downloaded ones since embedded subs are usually pretty accurate, at least as far as not needing timing adjustments.

**Comment by pannal** [comment]
To clarify: Manually extracting subtitles via the menu sets that subtitle as the current one - automatically extracted ones are set as current if there is no current subtitle set.

To keep your extracted subtitles, you'd have to deactivate `Scheduler: Overwrite manually selected subtitles when better found`. I might add advanced settings for more fine grained control over that in the future.

**Comment by kjac3585** [comment]
ok, that makes sense. I'll just uncheck that setting then.

As far as OCR goes, I saw [subextractor](https://archive.codeplex.com/?p=subextractor), but this bit doesn't sound ideal.

> most DVDs should require manual matching of just a few characters. Some characters like l, I, 1, o must be manually matched for every DVD since they have a lot of false positives.

I'm not sure what all is available for OCR that is open source, I remember ABBYY FineReader being called the best in OCR back when I did book scanning, but I'm sure it's not open source.

**Comment by pannal** [comment]
Well there's Googles' tesseract, which is used by SubtitleEdit, but it still needs a fair amount of manual training. I guess it could be done fairly reasonable with a huge amount of samples, but that's completely out of scope right now.

**Comment by matthewmcpartland** [comment]
I also had the issue of PGS subs not being considered for embedded subs, so it would still download the SRT file for the movie even though it should have been setup not to.

I haven't tried the special builds you made for kjac. Would it be possible to give an option within subzero to download SRT when you only have image based subs, as it does right now? Image based causes transcoding pretty often and autograbbing SRT in this scenario is actually kind of nice. Maybe an option to try and find SRT also when only ASS/SSA are present, since those have very little support as well

**Comment by pannal** [comment]
@matthewmcpartland I'm not sure I follow you there. You can uncheck option 3 here: `https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#scanning-configuration`, then SZ will pay no attention to the embedded subtitles and will act accordingly. If you leave that checked, only text based subtitles will be considered as existing, and image based won't. By enabling option 6, even image based ones will be considered as existing.

Currently there's no distiction between ASS/SSA and SRT, as both are text based and should work on most of the modern devices. That may be a good addition to the `advanced_settings.json`, though.

Auto-converting PGS won't work.

**Comment by matthewmcpartland** [comment]
I didn't realize that option existed and worked with PGS since it didn't say PGS but did list the text based options. I deleted the subtitle SZ grabbed for me and it didn't seem to come back when refreshing the movie. My problem is solved!
