### ISSUE TITLE
Allow specification of text-based subtitle formats in advanced_settings.json

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#464]
Currently considered as image-based: "srt", "ass", "ssa", "vtt", "mov_text"

**Comment by pannal** [comment]
#455

**Comment by pannal** [comment]
Fixed in next release

**Comment by ukdtom** [comment]
Guess image-based means txt-based in my book :)

**Comment by pannal** [comment]
Yup, fixed
