### ISSUE TITLE
Add Argenteam provider

### ISSUE THREAD

**Issue by jcastilloalonso** [pannal/Sub-Zero.bundle#465]
Argenteam is a great source of Spanish subtitles, plus very flexible (supports rss etc.)

I know Subliminal was very close to integrate it but it was never completed:

https://github.com/Diaoul/subliminal/pull/883

Hopefully you could finish it and integrate it, We still suffer with Spanish subtitles as there is no dedicated source for it.

Thanks!

**Comment by pannal** [comment]
This is easy enough and complete enough to be integrated into SZ. @jcastilloalonso would you be up for testing?

**Comment by jcastilloalonso** [comment]
Sure @pannal I would love to test it out. A main Spanish source of subtitles would be a great addition to your already amazing agent/channel :)

**Comment by pannal** [comment]
Then please follow this: https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes
