### ISSUE TITLE
Storage of subtitles in metadata does not seem to work

### ISSUE THREAD

**Issue by jkoopmann** [pannal/Sub-Zero.bundle#466]
Hi,

I cannot have SZ add SRT files to the original movie files as I am using plexdrive with google and hence from plex point of view have a read only filesystem. So I chose to store in metadata. According to the log things are downloaded and stored. However the subtitles do not show up in plex. If I look at the metadata bundle associated with the movie I can see a com.plex.agent.subzero.bundle directory with an Info.xml in it. But no srt files. Any idea what is going wrong?

If I use a custom directory for it, the SRT files are placed there correctly however again plex does not show them. Does the custom dir need to be in the library search path?

Regards,
   JP

**Comment by jkoopmann** [comment]
The XML file associated with the movie also does not show any reference of SRT files either.

**Comment by pannal** [comment]
Can I see log zips for both cases? (see the wiki on how to obtain logs) 

Metadata storage and global custom Subtitle folders are features that are very rarely used, so it's completely possible this is a bug.

**Comment by pannal** [comment]
I've just tried it locally, by extracting an embedded subtitle using the SZ menu:
`DEBUG (storage:197) - Using metadata as subtitle storage`
`DEBUG (subtitlehelpers:198) - Found metadata subtitle: en, ('Media', 'srt', None, None, 'srt', None, None, None)`

And I can access the subtitle using Plex Web and see it in the XML output.

**Comment by jkoopmann** [comment]
Hi,

it works on some of the movies and does not work for others without me being able to clearly see a difference in the logs. I will try to reproduce this later on with debug level set to high and drop you a log snipplet. I can confirm that it is not ALWAYS disfunctional. Where exactly are the SRTs stored so I can maybe take a look there?

Regards,
   JP

**Comment by pannal** [comment]
I think they're stored in `Media/localhost/X/XXXXXXXXXXXXXXXXXXXXXXX/Contents/Subtitles`. You'd have to look directly at the sqlite database of the PMS to find the specific folder for an item, though.

**Comment by jkoopmann** [comment]
I got the logs. Any safe way of getting them to you? Due to potential unsafe information I would rather not simply attach them here if not necessary...

**Comment by pannal** [comment]
Yeah, [join our Slack](https://szslack.fragstore.net) and send them there.
