### ISSUE TITLE
Setting HI

### ISSUE THREAD

**Issue by ukdtom** [pannal/Sub-Zero.bundle#467]
When setting "Download hearing impaired subtitles" to either forced or preferred, then during the pref validate function, it should set "Remove Hearing Impaired tags from downloaded subtitles" to false, IMHO

https://docs.google.com/document/d/1hhLjV1pI-TA5y91TiJq64BdgKwdLnFt4hWgeOqpz1NA/edit#heading=h.n7bxuzuq61gp

Best Regards

Tommy

**Comment by ukdtom** [comment]
And adding to this ;)

If OS Agent is enabled in SZ, then maybe disable native agent?

**Comment by pannal** [comment]
I'm not really a fan of auto changing stuff without being able to tell the user so. I get the argument, but I'm not sure this'll change anytime soon. 

Notifications or inline verification/messaging inside the settings view would help with that.

**Comment by ukdtom** [comment]
True, but sadly not possible within the prefs...
But a msg popup directory object could be called from the validate function I guess

**Comment by pannal** [comment]
Hm no, the validate function doesn't return any ObjectContainers. I could store the message and display it when the user visits  the channel again or something like this.

Not prio 1 right now :)
