### ISSUE TITLE
Channel gone on Nvidia Shield TV ?

### ISSUE THREAD

**Issue by stve-a** [pannal/Sub-Zero.bundle#468]
Can no longer see the SZ channel on PMS on Nvidia Shield TV ?

When I go to install, it says it's already installed.
Tried reset of the channel but did not work.
Reboot of PMS also didn't change anything.

regards
S

**Comment by pannal** [comment]
Which version are we talking about and can you provide logs?

**Comment by stve-a** [comment]
Hi Pannal, 

I can't see the version cause I cannot enter the channel nor it's config.
Had to go an install an SSH server from google store to get on the filesystem.

I managed to find the logs after searching for awhile:

INFO (core:349) - Starting framework core - Version: 2.6.3, Build: c40bba8 (Fri Feb 16 03:03:51 UTC 2018)

I'll provide logs tomorrow if you need.

Regards
S

**Comment by stve-a** [comment]
UPDATE:

Very weird. Looks like after my SSH session I can see the channel again.
I honestly didn't do anything else (you can't do much with a non-rooted stock nvidia shield tv)

Looks resolved. Thanks for your time !
Regards
S

**Comment by pannal** [comment]
Phew, that would've been a blocking issue for the upcoming release. Glad it sorted itself out! Cheers!
