### ISSUE TITLE
SZ disapears under PLEX plugins

### ISSUE THREAD

**Issue by MoellerClaus** [pannal/Sub-Zero.bundle#474]
Hi
I have installed Subzero and today I uninstalled it from Plex, plugins in order to update to recent version (from yesterday).

Now it disappers under the overview of plugins. When I go into plugin overview and find Subzero it ticks it off as installed. But as said it does not appear in the plugin - overview.
Uninstalling and installing does not make a difference.

Anybody experienced the same?
![subzeronoplugins](https://user-images.githubusercontent.com/5902676/37877811-529b3832-3060-11e8-9d46-6491a46f8118.png)
![subzeroinstalled](https://user-images.githubusercontent.com/5902676/37877816-55fb9666-3060-11e8-954d-2e5f6867f851.png)

**Comment by ukdtom** [comment]
Hej med dig.

Please take a peak here:

https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q1-sub-zero-is-not-visible-among-the-channels

**Comment by MoellerClaus** [comment]
Tak til dig.

Yes Agent + Channel must be enabled.
