### ISSUE TITLE
Calling external script - arguments aren't pass to external script

### ISSUE THREAD

**Issue by Haxy89** [pannal/Sub-Zero.bundle#477]
![image](https://user-images.githubusercontent.com/37550896/37916125-59d7837e-311b-11e8-8833-fb54a7a81a58.png)
![image](https://user-images.githubusercontent.com/37550896/37916151-6f98e50e-311b-11e8-903a-a750061db735.png)

**Comment by Haxy89** [comment]
Sorry, documentation is not clear. Need to pass parameters manually:

![image](https://user-images.githubusercontent.com/37550896/37917308-5c2b9842-311e-11e8-9de5-7ace89dcaede.png)

**Comment by pannal** [comment]
Yes, you need to specify the arguments you want it to pass.
