### ISSUE TITLE
Napiprojekt: Subtitles for TV shows are found but not downloaded

### ISSUE THREAD

**Issue by Haxy89** [pannal/Sub-Zero.bundle#478]
File name: 
![image](https://user-images.githubusercontent.com/37550896/37916500-42ab0fe4-311c-11e8-8428-2639e0c1fa69.png)

Log files:

[log.txt](https://github.com/pannal/Sub-Zero.bundle/files/1848459/log.txt)

**Comment by pannal** [comment]
Yep, it's a bug.

**Comment by Haxy89** [comment]
Do I need install it manually?
When new version will be available for auto update?

**Comment by pannal** [comment]
Yeah if you want to try the fix, you need to install manually.

The currently queued auto-update release is not merged yet, and I can't control when it will be.

**Comment by KBlixt** [comment]
how long time does it usually take for these kind of update to get merged? ar we talking hours, days or weeks?

**Comment by Haxy89** [comment]
https://github.com/plexinc-agents/Sub-Zero.bundle/pulls
It is a joke, waiting for merge 24h...

**Comment by pannal** [comment]
It can range from minutes to days, depending on how busy the maintainer is. Then it takes up to a day for the update to be rolled out to everyone.

**Comment by Haxy89** [comment]
@pannal 
The newest hotfix does not work.
Before hotfix subtitles were found but not downloaded, 
After hotfix subtitles are not found for the same file

See log file:
[log.txt](https://github.com/pannal/Sub-Zero.bundle/files/1852614/log.txt)

Please, fix asap

**Comment by pannal** [comment]
They're still found judging by your log. Please post the full log zip (advanced menu -> get my logs)

**Comment by pannal** [comment]
Also, the napiprojekt fix is *not* included in hotfix 2.5.3.2422, as you can see by looking at the changelog.

You're still welcome to try the develop-2.5 branch with a manual installation. It'll take a couple of days until I release the next version officially.

**Comment by Haxy89** [comment]
@pannal 
I don't see release 2.5.3.2429 here https://github.com/pannal/Sub-Zero.bundle/tags

**Comment by pannal** [comment]
Because there is none. Now either wait for an upcoming release, or go the manual route and [install the develop-2.5 branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.5.zip). Be sure to rename the extracted folder from `Sub-Zero.bundle-develop-2.5` to `Sub-Zero.bundle`.

**Comment by Haxy89** [comment]
Fix in 2.5.3.2429 works. Many thanks 👍
