### ISSUE TITLE
Sub-Zero menu view settings are not saved - always reset to "Details" view

### ISSUE THREAD

**Issue by Haxy89** [pannal/Sub-Zero.bundle#480]
I am trying to set menu view to list but it always reset to default details view

![image](https://user-images.githubusercontent.com/37550896/37921447-24c82544-312a-11e8-9e49-79dc03278af1.png)

**Comment by pannal** [comment]
That's intended behaviour as the details view is needed to show the necessary information to navigate SZ properly.
