### ISSUE TITLE
possible bug: 'Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing'

### ISSUE THREAD

**Issue by mickeldaelmans** [pannal/Sub-Zero.bundle#482]
Hi panni,

Recently I noticed that the 'Search for missing subtitles' task only took 40 something minutes (it used to take a good few hours with my current settings). I also noticed that my history contained very few to none new subs that could have been picked up by the task. 

When checking the logs I saw this error:

'Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing'

When checking the other log files it seems that the task stops after that error.

please see 2018-03-28 08:54:16,393 in the attached com.plexapp.agents.subzero.log for the latest occurence of the error.

[Logs_180328_12-00-20.zip](https://github.com/pannal/Sub-Zero.bundle/files/1855485/Logs_180328_12-00-20.zip)

**Comment by pannal** [comment]
You're running 2.5.3.2414, this is fixed in hotfix release 2.5.3.2422.

Also you should see a lot less memory usage with the search for missing subtitles task in 2.5, compared to the older versions.
