### ISSUE TITLE
Opensubtitles won't download - response error, reinitializing

### ISSUE THREAD

**Issue by hogmac** [pannal/Sub-Zero.bundle#483]
Hi - not sure if this is related to a previous issue I reported a few days ago, but today I'm not able to download any subtitles from Opensubtitles.  Receiving below error:

`ERROR (logger:38) - subliminal_patch.core: Provider 'opensubtitles' response error, reinitialising`

Also have other line inlets reflecting

`SSLError: ('The read operation timed out',)`.  Please see full logs attached and let me know what may be causing this issue.  Thanks in advance.

[Logs_180330_01-28-04.zip]
(https://github.com/pannal/Sub-Zero.bundle/files/1862429/Logs_180330_01-28-04.zip)

**Comment by pannal** [comment]
Hey,

I'm still trying to figure out some of the latest OpenSubtitles issues. Would you be up for testing? I've added more debug logging to the current develop version and an option to disable HTTPS for OpenSubtitles.

If you want, try a [manual installation](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation) of [develop-2.5](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.5.zip). Be sure to rename the extracted bundle to `Sub-Zero.bundle`.

**Comment by pannal** [comment]
If you just used develop-2.5, be sure to update again (re-download zip). I've reimplemented the request handling. 

Anything SZ related should be fixed now.

**Comment by hogmac** [comment]
> If you just used develop-2.5, be sure to update again (re-download zip). I've reimplemented the request handling.

Anything SZ related should be fixed now. <

I just tested developer version 2.5 (the most updated one you have) and opensubtitles seemss to be working again.  No issues so far.  Thanks for the quick handle, hope this won't break again.

**Comment by pannal** [comment]
#475 wasn't a good fix then. This one may be.
