### ISSUE TITLE
Opensubtitles only download when "forced find subtitles"

### ISSUE THREAD

**Issue by MoellerClaus** [pannal/Sub-Zero.bundle#484]
From the log I can see that subzero is initiated and started.
It finds nothing even though there are no subtitles.
It gives a decode-error. As I see it there are no non english characters in the titles.

Everything works fine with if I manually go in to the subzero and finds the film and force it to find subtitles. Podnapsi and Opensubtitles gives subtitles back as needed.

Running Version 2.5.3.2422.

Maybe I just have to tick something on? Thanks for any advice.

[Logs_180330_07-01-52.zip](https://github.com/pannal/Sub-Zero.bundle/files/1862920/Logs_180330_07-01-52.zip)

**Comment by pannal** [comment]
Did you manually install/update Sub-Zero? The error I'm seeing has been fixed a couple of versions ago.

**Comment by MoellerClaus** [comment]
Thanks Pannel for coming back to me on this issue.

I have installed the latest version via the Plex, Plugin menue. It could not update automatically when cheking for new version. So I uninstalled via this menu and installed again and the latest version was now installed.
What puzzles me a bit is that the settings remains intact even after this procedure. Where do SZ store the user setttings? Maybe a real from scratch installation may help?

**Comment by pannal** [comment]
This might actually be an issue. Can you please copy your `\Library\Application Support\Plex Media Server\Plug-in Support\Preferences\com.plexapp.agents.subzero.xml` file to a safe place, then delete it, then restart your PMS?

Then attach the old and the new file here. I've seen another user with this issue recently and I'd like to fix it.

SZ retains its settings and its database (PMS does) between updates.

**Comment by MoellerClaus** [comment]
In between I have stopped Plex-server; reinstalled the plex, installed subzero via the menu in plex, complete new scan of all my libraries. Same result as mentioned. Works well with forcing update via subzero menu - title by title. According to log no files are "guessed".

[Plex_SubZero_xlms.zip](https://github.com/pannal/Sub-Zero.bundle/files/1886125/Plex_SubZero_xlms.zip)

**Comment by MoellerClaus** [comment]
[Logs_180407_20-55-00.zip](https://github.com/pannal/Sub-Zero.bundle/files/1886640/Logs_180407_20-55-00.zip)

**Comment by pannal** [comment]
Do you have the means to install the current develop-2.5 branch? I've added fallbacks for the decoding errors.

**Comment by MoellerClaus** [comment]
Ofcourse; please see below for the logs.

[Logs_180408_08-45-05.zip](https://github.com/pannal/Sub-Zero.bundle/files/1887100/Logs_180408_08-45-05.zip)

**Comment by MoellerClaus** [comment]
I uploaded a new media; All metadata except subtitles where updated automatically. I then went to the desktop picked the new media and ask to scan files. Wupti it found subtitles for the specified three languages. My is guess is that you should look automatic scanning - but what do I know ;-)
Attached the logs where it semi-worked.

[Logs_180408_08-48-45.zip](https://github.com/pannal/Sub-Zero.bundle/files/1887106/Logs_180408_08-
48-45.zip)

**Comment by pannal** [comment]
Please set SZ's log level to DEBUG ("How verbose should the logging be?"), then try to reproduce the issue, please.

**Comment by MoellerClaus** [comment]
Attached please find the test with making a new directory and adding 2 media that has subtitles in all 3 languages. It works now of the shelf! Not changing the version of SZ nor adding anything. Could it have been an error correctiv in some software that SZ calls?
I will make further test and come back. But thanks so much it seems to work now (again)

[Logs_180411_19-43-38.zip](https://github.com/pannal/Sub-Zero.bundle/files/1899883/Logs_180411_19-43-38.zip)
