### ISSUE TITLE
Sub-zero not showing Legendas.tv subs when searching manually

### ISSUE THREAD

**Issue by mimed** [pannal/Sub-Zero.bundle#487]
I'm unable to download subtitles from the agent Legendas.tv. It doesn't even show options from Legendas.tv when manually searching on Subzero. It only show subs from OpenSubtitles and Addic7ed.

Here are screenshots from my config
<img width="1580" alt="screenshot 2018-04-02 12 13 26" src="https://user-images.githubusercontent.com/6992776/38202062-ca2fba42-3670-11e8-98cd-e9cce8e763bc.png">
<img width="573" alt="screenshot 2018-04-02 12 11 21" src="https://user-images.githubusercontent.com/6992776/38202063-ca538b7a-3670-11e8-9003-0bfcb78e823b.png">
<img width="565" alt="screenshot 2018-04-02 12 11 03" src="https://user-images.githubusercontent.com/6992776/38202064-ca744bb2-3670-11e8-8225-d9eeaad0fdd2.png">

.

**Comment by pannal** [comment]
Please set SZ's log level to DEBUG, then navigate to an item in question and do the subtitle listing. Then attach your log zip here (see wiki), thanks!

**Comment by mimed** [comment]
Here it is @pannal. 
[Logs_180402_12-35-02.zip](https://github.com/pannal/Sub-Zero.bundle/files/1868476/Logs_180402_12-35-02.zip)

**Comment by pannal** [comment]
OK. It definitely is because UNRAR isn't available. I'm hoping to fix this in the upcoming version by shipping unrar with Sub-Zero.

**Comment by pannal** [comment]
You can mitigate this by making unrar available inside your environment, as per #311 - I can't help you with the proper installation instructions, though.

**Comment by brunoluzsousa** [comment]
Hi, @pannal. I believe I am witnessing a similar SZ behavior. In order to SZ show me Legendas TV subtitles I have to click "List available subtitles" three times before SZ actually show me the subtitles.

Here's a Dropbox link with a video demonstrating the issue and the log zip: https://www.dropbox.com/sh/abh6nzcqe6qf2w0/AACD3CcyhPXDCWEgadgZIYsTa?dl=0

**Comment by mimed** [comment]
Hi @brunoluzsousa 

After clicking list available subtitles three times, are you able to download the sub using the method you provided on #311?

**Comment by brunoluzsousa** [comment]
No, @mimed. This is the unrar issue @pannal is trying to show.

**Comment by pannal** [comment]
@brunoluzsousa that's expected behaviour. You can just click `Searching for XXXX, refresh here` instead of going back to see whether the background task has finished searching for subtitles.

**Comment by brunoluzsousa** [comment]
Ooh, right! Got it, @pannal!

**Comment by mimed** [comment]
Lovely, @pannal. Thanks for the amazing work.

When is the next version going to be shipped?

**Comment by pannal** [comment]
@mimed I'm guessing in the coming week.
