### ISSUE TITLE
OpenSubtitles ConnectTimeout

### ISSUE THREAD

**Issue by phatassdk** [pannal/Sub-Zero.bundle#488]
Hi,

Keep getting timed out when SZ is searching for subtitles at OpenSubtitles.
This error has been present for the last many releases.

Please see attached logs and let me know if you'd like me to provide additional info. Thanks. :)
[Logs_180404_08-05-54.zip](https://github.com/pannal/Sub-Zero.bundle/files/1874511/Logs_180404_08-05-54.zip)

**Comment by phatassdk** [comment]
Sorry for a late response. Would be interesting to check if a longer timeout might help. It does however seem a little strange if the "timeout timer" is the only culprit. If the actual issue is that it takes 20 seconds to get a response from OS via a Shield, wouldn't I currently see OS working once in a while when the OS servers are lightly loaded? I am not able to DL anything from OS at all. 
Would you be able to add the HTTPS/HTTP advanced option in the menu as well? I cannot access Plex files as you suggested without rooting. Ended in a bootloop twice when I tried to root. Without root I can only access the regular folders such as Downloads, DCIM... ect. 
Thanks. :)

**Comment by pannal** [comment]
I'll add a different way of providing the `advanced_settings.json` file, with a user-defined path. Those settings shouldn't be in the general settings area.

**Comment by pannal** [comment]
Unfortunately no, not unless Plex Inc changes the way plugin preferences work. I literally have no control over how they're displayed.

**Comment by phatassdk** [comment]
That's also quite minor compared to find the OS/Shield bug. :)
