### ISSUE TITLE
Sub Zero issues with Addic7ed

### ISSUE THREAD

**Issue by dny238** [pannal/Sub-Zero.bundle#490]
I'm one of the developers on Addic7ed. we're working on an API and would like some input from you. Would you be willing to email me on the side?

**Comment by pannal** [comment]
Of course. We could also talk on Slack (https://szslack.fragstore.net)

**Comment by pannal** [comment]
@dny238 email or slack?

**Comment by pannal** [comment]
@dny238 bump?

**Comment by dny238** [comment]
https://sub-zero-plex.slack.com/messages/DAA573SQM/team/UA9PQ12LU/

**Comment by pannal** [comment]
Gotcha

**Comment by pannal** [comment]
Well, @dny238, you're not answering.
