### ISSUE TITLE
Guessit problem

### ISSUE THREAD

**Issue by morpheus133** [pannal/Sub-Zero.bundle#493]
There is some problem with guessit in case of The.100.S04E06.HDTV.x264-SVA.mkv

SZ log:
2018-04-09 12:42:48,736 (492c) :  DEBUG (logkit:13) - subzero.video: Parsing video: The.100.S04E06.HDTV.x264-SVA.mkv, hints: {'episode_title': 'We Will Rise', 'type': 'episode', 'title': u'A visszat\xe9r\u0151k'}
2018-04-09 12:42:48,736 (492c) :  INFO (logkit:16) - subliminal_patch.core: Scanning video 'The.100.S04E06.HDTV.x264-SVA.mkv' in 'C:\\--Own--\\TEEEEEEEEEEEEST2\\The 100'
2018-04-09 12:43:02,696 (492c) :  DEBUG (logkit:13) - subliminal_patch.core: GuessIt found: {
    **"title": "The",** 
    "episode_title": "The 100", 
    "season": 4, 
    "episode": 6, 
    "format": "HDTV", 
    "video_codec": "h264", 
    "release_group": "SVA", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}

But with guessit it is working:

C:\--Own--\test>guessit The.100.S04E06.HDTV.x264-SVA.mkv
For: The.100.S04E06.HDTV.x264-SVA.mkv
GuessIt found: {
    **"title": "The 100",**
    "season": 4,
    "episode": 6,
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "SVA",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

I checked and the problem is with the core.py and the directory path I use:
'C:\--Own--\TEEEEEEEEEEEEST2\The 100\The.100.S04E06.HDTV.x264-SVA.mkv

```
# hint guessit the filename itself and its 2 parent directories if we're an episode (most likely
    # Series name/Season/filename), else only one
    split_path = os.path.normpath(path).split(os.path.sep)[-3 if video_type == "episode" else -2:]
    logger.info('split_path %s ', split_path)
    # remove crap from folder names
    if video_type == "episode":
        if len(split_path) > 2:
            split_path[-3] = remove_crap_from_fn(split_path[-3])
    else:
        if len(split_path) > 1:
            split_path[-2] = remove_crap_from_fn(split_path[-2])

    logger.info('split_path2 %s ', split_path)
    guess_from = os.path.join(*split_path)

    logger.info('guess_from %s ', guess_from)
```

**Comment by morpheus133** [comment]
Than plus additions:
- I am creating a new provider.
-Some match happen because SZ get the match from plex. (But it is Hungarian, not the original one)
- As I see the original title is added to video.alternative_titles  but in current case it is "The" instead of "The 100"

(Some plus log is visible in core.py I dont deleted them)
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1890092/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Hmm. Why is there no proper original title for that series in your library? Shouldn't that be the original, unmodified title, i.e. "The 100"?

**Comment by pannal** [comment]
Are all the titles localized in the properties of the show in your library?
