### ISSUE TITLE
Not downloading subs CRITICAL (core:574)  

### ISSUE THREAD

**Issue by adrian2lee** [pannal/Sub-Zero.bundle#494]
Not downloading any subtitles from any provider, following log is after trying to refresh metadata for single tv episode. Any advise?

[com.plexapp.agents.subzero - Copy.zip](https://github.com/pannal/Sub-Zero.bundle/files/1902105/com.plexapp.agents.subzero.-.Copy.zip)

**Comment by pannal** [comment]
Please attach your log zip (see wiki) instead of pasting first, thank you

**Comment by pannal** [comment]
Resolved?

**Comment by adrian2lee** [comment]
It works on time to time, so I think its plex problem or timeout problem
