### ISSUE TITLE
The Channel Is Not Responding

### ISSUE THREAD

**Issue by WeirDave** [pannal/Sub-Zero.bundle#499]
I am a beginner with regard to QNAP but mine's sole purpose is Plex.

Would really like to get your plugin working. Plus it's a cool concept / idea to use "Sub-Zero"!

QNAP TS-653A
Firmware version: 4.3.4.0537 Build 20180331
Serial Number: Q17CI11582
Hard Drives:
Seagate ST3000DM001 - 3TB
Toshiba MDo4ACA500 - 5TB
Western Digital - WD6001FZWX - 6TB
Seagate ST8000DM004 - 8TB

Logs attached. 

[Logs_180417_21-20-39.zip](https://github.com/pannal/Sub-Zero.bundle/files/1922139/Logs_180417_21-20-39.zip)

Thanks a bunch,
WeirDave
[http://www.weirdave.com](http://www.weirdave.com)

**Comment by WeirDave** [comment]
I leave the NAS with the PMS running 24/7 it is new however and has been sporadic... that being said I did run the optimize database function since it is a "new database". I will continue to run this (I forgot about the feature truthfully)

**Comment by pannal** [comment]
Is this still happening?

**Comment by WeirDave** [comment]
> Is this still happening?

No it appears to be working now. Thank you. I didn't get around to doing anything to it but I just logged in and it appears to be working.
