### ISSUE TITLE
Not downloading when manual. Auto works sometimes?

### ISSUE THREAD

**Issue by LaMpiR** [pannal/Sub-Zero.bundle#505]
Hi.

So I am having some problems with manual downloads of the subtitles.

Please help.

IOError: [Errno 13] Permission denied

[Logs_180424_23-07-12.zip](https://github.com/pannal/Sub-Zero.bundle/files/1944624/Logs_180424_23-07-12.zip)

**Comment by pannal** [comment]
Yeah you've got massive permission issues. I can't help you there - you can [read the FAQ](https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q3-sub-zero-complains-about-permissions), but that you'll have to fix for yourself.

**Comment by pannal** [comment]
Closing for now
