### ISSUE TITLE
OpenSubtitles download-via-API breaks encoding for Serbian subtitles

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#506]
Downloading http://www.opensubtitles.org/en/subtitles/7237088/sid-TnMDyizh5t7Ldu0zQP7rAHgk5Y2/dark-skies-sr via web browser results in a file encoded with `windows-1250`.

Downloading the same file via XMLRPC API breaks the encoding, making it decodable with `iso-8859-2`, not `windows-1250`, breaking certain characters.

Correct result (downloaded via web, decoded using `windows-1250`):
```
1
00:00:06,000 --> 00:00:12,074
Reklamirajte vaš proizvod ili brend ovdje 
kontaktirajte nas www.OpenSubtitles.org

2
00:00:34,367 --> 00:00:36,161
Mnogo pre rođenja svetlosti

3
00:00:37,079 --> 00:00:38,872
postojala je tama.

566
01:03:14,663 --> 01:03:17,958
Zato, prijatelju moj,
nećemo bežati pešice.
```

Broken result (downloaded via XMLRPC, decoded using `iso-8859-2`):
```
1
00:00:06,000 --> 00:00:12,074
Reklamirajte vaš proizvod ili brend ovdje 
kontaktirajte nas www.OpenSubtitles.org

2
00:00:14,000 --> 00:00:20,074
ÐžÐ³Ð»Ð°ÑˆÐ°Ð²Ð°Ñ˜Ñ‚Ðµ ÑÐ²Ð¾Ñ˜ Ð¿Ñ€Ð¾Ð¸Ð·Ð²Ð¾Ð´ Ð¸Ð»Ð¸ Ð¼Ð°Ñ€ÐºÑƒ ÐºÐ¾Ð´ Ð½Ð°Ñ; ÐºÐ¾Ð½Ñ‚Ð°ÐºÑ‚Ð¸Ñ€Ð°Ñ˜Ñ‚Ðµ www.OpenSubtitles.org

3
00:00:34,367 --> 00:00:36,161
Mnogo pre roðenja svetlosti

567
01:03:14,663 --> 01:03:17,958
Zato, prijatelju moj,
neæemo bežati pešice.
```

Line number `2`, which you insert when XMLRPC is used, seems to be UTF-8 encoded, and **cyrillic** content for a **latin** encoded serbian subtitle:
```
>>> print x.decode("utf-8")
00:00:20,074
Оглашавајте свој производ или марку код нас; контактирајте www.OpenSubtitles.org

>>> print repr(x.decode("utf-8"))
u'00:00:20,074\n\u041e\u0433\u043b\u0430\u0448\u0430\u0432\u0430\u0458\u0442\u0435 \u0441\u0432\u043e\u0458 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434 \u0438\u043b\u0438 \u043c\u0430\u0440\u043a\u0443 \u043a\u043e\u0434 \u043d\u0430\u0441; \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0438\u0440\u0430\u0458\u0442\u0435 www.OpenSubtitles.org'
```

Which is the same as:
`Advertise your product or brand with us; contact www.OpenSubtitles.org`

@opensubtitles this is a problem!

**Comment by pannal** [comment]
@opensubtitles this is serious. You insert UTF-8 encoded content into subtitles encoded with another encoding.

**Comment by pannal** [comment]
Also you seem to add the advertisement twice.

**Comment by opensubtitles** [comment]
Hi, I checked issue and confirm. The issue with Serbian language it can be in Cyrillic and Latin, and in advertisement system we are serving Cyrilic, which was forced to insert in Latin subtitles.

Anyway it is not really used, so as quick fix I turned off inserting ads into subtitles for Serbian.
