### ISSUE TITLE
No subtitle after refreshing metadata

### ISSUE THREAD

**Issue by shahesam84** [pannal/Sub-Zero.bundle#507]
Hi,
Thanks for your great work. I follow below steps but no subtitle appears in current folder and plex media library:
1- installed SZ
2- enabled SZ and entered Opensubtitles.org account info in settings
3- start refreshing the metadata of library 
Problem: Logging in to Opensubtitles.org account shows that the number of downloaded subtitles are increasing but when I check it in my library there is no subtitle activated or downloaded in current directory!
Where is my mistake? Please help me.
Thanks,

**Comment by pannal** [comment]
You're most likely experiencing permission issues.

Please post a DEBUG log (see wiki) after refreshing the metadata of an item.

**Comment by shahesam84** [comment]
If you asking for a log file that I can generate using [this ](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs)link, the url at the last stage does not direct me to the zip file. What else I can do?

**Comment by pannal** [comment]
Then you can go to the Plug-Ins folder of your PMS and zip the subzero log files yourself, then attach the zip here.

**Comment by pannal** [comment]
Closing for now as no proper DEBUG logs are present
