### ISSUE TITLE
still issues when applying color to a line involving ":[a letter]"

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#510]
I've had this issue eariler and was solved. read issue 408 

https://github.com/pannal/Sub-Zero.bundle/issues/408

now it's back again however.

in the movie "the post" this section: 

    1117
    01:48:06,076 --> 01:48:11,040
    Ja, det är väl det. Tack och lov
    att HD:s beslut var så solklart.

gets altered to 

    1117
    01:48:06,076 --> 01:48:11,040
    <font color="#FFFFFF">Ja, det är väl det. Tack och lov
    s beslut var så solklart.</font>

I can post logs and the source file but I doubt they would help. maybe the original fix have just broken.

**Comment by pannal** [comment]
What exactly does HD:s mean? And yes, it might be a regression.

**Comment by KBlixt** [comment]
HD:s is short for Högsta Domstolen which is a translation for The supreme court. 

Although I fail to see why it's relevant. It's not an isolated issue with "HD:s" I've seen other subtitles have this issue again.

**Comment by pannal** [comment]
Do you have hearing impaired removal active?

**Comment by KBlixt** [comment]
yeah, does the subs that i provided last time cause issues or will you need a fresh example?
