### ISSUE TITLE
Downloading a bunch of wrong subtitles

### ISSUE THREAD

**Issue by alculete** [pannal/Sub-Zero.bundle#516]
Sub-zero is downloading subtitles that are not from the correspondent tv show or movie.... I'm using the last version of sub-zero

**Comment by pannal** [comment]
Attach your Debug log please. (see wiki)

**Comment by Alculete** [comment]
[Logs_180521_20-10-06.zip](https://github.com/pannal/Sub-Zero.bundle/files/2023618/Logs_180521_20-10-06.zip)

**Comment by pannal** [comment]
OK, first please fix your permission issues: `IOError: [Errno 13] Permission denied: u'/home/alculete/Media/Movies/The Monkey King (2014)/The Monkey King (2014) Bluray-720p.en.srt'`

Set SZ to log level DEBUG in SZ's settings (at the bottom).
Then issue a force-find of a media item in question using the SZ plugin menu and post your logs again.

**Comment by pannal** [comment]
Closing for now, please reopen if issue persists
