### ISSUE TITLE
Subtitles aren't updating properly

### ISSUE THREAD

**Issue by edgardoRodriguez** [pannal/Sub-Zero.bundle#517]
#507 Hello, thanks for you effort doing this, i have been figthing with plex because i didn't make that the plugin works for me, when I create a new library in the plex then the pluggins download all the subtitules fine, but when i add any new file and refresh metadata to the library already created then the plugin dont download anything even the manually download, i've looking in the logs and don't  see anything, what could be happening? is a rare behaviour.

**Comment by pannal** [comment]
Not sure, is SZ even called when a new file has been added? How are files added to your library? Sonarr/Radarr or manually?

**Comment by pannal** [comment]
Might be the same as #524

**Comment by pannal** [comment]
Closing for now, please reopen if different than #524
