### ISSUE TITLE
Filebot refiner not working on OSX

### ISSUE THREAD

**Issue by mendozal** [pannal/Sub-Zero.bundle#518]
I'm using plex on macOS and having problems downloading subtitles for tv shows. Apparently it works on movies.

I turned on Debug on sub-zero's logs and appanrently it founds several subtitle options but it is not downloading any of them.

Plex=1.13.1.5063
Sub-Zero=2.5.4.2541

I'm attaching logs.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2027195/com.plexapp.agents.subzero.log)

**Comment by oldowl2** [comment]
I have this same exact issue, except my plex is running on Windows 10.

Plex - Version 1.13.0.5023
Sub-Zero - Version 2.5.4.2541

**Comment by mendozal** [comment]
Navigating the logs, it appears the issue has to do with this setting in sub-zero's configuration:
Minimum score for TV (min: 240, def/sane: 337, min-ideal: 352; see http://v.ht/szscores)

All subtitles found had scores less than 337 so they were ignored.
Playing with that value, sub-zero started to download some subs but not always the correct ones.

I left this setting configured to 335 right now and it works.

**Comment by pannal** [comment]
I think filebot fails on your part, thus SZ doesn't receive the correct original filename and isn't able to score properly.

The error I see is: `TypeError: Non-hexadecimal digit found`. Going to investigate. < 337 is prone to result in bad subs.

**Comment by pannal** [comment]
@oldowl2 you're most likely experiencing something different. Please open a separate issue and post your DEBUG log zip there (see wiki).

**Comment by pannal** [comment]
@mendozal can you execute this in the command line: `xattr -p "net.filebot.filename" /Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv` and post the result here?

**Comment by mendozal** [comment]
@pannal, yes, this is the result:

48 75 6D 61 6E 73 2E 53 30 33 45 30 31 2E 37 32
30 70 2E 48 44 54 56 2E 78 32 36 34 2D 4D 54 42
5B 4E 31 43 5D 2E 6D 6B 76 00

**Comment by pannal** [comment]
Can you actually paste the whole command line with the result? I think there are newlines in there that I don't handle well.

**Comment by mendozal** [comment]
like this?

Luiss-iMac:~ luis$ xattr -p "net.filebot.filename" "/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv"
48 75 6D 61 6E 73 2E 53 30 33 45 30 31 2E 37 32
30 70 2E 48 44 54 56 2E 78 32 36 34 2D 4D 54 42
5B 4E 31 43 5D 2E 6D 6B 76 00
Luiss-iMac:~ luis$

**Comment by pannal** [comment]
Hmm I think the newlines get converted on the go so that doesn't really help.

I've pushed a possible fix to the develop-2.5 branch. Care to try it out?

**Comment by mendozal** [comment]
I installed a the new .bundle file and tested with the same episode in debug mode.
I'm attaching the log file.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039605/com.plexapp.agents.subzero.log)

**Comment by mendozal** [comment]
Yes, version 2.5.4.2547 DEV
It did not download the sub.

Attaching the log file.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039678/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
OK that looks better at least. I've updated the branch again with additional debug logging, to version 2552. Can you try again so I can confirm it works?

**Comment by mendozal** [comment]
updated to version 2552,
attaching log file

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039788/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
OK, something's still going wrong here. Updated the branch again with more logging - please bear with me :) (no version change)

**Comment by pannal** [comment]
I've noticed you were testing it with episode 2 of that show. Does `xattr -p "net.filebot.filename" "/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E02 - Episode 2.mkv"` return anything?

**Comment by mendozal** [comment]
No problem at all, glad to help.

Attaching the log file.
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039848/com.plexapp.agents.subzero.log)

Also, this is the output of xattr
[xattr.txt](https://github.com/pannal/Sub-Zero.bundle/files/2039854/xattr.txt)

**Comment by pannal** [comment]
Hmm, and exactly that: `xattr -p net.filebot.filename '/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv'`?

**Comment by pannal** [comment]
Is that file by chance a symbolic link?

**Comment by mendozal** [comment]
no, it is the file itself.

**Comment by mendozal** [comment]
ok, this is the output.

[xattre01.txt](https://github.com/pannal/Sub-Zero.bundle/files/2039878/xattre01.txt)

**Comment by pannal** [comment]
OK, that's weird. When executed from SZ in the PMS context, xattr returns exit code 1.
Is the user the PMS runs as the same as the one you've executed the command in the command line with? May this be a permission issue or a restriction by OSX?

**Comment by mendozal** [comment]
Yes
Apparently it is the same user. 

<img width="898" alt="captura de pantalla 2018-05-25 a la s 11 17 08" src="https://user-images.githubusercontent.com/4621970/40552338-5fd27ab0-600d-11e8-929a-e480616351d0.png">

I was using windows 10 before an it was working, after migrating to macosx I started to see this.

**Comment by pannal** [comment]
OK, interesting. I've updated the branch again and will hopefully see more info about why the execution fails.

**Comment by mendozal** [comment]
Here is the output

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039945/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Uh, have you by any chance installed xattr by yourself?

Somehow, when it's called by SZ, the xattr binary fails: `ImportError: No module named pkg_resources\n` - the binary is located in `/usr/bin/xattr-2.7`.

What does `which xattr` output?

**Comment by pannal** [comment]
And `filebot fn:xattr '/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv'`?

**Comment by pannal** [comment]
And another update to the branch. I'm now setting a proper environment for the xattr call, so hopefully this will help. Version 2557.

**Comment by mendozal** [comment]
no, I haven't. 
Though I installed filebot using homebrew, I don't know if it has anything to do with this.

Luiss-iMac:~ luis$ which xattr
/usr/bin/xattr
Luiss-iMac:~ luis$ ls -l /usr/bin/xattr
-rwxr-xr-x  2 root  wheel  925 Jul 15  2017 /usr/bin/xattr


I modified the filebot command to this:
filebot -script fn:xattr '/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv'
because the one you pasted opened the filebot GUI.

This is the output:

Luiss-iMac:~ luis$ filebot -script fn:xattr '/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/usr/local/Caskroom/filebot/4.7.9/FileBot.app/Contents/Java/FileBot_4.7.9.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/Volumes/Data/Media/TV Shows/Humans/Season 03/Humans - S03E01 - Episode 1.mkv
	net.filebot.filename: Humans.S03E01.720p.HDTV.x264-MTB[N1C].mkv
	net.filebot.metadata: {"@type":"Episode","seriesName":"Humans","season":3,"episode":1,"title":"Episode 1","absolute":17,"airdate":{"year":2018,"month":5,"day":17},"id":6627657,"seriesInfo":{"database":"TheTVDB","order":"Airdate","language":"en","id":292124,"name":"Humans","aliasNames":["Humans (2015)","Люди","אנושיים","휴먼스"],"certification":"TV-MA","startDate":{"year":2015,"month":6,"day":14},"genres":["Drama","Science-Fiction"],"network":"Channel 4","rating":8.6,"ratingCount":54,"runtime":45,"status":"Continuing"}}
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by mendozal** [comment]
New logs, version 2557

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2040011/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
OK, please try again. I've removed native xattr handling for OSX for now and filebot itself is used.

**Comment by mendozal** [comment]
Here are the new logs

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2041252/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
OK, pushed another try to use the filebot binary.

**Comment by mendozal** [comment]
It downloaded a subtitle!

Here is the log file.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2041264/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Awesome - kind of. For OSX, SZ now uses the filebot xattr "native" implementation which is more resource-intensive but (seems to) work.

Pushed a permanent fix, version should be 2562.

Please verify that it still works. Thank you for testing, this will be in the next stable/bugfix release.

**Comment by pannal** [comment]
Great :)
