### ISSUE TITLE
[New feature]Don't download subtitles if audio is in %language

### ISSUE THREAD

**Issue by Haxy89** [pannal/Sub-Zero.bundle#519]
Hi,

Is it possible to add option to not searching for subtitles if audio is in the same language as requested sub?

Example:

1. Subtitles primary language to search: PL in Sub-Zero options

One of the track in file is in pl language so don't try to search for subtitles

**Comment by pannal** [comment]
Yep.

**Comment by pannal** [comment]
@Haxy89 I've pushed exactly that feature to the current develop-2.5 branch. Care to try?

**Comment by Haxy89** [comment]
I will check

**Comment by pannal** [comment]
Do you need help with that?

**Comment by Haxy89** [comment]
No, just give me one or two days to check that

**Comment by Haxy89** [comment]
Works for me on DEV

[log.txt](https://github.com/pannal/Sub-Zero.bundle/files/2111914/log.txt)

**Comment by pannal** [comment]
Thanks for testing!
