### ISSUE TITLE
Call executable upon subtitle download - how to use path with spaces?

### ISSUE THREAD

**Issue by Haxy89** [pannal/Sub-Zero.bundle#520]
Path to executable sh:
`config/Library/Application Support/Plex Media Server/subtitlesDownloadCompleted.sh %(subtitle_filename)s %(provider)s %(title)s`

Path is correct and sh file is executable with right permissions. Problem is with spaces in my path.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/37550896/40504705-53946e00-5f92-11e8-95fb-ca96542ca2f8.PNG">
<img width="841" alt="2" src="https://user-images.githubusercontent.com/37550896/40504709-568cbbc6-5f92-11e8-95ba-debbef457814.PNG">

Tried escaping with  "" or \ but path still breaks after first space

**Comment by pannal** [comment]
Hmm yeah. That actually is a bug.

**Comment by pannal** [comment]
I've pushed a possible fix for this into the develop-2.5 branch. Care to try?

**Comment by pannal** [comment]
@Haxy89 ?

**Comment by Haxy89** [comment]
@pannal 
Fixed on DEV
