### ISSUE TITLE
SubZero Plugin do not download subtitles at all, attaching log

### ISSUE THREAD

**Issue by goldshlager** [pannal/Sub-Zero.bundle#521]
Hi All,

I installed subzero plugin on plex but for some reason it does not download any subtitles, I guess there are some errors but I can't find the reason, attaching the log file, please assist.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2039763/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Please set SZ to DEBUG logging, then refresh an item in question and attach your logs (see wiki).

**Comment by pannal** [comment]
Closing for now, please reopen with proper logs
