### ISSUE TITLE
Not downloading subtitles for TV shows on Windows 10

### ISSUE THREAD

**Issue by oldowl2** [pannal/Sub-Zero.bundle#522]
Sub-Zero is working perfectly with Movies, but in TV Shows it is not working at all. Plex is running on Windows 10.

Plex - Version 1.13.0.5023
Sub-Zero - Version 2.5.4.2541

[
[Logs_180525_12-26-56.zip](https://github.com/pannal/Sub-Zero.bundle/files/2040133/Logs_180525_12-26-56.zip)
](url)

**Comment by pannal** [comment]
Yeah, your episodes lack the necessary information for SZ to find fitting subtitles for them. Please read up [here](https://github.com/pannal/Sub-Zero.bundle/wiki#attention) and [here](https://github.com/pannal/Sub-Zero.bundle/wiki/Media-Score). Do you use any tool to automatically rename your episodes?

**Comment by oldowl2** [comment]
Yes, I have filebot renaming all my episodes. IE: Game of Thrones - 1x01 - Winter Is Coming. Isn't this the right tool that is used?

Thank you for your help,
 -Marc

**Comment by pannal** [comment]
Yes, but something is wrong with your setup (or SZ):
```
2018-05-25 12:22:29,017 (3ba8) :  INFO (logkit:16) - subliminal_patch.core: Refining video with filebot
2018-05-25 12:22:29,026 (3ba8) :  DEBUG (logkit:13) - subliminal_patch.refiners.common: Got original filename: Louie - s03e06 - Barney-Never.mp4
```
for example. The name of the file is: `Louie (2010) - 4x07 - Elevator (4).mp4` - neither the current nor the original filename contain enough information for SZ to act on.

Is there any other instance in your download-routine that renames before filebot?

**Comment by oldowl2** [comment]
No, from the original files I originally renamed everything by hand (Louie - s03e06 - Barney-Never.mp4 was the original format I used), it is not until recently I have used filebot to rename all my files. The example you have "Louie (2010) - 4x07 - Elevator (4).mp4" seems like it should have all the info for SZ to pick up on, maybe I am missing something. SZ works perfectly with my movies named with filebot (again, originally renamed by hand by me for years) so I thought the TV series would work the same. After using filebot more recently (without originally renaming) I noticed that the subs are pulling correct, what should I do with my original 60 TV shows that were renamed before I knew of filebot?  I've attached updated logs


[Logs_180611_22-54-43.zip](https://github.com/pannal/Sub-Zero.bundle/files/2092374/Logs_180611_22-54-43.zip)

**Comment by pannal** [comment]
You can't do anything to be honest. TV shows need the source/format (WEB-DL, HDTV etc.) and/or the release group of the file to be able to match any subtitles properly.

You could lower the necessary TV score to `330`, that'll get you subtitles, but with a higher chance of bad matches.

If you know the source of the files, you can create `file_info` files for them, [see here](https://github.com/pannal/Sub-Zero.bundle/wiki/Refiners#file_info-index-files).

**Comment by pannal** [comment]
Movies are quite a different beast, the scores for movie subtitles are lower, as the framerate rarely differs between sources and there are no commercial breaks that change the length of the media item between different formats/sources.

**Comment by oldowl2** [comment]
Thank you so much for the help. I guess the only route for me to do is lower the score to 330 to get subs on the rest of the shows. I changed it to 330 a few hours ago and checked how it was doing just now and still the subtitles aren't showing up with the lower hash. Do I need to change anything else to get any subs in when lowering the hash to 330?

**Comment by pannal** [comment]
Normally, no. Please re-upload your log zip after a refresh.

**Comment by oldowl2** [comment]
Here you go. After looking at a few of these titles I have, it looks like things are working with Subzero after lowering the threshold (most, not all are there). Thank you so much for your help!
[Logs_180627_14-22-09.zip](https://github.com/pannal/Sub-Zero.bundle/files/2142424/Logs_180627_14-22-09.zip)

**Comment by pannal** [comment]
I hope your results aren't too bad with 330. Closing!
