### ISSUE TITLE
Only downloads sub when new item is added, not for existing items

### ISSUE THREAD

**Issue by Tyree** [pannal/Sub-Zero.bundle#524]
I'm running Plex on Windows 7 64bit.
I've been working with this for a few days. After another user posted on facebook that he had a similar problem, I tried what he said his issue was and, turns out, we have the exact same issue. SZ will not download subs for items already in the library. 
I've been working with a few test movies that I know should have forced subs. I tried refreshing the movie and also forcing the download of subs via the SZ interface, no luck. I also did a full meta data refresh of the entire Plex library. Still nothing. 
It's not until I remove a movie from the library and then add it back that SZ will download the sub.

So, it would appear I have all the settings correct, since it can download subs for new items and if I remove and add an item. Also does lookups for new TV show recordings. It just refuses to "see" existing items and realize it needs to lookup/download the subs.

The logs don't change when I refresh an item other than showing the status of the refresh. It never goes through any operations for looking up subs.

Any help is appreciated!

**Comment by Tyree** [comment]
Just in case you need them. Logs attached.
[Logs_180528_17-09-32.zip](https://github.com/pannal/Sub-Zero.bundle/files/2046197/Logs_180528_17-09-32.zip)

**Comment by Tyree** [comment]
Here are my settings: https://drive.google.com/file/d/1kCWwLLVoRdoSNKA8cCifkpMPgI-vjOs8/view

**Comment by pannal** [comment]
And the agent is properly enabled for the library in question?

**Comment by Tyree** [comment]
Must be, since it will download subs for new items added to the library. The library is "3Movies." You can see in the logs it says it is enabled for that library, among others.

**Comment by pannal** [comment]
Well, the PMS doesn't seem to call SZ in that case. Can you create a separate test library, enable SZ for it, add an item and try to reproduce it there?

I've had users with issues like these in the past.

**Comment by pannal** [comment]
Yeah that should work. Or enable SZ from the get-go, let it download subtitles, delete them, then refresh the items using the interface.

**Comment by Tyree** [comment]
Okay, I went and did some testing with agents. Here's what I found:

The agent for the library is The Movie Database. I checked the agent order under The Movie Database and SZ is enabled. However, it was not enabled for the Plex Movie agent. Even though that's not what the library is set to, once I enabled SZ under Plex Movie, I was able to refresh and get an SRT file.

Here's the thing: This library USED to have Plex Movie as the agent. I changed it 2 weeks ago and did a full library meta refresh. The Movie Database agent should have been all it cared about. I added NEW movies and the subs downloaded, but all the old movies seem to still engage Plex Movie.

I'll do more testing to see if I'm right about that. I'll also ask the other guy with the same problem to check the same settings and see if he gets the same result.

**Comment by pannal** [comment]
Ah, that's interesting. The old movies may still have the old primary metadata provider stored and that doesn't get updated when you change the primary metadata provider.

I'll talk to the Plex guys to see whether this is a bug or intended behaviour once you got back to me with the final result.

**Comment by Tyree** [comment]
Just tested again with another "old" movie. Did a refresh via the SZ interface and the subs downloaded. I'm going to try disabling SZ under Plex Movie and see if it fails again.

**Comment by pannal** [comment]
I'm guessing after you Fix-Match the movie, it might change the primary metadata agent to the current one.

**Comment by Tyree** [comment]
Confirmed. Just disabled SZ under Plex Movie. Tried to refresh a movie. Nothing in logs. Re-enabled SZ for Plex Movie, refreshed the same movie, sub is downloaded.
The "old" movies are definitely stuck on the old primary, even after a full meta refresh on the library.
I worry about this being desired behavior. What if you want all movies to have metadata from the new provider? You'd have to remove all items and re-add them. :-/
Ah, or as you suggested, fix-match EACH movie. Yikes.

**Comment by pannal** [comment]
A completely new library with the same location might fix this in whole. I'm trying to confirm with Plex whether this is intended or not.

**Comment by pannal** [comment]
OK, confirmed. This is by design.

You have two options:
- break down the library and recreate it
- enable SZ for the Plex Movie agent

**Comment by Tyree** [comment]
Weird. That's by design? Interesting. I wonder why.
Thanks for confirming and for your attention!

**Comment by pannal** [comment]
Added FAQ entry: https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q11-ive-changed-the-primary-metadata-agent-for-my-library-and-now-my-old-movies-dont-get-any-subtitles

I'm not 100% fond of that behaviour either - maybe create a forum thread about this?

**Comment by Tyree** [comment]
Yeah, I may run this further up the flagpole. I wonder if it's truly intentional or if it's a "Oh yeah. We meant to do that." reaction from them. I'm trying to wrap my brain around WHY that would be the desired behavior. I mean, what's the point of being able to change the provider for the entire library after it's created if it doesn't change the agent for the items inside? Especially after a full meta refresh on the library.

**Comment by pannal** [comment]
The reason is apparently, that you can match a couple of movies with agent X, then change the agent to Y and match all the new movies using that one, without destroying your initial choice.

I get the explanation, but I'm not on board 100%.

It's btw documented: https://support.plex.tv/articles/200241558-agents/ (last paragraph)

**Comment by Tyree** [comment]
Ah man, yeah, there it is: "Tip!: Changing the metadata agent for an existing library will only affect future content. It does not retroactively change the agent used for existing library content."

Well, that sucks! :-D

**Comment by Tyree** [comment]
Too bad there's not a recursive checkbox when you change it. To force all items int he library to change providers.
