### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by rourke** [pannal/Sub-Zero.bundle#528]
In my opinion the Dutch translation isn't very well done. A lot of words are very uncommon or old-fashioned. I tried to see if I could join the Sub-Zero poeditor.com project to suggest improvements, but it seems to be closed for Dutch.

My username on poeditor.com is `Serik`. Could you (@pannal) perhaps add me manually?

**Comment by ukdtom** [comment]
User not active on POEditor!

Try and sign up again

**Comment by ukdtom** [comment]
Ohhh.....And noticed, that @pannal selected to lock a language, when on 100 % !!!!

So have to wait for him to chime in here, since his project, so don't wanna alter that setting

**Comment by rourke** [comment]
Fair enough. I'll wait. :)

**Comment by pannal** [comment]
Yeah please join the project using the link @dane22 provided, then we can add you to the Dutch translation as a contributor.

**Comment by rourke** [comment]
I can't join the project manually unless I select a language I don't know. Do you want me to do that?

**Comment by pannal** [comment]
Poeditor usability goodness as always. I've unlocked the completed languages altogether as it doesn't allow to unlock specific languages. 

You can join the language now, thanks for contributing!

**Comment by rourke** [comment]
That did the trick. I joined the project. I won't be able to submit improvements right away. But you'll see some in the upcoming days. Thank you guys!

**Comment by rourke** [comment]
I applied some improvements on the word `Extract`. It used to be `Extraheer` in Dutch, but this is not commonly used. `Extract` can be used in Dutch too, but is just adopted from English. A proper Dutch translation would be `Uitpakken`, but it doesn't fit in the context, which is about extracting subtitles from the video files. Therefor I decided to go with `Exporteren`. I know this is a translation for `Export`, but I ran it through a couple of friends and we agreed this is the best option to explain what it does.

I might do some other translations, but this had the biggest priority for me. You can use what is on poeditor.com.

**Comment by pannal** [comment]
Yeah I guess export works, too, as embedded is mentioned in the same sentence and should indicate what it does. 

Thank you for your contributions, they'll get added to the next release.

**Comment by jippo015** [comment]
I did the initial translation and extraheer is a pretty common word especially in the mathmatics world. But i guess exporteren is a pretty good alternative in this context.

**Comment by rourke** [comment]
Hey Jippo015. Thanks for your translation work. I know extraheer is a common word in the mathmatics world, but to the common folks I think it can be a bit out of place.
