### ISSUE TITLE
Forced Subtitles Question

### ISSUE THREAD

**Issue by animosity22** [pannal/Sub-Zero.bundle#529]
I was trying to figure out why these were showing up as forced:

 The.Handmaids.Tale.S02E10.en.forced.srt goes with
 The.Handmaids.Tale.S02E10.mkv

and it looks like it was from subscene TV, but it isn't forced, it's the entire english set of subtitles for the show.

I have this setup:

![image](https://user-images.githubusercontent.com/5088712/42005592-4e7276c6-7a43-11e8-98c5-e6eba17c569e.png)

Was the provider -> 
![image](https://user-images.githubusercontent.com/5088712/42005602-5b953fc8-7a43-11e8-8022-2d9e477d12f5.png)

Is that just a bad match or something I can do to prevent that?

**Comment by animosity22** [comment]
Awesome. Thanks for the quick reply as I wasn't sure if I misconfigured something as there are a lot of boxes to check :)

**Comment by pannal** [comment]
Yeah. I think it's time for two things: a separate quick GUI that can be used to search for subtitles on demand using your mobile device, and some separate configuration page. Both sadly are impossible to do using the Plex plugin framework, so they may never come, depending on on my workload.

**Comment by pannal** [comment]
The on demand thing might come at some point in time, because I need it as well, as plex4kodi is my daily driver and it doesn't have channel support.

**Comment by pannal** [comment]
Oh and one quick notice for the actual bug: the implementation is so broken that SZ takes any subscene result as foreign-only if the option is enabled in SZ. 

Sorry for that.
