### ISSUE TITLE
Downloading subtitles for entire show

### ISSUE THREAD

**Issue by daemonanyndel** [pannal/Sub-Zero.bundle#530]
When I refresh metadata on individual items, the subtitles are correctly downloaded, but if I refresh metadata on the show as a whole, no subtitles are downloaded. Its a bit annoying to have to have to do each file individually, is there a way I'm missing to make it happen? I've searched the wiki and been googling it for a couple days now and found no answers yet.

**Comment by pannal** [comment]
Have you tried issuing a force-refresh on the series using the Sub-Zero plugin menu?

**Comment by pannal** [comment]
Please reopen if necessary
