### ISSUE TITLE
[Feature Request] Download from an external link

### ISSUE THREAD

**Issue by georgekarapi** [pannal/Sub-Zero.bundle#531]
It would be really convenient if you could download from a direct link, especially in situations that you are connected remotely to the Plex server. 

Just a text field with a drop-down menu to choose language would be perfect.

**Comment by pannal** [comment]
Sadly I can't implement this with the current state of the Plex Plugin Framework.

**Comment by georgekarapi** [comment]
Is drop-down an issue or something else? Sorry if I bother you.

**Comment by ukdtom** [comment]
The framework only allows a drop-down in the preferences, and not in the interface itself.
An input field dialog is also broken in the Web-Client.

Consider the fact, that the main purpose of the framework, where SZ lives under, is to stream medias.
Even having SZ been evolved into it's currect state, was/is a darn miracle

**Comment by pannal** [comment]
@georgekarapi I can't do anything fancy besides actual text-elements inside the GUI, sadly.

**Comment by georgekarapi** [comment]
Let's hope they will enrich their plugin's framework then. Anyway, thanks for the effort guys!
