### ISSUE TITLE
"Plugin Not Responding" when trying to ignore title

### ISSUE THREAD

**Issue by gabeon** [pannal/Sub-Zero.bundle#535]
I had this issue in April and was told that it was going to be fixed in an upcoming release.  I am still having the issue.  What kind of logs can I upload to see what the issue is?

**Comment by pannal** [comment]
Yeah, it was fixed with version 2.5.4.2541.

Please upload your [log zip](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs) after you've encountered the issue.

**Comment by gabeon** [comment]
Here are my logs.  I got the Plugin Not Responding after trying to Ignore Iron Man 2 at 11:50
[Logs_180716_11-51-00.zip](https://github.com/pannal/Sub-Zero.bundle/files/2198517/Logs_180716_11-51-00.zip)

**Comment by pannal** [comment]
Where did you try to ignore it from? Which submenu?

**Comment by gabeon** [comment]
I did the following:

- went to the Plugins section
- clicked on Sub-Zero
- clicked on the Recently Played Items
- clicked on Iron Man 2
- scrolled to and clicked on the Ignore Item: Iron Man 2 link

Now I can't even click on the plugin without getting the Plugin is not Responding mesage.

**Comment by pannal** [comment]
Thank you, fixed in the upcoming version.

**Comment by pannal** [comment]
Until it's released: It should work when navigating using the browse menu.

**Comment by pannal** [comment]
#504
