### ISSUE TITLE
Passwords greyed out for OpenSubtitles and Addic7ed

### ISSUE THREAD

**Issue by Blistex77** [pannal/Sub-Zero.bundle#536]
Hello,

I've just installed Plex, added my library and SubZero to get French subtitles, but I'm unable to enter any password for OpenSubtitles or Addic7ed, the field is unavailable and stays greyed out even after I enter a username.
 
Edit : I've attached log file, but I don't know which configuration file to upload or change to add the missing passwords.

https://pastebin.com/rhvKtbyD

Thank you for your help!

**Comment by pannal** [comment]
Have you tried a different browser or an incognito tab? I can't actively control whether an input field is enabled or disabled in the plugins' settings. All of them are always enabled.

**Comment by Blistex77** [comment]
I didn't and I should have thought of that, thanks!

I successfully added the credentials for both provider, but it seems Addic7ed's still not used :
`2018-07-16 17:16:33,606 (7fb76322d740) :  DEBUG (menu:336) - config.providers: ['podnapisi', 'subscene', 'opensubtitles']`

**Comment by pannal** [comment]
Is Addic7ed perhaps throttled? (You can see that in the root plugin menu)
