### ISSUE TITLE
Use AKA name when nothing found (or use Plex matching name)

### ISSUE THREAD

**Issue by Xebozone** [pannal/Sub-Zero.bundle#537]
Feature request to use the AKA (Also Known As) name for movies when a subtitle cannot be found.
For example,

Harry Potter and the Philosopher's Stone
https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone

This movie is known also as Harry Potter and the Sorcerer's Stone (and is listed as such on opensubtitles)

Details for AKA names of movies is in opensubtitles, in fact, searching for this film (as the non-American name) in opensubtitles returns the American name as the first result. Searching that will reveal the AKA name, so the parser should be able to pick this up.

**Comment by Xebozone** [comment]
On second inspection, this may already be the case.
The file name had 1 letter incorrect which may have resulted in no detection!

Is the match based on the actual file name, or on the metadata in Plex (because Plex correctly matched the file regardless)?

**Comment by Xebozone** [comment]
On second inspection, this may already be the case.
The file name had 1 letter incorrect which may have resulted in no detection!

Is the match based on the actual file name, or on the metadata in Plex (because Plex correctly matched the file regardless)?

**Comment by pannal** [comment]
The initial matching of the item is done using the original filename. If that doesn't yield a result (TMDB/TVDB), the Plex item title is used to re-refine the data.

Please provide debug logs (see wiki) if this wasn't the case.
