### ISSUE TITLE
still issues with : followed by letters.

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#542]
see previews issues #408 and #510 

    308
    00:51:23,110 --> 00:51:27,908
    - Bank?
    - IMF:s stordator.

turns into.

    308
    00:51:23,110 --> 00:51:27,908
    <font color="#FFFFFF">- Bank?
    s stordator.</font>

**Comment by pannal** [comment]
Yeah. Fixed in develop-2.5, sorry.

**Comment by pannal** [comment]
Are those abbreviations always in that format? a word before the colon, then one single character?

**Comment by KBlixt** [comment]
Yes. But unless you have a specific reason not to. I'd check for up to two letters after the colon just to be safe. I can't think of any situation where there would be two letters after the colon but languages are weird sometimes. I'm only speaking for English and Swedish. There should never be three or more though.
