### ISSUE TITLE
Error with Spanish translation

### ISSUE THREAD

**Issue by notorius28** [pannal/Sub-Zero.bundle#543]
This is probably my fault... I made the Spanish translation of the plugin, but something is broken. It happens every time I select a video file. My log's attached.

**ValueError: unsupported format character 'M' (0x4d) at index 15
CRITICAL (i18n:85) - Broken translation! (most recent call last):**

Thank you. 

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2242301/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Fixed in the upcoming version, thanks for your contribution!
