### ISSUE TITLE
Add more match to supersubtitles

### ISSUE THREAD

**Issue by morpheus133** [pannal/Sub-Zero.bundle#546]
https://github.com/pannal/Sub-Zero.bundle/blob/42cc500b051fccf6ae912a39e45fdfdc8c0d1949/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py#L134

Can you remove the comment string ('#' )before the line? 
It will be good to add all other matches.
Do I need to create new pull request to it?

**Comment by pannal** [comment]
I can do that, thank you :)

**Comment by pannal** [comment]
`release_info` is unicode from the server? I highly doubt that.

`self.release_info.encode("utf-8")` - is this meant to be `decode`? 
Ah you're `u","` joining the `releases` attribute. Will this make any difference in matching?

**Comment by pannal** [comment]
I think it would make sense to put this line above all else, so if bad information is parsed from that, it doesn't overwrite the safe information.
