### ISSUE TITLE
Getting lots of errors

### ISSUE THREAD

**Issue by orbitingful** [pannal/Sub-Zero.bundle#549]
Here are my logs
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2294131/com.plexapp.agents.subzero.log)
[com.plexapp.system.log](https://github.com/pannal/Sub-Zero.bundle/files/2294132/com.plexapp.system.log)

What's going on? Thanks.

**Comment by pannal** [comment]
Hmm, does the plugin work at all?
