### ISSUE TITLE
Add channel view : items with missing subtitles

### ISSUE THREAD

**Issue by ledge74** [pannal/Sub-Zero.bundle#55]
Hey Panni,

One cool enhancement to this plugin would be to add one new view in the channel called : "items with missing subtitles". In this view the user would only see items with missing subs and would also have to possibility to refresh them. 

What do you think? 

Cheers

**Comment by pannal** [comment]
That's a cool but expensive feature, as to find missing items the agent does:
- get all eligible recently-added items
- check all the available stream metadata for every file part
- refresh the ones with missing subs

We'll see, perhaps if we stick to the recently-added missing, this may work.

**Comment by chopeta** [comment]
+1 here

@pannal I recall you mentioning something about this... can we use SZ internal database to compile this list without been too expensive? 

I know it won't be perfect if files are manually changed directly on the filesystem or if you never executed a "Full Refresh" with SZ previously installed but that's better than nothing.

In theory a 'Refresh All' is already gathering all that info. you mentioned in your previous comment.

Currently Recently Added list is awesome for the auto. task but if one want to fix everything this other list became a must.

I hope we can do it at some point even if that requires more changes to the internals and more 'Refresh All' after that :)

**Comment by pannal** [comment]
This kind-of is in the newest release. With a limit of 200 (default) items per library considered. You can up the limit if you want to, and your PMS can handle it.

**Comment by pannal** [comment]
This kind of is in the newest release. But with a (configurable) limit of 200 items per section. Does that work for you or do you still need the exact feature?

We might use the SZ internal database, I'm not sure at the moment.

**Comment by ledge74** [comment]
To me you can close this ! I think it will do the job just fine :+1:

**Comment by chopeta** [comment]
I would like to have a view that shows only items with missing subs, in all libraries... even if an item has no subs at all... we could save that info. during the 'Refresh All' and them it use later... not sure if we need a dedicated database or what... if it's too expensive for the server then it would be my utopia forever :)

**Comment by pannal** [comment]
Nah, it's totally possible.

**Comment by pannal** [comment]
This will be added after the internal subtitle storage has been deemed stable.
There has been an internal SZ info storage live for quite some versions. I'll maybe add a debug view for that so we can determine whether it's accurate enough for this feature.

**Comment by pannal** [comment]
Internal storage isn't stable yet. I'm still trying to figure out, why certain items don't get stored in the internal storage log.

**Comment by pannal** [comment]
This should make it into 1.4.

**Comment by pannal** [comment]
Still not relying on our internal subtitle database. Not because it isn't stable anymore, but because there may be some users who still have the unstable version active. 

Will be re-visited later on.
