### ISSUE TITLE
Add Subscene for movies

### ISSUE THREAD

**Issue by Maximus97** [pannal/Sub-Zero.bundle#551]
Subscene is a great source for movie subtitles, would be great if it worked for movies too and not just tv-shows.

**Comment by pannal** [comment]
Subscene is very broken for movies. You can enable it using `advanced_settings.json` if you want to.

**Comment by john626** [comment]
Thank you for quick answer. Do you mind saying what is broken?

**Comment by pannal** [comment]
When we tested the provider with the beta team during the SZ 2.5 beta, it generated a huge amount of badly matched results. So bad, that the provider was disabled for movies by default.
