### ISSUE TITLE
Treat external unknown subtitle file as Language 1 subtitle file

### ISSUE THREAD

**Issue by Maximus97** [pannal/Sub-Zero.bundle#554]
Some torrents come with a subtitle file in the same directory as the movie file, they are named as the movie file but they don't have the language tag. Would be great if there was a function to treat unknown external file in the same folder as the movie as the Language 1 subtitle file so that SZ doesn't try to download another one when the correct one already exists.

**Comment by pannal** [comment]
Good idea. I might change `Embedded subtitles: Treat "Undefined" (und) as language 1` to do the same for external subs if enabled.

**Comment by john626** [comment]
Yeah that would be awesome. And would be even cooler if it could do the same for unknown subtitle file in subfolder too :)

**Comment by pannal** [comment]
It will, given that you've configured the sub folder.
