### ISSUE TITLE
Lot of OSError: [Errno 75] Value too large for defined data type:

### ISSUE THREAD

**Issue by beloware** [pannal/Sub-Zero.bundle#555]
I get a full of log with this error. And ofcourse it is not auto working snd manual is hardly usable also.

Linux Latest plex

**Comment by pannal** [comment]
Please attach your log zip.

**Comment by beloware** [comment]
@pannal 
[sublog.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/2332073/sublog.tar.gz)

**Comment by beloware** [comment]
@pannal 
[Logs_180830_22-50-38.zip](https://github.com/pannal/Sub-Zero.bundle/files/2337886/Logs_180830_22-50-38.zip)
Ok. Found it.

**Comment by pannal** [comment]
This'll be fixed in the upcoming version. You can try [the develop branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.5.zip) if you want to. See [here ](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)for installation.
