### ISSUE TITLE
If forced subs exist for non-English movies, Sub-Zero still downloads subs

### ISSUE THREAD

**Issue by SpiralGalaxy** [pannal/Sub-Zero.bundle#557]
If you have a foreign movie with an embedded sub with the forced flag or a sub named ~~"filename.**forced**.en.srt"~~ "filename.en.forced.srt" , subzero is still downloading a sub.

**Comment by pannal** [comment]
Yes, SZ expects the `forced` and other advanced tags *after* the language tag. `filename.en.forced.srt` should work.

**Comment by SpiralGalaxy** [comment]
Sorry, I typed it wrong. The forced is in fact after language but it still downloads. Also affects mkvs with the forced flag.

**Comment by SpiralGalaxy** [comment]
Okay, thanks. I use sub for all movies so I'll just add subzero.ignore files in folders containing foreign movies.

**Comment by pannal** [comment]
So you'd want an option to not search for subtitles if an external or embedded forced subtitle exists for one of the selected languages?

**Comment by SpiralGalaxy** [comment]
Yes, that would be nice. Something more robust would take into account audio language to determine if forced or forced plus full subs is needed. Keeping it simple works good enough for me though.
