### ISSUE TITLE
Don't download subtitles for certain video qualities

### ISSUE THREAD

**Issue by isaac2004** [pannal/Sub-Zero.bundle#558]
My Plex box isn't very powerful and playing 4k videos with subtitles does not work. Is there a way to prevent auto searching for subtitles based on video qualities? Example being don't download subtitles for 4k content.

**Comment by pannal** [comment]
Hm no. You can either manually add the media you don't want subtitles for to the ignore list (via menu or file). The easiest way is to put 4k media into its own library and not enable SZ for it, or add the library to the ignore list.
