### ISSUE TITLE
SZ only extracts first subtitle

### ISSUE THREAD

**Issue by Maximus97** [pannal/Sub-Zero.bundle#560]
I noticed that when I used Sub-Zero on my GoT collection, which had both nonforced and forced (without forced tag) subtitles, only the forced embedded subtitles got extracted. Is it by design that only **one** subtitle of a language gets extracted?

**Comment by pannal** [comment]
Do you have (3) enabled [here](https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#language-configuration)?

**Comment by pannal** [comment]
Yes, and if that's enabled, SZ will only extract the forced subtitles. Will be fixed as the whole forced/foreign handling will change for 2.6.
