### ISSUE TITLE
SRT downloads not complete

### ISSUE THREAD

**Issue by Reemster** [pannal/Sub-Zero.bundle#561]
I use Sub-zero now for a few weeks. And i like it, especially for movies, because that works for 99%. But with series it's not working nice for the most of the time. If i add a new series to my plex, not all episode get a SRT. And they exist on opensubtitles. Like the serie Mindhunter. There are 10 episodes. But Sub-Zero download only 6 srt-files. episode  3, 4, 9 and 10 get skipped. I don't know why? i don't see any errors in the log. And i'm VIP-user by opensubtiles.. Maybe someone else see the problem?

[comMINDHUNTER.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/2343552/comMINDHUNTER.plexapp.agents.subzero.txt)

**Comment by Reemster** [comment]
I already see the problem with this case. The 4 episodes what not had a SRT file are with embedded subtiles.. So annoying.

**Comment by Reemster** [comment]
Ok, strange. Because i though the option "Don't search for subtitles of a language if there are embedded subtitles inside the media file" (options 3)
<img width="549" alt="conf_scanning" src="https://user-images.githubusercontent.com/19860405/44958608-e6a1b780-aee2-11e8-9af3-153a82bd16f4.png">
 is enabled, that's the case that there no SRT files get downloaded. But this function is not selected. So still i'm curious now why the SRT files not get downloaded.

**Comment by pannal** [comment]
Embedded is not at issue here.

I've had a look at your logs and the subtitle availablen on OpenSubs: https://www.opensubtitles.org/en/subtitles/7125155/mindhunter-episode-1-3-nl

It's tagged with `25.000` FPS and your file is `23.976`. SZ makes the correct decision here - whether the subtitle actually is 25fps I can't say, but it's tagged that way.

**Comment by Reemster** [comment]
Ok, thanks for the information. I didn't find this in the logs. Is it maybe an idea to have a monitor screen/panel in sub-zero where you can look why a movie or serie not got a SRT file? this information must be in the logs, so maybe its "easy"  to get this out of the log and in simple English what's going on.

**Comment by pannal** [comment]
In theory, yes, but in practice this is really hard. I have no real control over how the plugin menus are displayed, and the second problem is the sheer mass of data. There can be thousands of subtitles per query that get ignored because of wrong FPS or a low score, which would all be data I'd have to keep inside the plugin memory or store it somewhere, maintain it etc.

What you can do is do the manual listing via the SZ menu - there you'll see the scores and the wrong FPS info as well, but then you can decide to download it and fix the FPS using the modification menu.

**Comment by Zixim** [comment]
i was googling for a way to view/follow/monitor what is going on when sub-zero is asked to refresh, and found this thread.
Is there a log file that i could tail which would show the progress of a refresh ?
