### ISSUE TITLE
Arabic Subtitles Reverse

### ISSUE THREAD

**Issue by AWaheedi** [pannal/Sub-Zero.bundle#564]
Hello there,

There is an issue with Arabic subtitles similar to the one mentioned in the other post https://github.com/pannal/Sub-Zero.bundle/issues/409

Subtitles are displayed correctly in some players and reversed special special in other players (punctuation displayed correctly on Mac and reversed in Apple TV)

Strangely, when I was trying to troubleshoot the issue and changing some settings in the .srt file, when I choose writing direction LTR and save the file, it plays correctly in all devices.

It will be hard to fix this issue by opening all the files and correct them one by one. It will be great if it gets implemented in sub-zero.

Thanks in advance.

**Comment by pannal** [comment]
I'll add Arabic to the reverse_RTL modification so you can use it from the menu if you need it.

**Comment by AWaheedi** [comment]
That would be great thanks! Do I have to wait for the update or there is something that I must install separately?

**Comment by pannal** [comment]
You'll need for the next update, yeah. Still sorting issues out.

**Comment by AWaheedi** [comment]
Sure, thanks for the effort
