### ISSUE TITLE
Folder is auto deleted after extraction and start up server

### ISSUE THREAD

**Issue by qtronicx** [pannal/Sub-Zero.bundle#567]
First of all I cant find Sub Zero anywhere on channels/plugins on the server to install, can find many other plugins but not that one.
And not listed on the Agent

I have also extracted the sub-zero.bundle folder into the plug-ins folder, but when I start up the server the sub-zero.bundle is auto deleted from plug-ins folder.

I tried other releases but its the same thing.
Read the manual install guide, but its deleted every time no matter what I do

**Comment by pannal** [comment]
It should be listed under plugins -> install plugins -> what's new.

If you want to do a manual installation, please follow this: https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation

**Comment by pannal** [comment]
Any news?

**Comment by qtronicx** [comment]
Yeah sorry for late responding.
The only way I got it to work, is by having the server up and running and copy paste the bundle folder into the plugins folder.
Then  I can see it under plugins in chrome, and do what ever changes I want

But when I go to the minimized icon and choose exit and then restart the program or perhaps restart my pc, the folder disappear and i have to copy paste it one more time.

**Comment by qtronicx** [comment]
extracted the folder without having pms started also, but as soon as i started pms, i looked as the bundle folder was deleted.

**Comment by qtronicx** [comment]
Yeah i did the plug-ins and not the support folder, key string also.
I tried looking at every possible plugins to install no where to find sz for auto install, not under whats new either.

Here is the funny part.
I dont know why my server did not auto update, found out just now. (5 september update)
But downloaded latest server update and now i suddenly can find it under whats new, and it seems to work.

Stopped and started the server a few times, and the folder is still there so now it worked perfect.
It should have work even if i had almost the newest release but.
Read the guide like 100 times, and know i did everything right :)

**Comment by pannal** [comment]
> Yeah i did the plug-ins and not the support folder, key string also.

Not inside `C:\Program Files` or `C:\Program Files (x86)` right?

**Comment by qtronicx** [comment]
no inside the appdata

**Comment by ukdtom** [comment]
Do check the other plugins.XXXX folders regardless....

If SZ is present there, the one in the real plugin directory will be deleted during startup
