### ISSUE TITLE
Sub-Zero not detecting embedded subtitles and downloading externals

### ISSUE THREAD

**Issue by intelligence** [pannal/Sub-Zero.bundle#568]
Hello!

Thanks for an awesome plugin for Plex, really makes my life easier.

I have noticed that Sub-Zero pulls subtitles for movies that has subtitles embedded. Ultimately I'd like to use the embedded ones as they usually are a better match than external ones.

Is this a bug or expected behaviour due to my settings?
https://i.imgur.com/ikkW6o8.png

Screen from VLC showing English subtitle already present:
https://i.imgur.com/CMTeUmc.png

Log:
https://pastebin.com/W0QRgMPQ

**Comment by pannal** [comment]
I'm guessing the language tag isn't set properly on those embedded subtitles. You want to enable those settings: https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#language-configuration (enable 7), https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#scanning-configuration (enable 3)
