### ISSUE TITLE
Can't open Sub-zero with enabled plex/reverse proxy

### ISSUE THREAD

**Issue by alhatmy** [pannal/Sub-Zero.bundle#570]
Just enabled "Plex" / behind reverse proxy example; plex.domain.com .. works fine ...
But! I can't access sub-zero (actual plugin where i can manually search)
Error Message; This plugin is not responding.

Seems that i can access it through (localhost:32400 itself) but i need to access it remotely

**Comment by pannal** [comment]
Full log zip please

**Comment by animosity22** [comment]
What proxy are you using? I use Caddy and have 32400 off completely and I can access Subzero and all other plugins just fine.

**Comment by pannal** [comment]
Please reopen in case this is still an issue.

**Comment by alhatmy** [comment]
just happened again, with a new log "now" 
[Plex Media Server Logs_2019-04-23_22-12-14.zip](https://github.com/pannal/Sub-Zero.bundle/files/3108997/Plex.Media.Server.Logs_2019-04-23_22-12-14.zip)

**Comment by alhatmy** [comment]
how can i open it !!!

**Comment by animosity22** [comment]
In the log you uploaded, there aren't any subzero plugin logs that I see in it, which might tell you why it isn't working.

In the plex logs, you can see it did make a connection though to local 32400.

```
com.plexapp.system.log.2:2019-04-23 21:20:41,422 (152e43791700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjBzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTUKbnM4CnBhcmVudElEczQzCmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiOi8vMzUwNDU4P2xhbmc9ZW5zNApndWlkYjFzNQpmb3JjZXMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMwpwcmltYXJ5X2FnZW50czYKMzExODQwczIKaWRyMAo_'
com.plexapp.system.log.2:2019-04-23 21:20:41,927 (152e43d94700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgozMTE4NDBzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Mwpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYjovLzM1MDQ1OD9sYW5nPWVuczQKZ3VpZHM0Cm51bGxzMgppZHIwCg__'
```

**Comment by alhatmy** [comment]
so is this the issue? the plugin works ... all the time
plex crashes once every few days ..
