### ISSUE TITLE
Subtitles not being replaced when manually selected

### ISSUE THREAD

**Issue by jackyaz** [pannal/Sub-Zero.bundle#576]
Using metadata storage - how does one purge previously downloaded subs? Manually selecting others keeps using the same set

**Comment by pannal** [comment]
> Manually selecting others keeps using the same set
Please supply your log zip.

**Comment by jackyaz** [comment]
I suspect it is related to metadata storage - filesystem storage works fine

I would upload logs but I purged all metadata subs and started over :(
