### ISSUE TITLE
Open Subtitles Hash Matches but doesnt get downloaded because "Wrong FPS"

### ISSUE THREAD

**Issue by marcel5454** [pannal/Sub-Zero.bundle#578]
Sub-Zero doesnt download a ton of subtitles because Open Subtitles reports the wrong FPS even though the Hash matches. Addic7ed is constantly throttled so woul be happy about a fix, or some setting to force download if hash matches.

![Image](https://i.imgur.com/ih5PZ0O.jpg)

**Comment by pannal** [comment]
I can add a setting for that. But rest assured, you won't like the false-positives it generates.

**Comment by marcel5454** [comment]
Yes I can imagine. It mainly happenes with Romanian subtitles and not english. Its just really painfull to download the subtitles 1 by 1 for a whole season because somebody set the wrong fps on open subtitles.

**Comment by beloware** [comment]
Also noticed this problem, not uniq.
