### ISSUE TITLE
Download subtitles without enabling them

### ISSUE THREAD

**Issue by buffhardback** [pannal/Sub-Zero.bundle#579]
I'm not a huge fan of using subtitles all the time, and generally only turn them on when I need them on/requested by a viewing partner. Am I missing an obvious setting somewhere that's "download the subs, but don't default them to enabled"?

**Comment by pannal** [comment]
SZ doesn't enable subtitles. Your PMS settings do. https://support.plex.tv/articles/204985278-account-audio-subtitle-language-settings/

**Comment by buffhardback** [comment]
Weird. I have my settings set to English audio/subs but I guess not enough videos have the language properly set. Thanks!
