### ISSUE TITLE
Playback issues - provider feliratok.info

### ISSUE THREAD

**Issue by syluccy** [pannal/Sub-Zero.bundle#580]
I'm not sure, if it's the right place to ask, but have you experienced playback issues with any providers?
I really appriciate  feliratok.info (Hungarian) provider, but when I try to play anything with subtitles downloaded from this provider, playback just won't start.
those subtitles even have a weird long name.
<img width="243" alt="screen shot 2018-09-22 at 9 49 35" src="https://user-images.githubusercontent.com/8645712/45914999-82bd3f80-be4d-11e8-9a06-cf9bf702f8de.png">

if I change the subtitle, playback works fine.
I'm not sure, how to read logs, I attach them.
does anyone have any idea?

[logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/2407591/logs.zip)

**Comment by beloware** [comment]
Provider have serious issues, i think, dev versions not even show any sub from site.

**Comment by morpheus133** [comment]
Hi!
Are you also use https://github.com/balesz/SuperSubtitles.bundle plugin? 
On a Hungarian forum they find that as guilty for this fault. 
In case of provider fault Subzero dont download anything.

But use the latest version from master here because it is already corrected:
https://raw.githubusercontent.com/pannal/Sub-Zero.bundle/master/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py

**Comment by morpheus133** [comment]
You can check it in the plex plugin logs if logging was enabled. Or you can disable one of the agent delete srt and make a force refresh metadata to check what happen.
But subzero was working for me tested it with several series. Just use version from master and uncomment this https://github.com/pannal/Sub-Zero.bundle/blob/bb2ed5a1167bb71936e573ec824f6701d667682d/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py#L134

**Comment by syluccy** [comment]
thanks, I've disabled the stand alone SuperSubtitles.bundle plugin, and now those subtitles with the long hashcodes dissapeared.
I think we can say, it wasn't the Sub-Zero plugin's fault.
But new discovery. When I ran it, to one particular file ( Ray Donovan - 4x01) Sub-Zero didn't find anything on Feliratok.info even though it exists there. Is it possible, the plugin doesn't like complete seasons packed in an archive file?
Here is the log file. Btw I've changed the .py file as you asked me to.
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2433449/com.plexapp.agents.subzero.log)

**Comment by morpheus133** [comment]
Hi @syluccy!
For me with the lates modifications it works with this.

Use the full file from here:
https://github.com/pannal/Sub-Zero.bundle/blob/bb2ed5a1167bb71936e573ec824f6701d667682d/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py#L134
And modify that one. (Not the already available)

Also you can use for hosszupuska this file:
https://raw.githubusercontent.com/pannal/Sub-Zero.bundle/20952b5c26ad38268486d34efba252c584bd4483/Contents/Libraries/Shared/subliminal_patch/providers/hosszupuska.py

For that also this is needed: 
https://raw.githubusercontent.com/pannal/Sub-Zero.bundle/20952b5c26ad38268486d34efba252c584bd4483/Contents/Libraries/Shared/subliminal_patch/utils.py

**Comment by syluccy** [comment]
okay, I don't understand, why I had to do these, because I should have the latest plugin installed, but I did.
and 
I think it's not working properly.
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2433849/com.plexapp.agents.subzero.log)

**Comment by morpheus133** [comment]
Because the latest plugin is more than 3 month old.
I already corrected some issue what will be included in next release.


Currently the problem that you delete too much or too less space here:
`# matches |= guess_matches`

just delete
``# ``  (# and space)
intend is very important in python. 
matches must start at the same column as if 2 line after.

`

**Comment by syluccy** [comment]
made the modifications for supersubtitles.py, nothing seems to be changed I think :/
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2438118/com.plexapp.agents.subzero.log)

**Comment by syluccy** [comment]
[supersubtitles.py.zip](https://github.com/pannal/Sub-Zero.bundle/files/2438122/supersubtitles.py.zip)

**Comment by morpheus133** [comment]
Are you activate supersubtitles in settings? 
I only see hosszupuska and opensubtitles as activated ones.
![image](https://user-images.githubusercontent.com/6975928/46369836-5773f500-c684-11e8-9062-02cb4a9a4b89.png)

**Comment by morpheus133** [comment]
Sorry I just quikly check the logs and missed it:
It is activated:
config.providers: ['supersubtitles', 'opensubtitles', 'hosszupuska']

Can you set the logging level to Debug. (Currently it is warning)
![image](https://user-images.githubusercontent.com/6975928/46391913-81a6d080-c6df-11e8-92a5-85b43d8f8808.png)

**Comment by syluccy** [comment]
wow...where the hell is that option gone?
I know I've seen it before, but I can't find it.
I'm using Version 1.13.8.5395, and advanced options are shown.

Found only this one.
![kepernyofoto 2018-10-05 - 12 23 01](https://user-images.githubusercontent.com/8645712/46530285-8f07ba80-c899-11e8-9593-0c514d9d86e5.png)

Btw, I'm not even sure, the plugin works, because I've disabled all other plugins, and I didn't have any subtitle for New Amsterdam (2018) - 1x01 even though there is.
https://www.feliratok.info/index.php?sid=5273
https://www.opensubtitles.org/en/search/sublanguageid-all/imdbid-8385764

I've enabled SuperSubtitles.bundle and the stand alon Opensubtitles plugin, and they could download it.
How can I make sure, if it even works?

**Comment by morpheus133** [comment]
You need to set it in the plugins settings. (Where you enabled the providers.)

**Comment by syluccy** [comment]
sorry for the late response.
I've set the logging to DEBUG, and I'm not sure, if it has anything to do with it, but it seems to me that the Sub-Zero plugin downloads subtitles again. Because when I ran the refresh for two episodes, all the other subtitle plugins were disabled. can you confirm it from the logs?
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2464905/com.plexapp.agents.subzero.log)
