### ISSUE TITLE
Not downloading subtitles for some shows

### ISSUE THREAD

**Issue by AlfHou** [pannal/Sub-Zero.bundle#581]
Hi. Sub Zero seems to have a lot of trouble finding subtitles for some of my shows. Here is the log: [https://pastebin.com/tnPfkJAf](https://pastebin.com/tnPfkJAf).

**Comment by pannal** [comment]
Do you have your refiners properly configured? I can see Sonarr/Radarr are connected, but they aren't used. What's your `I rename my files using` setting set to?

**Comment by AlfHou** [comment]
I believe the refiners are configured properly, here is a screenshot of the sonarr/radarr settings: ![screenshot](https://i.imgur.com/Uf5hYNN.png). Also, when I look at Sub-Zeros history it has managed to download subtitles, so it is active, even with an earlier season of the same show it has trouble with: ![screenshot](https://imgur.com/7b7dAbe.png)

**Comment by pannal** [comment]
OK, could you set SZ's logging to DEBUG, refresh an episode in question, then post your log zip? (see wiki)

**Comment by AlfHou** [comment]
[Logs_181017_09-27-52.zip](https://github.com/pannal/Sub-Zero.bundle/files/2486257/Logs_181017_09-27-52.zip)
Here you go.

**Comment by pannal** [comment]
You're most likely hitting two issues:
- opensubtitles being throttled massively lately (will be somewhat fixed with 2.6)
- subscene doesn't use the original filename (fixed in 2.6)
