### ISSUE TITLE
Any plans to adapt to the announced sunsetting of plugin support in plex?

### ISSUE THREAD

**Issue by IkeKap** [pannal/Sub-Zero.bundle#584]
Plex has recently announced that they are planning a phase-out of plugin support in plex. Read the announcement [here](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/) for more details.

Sub-zero is a massive help for getting quality subtitles for me and likely many others. I would really like for this addon to continue in some shape or form. 

The way I see it (don't hesitate to correct me if I'm wrong) there are 2 options that subzero could continue working even after Plex discontinues supporting addons

1. Subzero becomes a standalone app that integrates with Plex, not unlike Tautulli. The devs of Plex were specific in pointing out that Tautulli would not be effected by the phase out of plugins and that they believe this is "a better approach". A problem for this method is that subzero would have to probably redesign the User interface completely and perhaps restructure the way it accesses files within the Plex library

2. Subzero becomes simply a metadata agent. This might be a simpler option, but it might lack some of the features that users have learned to depend upon.

Please let me know what you think of my proposed option!!

**Comment by pannal** [comment]
I'll have an answer to you tomorrow or the day after, with a plan for the future.

**Comment by IkeKap** [comment]
As an update, it seems @pannal has covered his next steps in [this reddit post](https://www.reddit.com/r/PleX/comments/9n9qjl/subzero_the_future/)

**Comment by IkeKap** [comment]
The following is a copy paste job for those who either can't visit reddit or would prefer to stay in one place. The formatting at a glance seems "fine" but it may have issues and inconsistencies.

Introduction
Dear Plexians,

As those of you who have read the blog post from late September and the accompanying FAQ entry will have caught wind of by now, Plex Inc. is abandoning plugins over time, for good. This poses a major problem to users that rely on plugins to improve their Plex experience, such as myself and all the Sub-Zero users.

Problems
Problem 1
The first step is the removal of the Plugin Directory on Plex Web, thus forcing everyone to manage their plugins manually, again. Also the support for visual/UI based plugins is being phased out of the client apps. The UI Sub-Zero provides isn't very well usable, but at least it provided some fine grained manual tuning.

Problem 2
Quote from the blog post:

But don’t panic—while the Plugin Directory will soon be gone, you can still manually install plugins for the foreseeable future.

What worries me here is the "foreseeable future" part.



Also this quote seems to relieve some concerns people had, but in reality it doesn't:

While support for browsable plugins is being discontinued, nothing is happening to scanners and metadata agents with this announcement.

This may imply that over time even custom agents and scanners will most likely not work anymore, at least in their current state.

Solutions
Solution 1
Everyone will have to install their plugins manually. With the release of Sub-Zero 2.6 I'm planning to include an automatic update function, so this will only have to be done once.

Solving the soon-missing-UI-functionality-issue is a bigger one and it doesn't only affect Sub-Zero itself, but plugins like Trakt for example, as well.

Enter Kitana.

Kitana is a standalone plugin UI proxy if you like, that exposes existing UI routes of Plex plugins to the outside world. For now it doesn't add any UI functionality compared to the original UIs of the plugins, but it makes them usable again, is server agnostic, is designed to run behind reverse proxies and is responsive.



This has the added benefit of being able to properly control your plugins from your mobile phone, which has always been a hassle in the past.

Kitana is not Sub-Zero specific and one instance can be used to manage all of your plugins on all of your owned servers.

Early Screenshots:

Server selection

Main interface big screen

Main interface mobile



The project will be pushed to GitHub next week and will have its first official release soon after. I'm not quite sure how much love it'll receive feature-wise, aside from the core functionality, as this is more of a stopgap solution to enable users to keep using their installed plugins.

Solution 2
Plugins will most likely completely go away over time - when that'll be and how open Plex Inc. will be with their schedule remains to be seen.



The upcoming 2.6 version of Sub-Zero will be the last major release in its current form as a PMS agent/UI plugin.



At some point in the not so distant future, Sub-Zero will most likely morph to a standalone solution, either integrated into existing ones, or as a completely separate app.

I've been in contact with the developer(s) of Bazarr and depending on how well our codebases match there is a good chance that most of SZ's functionality can be integrated.

I'll be joining the Bazarr team once 2.6 and Kitana have been released to help with development.

There's still a long way to go, but I think we can get to a satisfying solution.

Closing words
This is a sad time for advanced Plex users and I don't fully understand the reasoning behind the abandonment of its most enthusiastic core user base and the way all of this was handled.

I hope I'll have enough free time to aid in bringing you an even better subtitle solution than SZ in the future.



Cheers everyone,

panni



Edit: Clarified "plugin directory" above.

Edit 2: This means = This may imply

Edit 3: it really doesn't = in reality it doesn't

**Comment by pannal** [comment]
Most of you will want to add [Kitana](https://github.com/pannal/Kitana) to your infrastructure for now :)
