### ISSUE TITLE
Sub-Zero missing from channel

### ISSUE THREAD

**Issue by pietro95** [pannal/Sub-Zero.bundle#585]
Hello Everyone

So recently I noticed that Sub-Zero is not anymore in my channel and I can't access to it. I tried to reinstall it directly from Plex, I tried to reinstall manually, but it doesn't show. I read the official FAQ and tried what they said but it still doesn't work! I also tried downgrading plex to 1.13.5.5332 but still doesn't show. What can I do?

**Comment by pannal** [comment]
Please attach your log zip if this issue still persists.

**Comment by pannal** [comment]
This was an error on my side. When OpenSubtitles was the only enabled provider, and it was throttled, the plugin disabled itself. Will be fixed in 2.6.
