### ISSUE TITLE
Subzero doesn't work as agent, but works in force-find

### ISSUE THREAD

**Issue by v9999** [pannal/Sub-Zero.bundle#589]
Hey guys, I run PMS in a RaspberryPi and I've been facing some issues with Subzero.
It doesn't seem to work as an agent, even though its channel page lists the current refresh in the current or last state.
However, this usual refresh never finds any subtitles (I'm using LegendasTV).
Then I go to the plugin's channel, ask for a force-find subtitle on the same media and voilà, the subtitles appear.
In my settings, Subzero agent is on top in PlexMovies, TVDB and TheMovieDB.

I've restarted the server a few times and the issue remains.
I've deleted the plugin a few times too, removing all its folders and references in the PMS' folders, but this issue remains. Please let me know any particular procedure or logging that I can provide.
Thanks.

**Comment by pannal** [comment]
Which one? develop-2.6 or the old branch?

**Comment by v9999** [comment]
> Which one? develop-2.6 or the old branch?

Sub-Zero 2.5.8.2708 DEV
should I get the newer one? :)

**Comment by pannal** [comment]
Hmm no, but that's weird, as it's essentially the same as master (the one that's inside the Plex repo)

**Comment by pannal** [comment]
Actually no, it's more recent than master. Forget that.
