### ISSUE TITLE
Forced Subtitles not playing as default

### ISSUE THREAD

**Issue by antigravity83** [pannal/Sub-Zero.bundle#590]
I have SubZero working quite well, however I’m struggling to get Plex to autoplay forced subtitles that Subzero downloads. 

Currently I have to manually select forced subtitles when playing content - which is frustrating.

I’ve told Sub-Zero to save the subtitles as Metadata, as the media files are saved in a read only folder.

Is there a way for Sub-Zero to save forced subtitles as Metadata, and have Plex auto select them when playing content?

**Comment by pannal** [comment]
This is nothing SZ can control. I'd ask on the Plex forums.

Normally forced subtitles are auto-selected by Plex.
