### ISSUE TITLE
Downloads English subtitles even with English audio track

### ISSUE THREAD

**Issue by tbotcotw** [pannal/Sub-Zero.bundle#592]
I've got it set to download main subtitles only if the audio track is not English, and to download forced subtitles if the audio track is English. It downloads both the full English subtitle and the forced subtitle even for files with an English audio track. I'm using 2.6.4.2834, and my media files are .mp4.

**Comment by pannal** [comment]
So it downloads two separate subtitles?

Can you attach your [DEBUG log](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs)?

**Comment by pannal** [comment]
Also can you attach a screenshot of your SZ settings page, where the language settings are?

**Comment by tbotcotw** [comment]
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2559359/com.plexapp.agents.subzero.log)
![screen shot 2018-11-07 at 2 58 07 pm](https://user-images.githubusercontent.com/42870759/48163731-acb3af80-e29d-11e8-86ce-7079b26ffea8.png)

There's today's log and my settings. Let me know if you need previous logs.

**Comment by tbotcotw** [comment]
And yes, it downloads two different subtitle files.

**Comment by pannal** [comment]
@tbotcotw please set the logging verbosity in SZ's settings to DEBUG, then refresh the item in question and post the log again.

**Comment by tbotcotw** [comment]
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2559609/com.plexapp.agents.subzero.log)

I think this is what you need.

**Comment by pannal** [comment]
`Setting log-level to WARNING` - nope, still wrong log level. You want to set the logging setting to DEBUG: https://github.com/pannal/Sub-Zero.bundle/raw/master/Wiki/ImagesV2/Conf_v2.5/conf_logs.png

**Comment by tbotcotw** [comment]
Third time's the charm.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2559624/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Thanks, I'm on it.

**Comment by pannal** [comment]
This will be fixed in the next bugfix release.

You can try it using the [develop-2.6 branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.6.zip), ([instructions here](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)) to confirm it's fixed.

**Comment by tbotcotw** [comment]
Thank you, that's working perfectly. And thank you for getting forced subtitles working so well, that was the last feature I needed to get everything automated.
