### ISSUE TITLE
Sub-zero doesn't appear in Plex plugins list, yet the directory says it's installed.

### ISSUE THREAD

**Issue by acosmichippo** [pannal/Sub-Zero.bundle#593]
Hello!

I was just tweaking my sub zero settings after hearing about the latest update, but something went wrong and now sub-zero doesn't seem to work at all. [It doesn't show up in my list of plugins](https://i.imgur.com/f9dxFJa.png), but [it DOES show up in Agents](https://i.imgur.com/OufFbcF.png).

When I go to re-install/reset it from the Plugin Directory, [Plex says it's already installed](https://i.imgur.com/5L6WMSk.png). I've tried restarting it, resetting it, uninstalling and reinstalling from the Plex Plugin Directory, and also manually installing from GitHub. Also stopped and restarted Plex each time.  No matter what I do I see the same problem.

This isn't expected behavior, is it? 

If it makes a difference I'm running Plex on a synology NAS.

Thanks so much for any help!

**Comment by pannal** [comment]
Please attach your DEBUG log. Set SZ's log verbosity to DEBUG in its settings via the agents interface, restart your PMS, then find your subzero.log and attach it here.

You didn't by any chance set the Sub-Zero mode to channel only? (https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#advanced-configuration)

**Comment by acosmichippo** [comment]
Thanks!  Where should I look for the logs?  I've tried poking around but haven't been able to find it.

> You didn't by any chance set the Sub-Zero mode to channel only?

Not unless I did so accidentally.

**Comment by pannal** [comment]
https://support.plex.tv/articles/200250417-plex-media-server-log-files/ there should be a subfolder called `PMS Plugin Logs` and then there should be one or more `com.plexapp.agents.subzero.log` files.

**Comment by pannal** [comment]
> Not unless I did so accidentally.
I meant agent only.

**Comment by acosmichippo** [comment]
no, it's set as agent+interface.

Anyway, I didn't realize I could get to the settings via Plex's agent page.  As long as that still works I should be good.

**Comment by pannal** [comment]
Hmm no, please retrieve your logs, I'd like to get to the bottom of this. The plugin should definitely appear.

**Comment by acosmichippo** [comment]
Sorry, I'm just having trouble finding where the sub-zero log is....  I've downloaded the PMS logs, but I don't see anything related to sub-zero in there.

**Comment by pannal** [comment]
@acosmichippo which SZ version are you on?

**Comment by acosmichippo** [comment]
sure, here are the PMS logs.

[Plex Media Server Logs_2018-11-08_11-14-56.zip](https://github.com/pannal/Sub-Zero.bundle/files/2563298/Plex.Media.Server.Logs_2018-11-08_11-14-56.zip)

The VERSION file says "22db02d (Wed Nov 07 14:11:43 UTC 2018)".

**Comment by pannal** [comment]
No I meant the Sub-Zero version (should be visible under agents). Also, do you have any provider enabled at all?

**Comment by acosmichippo** [comment]
yeah, I would have gotten it from there, but my agents page isn't working right now.  I suppose because I started a library metadata update to see if SZ was working.  I'm pretty sure it's the new version because I uninstalled and reinstalled it so many times, but I will verify as soon as the agents page is working again.

**Comment by pannal** [comment]
It looks up to date yeah. I'm not sure how to debug this, as I can't reproduce it.

Would you be open to join the SZ Slack chat and let me have a look?

**Comment by acosmichippo** [comment]
Thanks, I've joined.

**Comment by pannal** [comment]
Did you by any chance set sonarr/radarr settings recently?
