### ISSUE TITLE
installing sub zero problem

### ISSUE THREAD

**Issue by rderickson9** [pannal/Sub-Zero.bundle#594]
not able to find sub zero on agents in PMS.  Able to download the bundle, extract it into plex addons.  I restart PMS.  when I go to look up agents sub zero is missing.  

PMS 1.13.9.5456
Windows 10

**Comment by pannal** [comment]
Which addon folder do you extract it to and how's the layout afterwards?

**Comment by rderickson9** [comment]
AppData\Local\Plex Media Server\Plug-ins

**Comment by rderickson9** [comment]
Sub-Zero.bundle

**Comment by pannal** [comment]
Can you attach your logs including the Plug-In logs?

**Comment by rderickson9** [comment]
[Plex Media Server Logs_2018-11-08_17-32-45.zip](https://github.com/pannal/Sub-Zero.bundle/files/2563997/Plex.Media.Server.Logs_2018-11-08_17-32-45.zip)

**Comment by rderickson9** [comment]
let me know if you need something else.  I'm not the brightest when it comes to this kind of stuff

**Comment by pannal** [comment]
Hmm, what's inside your Sub-Zero.bundle folder? Plex doesn't see the plugin at all.

**Comment by pannal** [comment]
You could also try visiting your local plex web instance (127.0.0.1:32400) and install the plugin from the Plugin Directory there. I'd like to solve this specific problem, though.

**Comment by virrexd** [comment]
Okay it installed after i pressed install 100 times lol..

**Comment by rderickson9** [comment]
lol

**Comment by pannal** [comment]
@rderickson9 how?

**Comment by pannal** [comment]
@rderickson9 ?
