### ISSUE TITLE
Missing subtitle after Sonarr replaced WEBDL (SRT) with Bluray (PGS)

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#604]
On my system, I had The Handmaid's Tale S2-E1 [WEBDL] with embedded SRT extracted.

Sonarr replaced (upgraded) to The Handmaid's Tale [Bluray] with PGS subtitles.

![the handmaids tale webdl opdate to bluray](https://user-images.githubusercontent.com/45288008/49643173-4f825980-fa15-11e8-89d2-27a5c4ade5b7.PNG)

[Media Info - The Handmaids Tale.txt](https://github.com/pannal/Sub-Zero.bundle/files/2656940/Media.Info.-.The.Handmaids.Tale.txt)

After The Handmaid’s Tale S02-E1 was replaced, there is no subtitle in the folder (no download).

![folder - the handmaids tale](https://user-images.githubusercontent.com/45288008/49643140-37123f00-fa15-11e8-8fa9-629921e5d64a.PNG)

As far as I know, SZ is not able to extract the embedded PGS, so I would like SZ to download a subtitle and use the ‘configured default mods’.

If I from the SZ menu click on “Force-find subtitles: The Handmaid’s Tale S02E01, June” the subtitle is downloaded.

In the same SZ menu under “Manage English subtitle”, I can see that SZ think there is a current subtitle.

![sz menu for the handmaids tale](https://user-images.githubusercontent.com/45288008/49644192-11d30000-fa18-11e8-9665-051455284225.PNG)

I have set SZ to DEBUG and did a "Refresh Metadata" for The Handmaid's Tale.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2657048/com.plexapp.agents.subzero.log)

![sub-zero subtitles settings 1](https://user-images.githubusercontent.com/45288008/49645929-e226f680-fa1d-11e8-88d8-cb847e2c460f.PNG)

![sub-zero subtitles settings 2](https://user-images.githubusercontent.com/45288008/49645944-e8b56e00-fa1d-11e8-9dfc-51ee8167647c.PNG)

![sub-zero subtitles settings 3](https://user-images.githubusercontent.com/45288008/49645952-ee12b880-fa1d-11e8-938f-bf0efaffa3bf.PNG)

![sub-zero subtitles settings 4](https://user-images.githubusercontent.com/45288008/49645966-f3700300-fa1d-11e8-8d72-21e0e871c64e.PNG)

![sub-zero subtitles settings 5](https://user-images.githubusercontent.com/45288008/49645974-f7038a00-fa1d-11e8-8ee8-87f419368def.PNG)

**Comment by pannal** [comment]
And do you have DEBUG logs for this? :)

**Comment by cphmichael** [comment]
The DEBUG log is attached above the Sub-Zero Subtitles Settings and here:

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2659699/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Another thing, which is not the issue here, but it's important: If you rely on the PMS to rescan the filesystem on changes and don't use the Sonarr connection push events, the PMS will not trigger Sub-Zero when a quality change happens.

**Comment by pannal** [comment]
Disabling this should fix your issue: ![img](https://i.imgur.com/8bomgoL.png).
That will instruct SZ to skip non text subtitles and it should download new ones.

**Comment by cphmichael** [comment]
My PMS had The Handmaids Tale S02E01 [WEBRip] with embedded English SRC that SZ had extracted to an external subtitle file 7 months ago.

Yesterday Sonarr picked up a Bluray version with embedded English PMS subtitles and 'upgraded' PMS with the better one.

![sonarr](https://user-images.githubusercontent.com/45288008/49686680-503fec00-faf8-11e8-8e9c-c86ef5f8c215.PNG)

SZ did not automatically download a subtitle-file for the new Bluray version.

When I discovered that, I opened the SZ menu and clicked on “Force-find subtitles: The Handmaid’s Tale S02E01, June”, then SZ downloadeaded a subtitle for the Bluray version.

**Comment by cphmichael** [comment]
Maybe I refresh in a wrong way.

I did a "Refresh Metadata" from my PMS for The Handmaid's Tale.

Do that not trigger the SZ in the same way as when Sonarr download a new file?

**Comment by pannal** [comment]
It does. But SZ didn't download any subtitle, because of the setting I just posted a screenshot for. It had embedded subtitles, and you configured SZ to not search for subtitles if there are embeddeds, even if they're non-text (PGS).

**Comment by pannal** [comment]
Just follow [this](https://github.com/pannal/Sub-Zero.bundle/issues/604#issuecomment-445460579).

**Comment by pannal** [comment]
Is this resolved? It should work after disabling the exotic subtitle extensions.

**Comment by cphmichael** [comment]
"disabling the exotic subtitle extensions"

Is that the same as disabling "include non-text subtitle formats" as you suggested yesterday?

I did that and after that I did a "refresh" from the SZ menu, but I still didn't get the subtitles.

Therefore I looked in the new DEBUG log and discovered the addic7ed "DownloadLimitExceeded error".

Today I did another "refresh" from the SZ menu, and this time I got the subtitles :-)

Sonarr haven't picked up any series with embedded PGS after I disabled the switch, so I don't know if it works automatically (when Sonarr add a new series).

**Comment by pannal** [comment]
> Is that the same as disabling "include non-text subtitle formats" as you suggested yesterday?

Yep.

> Sonarr haven't picked up any series with embedded PGS after I disabled the switch, so I don't know if it works automatically (when Sonarr add a new series).

It should. Please reopen this should it happen again.
