### ISSUE TITLE
Addic7ed not using credentials

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#605]
In the attached DEBUG log it says:

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2659787/com.plexapp.agents.subzero.log)

2018-12-08 15:41:14,283 (147b5427c700) :  INFO (config:804) - Not using addic7ed until 18/12/08 18:17, because of: DownloadLimitExceeded

When I login with my account to addic7ed it says that I haven't downloaded any subtitles today:

![addic7ed](https://user-images.githubusercontent.com/45288008/49687365-15db4c80-fb02-11e8-9781-a485e5d0fc53.png)

![sz setup](https://user-images.githubusercontent.com/45288008/49687423-b6ca0780-fb02-11e8-8868-98b31c6584a9.png)

**Comment by pannal** [comment]
Well, SZ throttles the provider for a fixed amount of time after a DownloadLimitExceeded error had been raised.

Does addic7ed reset the limits at a fixed time of day? If so, I can integrate that.

**Comment by cphmichael** [comment]
DEBUG log:

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2660598/com.plexapp.agents.subzero.log)

Today I was able to download the subtitles from addic7ed:

2018-12-09 14:35:20,938 (153b594ed700) :  INFO (logger:38) - subliminal_patch.core: Downloading subtitle <Addic7edSubtitle u'http://www.addic7ed.com/updated/1/136462/10' [en]>

I logged in to my addic7ed account, but it did still says "Downloads by User Today 0 of 40"

I copy/paste "http://www.addic7ed.com/updated/1/136462/10" to my browser and it downloaded the subtitles.

After that addic7ed updated my download to 1 of 40

So it seems like when SZ downloads subtitles from addic7ed it doesn't do that from my account.

That can maybe be the reason that I got the "DownloadLimitExceeded error" yesterday, but my addic7ed did say 0 of 40.

What is "Addic7ed boosting"?

2018-12-09 14:35:20,921 (153b594ed700) :  INFO (logger:38) - subliminal_patch.providers.addic7ed: Boosting Addic7ed subtitle by 19

![addic7ed boost score](https://user-images.githubusercontent.com/45288008/49698453-42579d00-fbc4-11e8-924d-baadf7a25d05.png)

Can that have something to do with the problem?

**Comment by pannal** [comment]
The addic7ed login was actually broken.

**Comment by cphmichael** [comment]
Can you explain what the "Addic7ed: boost score" is?

Just for my curiosity :-)

**Comment by pannal** [comment]
Sure, it's [on the wiki](https://github.com/pannal/Sub-Zero.bundle/wiki/Media-Score#addic7ed_boost-tv) :)

**Comment by pannal** [comment]
You can try a manual install of the develop-2.6 branch btw, and see whether your issue is resolved.
