### ISSUE TITLE
Question: find all Embedded subtitles and extract them

### ISSUE THREAD

**Issue by Soulplayer** [pannal/Sub-Zero.bundle#613]
Hello,

This is a question: is there a way to force sub-zero to scan all files already on plex and extract all the embedded subtitles? I cannot seem to find this option.

Thank you,

Soul

**Comment by pannal** [comment]
Yes, you can refresh the metadata of all of the items inside your library.
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q2-im-running-the-plugin-for-the-first-time-and-want-to-have-subtitles-for-all-of-my-old-items
