### ISSUE TITLE
Auto Extract embedded subtitles = Unknown (SRT External)

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#614]
I have enabled "Automatically extract and use embedded subtitles upon media addition"

As you can see on the attached screendump, Plex has recognized the embedded subtitles as "English (SRT)", but the extracted embedded subtitles show up as "Unknown (SRT External)" in Plex:

![unknown srt external](https://user-images.githubusercontent.com/45288008/52058548-f859ba80-2567-11e9-925d-af0bc4d147d0.PNG)

Is the log it looks like SZ tries to search for subtitles from 'opensubtitles' but abort because it 'determining existing subtitles'.

I have unchecked the "After automatic extraction of embedded subtitles, also immediately search for available subtitles".

Log attached:

[subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/2817454/subzero.txt)

- - - - - - - - 

![1](https://user-images.githubusercontent.com/45288008/52058819-8cc41d00-2568-11e9-8f3e-b87050541c77.PNG)

![2](https://user-images.githubusercontent.com/45288008/52058899-b8df9e00-2568-11e9-932c-4b441a0b9549.PNG)

![3](https://user-images.githubusercontent.com/45288008/52058911-bc732500-2568-11e9-90c9-bcafc530cfbf.PNG)

![4](https://user-images.githubusercontent.com/45288008/52058927-c137d900-2568-11e9-8a1e-afbf6722b971.PNG)

![5](https://user-images.githubusercontent.com/45288008/52058931-c39a3300-2568-11e9-9873-775a0ec61d99.PNG)

**Comment by pannal** [comment]
Well, as you've enabled `Restrict to one language` Plex handles those as Unknown, because they don't have a language tag inside the filename. SZ *should* override that, that might be a bug.

**Comment by cphmichael** [comment]
If I uncheck the "Restrict to one Language" and keep "Subtitle language (2) and (3)" to NONE, will that solve the problem and I will still get only English subtitles?

**Comment by pannal** [comment]
Yes.

**Comment by cphmichael** [comment]
Uncheck the "Restrict to one Language" fixed the problem for me :-)
