### ISSUE TITLE
subzero not picking up subtitles on disk.

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#615]
subzero have previously downloaded a subtitle for one of my movies but have now "forgotten" about it and it says that it have no English subtitle in storage. updating the movie metadata changes nothing nor does refreshing the movie in the sub-zero plugin menu. I could force find new subtitles but this triggers a re download of all subtitles which I don't want since I've already modified my Swedish subtitle somewhat.

**Comment by pannal** [comment]
Can you supply a log when refreshing an item in question?
