### ISSUE TITLE
Sub-Zero not downloading subtitles

### ISSUE THREAD

**Issue by czarmin** [pannal/Sub-Zero.bundle#617]
I'm not very good with plex. I couldn't make plugins work, until today, when I reinstalled it. So when it worked I instantly downloaded Sub-Zero, but It's not working. I tried reading the log, but I'm not sure what is the problem. I think It's maybe about permissions, but I'm really not sure.

Here is my log:
https://pastebin.com/YDs35vE8

Any help? Thanks!

**Comment by ThomasClemenceau** [comment]
Hello,

Did you tried to access to this file : "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/b/ec12d2aa54df9a7336ac5786488fe505b1bdeb3.bundle/Contents/com.plexapp.agents.subzero"

If this file doesn't exist, please re install Sub-Zero. Else check permissions (ls -la) in the folder "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/b/ec12d2aa54df9a7336ac5786488fe505b1bdeb3.bundle/Contents"

**Comment by pannal** [comment]
@ThomasClemenceau the `ERROR (model:205) - Cannot read model from` entries aren't important, those happen often (Plex internal, doesn't break anything).

@czarmin you don't have permission issues. Can you set `How verbose should the logging be?` in SZ's settings to DEBUG, then refresh an item with missing subtitles, then post your log again?
