### ISSUE TITLE
blacklist current subtitle not working

### ISSUE THREAD

**Issue by defranco** [pannal/Sub-Zero.bundle#618]
Hi!

I have an issue that the "blacklist current subtitle" option never works. I use this option when I notice a bad subtitle. 

it always says that are searching for a new subtitle but never gets a new one - even there is a lot of subtitles available.

 What I expect is that it searches for a second option and replace the current subtitle. Am I understanding wrong how this option works?

**Comment by pannal** [comment]
You understand the option correctly.

Please provide logs.

**Comment by Vivienb** [comment]
Hi, I have a similar problem.
I tried with the blacklist, the paths and the different files to prevent the download without success.
What types of logs do you need?

**Comment by pannal** [comment]
@Vivienb https://github.com/pannal/Sub-Zero.bundle/wiki/Logs

**Comment by Vivienb** [comment]
I hope this will help you.

[Logs_190411_19-12-53.zip](https://github.com/pannal/Sub-Zero.bundle/files/3069812/Logs_190411_19-12-53.zip)

**Comment by pannal** [comment]
Please set SZ's logging verbosity to DEBUG (lower part of SZ's settings), then try and simulate the behaviour again.

In the current rollout subscene and addic7ed aren't working, so your blacklist might just work, but there aren't any other viable sources available.

**Comment by Vivienb** [comment]
At times, the blacklist is well taken into account. Since I can not reproduce. I will try to prevent it if it ever happens again.

**Comment by pannal** [comment]
OK, please reopen if the issue persists.

**Comment by Vivienb** [comment]
Hi, 

I'm coming back for the unwanted download.
In file number 5 we see that the series "Le monde de Jamy" is ignored, but in file number 4 there is a call to retrieve the subtitles.

I did not find other series / movies that have problem in the logs but I find myself well with several films / series with unwanted subtitles. (With the dates of creation of .srt the logs do not go back enough).

[Logs_190508_21-06-03.zip](https://github.com/pannal/Sub-Zero.bundle/files/3158958/Logs_190508_21-06-03.zip)
