### ISSUE TITLE
Downloads language even when select not to

### ISSUE THREAD

**Issue by nerradtreborsniktaw** [pannal/Sub-Zero.bundle#620]
Hi, I have same issue as #592. I am using 2.6.4.2911. Is issue fixed in this version or should I try the developer version as suggested in #592? #59

TIA

**Comment by pannal** [comment]
Can you supply your log zip please?

**Comment by nerradtreborsniktaw** [comment]
[Logs_190312_10-37-36.zip](https://github.com/pannal/Sub-Zero.bundle/files/2956382/Logs_190312_10-37-36.zip)

It also seems I can only get the plugin to get subs from doing Refresh All Metadata on the library.

**Comment by pannal** [comment]
I really can't make much out of your logs. There seem to be massive issues with your library.

Please set Sub-Zero to DEBUG logging (bottom of SZ settings, logging verbosity), then refresh the item in question, then post your logs again.
