### ISSUE TITLE
Opensubtitles - various errors

### ISSUE THREAD

**Issue by antigravity83** [pannal/Sub-Zero.bundle#621]
I've recently updated to the latest version of Sub-Zero in an attempt to fix errors I'm having with OpenSubtitles. 

It seems to work for a short while, but regularly throws up these various errors:
- Serviceunavailable
- limitreached (even though I'm VIP and haven't reached my daily limit. Ie. last I checked I had downloaded only 10 subtitles that day)
- toomanyrequests

I've re-entered my Opensubtitles credentials into the plugin. 

It seems it works sometimes, but most of the time it doesn't.

**Comment by DeviDarkL** [comment]
I'm having the same problem. Can't download any subtitle with SUBZERO. 

Logs only show:
`2019-02-24 19:42:34,736 (3d40) :  CRITICAL (core:574) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.4.2911)', called with guid 'com.plexapp.agents.thetvdb://350667/1/16?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d893009fb\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "G:\Plex.Metadata\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 227, in update
    Log.Warning("Plex Transcoder not found, can't auto extract")
AttributeError: 'LogKit' object has no attribute 'Warning'`

**Comment by antigravity83** [comment]
Constantly getting these errors:

![image](https://user-images.githubusercontent.com/27241813/53672296-9e1a5980-3ccd-11e9-8be5-4abea50bfeb3.png)

**Comment by pannal** [comment]
@antigravity83 your issues seem to be throttling (DownloadLimitExceeded), which simply is an OpenSubtitles limit which has been hit.

@DeviDarkL the issue will be resolved soon.

**Comment by pannal** [comment]
@antigravity83 please supply logs
