### ISSUE TITLE
SubZero not being added to Plugins

### ISSUE THREAD

**Issue by georgeduckett** [pannal/Sub-Zero.bundle#624]
I have Plex running on a Synology box.

It doesn't appear in the Plugins section, and the SubZero agent doesn't appear as an option.

In the log files it complains about a URLOpen timeout error; I believe the relevant part of the stack trace is here:

    File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/root.py", line 45, in agents
    response = self.http.get('system/agents')

The full log is [here](https://pastebin.com/raw/VExj0jim).

My Synology box is fairly underpowered, so I wonder if the issue is simply that the request is taking too long. Is it possible to increase the timeout, or perhaps there is something else going on entirely?

Any help is much appreciated.

**Comment by pannal** [comment]
Can you see the agent under your metadata agents by any chance?

**Comment by georgeduckett** [comment]
I'm not 100% sure where you mean, but if you mean the agent selection under advanced when editing a library, then no. I don't get it in the list of agents anywhere I can see.

**Comment by pannal** [comment]
I've answered you in Slack, let's move there.

**Comment by pannal** [comment]
> I'm not 100% sure where you mean, but if you mean the agent selection under advanced when editing a library, then no. I don't get it in the list of agents anywhere I can see.

No, I mean in the [agent settings](https://github.com/pannal/Sub-Zero.bundle/wiki/Agent-configuration).

**Comment by georgeduckett** [comment]
@pannal 	I don't see it there either.

**Comment by marine1988** [comment]
i see it on agent settings but not on plugins what can I do :(

**Comment by pannal** [comment]
@marine1988 please open a separate issue with your full SZ DEBUG logs attached. This issue has been unresolved, it seems like his NAS is too weak to run most plugins.
