### ISSUE TITLE
Subtitle matching too "precise"

### ISSUE THREAD

**Issue by ksotin** [pannal/Sub-Zero.bundle#625]
For example, in my library there are TWO versions of ONE movie, one of which named XXX.H264.AAC.mp4 and the other XXX.x264.DTS.mkv. The weird thing is that one of them would successfully match a subtitle while the other would fail. Is this an issue to be solved or just due to my misuse? Please help. Thanks in advance.

**Comment by pannal** [comment]
Are they recognized by Plex as two versions of the same movie/episode?

**Comment by ksotin** [comment]
@pannal No. They never exist in my library at the same time.

**Comment by pannal** [comment]
OK, I'll need your logs for this. Please set SZ's log level to DEBUG (bottom of SZ settings), simulate the behaviour, then post your log zip

**Comment by ksotin** [comment]
@pannal Sorry, the problem did not reappear. Maybe I wrongly memorized something for the first time. Thank you for your support!
