### ISSUE TITLE
Calling a Python script after subtitle grabbing 

### ISSUE THREAD

**Issue by Psycoguana** [pannal/Sub-Zero.bundle#626]
Hey! I wrote a  Python script and try to run it after a subtitle grab, but there's no luck.

This is what I'm using in the SZ config:
`/usr/bin/python3.6 /home/psyco/Programming/Python/Sub_cleaner/menu.py --auto`
I'm using the exact python path because "python3.6" gave me an error. The thing is, now I have no errors at all, and yet the script is not working.

Executing that exact line of code in the terminal works by the way.

I tried looking for that path in the logs but there's nothing, someone knows what can I do? Or what can I look for in the logs?

**Comment by pannal** [comment]
You could set SZ's log level to DEBUG, then post your log zip :)

**Comment by pannal** [comment]
Also, you don't seem to be using any parameters SZ provides, is that intentional?

**Comment by Psycoguana** [comment]
Yes, not using any parameters is intentional, when I wrote the script I didn't even know about this feature, lol.

Ok, now I see it is actually being called (It's not running tho)
I think these are the important lines:
`Calling /usr/bin/python3.6 with arguments: [u'/home/psyco/Programming/Python/Sub_cleaner/menu.py', u'--auto']`
`Process output:`

The script dumps the time it runned in a file, if it fails for any reason it dumps the error, so I don't think it's a problem with that.

[Here's the complete log](https://drive.google.com/open?id=1HAHYRXxeSEqlvvTsjMwsNY7X_o6awF50)

**Comment by pannal** [comment]
Can you follow [this](https://github.com/pannal/Sub-Zero.bundle/issues/355#issuecomment-395711880) with a new blank python file and post the results?

This smells like something I've seen before.

**Comment by pannal** [comment]
Also please create a small sh file that calls your python script to see whether that makes any difference.

The PMS imposes its own python environment heavily on any script it runs (e.g. SZ). I'm guessing we're in similar territory here.

**Comment by Psycoguana** [comment]
I actually saw that issue before, I opened this one because I wasn't sure what the solution was.

This is what I get:
`environ({'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/sublime_text.desktop', 'QT_ACCESSIBILITY': '1', 'LANG': 'es_AR.UTF-8', 'QT_IM_MODULE': 'ibus', 'USER': 'psyco', 'XDG_VTNR': '1', 'XDG_SESSION_TYPE': 'x11', 'IM_CONFIG_PHASE': '2', 'QT4_IM_MODULE': 'xim', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'XDG_SESSION_DESKTOP': 'ubuntu', 'SHELL': '/bin/bash', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'WINDOWPATH': '1', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'GDMSESSION': 'ubuntu', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'XMODIFIERS': '@im=ibus', 'HOME': '/home/psyco', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'DESKTOP_SESSION': 'ubuntu', 'XDG_SEAT': 'seat0', 'PWD': '/home/psyco', 'GTK_MODULES': 'gail:atk-bridge', 'XDG_SESSION_ID': '1', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'TEXTDOMAINDIR': '/usr/share/locale/', 'DISPLAY': ':0', 'JAVA_HOME': '/usr/lib/jvm/java-11-oracle', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'SSH_AGENT_PID': '1468', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'USERNAME': 'psyco', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_MENU_PREFIX': 'gnome-', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LIBVIRT_DEFAULT_URI': 'qemu:///system', 'TEXTDOMAIN': 'im-config', 'PATH': '/home/psyco/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-11-oracle/bin:/usr/lib/jvm/java-11-oracle/db/bin', 'DERBY_HOME': '/usr/lib/jvm/java-11-oracle/db', 'SESSION_MANAGER': 'local/guana:@/tmp/.ICE-unix/1307,unix/guana:/tmp/.ICE-unix/1307', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '21190', 'SHLVL': '0', 'J2REDIR': '/usr/lib/jvm/java-11-oracle', 'CLUTTER_IM_MODULE': 'xim', 'LOGNAME': 'psyco', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'GTK_IM_MODULE': 'ibus', 'LANGUAGE': 'es_AR:es', 'J2SDKDIR': '/usr/lib/jvm/java-11-oracle'})`

**Comment by Psycoguana** [comment]
Alright, now I get this:
`Handling request GET /video/subzero/:/prefs/set?notify_executable=%2Fhome%2Fpsyco%2FProgramming%2FPython%2FSub_cleaner%2Ftest.sh`

And after some more stuff, this:
`Notify executable not existing or not executable: /home/psyco/Programming/Python/Sub_cleaner/test.sh`

I checked the permissions of the file and they were '-rwxrw-r--', I don't understand much about permissions, but just in case I did a 'chmod 777'.

Anyway, now it's not even being called

**Comment by pannal** [comment]
You need `chmod +x /home/psyco/Programming/Python/Sub_cleaner/test.sh`

**Comment by Psycoguana** [comment]
It's still not being called anymore, [here is the new log](https://drive.google.com/open?id=1i4cYWDNJ5b1nWta58-OX0udG6i2HUJga), I can't see anything relevant

**Comment by pannal** [comment]
`Notify executable not existing or not executable: /home/psyco/Programming/Python/Sub_cleaner/test.sh` - did you restart SZ after the chmod? You can do that via the menu.

**Comment by Psycoguana** [comment]
Oh, I didn't know that was necessary.

Now I get:
`Calling /home/psyco/Programming/Python/Sub_cleaner/test.sh with arguments: []`
`Process output:`

Still the python script is not running. When it runs it may or may not print several lines, also a "Finished!" at the end. I'm not sure if that could cause any issues

**Comment by pannal** [comment]
Can you post your Python script here? And can you try calling `/usr/bin/python3.6 -c "print 'hello'"` from your .sh file?

Also an echo inside your sh file would help to see whether it gets executed properly.

**Comment by Psycoguana** [comment]
Ok, I've done the changes to the .sh file, now in the logs I get:
`Calling /home/psyco/Programming/Python/Sub_cleaner/test.sh with arguments: []`
`Process output: test.sh called :)`

Calling from the terminal also gets me the output of print('hello')

I'm calling the python script with the next line, but I thinks it's correct:
`/usr/bin/python3.6 /home/psyco/Programming/Python/Sub_cleaner/menu.py --auto`

[Here](https://drive.google.com/file/d/1yw1YX--GpbrIEDP6NlTVnJN_RuYAXPcy/view?usp=sharing) I uploaded my script (spoiler alert, it's the first thing I ever wrote so the code it's awful)

**Comment by pannal** [comment]
Can you post your `test.sh` in its current state as well?

**Comment by Psycoguana** [comment]
Sure

```
#!/bin/sh

/usr/bin/python3.6 /home/psyco/Programming/Python/Sub_cleaner/menu.py --auto

/usr/bin/python3.6 -c "print('hello')"
echo 'test.sh called :)' 
```

**Comment by pannal** [comment]
And if you comment out the `echo` part, is "hello" printed?

If not, can you add "echo `/usr/bin/python3.6 -V`"?

**Comment by Psycoguana** [comment]
In the shell it is printed, in the logs it's an empty output.

Adding the line you asked me gets me this:
`Process output: Python 3.6.7`

**Comment by pannal** [comment]
This might still be a PATH issue. Is there anything inside your `log.txt`? Can you issue a `find / --name "log.txt"`?

**Comment by pannal** [comment]
Also `python3.6 -c "import os; print(os.path.abspath("."))"` might shed some light on this

**Comment by Psycoguana** [comment]
It's currently empy, 

> This might still be a PATH issue. Is there anything inside your `log.txt`? Can you issue a `find / --name "log.txt"`?

Is that a shell command or should I put it in the .sh file?

**Comment by pannal** [comment]
Shell command

**Comment by pannal** [comment]
Also are you sure this isn't a permission issue? Does the PMS user have access to write to the log file?

**Comment by Psycoguana** [comment]
The find command is still running, if you need it I'll dump the whole content once it's over, these are the only lines regarding user files tho:
```
find: ‘/home/psyco/.cache/dconf’: Permiso denegado
/home/psyco/.cache/go-build/log.txt
/home/psyco/log.txt
/home/psyco/Programming/Python/Sub_cleaner/log.txt
find: ‘/home/psyco/.dbus’: Permiso denegado
/home/psyco/.config/Jackett/log.txt
find: ‘/home/psyco/.config/enchant’: Permiso denegado
/home/psyco/.config/libreoffice/4/user/uno_packages/cache/log.txt
/mnt/datos/Games/The Legend of Zelda Breath of the Wild/cemu/log.txt
find: ‘/mnt/datos/Users/Psycoguana/Videos/Series/Bob's Burgers S01-S06 Collection [1080p WEB-DL HEVC:x265]’: Error de entrada/salida
```


The abspath is: /home/psyco/Programming/Python/Sub_cleaner

I'm not sure how to check the permissions PMS has, I assumed that wasn't an issue because every file inside this dir looks like this `-rwxrwxrwx 1 psyco psyco    215 mar 17 01:02  test.sh`

**Comment by pannal** [comment]
OK, but your python file definitely gets executed, right? As you were able to print `os.environ` inside your test script.

What was the output of `python3.6 -c "import os; print(os.path.abspath("."))"`?

**Comment by Psycoguana** [comment]
You mean when I call the .py file from the test.sh using the shell? Yes, it does. 
SZ  can run a .sh file, and python code inside it. But it doesn't execute code inside a .py file, even if it's called from the .sh.

The output of the abspath command was `/home/psyco/Programming/Python/Sub_cleaner`

**Comment by Psycoguana** [comment]
Running groups plex gives me:
`plex : plex video`

Could that be important?

**Comment by pannal** [comment]
> Running groups plex gives me:
> `plex : plex video`
> 
> Could that be important?

Might be, not sure. 

> You mean when I call the .py file from the test.sh using the shell? Yes, it does.
> SZ can run a .sh file, and python code inside it. But it doesn't execute code inside a .py file, even if it's called from the .sh.

Are you sure? Did you try creating a new .py file just containing 
```
import os
print(os.environ)
```
and calling it from your .sh, and setting the .sh as your notification executable?

**Comment by Psycoguana** [comment]
I created a new .py file containing
`print("This works")`

I called it from the .sh, which then I ran from a terminal and printed just fine.

Later I made SZ call the .sh file, which it did, but the output was empty.

**Comment by pannal** [comment]
Can you post the .sh and the .py that were used, please?

**Comment by Psycoguana** [comment]
test.py
```
print("This works")
```
test.sh
```
#!/bin/sh
/usr/bin/python3.6 test.py
```

BTW, I also tried just running test.py with SZ, which also gave me a blank output

**Comment by pannal** [comment]
Can you try [this branch](https://github.com/pannal/Sub-Zero.bundle/tree/%23626_env_test)? It has a little more debug logging.

**Comment by Psycoguana** [comment]
I'm having a weird issue, Sub-Zero.bundle is not in:
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins`

I didn't know that was possible, I tried moving the folder from the new branch anyway, but when I restarted Plex it got deleted. I also can't delete the plugin from Plex

**Comment by Psycoguana** [comment]
Hey, I was able to replace it. Now I get a much more detailed log :)
Trying to directly run a python file gets me this:
```
Calling /usr/bin/python3.6 with arguments: [u'/home/psyco/Programming/Python/Sub_cleaner/test.py']
Executable: /usr/bin/python3.6 /home/psyco/Programming/Python/Sub_cleaner/test.py, Env: {'PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR': '/var/lib/plexmediaserver/Library/Application Support', 'PLEX_MEDIA_SERVER_TMPDIR': '/tmp', 'PYTHONDONTWRITEBYTECODE': '1', 'PLEX_MEDIA_SERVER_HOME': '/usr/lib/plexmediaserver', 'LOGNAME': 'plex', 'USER': 'plex', 'HOME': '/var/lib/plexmediaserver', 'PATH': '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'es_AR.UTF-8', 'SHELL': '/bin/bash', 'PLEXBUNDLEDEXTS': '1', 'U1pfT01EQl9LRVk': '789CF30DAC2C8B0AF433F5C9AD34290A712DF30D7135F12D0FB3E502006FDE081E', 'PLEXSERVERPORT': '32400', 'LIBVA_DRIVERS_PATH': '/usr/lib/plexmediaserver/dri', 'INVOCATION_ID': '58317956931444a398ef2d5d68bf7a82', 'PLEXLOCALAPPDATA': '/var/lib/plexmediaserver/Library/Application Support', 'PLEXTOKEN': 'bfUyjizqWi1EwYKzb8A2', 'JOURNAL_STREAM': '9:508491', 'PYTHONHOME': '/usr/lib/plexmediaserver/Resources/Python', 'LANGUAGE': 'es_AR:es', 'PWD': '/', 'SZ_USER_AGENT': 'Sub-Zero/2.6.4.2934-dev', 'PLEXBUNDLEDPLUGINSPATH': '/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476', 'PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS': '6'}, Exe_info: (u'/usr/bin/python3.6', [u'/home/psyco/Programming/Python/Sub_cleaner/test.py']), Output: , Errors: Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```

And trying to run it from the .sh file gets me pretty much the same
I tried to do `sudo dpkg-reconfigure python3` but it solved nothing.

I added "import encodings" to the test.py and succesfully runned it from the terminal with both python and python3.6 so I don't think my python installation is the problem

**Comment by ukdtom** [comment]
STRONGLY suggest you eedit your post @Psycoguana annd remove the token from it ;)

**Comment by ukdtom** [comment]
And disregard...
Found out I had the powers to scarmble it ;)

**Comment by Psycoguana** [comment]
I don't know why, but I felt like leaving it there, I randomly changed some letters tho. Thanks anyway :)

**Comment by pannal** [comment]
@Psycoguana you definitely want your plugins inside `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins` and not inside the system plugin folder.

As for your issue: I think this is the culprit:
```
'PYTHONHOME': '/usr/lib/plexmediaserver/Resources/Python'
```

I'll remove that env var and push an update to the branch.

**Comment by pannal** [comment]
@Psycoguana pushed the fix to the branch.

**Comment by Psycoguana** [comment]
Yeah, I have no idea why I moved it there, all my other plugins where in the /var/lib/...
It's where it's supposed to be now.

I'll update the plugin and let you now

**Comment by Psycoguana** [comment]
It's working now! Kinda, but good enough :)

If I run the .sh file it runs the python script perfectly, after I get `, Errors:`, but the script worked just fine.

Trying to directly call the python script gives me a permission error trying to write the log.txt, I got that from the shell as well once and then never again, but it may be a problem in my end. 

Anyway, I consider this fixed so I'll close the issue. Thanks a lot for the patience, you've been super helpful!

**Comment by pannal** [comment]
Great! I'll merge the changes to the develop-2.6 branch.

You should switch to the next stable release once it's out, because then you'll get automatic updates. Currently you're in Dev mode which is exempted from those.

**Comment by Psycoguana** [comment]
Oh, good to know. I'll keep an eye on it! Should I change to the develop-2.6 branch meanwhile?
