### ISSUE TITLE
Subzero doesn't download subtitle [logs included]

### ISSUE THREAD

**Issue by thu3n** [pannal/Sub-Zero.bundle#629]
Got a issue, with subzero. I switched plexserver and forgot to copy my subzero settings and had to start over with my settings, all fine now. But it doesn't download/find any subtitles... Can't read any of the logs. 

Agent is on, and i have also followed the guide in here from scratch only so that i can say with confidence that i have subzero configuerd correct. 

Log: https://drive.google.com/file/d/1stbbTkv6H0sdy1Bm_9S69HNrMKkq6yxQ/view?usp=sharing

**Comment by pannal** [comment]
This is a bug that'll be fixed with the upcoming version. #619
