### ISSUE TITLE
Subtitles in middle of screen

### ISSUE THREAD

**Issue by wills11** [pannal/Sub-Zero.bundle#638]
I'm incredibly uneducated in all of this, so forgive me if it's a silly question, but...

Using the Plex plugin, the subtitles appear in the dead center of the screen.

How do I control where onscreen (vertical & horizontal position) the subtitles appear?

Thanks so much!

**Comment by pannal** [comment]
This is not related to Sub-Zero. The positioning of your subtitles are done by your client.

**Comment by pannal** [comment]
Which Plex client are you using?

**Comment by wills11** [comment]
Thanks so much for your replies!

Web Client with Safari, Version 3.95.2

Here's the thing, other subtitles work fine—in other words, .srt files embedded in videos which are listed under "Streams".

It's only the ones Sub-Zero downloads and places in the folder that are in the center (and they don't show up under "Streams" with the videos).

**Comment by pannal** [comment]
Well, that's still a client issue. SZ doesn't have any ability to change the way subtitles are displayed.

**Comment by pannal** [comment]
https://forums.plex.tv/t/subtitles-appear-in-the-middle-of-the-screen/175221

**Comment by wills11** [comment]
Thanks so much for your help, but I'm a little lost—all I want to do is to be able to play videos with subtitles using Plex, and nothing seems to work.

1.  All .srt subtitles muxed in my videos play out of sync in Plex but are in the correct bottom-center screen position (the subtitles sync perfectly when these same videos are played in VLC, Quicktime, and other players).

2. The Sub-Zero plugin downloads the correct subtitle and plays it in sync—but in the center of the screen. (And when I mux the Sub-Zero .srt files with the video files, they then play out of sync in VLC and other players).

There's definitely something different in the way Plex handles muxed .srt subtitles than the .srt files Sub-Zero downloads. The first play out of sync in the correct position, and can be seen in the "Streams" of muxed videos. The second play in sync but are not shown in the "Streams" of the videos, and I don't know how to turn them on or off. When Sub-Zero downloads .srt files for already-muxed videos, and I select the muxed one in "Streams", BOTH subtitles appear, one synced but in the center, the other out-of-sync at the bottom.

**Comment by wills11** [comment]
And yes, under "Settings" for "Web Player" I have the correct position selected—but when I play the videos, previously muxed subtitles play as in the settings, while the Sub-Zero downloaded .srt files located in the folder play in the center of the screen. This is also true when using the Roku Plex App.

**Comment by wills11** [comment]
Here's what that looks like:


<img width="977" alt="Screen Shot 2019-04-27 at 19 22 14" src="https://user-images.githubusercontent.com/50034410/56856119-f2ceff00-6921-11e9-8c14-59d8cf92491d.png">

**Comment by wills11** [comment]
I see this is closed—I'll try posting a new question, more broadly.

Thanks!

**Comment by pannal** [comment]
This is really out of scope for this project. I'm sorry, but I can't help your with this.
