### ISSUE TITLE
Addic7ed don't found tv show

### ISSUE THREAD

**Issue by ptoutain** [pannal/Sub-Zero.bundle#639]
Hello,

Since couple of mounths, addic7ed don't find any TV shows even this show exists.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3126343/com.plexapp.agents.subzero.log)

For example, i have this stack strace on logs.
2019-04-27 09:39:38,639 (7fbbecff9700) :  ERROR (logger:34) - subliminal.providers.addic7ed: No show id found for u'Game of Thrones' ({'year': 2011})

**Comment by pannal** [comment]
Addic7ed has implemented CAPTCHA before access to shows. Please have a look [here](https://github.com/pannal/Sub-Zero.bundle#changelog) and [here](https://forums.plex.tv/t/rel-sub-zero-2-6-5-3017-subtitles-done-right/118396/2846?u=panni).

**Comment by pannal** [comment]
This should have been fixed with one of the recent releases. Please reopen if not.
