### ISSUE TITLE
Unable to get subtitle in Traditional Chinese

### ISSUE THREAD

**Issue by mu2004** [pannal/Sub-Zero.bundle#645]
In OpenSubtitles.org, the Traditional Chinese has a file designation of CHT.srt, where in Plex .zh.srt is used. For some reason, when searching manually in OpenSubtitles.org I can see the Traditional Chinese srt files listed, but using Sub-Zero with Traditional Chinese always finds nothing. If the second language in Sub-Zero is configured to be Chinese, it will then find a .zh.srt file that is always encoded with unreadable characters (on Mac.)

So there are two problems really: 
1. Traditional Chinese subs aren't found
2. Chinese subs .srt aren't readable on Mac

The example I used is Aquaman.2018.1080p.BluRay.x264.mp4

Manually downloading the cht.srt (traditional Chinese) from OpenSubtitles website always works.

The question is, what country code does Sub-Zero use when Traditional Chinese is selected, when the API is talking to OpenSubtitles? CHT.srt is the commonly used file extension, but it's not part of any standards. Would that be the reason why Traditional Chinese subs are never found?

**Comment by pannal** [comment]
Please supply DEBUG logs (set SZ's logging verbosity to DEBUG).
