### ISSUE TITLE
subscene

### ISSUE THREAD

**Issue by mehdi198080** [pannal/Sub-Zero.bundle#647]
after recent subcene update SZ can't find any subtitle in this provider,please check

**Comment by pannal** [comment]
This will be fixed with the upcoming maintenance release. Subscene have changed their search endpoint.

**Comment by FevLoad** [comment]
could you provide ETA not that I want to rush you but so we can know when to aspect it
thank you for your hard work.

**Comment by pannal** [comment]
Yeah, they've changed it again (this was fixed for a week?). Fixed again
