### ISSUE TITLE
When srt file downloaded with Sub-Zero is deleted from system, srt is still displayed in Plex

### ISSUE THREAD

**Issue by Dr0bac** [pannal/Sub-Zero.bundle#648]
I download 3 languages with subzero: Serbian, Serbian-Latin, Croatian
After sub-zero download subtitles i want to check them quickly with vlc to see if subtitles are ok.
When i notice bad subtitles i delete them from file system, Plex notice that Movie folder content is changed, and i get spinning circle on movie poster but that subtitle stays in menu.
And if i try to watch a movie and that subtitle stays active, movie will not start..

If i delete manually downloaded srt file, Plex register that and delete it from Plex Movie menu.

And i see that Plex recently introduced that i can delete srt file from Movie menu in Web client, and if i delete subtitle that is downloaded with sub-zero, srt will be deleted in movie folder, but it will again stays in menu, then after i delete it again, it will disappear from menu.

Edit - I made two videos that explain what i'm talking about

Manually downloaded subtitles

![manual](https://user-images.githubusercontent.com/43797966/58385276-fbccf200-7fed-11e9-967d-c42307e2e55f.gif)

Subtitles downloaded with Sub-Zero

![subzero](https://user-images.githubusercontent.com/43797966/58385278-0be4d180-7fee-11e9-89e3-e66475299744.gif)

Edit 2 - When i toggle sub-zero option to store subtitles to metadata, then i can't delete these subtitles

![Untitled](https://user-images.githubusercontent.com/43797966/58386867-3d699700-8006-11e9-9a39-9a904b48d756.png)

**Comment by pannal** [comment]
That's hardly an SZ issue tbh.

Do you have any DEBUG logs? It might be that SZ just re-writes or re-downloads the subtitle, as it seems like that the SRT-removal-via-GUI issues a metadata refresh (re-triggering SZ).

**Comment by Dr0bac** [comment]
On the right side of gif's there is file system window..you can see that subtitle files are deleted immediately.i don't think that deleting something trigger refresh metadata, it happens also when i delete subtitle from windows file system. Subtitles that i puted manually in movie folder are gone in plex after deletion, if i delete sub- zero subtitles, i get uknown subtitle in plex after that.. do you want sub-zero logs or plex logs.. i will try everything again after i turn on debug logging

**Comment by pannal** [comment]
Sub-Zero logs for now are enough. You can get them from the Advanced menu in the SZ channel. 
The logging needs to be set inside SZ's settings itself ("How verbose should the logging be?", at the bottom of the list)

**Comment by Dr0bac** [comment]
first, here is a gif for you to see what happen in plex when i delete sub-zero .srt files from file system.

![ezgif com-crop](https://user-images.githubusercontent.com/43797966/58504236-6d41a780-818a-11e9-8754-a9038a1bffe4.gif)

Next, here are logs

[Logs_190528_20-30-52.zip](https://github.com/pannal/Sub-Zero.bundle/files/3229240/Logs_190528_20-30-52.zip)

At 20:24 i deleted subtitles from plex directly

At 20:26 refreshed metadata (and sub-zero downloaded new subtitles)

At 20:28 deleted .srt files from file system

**Comment by pannal** [comment]
Interesting. As SZ isn't called directly by your actions, apart from the metadata refresh, I'd hand this over to the Plex guys for now, actually.

SZ uses the Plex functions to reference local subtitle files.
