### ISSUE TITLE
Subtitle that will force subzero to find new subtitles

### ISSUE THREAD

**Issue by Dr0bac** [pannal/Sub-Zero.bundle#649]
Now with plugins (channels) missing from plex clients, maybe we can be creative with how we tell subzero to force find better subtitles.

Can subzero create custom subtitle file, that when we choose it from plex while watching movie to force find better subtitles. Maybe subzero can detect that custom .srt file is loaded with plex api? I guess subzero can't name subtitle "find new subtitles" but we can choose how that subtitle is named in subzero settings, i guess english subtitle or something? I was thinking if subzero can detect when movie is played if there is no subtitles for movie it can start finding them, it can also then somehow detect that custom subtitle is enabled while playing movie.  

With that way we can transfer some tools from channel menu into movie subtitle menu. Users usually go to subzero channel to force refresh (find better subtitles)

**Comment by pannal** [comment]
Sadly neither functionality isn't really exposed or possible to implement :(
