### ISSUE TITLE
French Sub issue

### ISSUE THREAD

**Issue by Non0o** [pannal/Sub-Zero.bundle#650]
Hi ! 

I followed the tutorial displayed here on github, set up the config with my addicted and opensubtitle login. 

Everything seems to work, but i only get English subtitles (langage n°2 in my conf), and no french subtitles (langage n°1). 

I tried to change options a lot in subzero, i have rebooted subzero and PMS many times, even try to delete manually EN srt files in folders to see if that change something and still at the same point : lot of EN subs, but no french subs. 

Can anyone please help me ? don't know what do do or even try anymore :-(

THank you !

**Comment by pannal** [comment]
Please supply your SZ logs (see wiki)

**Comment by Groumy** [comment]
Based on the providers you configured, there might simply be no french subtitles. 

Also I had to lower the `Minimum score for TV` to be able to get some in my case.
