### ISSUE TITLE
Sub-Zero's subliminal CLI "standalone"

### ISSUE THREAD

**Issue by SeBayne** [pannal/Sub-Zero.bundle#651]
Hello,

First thank you for this great plugin!!

I'd want to know if there's a way to use directly the Sub-Zero's subliminal CLI as it would be done with the original one.
The library here is way more up-to-date than in the first Subliminal project and I'd need to use it as a standalone tool...

Thanks in advance!

**Comment by pannal** [comment]
Not really? You could write your own CLI and import `subliminal_patch`.

There currently are no plans to separate `subliminal_patch` from Sub-Zero. It has been detached for years and I don't want to support it seperately.
