### ISSUE TITLE
Subtitle font fat

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#654]
I'm not sure what is causing some of my subtitles to be too thick, is it sub zero or the plex player in my nvidia shield itself? When I play the same media file in the Plex web, it has different fonts. Could Sub Zero do anything with the subtitle font thickness?

**Comment by pannal** [comment]
Nope, SZ doesn't add its own font styles, and SRT doesn't support different fonts.

It's most likely the player that causes this.
