### ISSUE TITLE
Sub Zero doesn't download subtitles

### ISSUE THREAD

**Issue by DhooreBE** [pannal/Sub-Zero.bundle#656]
Since last week the Sub Zero plug-in does't work anymore for me. It can some some simple named movies like Avatar (2009) but it can't find things like Star Wars, The 5th Wave. It used to do this before. I rename my files using Filebot and enabled this in the settings. Also when i enable the setting to place my subtitles in a folder together it doesn't work with any movies.

Logs:

[Logs_190715_14-39-10.zip](https://github.com/pannal/Sub-Zero.bundle/files/3392307/Logs_190715_14-39-10.zip)

**Comment by pannal** [comment]
It doesn't seem to be called at all judging by your logs. Did you try a reinstall of the plugin and/or restarting the PMS?
