### ISSUE TITLE
Honor docker network aliases

### ISSUE THREAD

**Issue by EnorMOZ** [pannal/Sub-Zero.bundle#657]
When using in a docker infrastructure sub-zero will not allow you to use the docker network aliases of radarr/sonarr. It seems like the url field wants to do a DNS lookup each time. When using the alias it wont resolve. This helps  with dynamic container ips to resolve to the correct container each time. Also helpful when running containers on localhost.

`  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 351, in patched_create_connection
    ip = custom_resolver.query(host)[0].address
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/dns/resolver.py", line 1051, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
NXDOMAIN: The DNS query name does not exist: radarr`

**Comment by pannal** [comment]
This will be fixed with the upcoming release; in the meantime: Just set the SZ DNS to "system", that should solve the issue.

**Comment by EnorMOZ** [comment]
Changing it to "system" worked
