### ISSUE TITLE
SRT subs being downloaded even when MOV_TEXT subs are already present

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#662]
As requested, I'm creating a ticket for the issue I described in this [post](https://forums.plex.tv/t/rel-sub-zero-2-6-5-3124-subtitles-done-right/118396/2909?u=kevindd992002).

Here are the PMS debug logs: https://www.dropbox.com/s/giaovh9hh1fn1uf/Plex%20Media%20Server%20Logs_2019-08-16_11-22-02.zip?dl=0 

Is it normal that the SubZero channel is no longer present in the latest PMS version (the revamped one)? I have agent+interface set in my SubZero settings.

The episode that I refreshed is "Suits S08E07: Sour Grapes".

**Comment by pannal** [comment]
Hey, I can't see the SZ log in your zip, did you include the "PMS Plugin Logs" folder?

> Is it normal that the SubZero channel is no longer present in the latest PMS version (the revamped one)? I have agent+interface set in my SubZero settings.
Yes. See #655

**Comment by kevindd992002** [comment]
Sorry, I didn't realize that the Downloads Logs button inside Plex doesn't include the plugin logs. I just followed the "Manual" link in this [article](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs). Here you go: https://www.dropbox.com/s/fx0eb2twk5peko3/PMS%20Plugin%20Logs.zip?dl=0

**Comment by kevindd992002** [comment]
As for the plugin channels being deprecated from the Plex UI, don't you maintain a docker container (in Docker Hub) for Kitana so that I can simply add it to my docker compose yml file? I'm not an experienced Linux Docker user so I only have all my containers created automatically using docker compose.

**Comment by pannal** [comment]
> Don't you have any docker compose usage instructions for that though? I'm not an experienced Linux Docker user so I only have all my containers created automatically using docker compose.

Not really, no. Kitana doesn't need much, though, apart from one exposed port.

**Comment by pannal** [comment]
Can you refresh an item in question (with MOV_TEXT), wait a minute, then post your logs? Also please tell me which item I'm supposed to look for.

**Comment by kevindd992002** [comment]
Ok, I refreshed "Suits S08E07: Sour Grapes" again and here are the logs:

Plex logs: https://www.dropbox.com/s/zgohdtt8nohfgv2/Plex%20Media%20Server%20Logs_2019-08-18_12-03-35.zip?dl=0
PMS Plugin logs: https://www.dropbox.com/s/rd8cela7dii9160/PMS%20Plugin%20Logs.zip?dl=0

**Comment by kevindd992002** [comment]
@pannal , just following up on this?

**Comment by pannal** [comment]
Hmm, I can't see S08E07 being refreshed in your latest log. I think you did that while SearchAllRecentlyAddedMissing task was running, so the logs are full of that.

I've changed a couple of things in the latest develop-2.6 branch, regarding embedded and external subs. Can you try again with the current develop-2.6?

**Comment by pannal** [comment]
Ah, I've just found it.

Judging from the logs, it doesn't download any SRT, but extracts the MOV_TEXT embedded one into an SRT file. You can disable automatic extraction in the settings.

> DEBUG (__init__:147) - Skipping embedded subtitle extraction for 2634, already got <Language [en]> from stream_3

**Comment by kevindd992002** [comment]
But why would there be multiple MOV_TEXT and only one SRT usually? 

Which is better between embedded and external SRT subs anyway?

**Comment by pannal** [comment]
> But why would there be multiple MOV_TEXT and only one SRT usually? And are you referring to this setting: "Automatically extract and use embedded subtitles upon media addition (with configured default mods)"? If so, I wouldn't want to disable that because, if I understand correctly, the embedded subs will be extracted and the default mods applied, correct?

Correct.

> Which is better between embedded and external SRT subs anyway?

That fully depends on your playback device. There's no clear answer here.

**Comment by kevindd992002** [comment]
Ok. For multiple MOV_TEXT subs, which will SZ extract and convert to SRT? Is there a way to make the SRT the default sub for a certain release?

**Comment by pannal** [comment]
> For multiple MOV_TEXT subs, which will SZ extract and convert to SRT?

The first one found with the necessary specs (language, forced/not-forced).

> Is there a way to make the SRT the default sub for a certain release?

Not really. That's completely up to Plex.

**Comment by kevindd992002** [comment]
Ok, gotcha. Thanks for the help!

**Comment by kevindd992002** [comment]
@pannal , just following up on this please?
