### ISSUE TITLE
New installation: Can not open the Interface

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#663]
I have installed sub-zero on a new Plex server.

I can click the cog and enter the Settings but I can not open the Interface.

I have tried different browsers.

Regards

Michael

**Comment by pannal** [comment]
Duplicate of #655

**Comment by pannal** [comment]
You can try accessing the PMS locally (not via plex.tv), the interface might still be there. Also if you're using the new-style Plex Web interface, Plugins might be gone. I think you can change back to the old style.
