### ISSUE TITLE
New upload but don't download subtitles

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#664]
Sonarr has uploaded Killjoys S03E02 with embedded PGS subtitles.

I would like SZ to extract the embedded subtitles and if not possible because og wrong format, download an external subtitles.

If you search for S03E02 in the attached log you can see this debug near the end of the log:

2019-08-19 15:48:31,824 (15391df15700) :  DEBUG (scanning:80) - Detecting streams: /media/TVShows/Killjoys/Season 03/Killjoys - S03E02 - A Skinner, Darkly Bluray-1080p.mkv, external_subtitles=True, embedded_subtitles=True

It says "external_subtitles=True"

Does that mean that SZ thinks there already is a subtitles for the new uploaded Killjoys S03E02?

If you look at the attached PMS screendump you can see that there are two PGS, but no external subtitles.

If you look further to the end of the attached log it says:

2019-08-19 15:48:34,227 (15391df15700) :  INFO (download:121) - Killjoys - S03E02 - A Skinner, Darkly Bluray-1080p.mkv has missing languages: set([<Language [en]>])

Does that means that SZ now download a subtitles for the new Kiljoys S03E02?

Because that is not true. There is still not any external subtitles for Kiljoys S03E02.

- - - - 

I have waited 1/2 hour. Still no subtitles.

I go into PMS and do a Refresh Metadata and a few seconds later SZ has downloaded a subtitles.

2019-08-19 16:19:30,409 (15394cbbe700) :  INFO (download:121) - Killjoys - S03E02 - A Skinner, Darkly Bluray-1080p.mkv has missing languages: set([<Language [en]>])

Maybe you can see from the log why SZ don't download the subtitles after Sonarr has uploaded it, but it works after a Refresh Metadata.

Regards

Michael
![PMS - Killjoys S3E2](https://user-images.githubusercontent.com/45288008/63273543-78decf00-c29e-11e9-88bf-cdfd2b4ddf21.PNG)
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3516326/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
There actually was a bug which I was able to find using your logs. When Plex triggered a refresh on multiple items, there was the possibility that items with missing subtitles wouldn't trigger a download.

**Comment by pannal** [comment]
You can try the latest develop-2.6

**Comment by cphmichael** [comment]
I have installed Sub-Zero 2.6.5.3137 DEV.

This morning at 7:06 I received "Men in Black International"

When I looked in Plex there was no internal or external subtitles.

At 11:05 I did a Refresh Metadata and received an External subtitles.

I could be that there was no subtitles available at 7:06 but it was there at 11:05 and therefore SZ was not able to find any subtitles.

Or i could be that the same error as before still is there.

I have attached the two log-file so you can figure out if there still is a problem.

Regards
Michael

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3533850/com.plexapp.agents.subzero.log)

[com.plexapp.agents.subzero.1.log](https://github.com/pannal/Sub-Zero.bundle/files/3533854/com.plexapp.agents.subzero.1.log)

**Comment by pannal** [comment]
Yep, `2019-08-23 07:06:28,531 (152c84350700) :  INFO (logger:30) - subliminal_patch.core: Downloaded 0 subtitle(s)`. All good now :)

**Comment by cphmichael** [comment]
So the reason SZ didn't download a subtitles at 7:06 was that the subtitles was not available at that time, but is was there when I Refresh Metadata at 11:05?

**Comment by pannal** [comment]
Yes, there were subtitles available, but the quality/match-score wasn't high enough.

**Comment by cphmichael** [comment]
In the top of the settings there is an option "Download subtitles" where I can select Never or Always.

Is that an on/off switch for SZ?

If I select Never - SZ will not download any subtitles under any circumstances.
If I select Allways - Then SZ will download subtitles according to the setup in the settings

Maybe the setup guide needs an update with all the new improvement you have made :-)

**Comment by pannal** [comment]
You'll understand what the `Download subtitles` switch is all about when you look at the other options in there. It's related to the available audio streams inside a media file.

If you for example don't want subtitles when an audio stream is English, you'd use one of the other settings. If you don't want SZ to decide based on audio streams, set it to "Always".

**Comment by pannal** [comment]
That feature has been added a while ago, but the guide hasn't been updated for that.

**Comment by cphmichael** [comment]
Thank you for the explanation :-)

Can I ask you about "Don't search for subtitles if a subtitle in any configured language exists as"

If I set that as "External subtitles" does that means, that if there is an external .srt file, then SZ exit any further processing for that movie/series?

no searching for subtitles, no searching for better score etc.

**Comment by pannal** [comment]
Exactly. At least that's what it's supposed to do.

**Comment by cphmichael** [comment]
I am setting it to Always and watch how it behave.

I think SZ sometime get confused if there is an external subtitles and Sonarr upgrades from WEBDL to Bluray.

I would like SZ to extract the new Blueray subtitles but SZ think there already is a subtitles and therefore exit the extraction.

**Comment by pannal** [comment]
Yeah I know that issue; Sonarr/Radarr have to explicitly call a refresh on that item, instead of Plex handling the filesystem change. In case Plex handles it, it won't call SZ necessarily.
