### ISSUE TITLE
New upload but don't download subtitles (movie)

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#666]
Radarr has uploaded John Wick: Chapter 3 – Parabellum with included Italiano (PGS) and 
Romana (SRT), but SZ do not download external subtitles.

From the SZ menu I click on Recently-added items, Movies, John Wick, List English subtitles, Search for English subs

I get a list saying ‘Available: opensubtitles, score: 95’

In SZ I have set ‘Minimum score for movies = 95’

In PMS I have ‘Refresh Metadata’ but I still get no subtitles.

You can see the refresh in the attached log at:

2019-08-30 12:16:43,866 (14984298a700) :  DEBUG (__init__:170) - Sub-Zero 2.6.5.3137 DEV, movies search

Regards

Michael
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3559753/com.plexapp.agents.subzero.log)

![Plex - John Wick](https://user-images.githubusercontent.com/45288008/64018520-f58a6c80-cb2c-11e9-80f3-825677c7196f.PNG)

![Opensubtitles - score 95](https://user-images.githubusercontent.com/45288008/64018548-02a75b80-cb2d-11e9-83b7-bb6b864cb67b.PNG)

![SZ language](https://user-images.githubusercontent.com/45288008/64018663-544fe600-cb2d-11e9-9e4a-6f705faaa31c.PNG)

![SZ settings](https://user-images.githubusercontent.com/45288008/64018670-587c0380-cb2d-11e9-9756-81c8177578e9.PNG)

**Comment by pannal** [comment]
This should be fixed in current develop-2.6.

**Comment by cphmichael** [comment]
I am running Sub-Zero 2.6.5.3137 DEV that fixed the TV series problem.

Have you uploaded a newer version?

**Comment by cphmichael** [comment]
I did another refresh, but still no subtitles.

I then clicked on ‘Force-find subtitles’ and now SZ downloaded the subtitles.

The description says “Issues a forced refresh, ignoring known subtitles and searching for new ones”.

Can you see in the log if SZ thinks there already is a known subtitles, and that is the reason why it won’t download another one?

As you can see from the screen dump of the settings I have ticked:

* Don’t search for subtitles of a language if there are embedded subtitles inside the media file.
* Don’t search for subtitles of a language if they already exist on the filesystem

So if SZ thinks there already is a subtitles, then SZ won’t download another one, but will do it when I issues a forced refresh.

**Comment by pannal** [comment]
develop-2.6 is at 2.6.5.3141 as of today :)

Please try that one. I've explicitly fixed your bug.

**Comment by pannal** [comment]
And yes, force-find ignores existing languages, which circumvents the bug with the older version.

**Comment by cphmichael** [comment]
Today John Wick was upgraded to a 4K version with included PGS, and SZ downloaded an external subtitles.

I think you have solved the problem :-)

Thank you very much for your help :-)

![dev-3141](https://user-images.githubusercontent.com/45288008/64112282-46959d00-cd87-11e9-8374-07dee8101a4d.PNG)
