### ISSUE TITLE
Cannot find proper Chinese subtitles from assrt.net

### ISSUE THREAD

**Issue by Masterbaiter** [pannal/Sub-Zero.bundle#671]
I tried with 2 different settings on 2 movies.

First I use "chinese(similified)" and "chinese(traditional)" as my subtitle language, for the movie "Ghost in the shell 2: innocence", SZ downloaded 2 incorrect subtitle files, 1 labeled "chinese simplified" but actually in english, the other labeled "Chinese traditional" but is for a different ghost in the shell movie. 

I then use "Chinese" only for my primary language, tried it on the movie "Liz and the blue bird", this time it does not find any subtitle and do not download at all. 

upon checking the log it appears to me that the ISO-639-1 code does not reflect correctly on the site assrt.net? not sure if that's the case though. 

Will this be fixed or is there a workaround? Attached is the full log.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3586714/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
I'm on vacation right now. I've already received reports that assrt is problematic at the moment with SZ. I'll have a look once I'm back :)

**Comment by pannal** [comment]
Hmm, judging from your logs this isn't really fixable. Can you provide an example where SZ actually picks the wrong subtitle? (E.g.: Where you can pick the right subtitle by hand)

Please supply logs

**Comment by pannal** [comment]
Please reopen with logs
