### ISSUE TITLE
Prevent overwrite Extracted Embedded Subtitles from task "Find better subtitles"

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#673]
I saw in #672 that you talked about Advanced Settings.

I was not aware about this possibility, so I got curious and looked it up in the wiki.

I the Advanced Settings I read this option: 
* When the find better subtitles task finds a subtitle for an item that has an active extracted embedded subtitle set, what should be the minimum score that subtitle has to have in order to be considered better?

Does the scheduled “Find better subtitles” task, overwrite the Extracted Embedded Subtitles?

 I want to keep the Extracted Embedded Subtitles, so I have ticked the settings:
* Don’t search for subtitles of a language if there are embedded subtitles inside the media file.

Does that prevent the “Find better subtitles” task, from overwriting the Extracted Embedded Subtitles?

Regards

Michael

**Comment by pannal** [comment]
I've just looked through the code (on holiday right now an very limited in terms of coding capacity).

The embedded switch is only taken into account when actually scanning the media file. The findBetter task doesn't do that. Instead it looks at what it already has.

To achieve what you want you'd want to set `Scheduler: Overwrite manually selected subtitles when better found` to False, and/or the second option for manually modified subs to False as well. 

Extracted embedded subtitles are automatically set to "manual" subtitles internally.

Alternatively you can set the minimum score for extracted subs for findBetter inside advanced settings to something ridiculously high (it already is, at 352 and 82). Something it would never be able to match would be 369 for TV and 120 for movies).

**Comment by pannal** [comment]
Great question btw, glad to still see people that are actually caring enough to think about SZ's wildly complex settings. Bazarr will soon be where SZ is in terms of features.

**Comment by cphmichael** [comment]
Thank you for taking your time to look in to the code when you are on holiday :-)

Would you recommend me to change to Bazarr?

Is the settings easier to understand and is the "Periodically search for recent items with missing subtitles" working in Bazarr?

SZ works pretty well for me, so I am a little afraid of changing to a new system that I first have to learn to understand and maybe implement new bugs.

Are you planning to stop maintain SZ and instead focusing on Bazarr?

**Comment by pannal** [comment]
No I won't stop maintaining SZ as long as plugins are possible inside the PMS. This might change with the deprecation of Python 2.7 next year - depending on how Plex Inc. decides to handle that.

Bazarr uses SZ's core, the modified subliminal_patch library. I keep that one up to date in Bazarr's codebase as well.

I think there are still a couple of features that SZ provides (refresh on playback, subtitle modifications), but Bazarr is getting there. Also SZ is very set-and-forget nowadays.

So no clear answer for you there.

**Comment by cphmichael** [comment]
Thank you for your answer.

I like SZ and the great support, so I will stick to SZ :-)

Regards

Michael
