### ISSUE TITLE
@felho001 please don't highjack others' tickets.

### ISSUE THREAD

**Issue by felho001** [pannal/Sub-Zero.bundle#674]
@felho001 please don't highjack others' tickets. 
Your answer is in #655

_Originally posted by @pannal in https://github.com/pannal/Sub-Zero.bundle/issues/670#issuecomment-532144797_

**Comment by felho001** [comment]
ok but how can do this on synology nas?

**Comment by felho001** [comment]
Ok im done and work perfect thx

**Comment by pannal** [comment]
Great that it works now! Any special steps you took, someone else might benefit from knowing?

**Comment by felho001** [comment]
Nothing special I run docker on synology and serch pannal/kitana download instal and after sign in my ip:31337 port sign in plex.tv id and it work perfeckt

**Comment by pannal** [comment]
Great, thank you!
