### ISSUE TITLE
Problem playing extracted SRT subtitles

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#675]
This is a continuation to https://github.com/pannal/Sub-Zero.bundle/issues/662

@pannal I just noticed that for some files with embedded subtitles that get extracted to SRT because I have this setting enabled, my Plex media players (on different clients) don't play the subtitles at all. As a workaround, I need to manually choose one of the MOV_TEXT subs. So why won't the SRT (which is from the MOV_TEXT subs) work but the actual MOV_TEXT does?

**Comment by pannal** [comment]
Can you attach the original MOV_TEXT and the resulting SRT?

**Comment by kevindd992002** [comment]
Well the MOV_TEXT is embedded. Do I need to extract that manually as MOV_TEXT then?

**Comment by pannal** [comment]
Hmm, maybe attach the SRT first. It should be possible to extract the MOV_TEXT from the mp4, but I'm on holiday right now and don't have my tools.

**Comment by kevindd992002** [comment]
Sure. here you go.[https://www.dropbox.com/s/kst7y1e38snhm0y/Money%20Heist%20-%20S01E08%20-%20Episode%208%20%5BWEBDL-1080p%20Proper%20-%20SKGTV%5D.srt?dl=0](url)

**Comment by viking1304** [comment]
This is whole subtitle:

```
1
00:00:06,040 --> 00:00:11,760
<font color="#ffffff">junkyard closed
no trespassing</font>

2
00:00:34,800 --> 00:00:35,680
<font color="#ffffff">corpulent</font>

3
00:00:35,760 --> 00:00:37,960
<font color="#ffffff">assailant
woman?</font>

4
00:00:40,560 --> 00:00:41,880
<font color="#ffffff">the professor?</font>

5
00:02:14,600 --> 00:02:17,240
<font color="#ffffff">sunday</font>

6
00:02:25,480 --> 00:02:28,640
<font color="#ffffff">the negotiation between inspector murillo
and the thieves was leaked</font>

7
00:02:43,080 --> 00:02:45,880
<font color="#ffffff">50 hours since the heist</font>

8
00:07:56,320 --> 00:08:00,320
<font color="#ffffff">spanish, second-Class citizens</font>

9
00:15:07,440 --> 00:43:46,358
<font color="#ffffff">personal information
andrés de fonollosa</font>

```

**Comment by kevindd992002** [comment]
Ok, so I'm assuming that that was the one SZ extracted from the file.

**Comment by viking1304** [comment]
Do you have more subs in your video or just one? Can you post screenshot with your subtitle choices?

**Comment by kevindd992002** [comment]
I have two MOV_TEXT's in this video and one external SRT file. Here's a screenshot of its MediaInfo:

![image](https://user-images.githubusercontent.com/3907957/65295557-60f7b500-db94-11e9-8742-63e6fd361cda.png)

**Comment by kevindd992002** [comment]
Anyone?

**Comment by kevindd992002** [comment]
@pannal ?

**Comment by pannal** [comment]
I can't really test this, as you've got a converted mp4 file from the original mkv release. Is it possible for you to hit me up on Slack so I can get that exact file?

**Comment by kevindd992002** [comment]
> 
> 
> I can't really test this, as you've got a converted mp4 file from the original mkv release. Is it possible for you to hit me up on Slack so I can get that exact file?

Oh ok. Do you have Discord instead? If not, let me know and I can setup Slack (I've never tried it).

**Comment by pannal** [comment]
I do, can you get me your DiscordTag?

**Comment by kevindd992002** [comment]
Sure, it's 4180.

**Comment by kevindd992002** [comment]
@pannal , what's your DiscordTag? I'm in the GMT+8 timezone so I would think that we're several hours apart, if you're in the US.

**Comment by pannal** [comment]
You should have a friend requests on Discord

**Comment by pannal** [comment]
This was due to a badly tagged MOV_TEXT subtitle and Plex not detecting the `Title` property of the MP4 file. Can't fix for now, reported.

**Comment by pannal** [comment]
SZ can use mediainfo now, as an intermediate solution, for retrieving the missing stream titles.

**Comment by kevindd992002** [comment]
I was able to install mediainfo in my Plex docker container and will just be waiting for the upcoming version of SZ for the fix. Will you close this thread when the new version comes out?

**Comment by kevindd992002** [comment]
@pannal Is this fixed in the current version?

**Comment by pannal** [comment]
Yes, it's in the changelog:
`core: support using mediainfo for retrieving MP4 MOV_TEXT subtitle stream titles (PMS bug)`

**Comment by kevindd992002** [comment]
Which means that mediainfo should always be installed in my Plex docker container for this to work, correct?

**Comment by pannal** [comment]
Yep
