### ISSUE TITLE
Issue installing plug-in: Error starting framework core

### ISSUE THREAD

**Issue by nrgbistro** [pannal/Sub-Zero.bundle#677]
I cannot get Sub-Zero to successfully install. I've tried following the steps in installation instructions but when I restart the plexmediaserver, it says: sh[8052]: Error starting framework core for /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle

I'm very much a noob at this and I don't understand why it isn't initializing correctly...

**Comment by pannal** [comment]
Please set
```<key>PlexPluginConsoleLogging</key>
        <string>0</string>
``` to 1 in `Contents/Info.plist` inside `Sub-Zero.bundle`, then restart your PMS (or use `/usr/sbin/start_pms`, which might show stuff in stdout)
