### ISSUE TITLE
Stripping or ignoring embedded subtitles from mkv files. 

### ISSUE THREAD

**Issue by andrewe1** [pannal/Sub-Zero.bundle#68]
A lot of times embedded subtitles are useless or can't even be displayed in other devices that run plex.
They created useless entries in the subtitle drop down menu. 

It would be really useful to have plex strip or at least ignore all of these embedded or integrated subtitles.

**Comment by pannal** [comment]
The ignoring won't be possible, but the stripping *may* be.

**Comment by AquaRelliux** [comment]
Yea this would be great just to remove those ugly none working subs! Is it possible to just make Plex not show them on movies maybe?

**Comment by BrutuZ** [comment]
You mean never show subtitles by default? This can be set server-side on "Server > Settings > Languages > Mode: Always Show > Prefer subtitles in: None" and/or your Plex.tv Account preferences. It may feel odd to set "Always show none" instead of a "Never show" option but such are the ways of Plex.

Sorry if I misunderstood your question.

**Comment by andrewe1** [comment]
No, I was referring to the embedded subtitles that come with some mkv
files. They show in the drop down subtitle menu for each file. Sometimes
they don't even work, especially the ones that say PGS.

**Comment by andrewe1** [comment]
Here's a clear example:

http://i.imgur.com/8Gtmi3H.png

**Comment by BrutuZ** [comment]
I see, the "problem" is their presence in the list. If it's not a lot of files and they're embedded subtitles it would probably be easier to remux the file yourself with a tool like [MKVToolNix](https://www.bunkus.org/videotools/mkvtoolnix/downloads.html) to strip out the subtitle streams. Is a pretty straightforward process.

**IMHO** allowing an agent to save a single srt file beside the video files is ok, but letting it edit the media itself sounds a little bit concerning to me.

**Comment by pannal** [comment]
This is out of scope.
