### ISSUE TITLE
CRITICAL (runtime:1128) - Exception in thread named 'extract_embedded_sub' (most recent call last)

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#681]
After I created issue #680 I clicked "Extract stream 2" in Kitana, but after waiting 30 sec. there was no external subtitles and Kitana still says "No current subtitles in storage".

I took a new look in the SZ log and there are errors, so I hope that give you a hint about what is wrong :-)

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3697130/com.plexapp.agents.subzero.log)

![kitana](https://user-images.githubusercontent.com/45288008/66311090-f2458600-e90d-11e9-8e8d-fd35b5b443b8.PNG)

**Comment by pannal** [comment]
Yeah well, it's not clear to SZ how it should extract that subtitle. You don't have `Embedded streams: Treat "Undefined" (und) as language 1` on, right?
It can't really store a subtitle without the language attribute.

**Comment by cphmichael** [comment]
I have just checked, and this option is on.

![settings](https://user-images.githubusercontent.com/45288008/66312879-b2809d80-e911-11e9-999b-d80e46398f96.PNG)

**Comment by pannal** [comment]
Can you try the latest develop-2.6 and see whether that fixes your issue?

**Comment by cphmichael** [comment]
2.6.5.3152 DEV solved the .ASS problem for Mr. Robot  :-)

So you found an error in the code?

Before I changed to the new DEV, Sonarr uploaded Succession S2E09 with embedded .ASS

SZ was able to extract the subtitles for this one. So something must be different between the embedded .ASS for Mr. Robot and Succession.

I think your fix solved 680 and 681

**Comment by pannal** [comment]
I guess the embedded subtitle in Succession had a language tag set.

**Comment by cphmichael** [comment]
As you can see on the attached screen dump, Succession also says Unknown (ASS)

I received Succession yesterday but I first installed your fix this morning, so it is strange that SZ was able to extract the .ASS subtitles for Succession but not Mr. Robot.

But now you have fixed the Mr. Robot problem, so maybe it is not so interesting to use time to find the reason why it worked :-)

![pms succession](https://user-images.githubusercontent.com/45288008/66389555-f5ea1300-e9c8-11e9-91b1-2fe1f3ce6ede.PNG)

![succession](https://user-images.githubusercontent.com/45288008/66389578-01d5d500-e9c9-11e9-8e59-1b3f7b8baac6.PNG)

**Comment by pannal** [comment]
It seems like I didn't properly push the last fix. Can you try again?

**Comment by cphmichael** [comment]
I have installed 2.6.5.3161 DEV, but SZ has extracted the embedded .ASS since 2.6.5.3152 DEV, so I can not test the changes you have made to the new DEV version.
