### ISSUE TITLE
Embedded subtitle #678 + some download problame

### ISSUE THREAD

**Issue by trox88** [pannal/Sub-Zero.bundle#683]
Hello @pannal 

The problame is the same after SZ update to the latest release.
I also upgraded PMS to the latest version, Kitana to 0.1.9.
After these restarted SZ ->
![rest](https://user-images.githubusercontent.com/55915414/66713016-89df2480-eda5-11e9-9c30-1bb9332239d1.PNG)

Also deleted SZ bundle in plex plugin folder manually, and install again with latest release.
My previous report is #678 
I have changed the layout language to english so I've made other screenshots.

![sz1](https://user-images.githubusercontent.com/55915414/66712994-2ce36e80-eda5-11e9-9d68-cf7c46a43fd1.PNG)
![sz2](https://user-images.githubusercontent.com/55915414/66712995-2ce36e80-eda5-11e9-9a39-6723b7b0514a.PNG)
![sz3](https://user-images.githubusercontent.com/55915414/66712996-2ce36e80-eda5-11e9-916d-b13e3cce4ff3.PNG)
![sz4](https://user-images.githubusercontent.com/55915414/66712997-2ce36e80-eda5-11e9-8fa8-7454955132a4.PNG)
![sz5](https://user-images.githubusercontent.com/55915414/66712998-2ce36e80-eda5-11e9-8743-35686a2ddf9f.PNG)
![sz6](https://user-images.githubusercontent.com/55915414/66712999-2d7c0500-eda5-11e9-9445-69281918f380.PNG)
![sz7](https://user-images.githubusercontent.com/55915414/66713000-2d7c0500-eda5-11e9-969d-0f0a32f03dcc.PNG)

I tried with a new added movie but nothing changed, doesn't extract automatically forced embedded sub with default mods. 
![emb1](https://user-images.githubusercontent.com/55915414/66713093-77191f80-eda6-11e9-896d-ca5d06c16a67.PNG)
![emb2](https://user-images.githubusercontent.com/55915414/66713094-77191f80-eda6-11e9-912d-697445d1b1f1.PNG)
![emb3](https://user-images.githubusercontent.com/55915414/66713095-77191f80-eda6-11e9-9165-5fd0d0499db2.PNG)
![emb4](https://user-images.githubusercontent.com/55915414/66713096-77191f80-eda6-11e9-8359-44815514fe89.PNG)
![emb5](https://user-images.githubusercontent.com/55915414/66713242-7b463c80-eda8-11e9-9c42-ba60307e66e0.PNG)

Download problame:
Yesterday I released that some of my series doesn't have downloaded subtitle, 
for example Legacies is fine and downloaded automatically but for Supernaturals it doesn't find subtitle, but it has already 2 days in supersubtitles.com, I tried to run another periodic search but the reason is nothing, but I can find it manual of course.
Maybe my settings are wrong can you check it please?

![sub1](https://user-images.githubusercontent.com/55915414/66713201-cd3a9280-eda7-11e9-8275-d6d416254791.PNG)
![sub2](https://user-images.githubusercontent.com/55915414/66713202-cdd32900-eda7-11e9-975e-d84c1b228006.PNG)
![sub3](https://user-images.githubusercontent.com/55915414/66713203-cdd32900-eda7-11e9-9847-212a26cd613c.PNG)
![sub4](https://user-images.githubusercontent.com/55915414/66713204-cdd32900-eda7-11e9-9e5a-9bccac6b4595.PNG)

**Comment by pannal** [comment]
OK, this is a configuration issue.

You've got `Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?` enabled, so the automatic portion of SZ doesn't search for subtitles in that case. Of course you can find them when searching manually.

You've set `Download subtitles` to `When any audio stream is not any configured language` - the audio stream matches the configured language (Magyar), so it won't extract or search for any subtitle here.

You've set `Download foreign/forced subtitles` to `Never`, so forced subtitles won't be extracted, even if there are some.

You need to set:
`Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?` = False
`Download foreign/forced subtitles` = `Always` or `Only for Subtitle Language (1)`

**Comment by trox88** [comment]
Thank you for your particular, I'll check it and let you know about the reasons

**Comment by pannal** [comment]
Option 1 will not search for subtitles for any language if any subtitle exists for a language, no matter whether it's forced or not.
Option 2 will do the same, but existing forced subtitles don't count.

**Comment by trox88** [comment]
Yes as I see everything works well for me, thank you for your help!
