### ISSUE TITLE
Not auto-downloading or auto extracting subtitles, but works manually.

### ISSUE THREAD

**Issue by dyinggit** [pannal/Sub-Zero.bundle#687]
I noticed sub-zero isn't auto downloading subtitles or extracting embedded subtitles but it works if I use Kitana and look manually select subtitles.

I noticed these errors in my log, but also attached the log. Thank you in advanced for looking into this.
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3741830/com.plexapp.agents.subzero.log)

CRITICAL (core:574) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.5.3152)', called with guid 'com.plexapp.agents.thetvdb://343337?lang=en' (most recent call last):

ERROR (logkit:22) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):

ERROR (logkit:22) - subliminal.providers.tvsubtitles: No show id found for u'Riverdale' ({'year': 2017})

**Comment by pannal** [comment]
Can you try the latest develop-2.6 branch? It should be fixed there.

**Comment by dyinggit** [comment]
develop-2.6 worked. thanks!
