### ISSUE TITLE
Mr Robot subtitle files break SZ's external subtitle detection

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#688]
I have installed 2.6.5.3174 DEV.

Sonarr uploaded Mr. Robot S04E03, but SZ did not extract the embedded .SRT.

This time Kitana has listed Mr. Robot in Recently added > TV Shows

In the attached log.1 I can see this:

2019-10-21 11:09:04,721 (15024a3fe700) :  CRITICAL (agentkit:1091) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.5.3174 DEV)', called with guid 'com.plexapp.agents.thetvdb://289590?lang=en' (most recent call last)

I hope that can help you to see what the problem is :-)

[SZ.zip](https://github.com/pannal/Sub-Zero.bundle/files/3751086/SZ.zip)

![Sonarr - History](https://user-images.githubusercontent.com/45288008/67210529-8ab52d80-f419-11e9-8848-913bec0a6a6b.PNG)

![PMS - English SRT](https://user-images.githubusercontent.com/45288008/67210589-a3254800-f419-11e9-90d7-f9902140ffa0.PNG)

![Kitana](https://user-images.githubusercontent.com/45288008/67210620-ac161980-f419-11e9-9a4f-5f808053d806.PNG)

![Kitana - Mr Robot](https://user-images.githubusercontent.com/45288008/67210629-afa9a080-f419-11e9-9f27-2b76428eebb3.PNG)

**Comment by pannal** [comment]
`LanguageReverseError: u'gz'` - What the heck is "gz"? That's not a valid language code.

Argh: `Mr. Robot - S03E02 - eps3.1_undo.gz.mkv`

**Comment by pannal** [comment]
You can try latest develop-2.6

**Comment by viking1304** [comment]
> `LanguageReverseError: u'gz'` - What the heck is "gz"? That's not a valid language code.
> 
> Argh: `Mr. Robot - S03E02 - eps3.1_undo.gz.mkv`

All Mr. Robot episodes have file extensions or linux commands in their names. This episode name is 'eps3.1undo.gz'

**Comment by cphmichael** [comment]
Than you for your very quickly reply :-)

At 16:48, before upgrading to your latest develop-2.6, I did a Refresh Metadata from PMS, and this time SZ extracted the embedded subtitles for Mr. Robot.

Isn't that strange, because if it is the filename that confused SZ, then it should still not be able to extract the embedded subtitles when I did the refresh?

Her is the log where you can see the refresh:

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3751993/com.plexapp.agents.subzero.log)
