### ISSUE TITLE
Something wrong with Sub-Zero (Supersubtitles provider)

### ISSUE THREAD

**Issue by Dolphine80** [pannal/Sub-Zero.bundle#689]
Hi Everyone,

I get this error regularly but I don't know why. :(

> 2019-09-25 16:15:15,731 (7f82e6b1f0) : ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'supersubtitles': Traceback (most recent call last):
> File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
> results = self[provider].list_subtitles(video, provider_languages)
> File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 364, in list_subtitles
> subs = self.query(title, video=video)
> File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 263, in query
> subtitle = self.process_subs(series, video, url)
> File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 318, in process_subs
> sub_season = int((re.findall(r"(?<=- ).*?(?= - )", str(sub_english))[0].split('x')[0]).strip())
> IndexError: list index out of range

Some subtitles are downloaded, some are not and I don't know why. :(

**Comment by Dolphine80** [comment]
Today morning:

> 2019-10-28 07:44:26,857 (7f70ce11f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:44:27,669 (7f70ce11f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:44:28,252 (7f70ce11f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:44:28,895 (7f70ce11f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'H264-TBS'
> 2019-10-28 07:44:33,189 (7f70ce11f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:44:59,310 (7f4bd111f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:44:59,823 (7f4bd111f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:45:00,368 (7f4bd111f0) :  ERROR (logger:38) - subliminal_patch.core: Cannot parse language code u'x264-AVS'
> 2019-10-28 07:45:09,557 (7f4bd111f0) :  CRITICAL (__init__:275) - Something went wrong when saving subtitles (most recent call last):
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 273, in update
>     mods=config.default_mods)
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 201, in save_subtitles
>     save_subtitles_to_file(downloaded_subtitles)
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 129, in save_subtitles_to_file
>     debug_mods=config.debug_mods, formats=config.subtitle_formats, tags=tags)
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 867, in save_subtitles
>     with open(subtitle_path, 'w') as f:
> IOError: [Errno 13] Permission denied: u'/volumeUSB1/usbshare/Download/Series/The Blacklist/Season 07/The.Blacklist.S07E04.720p.HDTV.x264-AVS.srt'

Permission denied?! Why?!

**Comment by pannal** [comment]
I'll have a look at the first one. I'd need full DEBUG logs, though (set SZ verbosity to DEBUG at the bottom of the settings).

The second one I can't help you with. SZ runs as the user that runs the Plex Server. Obviously there's something wrong with your permissions.

**Comment by Dolphine80** [comment]
Did you think of this?
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3778223/com.plexapp.agents.subzero.log)

I think I added all permission to Plex. What else to need?
![Plex_Permission](https://user-images.githubusercontent.com/57061666/67672299-ec284f80-f977-11e9-8813-d79940055eda.jpg)

**Comment by pannal** [comment]
`IOError: [Errno 13] Permission denied: u'/volumeUSB1/usbshare/Download/Series/Supergirl/Season 05/Supergirl.S05E03.720p.HDTV.x264-AVS.srt'` - you definitely have permission issues.

Nothing I can do here :(

**Comment by Dolphine80** [comment]
How is it possible? Same directory, same permissions. 
![Plex_Subzero_NAS](https://user-images.githubusercontent.com/57061666/67688144-ac725f80-f999-11e9-9516-e45fa163cc1c.jpg)

**Comment by viking1304** [comment]
Have you checked actual permissions for every folder that you have a problem with?

Go to edit folder and you should see something like this:
![image](https://user-images.githubusercontent.com/28989870/67688930-e4c66d80-f99a-11e9-9ba3-d3a4c8b55abb.png)

Make sure you have write privilege set for every folder where you need to download sub.

**Comment by Dolphine80** [comment]
Of course! 
![Plex_NAS](https://user-images.githubusercontent.com/57061666/67697591-180ff900-f9a9-11e9-86bf-a7a48706a579.jpg)

**Comment by viking1304** [comment]
You need to check permissions for **every single** problematic folder, not plex itself.

`IOError: [Errno 13] Permission denied: u'/volumeUSB1/usbshare/Download/Series/Supergirl/Season 05/Supergirl.S05E03.720p.HDTV.x264-AVS.srt'`

In this case, you need to check **Season 05** folder inside **Supergirl** folder.

**Comment by Dolphine80** [comment]
> I tried something I hope I succeeded.
> In some cases, writing privileges were not granted to the group and others. Now I did that. I'll see if everything's okay.
> ![Plex_NAS_Permission](https://user-images.githubusercontent.com/57061666/67699419-64a90380-f9ac-11e9-9819-abab2d80aa42.jpg)

It"s working! 👍 
Thank you so much for help! 👏
