### ISSUE TITLE
Subtitle files Empty (0 octet)

### ISSUE THREAD

**Issue by clementTymate** [pannal/Sub-Zero.bundle#690]
Hello,

I just moved my plex to a Debian server and since I reinstalled Sub-Zero in the Plugins Folder and set up everything like before I got a problem with my subtitles.
It seems like it download the subtitles but the files are empty.

Is there a folder or something else that I should give permission to write in order to have subtitles working ?
Because every time I choose those empty subtitles files, the encoding on plex side failed.

<img width="1190" alt="Capture d’écran 2019-10-28 à 10 50 18" src="https://user-images.githubusercontent.com/53896462/67668715-c77ca980-f970-11e9-9ace-76395181b33d.png">

**Comment by pannal** [comment]
I'd need a full DEBUG log (set SZ's verbosity to DEBUG, at the bottom of its settings) to tell you what's wrong. It's most likely permissions, yes.

**Comment by clementTymate** [comment]
[Plex Media Server Logs_2019-10-28_21-54-12.zip](https://github.com/pannal/Sub-Zero.bundle/files/3780813/Plex.Media.Server.Logs_2019-10-28_21-54-12.zip)

@pannal Thanks for your response. Here are my plex logs.

I hope it's the right thing, you can check for the subtitles of the good place wich are the one that I try to get through Sub Zero

**Comment by clementTymate** [comment]
[Logs_191028_22-10-40.zip](https://github.com/pannal/Sub-Zero.bundle/files/3780857/Logs_191028_22-10-40.zip)

**Comment by pannal** [comment]
I can see nothing wrong in the logs at first glance. SZ properly writes the files to disk, and receives no error from the operating system.

Is every sub 0 bytes? Do you have any special Filesystem layers?

**Comment by clementTymate** [comment]
Every new sub is 0bytes. I'll try to do a lot of force refresh and so on tomorrow and give you the logs.  Thank you for your help. This project is a bomb.

By the way, my hard drive is mount when my Debian is launch. Should I specify some permission for Plex to the library folder ?

**Comment by clementTymate** [comment]
@pannal 
CRITICAL (__init__:275) - Something went wrong when saving subtitles (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 273, in update
    mods=config.default_mods)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 201, in save_subtitles
    save_subtitles_to_file(downloaded_subtitles)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 129, in save_subtitles_to_file
    debug_mods=config.debug_mods, formats=config.subtitle_formats, tags=tags)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 867, in save_subtitles
    with open(subtitle_path, 'w') as f:
IOError: [Errno 13] Permission denied: u'/media/freebox/Serie/Watchmen.S01E02.Martial.Feats.of.Comanche.Horsemanship.720p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.en.srt'


I found that on my logs, what should I do ?

**Comment by pannal** [comment]
Check that the user the Plex Server runs as has full access to your media folders.
I can't really help you there :/
