### ISSUE TITLE
OSX: unrar needs to be set executable

### ISSUE THREAD

**Issue by tvebax** [pannal/Sub-Zero.bundle#693]
I had this error repeatedly in my subzero log file:

```
#1679 | 2019-11-03  22:54:16,636 (70000319d000) :  DEBUG (config:335) - custom check failed  for: /Users/lumiere/Library/Application Support/Plex Media  Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/MacOSX/i386/UnRAR/unrar
-- | --
#1680 | 2019-11-03 22:54:16,701 (70000319d000) :  DEBUG (config:335) - custom check failed for: unrar
#1681 | 2019-11-03 22:54:16,702 (70000319d000) :  WARNING (config:345) - UnRAR not found
```

unrar is installed on my system and correctly included in environment path both globally and for my logged in user. So, I did not get how this error message was there. Until I read the log lines more closely and realised that the unrar file within subzero is not a script to check for unrar as I had assumed. It is an additional unrar executable which subzero insists on using, ignoring the system unrar.
Problem is, the "subzero specific" unrar file is not set to be executable:

```
$ ls -lah /Users/lumiere/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/MacOSX/i386/UnRAR/
total 640
drwxr-xr-x  3 lumiere  staff   102B Oct 26 05:18 ./
drwxr-xr-x  3 lumiere  staff   102B Oct 26 05:18 ../
-rw-r--r--  1 lumiere  staff   319K Oct 26 05:18 unrar
```

So. Now it makes perfect sense subzero is complaining.

I ran:
`$ chmod ug+x /Users/lumiere/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/MacOSX/i386/UnRAR/unrar`

This fixes the issue. Verified error messages are gone from logs.
But unless fixed within subzero, it likely needs redoing manually on each subzero update.

**Comment by pannal** [comment]
Did you download the zip instead of a direct check-out of the repository? The flags are correctly set.

**Comment by pannal** [comment]
You can try the latest develop-2.6 branch. It sets the executable permissions explicitly.

**Comment by tvebax** [comment]
Thanks! 

I just changed the permissions manually, hoping it sticks across updates. It's a year or 2 ago since I installed sub-zero, it seems to update itself.

The post here was mainly to let you and others know. I've seen several report the same error message. Might help them save some time debugging / help you fix.

Thanks again for making sub-zero, it's awesome :)

**Comment by pannal** [comment]
You're welcome. If you want to try the develop-2.6 branch and see whether it works, that'd be awesome.
