### ISSUE TITLE
No UI anymore?

### ISSUE THREAD

**Issue by tvebax** [pannal/Sub-Zero.bundle#694]
I no longer have a UI for subzero. Luckily sub-zero works so well it is not explicitly needed, but I kinda miss it. I am aware that Plex changed (limited) plugin support heavily. Is this a side effect of that? How do I get a UI again? Possible?

I might be entirely out of the loop and this has been asked and answered a million times. I have tried searching the wiki, FAQ, reddit and issues in this issue queue. No luck.
Reading through the issue queue on another topic, it seems other users still have a UI though?

I do not have a channels entry in my plex menu and yes, channel mode is enabled in subzero. Logs confirm this:
`#101 | 2019-11-03 12:41:46,386 (7fff8c07f380) :  DEBUG (menu:382) - config.enable_channel: True`

I do have a plugins entry in plex settings menu, which takes me to a screen on a /channel path, with subzero listed, looking exactly as it always did, when the plugins menu item was located in the main Plex menu.
The broken part is that the subzero item is not longer clickable. There is no link to go to, only a background image, the settings pop-up button and the remove plugin button:
<img width="954" alt="Plex" src="https://user-images.githubusercontent.com/42374813/68093261-fbd1f780-fe93-11e9-87af-89975bb5f21c.png">

Is that just how it is, or is there something I can do?

**Comment by ukdtom** [comment]
It's a side affect, but @pannal made a workaround

See: https://github.com/pannal/Kitana

And follow up there
