### ISSUE TITLE
Subtitles not downloading

### ISSUE THREAD

**Issue by Lukajjza** [pannal/Sub-Zero.bundle#695]
Okay so after trying many many things I still can't figure out while it's not working. I tried changing multiple settings and read many posts and FAQ etc. But still the sub-zero not downloaded single subtitles.

Log: https://pastebin.com/k83zvwm8

**Comment by pannal** [comment]
Please set SZ's log level to DEBUG (lowermost setting of Sub-Zero; `How verbose should the logging be?`), then post your log again.

**Comment by Lukajjza** [comment]
It is. Did you read the log?

**Comment by pannal** [comment]
Yes, there's almost nothing in it. Can you try refreshing an item from PlexWeb, then attaching the log?

Did you install SZ in the proper folder?

**Comment by Lukajjza** [comment]
From what I'm reading it's now searching for subtitles for one of my movies.

https://pastebin.com/vUYKMi1y

**Comment by Lukajjza** [comment]
Also SZ is in: plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/

**Comment by pannal** [comment]
Yeah, the log looks fine. You have titlovi enabled without an API username/password, though.
Opensubtitles seems to work.

**Comment by Lukajjza** [comment]
Well like I said I think it searched so far only for Joker subtitles? But I have one more movie in my library (Scarface) and about 10 TV shows which it didn't find single subtitles. (for ex. Arrow, Riverdale, Mr Robot, The Walking Dead)

**Comment by pannal** [comment]
Yes. You need to read the Wiki.

SZ doesn't automatically search for subs for your whole library. It reacts to new items being added and has a couple of periodic scheduled tasks that search for recently added items with missing subtitles.

You can refresh the metadata for a whole library to trigger SZ. You will run into provider limts, though, so it might take a couple of days and multiple refreshes to search for all your items.

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q2-im-running-the-plugin-for-the-first-time-and-want-to-have-subtitles-for-all-of-my-old-items

**Comment by Lukajjza** [comment]
I read most of the wiki, FAQ etc... Like I said in the first post. I refreshed metadata and also scanned whole library few times now over the few days I have SZ and like I'm saying it's not downloading any subtitles for my TV Shows. Also for example the last episode of Arrow aired and was downloaded when I had SZ installed already so it should download the subtitles automatically right?

**Comment by pannal** [comment]
It should yes.

From your logs I can see that you didn't enable SZ for your TV libraries, though: `DEBUG (config:663) - I'm enabled for: ['Movies']`

**Comment by Lukajjza** [comment]
Oh, but you enable it in the Agents settings right? I think I have it set correctly...?

https://imgur.com/a/sbHKsoK

**Comment by pannal** [comment]
Hmm weird, yes. Your library settings are properly set to TheTVDB as well?

**Comment by Lukajjza** [comment]
Holy, this actually might be the fault. I feel so dumb now, it wasn't set to TVDB.

**Comment by Lukajjza** [comment]
I somehow broke my plex now and it's being weird so I'll try to fix it and see tomorrow if it helped and eventually close this issue if it really was the cause, which I believe it was, but we'll see, thanks.
