### ISSUE TITLE
Sub-zero not saving information and minor renaming issue

### ISSUE THREAD

**Issue by Escondido** [pannal/Sub-Zero.bundle#699]
I have minor issues that I cannot figure out how to fix. This is on a brand new dedi with the latest version of plex installed. 

-I accidentally added a url base to the sonarr configuration area and when I try to remove it somehow it repopulates with the original after saving. 

-I'm unable to save a value lower than the default 337 for "Minimum score for TV" That also reverts after saving. 

-Final issue is that when I manually search for an English subtitle using Kitana, the file isn't correctly formatted. 

Should be= tv show.en.srt
Actual= tv show.srt

I'm not sure if that's a Sub-zero or Kitana issue. 

I checked permissions for the plugin-in and everything seems fine. I also restarted sub-zero using Kitana. The issues persist. I'm not sure if there is anything that can be done except reinstalling the plugin.

**Comment by pannal** [comment]
> -I accidentally added a url base to the sonarr configuration area and when I try to remove it somehow it repopulates with the original after saving.

Do you use a credential manager such as LastPass or Bitwarden? It probably saved the input fields. Try using an incognito window.

> -I'm unable to save a value lower than the default 337 for "Minimum score for TV" That also reverts after saving.

240 is the lower clamped value. See above.

> -Final issue is that when I manually search for an English subtitle using Kitana, the file isn't correctly formatted.

Kitana ist just a frontend. You probably have `Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)")` enabled.

**Comment by Escondido** [comment]
Both solutions worked perfectly. Thanks for the help.
