### ISSUE TITLE
What is the fastest way to see the output of all variables in python

### ISSUE THREAD

**Issue by saitoh183** [pannal/Sub-Zero.bundle#709]
Basically i want to see what i have to use in my script if i want to upload the sub with rclone to my gdrive into the propose location.

**Comment by saitoh183** [comment]
nvm figured something out

**Comment by ukdtom** [comment]
Thanks for sharing :(

**Comment by pannal** [comment]
Well, [this wiki page](https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#advanced-configuration) has all the available variables, which you can simply include.

**Comment by saitoh183** [comment]
> Thanks for sharing :(

Sorry I forgot to add what I did. I used python but an easier method is to just put all the variable you want output for in the post-processing field. Maybe with some indications.. for example:

subpath : %(subtitle_path)s

Then check the SZ log for a line staring with the word Calling. Then you will see what the variable represents.
