### ISSUE TITLE
Possible improvement download 720p subs for 1080p movies

### ISSUE THREAD

**Issue by AquaRelliux** [pannal/Sub-Zero.bundle#71]
Hello I have noticed that sometimes there are no subs for 1080p movies but there are for 720p movies with the same release. Example SPARKS releases, the 720p subs work fine for 1080p movies but they are not downloaded with Sub-Zero. Can this be fixed so that it ignores the quality? Since this is very inrealivant for the subtitle to work

**Comment by pannal** [comment]
Could you please provide a log where the resolution didn't match and SZ didn't download *any* matching subtitle for your file? It shouldn't do that.

The feature request, to treat 720p exactly like 1080p when the group matches, it's a good idea.

**Comment by AquaRelliux** [comment]
I have several examples, I dont know to get the logs but I could post examples of movies/tv shows that does not work for me? Pretty much every single instance of SPARKS releases in 1080p does not download the correspodning sub in 720p

**Comment by pannal** [comment]
Nope. I need logs. In the README there's a short instruction on how to get your logs. If that still doesn't help you, please ask in the forum thread. (Also linked in the README)

**Comment by AquaRelliux** [comment]
I noticed why the problem occours, the movies come with burnt in subs. Sub-Zero does not download additional subs then. The problem is that the burnt in subs are HI and I really don't want that on my subs.

**Comment by pannal** [comment]
You mean embedded internal subtitles? (Embedded in the .mkv or .mp4 file)
That's intended default behaviour and can be controlled by the "Scan: include embedded subtitles" option.

If you disable it, SZ will ignore the embedded subs and search for new externals.

Is that option not clear enough? Do we need to clarify it? If so, please make suggestions!

**Comment by AquaRelliux** [comment]
I like your helpful tone! I think that the problem is that the embeeded subtitles can't be distinguished if they are HI or non-HI? In my case all my embeeded subs are HI and therefor SZ does not download additional subs. I want it to skip downloading if the embeeded sub are non-HI and download if it is. And also it would be nice if it could tell me if a subtitle contains HI elements! I understand this may be a very hard problem to solve?

**Comment by pannal** [comment]
I don't know whether you mean your first sentence :P (I wasn't trying to be rude)
Generally, I leave "Scan: Include embedded subtitles" off, I'm with you there, most of the time embedded subs are horrible and can cause problems with playback clients.

Maybe I'll turn it off as a default for the next release.

Would it help you if i rename the option or improve the documentation for it? Did you understand at first what the option was about?

As for detecting HI/non-HI, I'll look into it. But as far as how badly most embedded subtitles are tagged (many don't even have the language set), I doubt that would help anyone.

**Comment by AquaRelliux** [comment]
I am always very serious when I write these comments, I mean every word I wrote! And regarding the documentation I really did not read it fully so that might be way I missed that detail :P embeeded subs really seems to suck, default option in my opinion should always ignore them who wants horrible subs!

**Comment by pannal** [comment]
OK, so changing the setting name to "Scan: ignore embedded subtitles" wouldn't make things better I suppose? (That would do the opposite, but would alert someone while reading it I think)

**Comment by pannal** [comment]
Next version will ignore embedded subs by default.
