### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by saitoh183** [pannal/Sub-Zero.bundle#710]
So I set the option in SZ to allow all and i assumed the next fiel was to put the libraries I want to ignore. But when I go into Kitana, in all items I see all the libraries except for my movie library and 2 other movie based library... I don't understand what Im doing wrong

**Comment by saitoh183** [comment]
Any help on this?

**Comment by pannal** [comment]
I don't understand your initial post.

**Comment by saitoh183** [comment]
i have 7 Libraries

Anime, TV, Movies , Movies 4k, FrenchTV and French Movies. kids-tv

I add all except  TV, Movies , Movies 4k to the ignore list and when i go in Kitnana, i only see this in Browse all

![image](https://user-images.githubusercontent.com/1534197/73130259-0dbec480-3fc3-11ea-9990-4867cf2803ba.png)

**Comment by saitoh183** [comment]
@pannal I opened another ticket thinking this one was closed #716
