### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by saitoh183** [pannal/Sub-Zero.bundle#716]
So i checked in Kitana and under all Items im missing libraries. I have restricted nothing in the SZ settings.

My Library
https://snipboard.io/J1Tn2E.jpg

Kitana
https://snipboard.io/LmZAzg.jpg

I dont know what to do to get them to appear

**Comment by pannal** [comment]
Please post your log zip

**Comment by saitoh183** [comment]
@pannal 
[SZ_logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/4234041/SZ_logs.zip)

**Comment by pannal** [comment]
Please restart the plugin, then re-post the logs.

**Comment by bbros7** [comment]
I have the same issue.
My libraries: https://snipboard.io/oW974c.jpg
Showing by SZ: https://snipboard.io/IaJhV1.jpg

My logs (just restarted the plugin): 
[Logs_200603_22-08-28.zip](https://github.com/pannal/Sub-Zero.bundle/files/4726901/Logs_200603_22-08-28.zip)


@pannal, some additional information:
1) When I play some item from the "missing" library, I do see it on "Recently played" menu (see here: https://snipboard.io/A4tUBf.jpg and after navigating thru it: https://snipboard.io/cLxJSh.jpg)
2) The "missing" libray is the only one I use Absolute Series Scanner + HamaTV (don't know if it's related to the issue)

**Comment by bbros7** [comment]
I just figured out what was wrong here. I had not configured the SZ for my "missing" library agent. 😅

**Comment by pannal** [comment]
@saitoh183 please check your agent config, otherwise reopen. Thanks @bbros7
