### ISSUE TITLE
Quickbox rtorrent media directory write issue

### ISSUE THREAD

**Issue by leceuv** [pannal/Sub-Zero.bundle#719]
Hi,

I have a permission problem to let plex and sub zero write srt files in my media directory.
I change my .rtorrent.rc file to add "system.umask.set = 0022" it worked few days but now it doesn't and i don't know why.

I wanted to follow the faq Q3 (

> If running QuickBox, then:
> 
> In a terminal, type: apt-get install acl
> Then Follow

) and so many other topic about this issue
 but, unfortunately, the link 

>  https://quickbox.io/ufaqs/plex-cannot-readwrite-my-media-directory/ 

is dead

I don't know how i can solve this issue.
Thank you for your help

**Comment by pannal** [comment]
Google is your friend: https://plaza.quickbox.io/t/plex-media-folder-permissions/2181
