### ISSUE TITLE
Manually trigger a subtitle scan of entire library?

### ISSUE THREAD

**Issue by amplicity** [pannal/Sub-Zero.bundle#725]
I've configured sub-zero successfully, but there doesn't appear to be a way to trigger a scan of all existing videos in a given library.

Is there anyway to trigger a scan of your entire library?

I was unable to find this in the readme or application settings. Thank you for your work here, @pannal ! Looks awesome.

**Comment by pannal** [comment]
Please look at the Wiki and especially the FAQ!
