### ISSUE TITLE
SZ agent not kicking in for upgrades to existing media

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#726]
@pannal 

I read in #691 and #692 that you were trying to talk to Plex in the past regarding the issue where the SZ agent is not being triggered after an upgrade to an existing episode. Do you have any case with them opened? If so, would you mind giving the link to it to me so that I can follow-up with them?

**Comment by pannal** [comment]
That's an internal ticket which I can't share. Nothing happened there, though.

**Comment by kevindd992002** [comment]
I see. What is their reasoning behind a library scan not calling the SZ agent for upgraded media?

**Comment by pannal** [comment]
I can't seem to find the related ticket right now. I think I'll have to repost it.

Although I won't hold my horses as this is related to plugins and might not receive any love from Plex Inc.

**Comment by kevindd992002** [comment]
I see. Since I'm using Sonarr to actually tell Plex to scan the library if there's either a new media, an upgrade, or a rename, would it make sense for Sonarr to scan the library + refresh the metadata of a specific media file when it gets upgraded? Refreshing the metadata should trigger SZ, right?

**Comment by pannal** [comment]
Yes, is that an option in Sonarr now?

**Comment by kevindd992002** [comment]
It is not yet but I'm trying to request it to be:

https://forums.sonarr.tv/t/plex-media-server-connector-clarification/25427/2

**Comment by pannal** [comment]
Ah I've got that active and still have that issue.

**Comment by kevindd992002** [comment]
You mean you have an active issue with them too?

**Comment by pannal** [comment]
I don't think I've ever raised that with Sonarr, as it seems to be a Plex problem.

**Comment by kevindd992002** [comment]
Oh ok, you meant you have the connector active. I hope they consider that feature request.

**Comment by pannal** [comment]
Please reopen once something happens here.
