### ISSUE TITLE
Settings optimization

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#728]
If I want to have the absolute best subs provider for my media files, would enabling just addic7ed be a wise move?

Also, how does "hybrid plus" really work? I mean if you're currently watching a media file that already has an external subtitle, how will SZ even delete that srt file if it's being used at the moment?

Also, how does "hybrid" pick between current episode OR next episode?

**Comment by pannal** [comment]
> If I want to have the absolute best subs provider for my media files, would enabling just addic7ed be a wise move?

Depends on your setup. When you exhaust addic7ted regularly, it's a no. Then adding something like subscene helps, as they "mirror" Addic7ed.

> Also, how does "hybrid" pick between current episode OR next episode?

You misunderstood the "hybrid" description. "hybrid" refreshes the current item (might be a movie or an episode) once it's played, hybrid-plus also refreshes the next episode in line when it is an episode.

> I mean if you're currently watching a media file that already has an external subtitle, how will SZ even delete that srt file if it's being used at the moment?

That's mostly determined by the filesystem. Generally when being in use, an SRT being replaced while playing won't impact the SRT being played.
