### ISSUE TITLE
Channel question

### ISSUE THREAD

**Issue by miniop** [pannal/Sub-Zero.bundle#73]
The channel idea is amazing !

The only issue is now you can share channels with your friends.
I want my friends to have access to the subzero channel so they can download any missing subtitle but i I dont want them to have access to the settings because they can see the settings , change settings,... .
Is it possible to seperate the config file for the channel and the agent ?

Thanks

**Comment by eltismerino** [comment]
I don't really know whether I can fix that. It'd be a question for the Plex devs I think.
Separating the channel's settings from the agent isn't possible, either. Perhaps it's possible to restrict the access rights of those users?

**Comment by pannal** [comment]
I don't really know whether I can fix that. It'd be a question for the Plex devs I think.
Separating the channel's settings from the agent isn't possible, either. Perhaps it's possible to restrict the access rights of those users?

**Comment by miniop** [comment]
Maybe there is a way as the settings are stored in com.plexapp.agents.subzero.xml .
If there is a simple settings gui and for advanced settings to have it protected ? is this possible ?

Or to have an option to hide/unhide the critical options from the settings page from a variable  ?

Thanks

**Comment by pannal** [comment]
Sadly, no. I can't control the settings of the plugin in any way as far as my knowledge goes (and the documentation provides).

This may be worthy a feature request on the Plex forums.
