### ISSUE TITLE
Can't find any subtitles on Personal Media Shows

### ISSUE THREAD

**Issue by ChrisDudeBoi** [pannal/Sub-Zero.bundle#730]
So I've had a badly timed sub and I decided to download this plugin. I donwloaded it, did refresh all metadata, and found that some of the videos don't have a subtitle. I tried rearranging stuff, and signing in to a few sites, but I can't seem to get it to work. Any ideas?

**Comment by pannal** [comment]
It'll not work on personal media shows, unless you really lower your minimum scores and live with a lot of false positives. Please see wiki.
