### ISSUE TITLE
HearingImpaired mod works a bit wrong.

### ISSUE THREAD

**Issue by interlark** [pannal/Sub-Zero.bundle#734]
HearingImpaired mod completely deletes entries like this one:
```srt
00:40:33,973 --> 00:40:37,140
(whistles) Come by! (Whistles)
```
Expected result:
```srt
00:40:33,973 --> 00:40:37,140
Come by!
```

**Comment by interlark** [comment]
Or another one:
```srt
01:53:31,319 --> 01:53:33,195
(Tom) 'Stop it!'
(Dickie) 'Boring, it's boring.'
```
transforms into:
```srt
01:53:31,319 --> 01:53:33,195
(Tom) 'Stop it!'
'Boring, it's boring.'
```
Expected:
```srt
01:53:31,319 --> 01:53:33,195
'Stop it!'
'Boring, it's boring.'
```

**Comment by pannal** [comment]
Yep, that stuff is pretty much undetectable. 

Non-full-uppercase HI is hard to detect as it leads to more false-positives, deleting things that you want to keep, especially for items with less than 4 characters.

It's not perfect, I know.

**Comment by pannal** [comment]
I've got a couple of test-subs that I align this on, and anything more aggressive breaks other subs.

**Comment by pannal** [comment]
Please reopen if you disagree and/or can supply better filtering based on the codebase.
