### ISSUE TITLE
How do I enter a HTTP proxy with credentials?

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#736]
My IPVanish account gives access to a SOCKS V5 proxy:

https://support.ipvanish.com/hc/en-us/articles/360001280013-What-is-the-IPVanish-SOCKS5

Can I use that in the **HTTP proxy to use for providers (supports credentials)** to give SZ access to OpenSubtitles - that is blocked in Denmark where I live?

If yes: How do I enter the hostname/username/password/port in a string that SZ understand?

**Comment by VilDegard** [comment]
Yes, you can.

Use the following format: `user:password@proxyserver:proxyport`
Proxy port should be 1080 for SOCKS5, 80 for HTTP.
On my side, only HTTP worked on Subzero (atm).

**Comment by glitdev29** [comment]
> My IPVanish account gives access to a SOCKS V5 proxy:
> 
> https://support.ipvanish.com/hc/en-us/articles/360001280013-What-is-the-IPVanish-SOCKS5
> 
> Can I use that in the **HTTP proxy to use for providers (supports credentials)** to give SZ access to OpenSubtitles - that is blocked in Denmark where I live?
> 
> If yes: How do I enter the hostname/username/password/port in a string that SZ understand?

Hi, Did you found any Solution for it? I am havng same error.

**Comment by cphmichael** [comment]
I tried to enter the IPvanish credentials, but I could not get it to work.
In in the meantime is Opensubtitles no longer blocked from Denmark :-)

![image](https://user-images.githubusercontent.com/45288008/89173506-ab9fd700-d584-11ea-8907-2a3b7b60829f.png)

**Comment by VilDegard** [comment]
Same from the Netherlands. Good to know. 
Probably Cloudfare did some IP whitelistings.
