### ISSUE TITLE
SubZero endless loop (download subtitles)

### ISSUE THREAD

**Issue by VilDegard** [pannal/Sub-Zero.bundle#740]
Hi,

It seems that when I add a new movie/tv show in and that Subzero grabs adequate subtitles, it doesn't record that it found the right subtitles. Instead, through the scheduler, it founds new subtitles, but then again 6 hours later it doesn't record any findings.

I store subtitles with metadata as I'm using a filesystem and it seems that copying subtitles doesn't work from Subzero, I assume it's linked to rights.

Do you have an idea of how to fix this please?
Thanks

**Comment by apathy** [comment]
Hey @VilDegard , long shot if you reply or not, but how did you manage to fix this? I have "Don't search for subtitles of a language if they already exist on the filesystem (metadata/filesystem)?" enabled, but it still downloads subtitles when they already exist on the filesystem.

**Comment by VilDegard** [comment]
Hey @apathy , long shot indeed, sorry I didn't see your post earlier. 

> it still downloads subtitles when they already exist on the filesystem.

Do you mean that in the "History" section, you see new subs added in? (despite the Don't search for subtitles of a language if they already exist on the filesystem (metadata/filesystem)?" enabled)-- or are you referring to something else?

It will take time to remember how I fixed this, but happy to put my head again into it if it can help you. Let me know.

**Comment by apathy** [comment]
@VilDegard Thanks for getting back to me! So, even with the "Don't search for subtitles of a language if they already exist on the filesystem (metadata/filesystem)?” option enabled, it still searches/downloads subtitles for those that exist and this causes a loop of downloading the same subtitles over and over. I’ve had to disable the search for missing subtitles option as this was starting to eat up all my daily limits on Addic7ed. I’ve tried completely deleting SubZero (including the files on the PMS directory) and reinstalling but still I can’t seem to fix getting SubZero to be satisfied with a subtitle once it’s downloaded. Any help would really be appreciated, thanks again.

**Comment by VilDegard** [comment]
Well I've just realised that in fact, I'm experiencing the exact same issue again. It's really weird because I thought I fixed it. I stopped using Addic7ed with a captcha solver service so I didn't really check again weither SZ was back into continuously adding subtitles already added (with the same score).

I need to investigate it further, let's keep each others posted if we find a solution.

**Comment by apathy** [comment]
Will do! I've opened a new issue 2 days ago https://github.com/pannal/Sub-Zero.bundle/issues/761 but I don't know if I'll get any response, might have to join the Slack and see if anyone there is willing to help.

**Comment by apathy** [comment]
This has been fixed for me, check https://github.com/pannal/Sub-Zero.bundle/issues/761, though if you aren't using a custom subtitle folder I'd open a new issue and provide as much information as possible.

**Comment by VilDegard** [comment]
Thanks @apathy, much appreciated. 
I'll take a look at it this weekend if I get a chance. 
Take care.
