### ISSUE TITLE
Can't access logs with Kitana

### ISSUE THREAD

**Issue by VilDegard** [pannal/Sub-Zero.bundle#741]
Hi,

I access SZ through Kitana (in Docker), when I try to get the logs, it opens a URL "http://localhost:31337/video/subzero/advanced" with a blank page. 

Sounds silly but do you know how to fix this please?

EDIT: Copy/paste didn't work until now... it's fixed. Sorry for the post.

Thanks in advance.

**Comment by pannal** [comment]
Are you using the current version of Kitana? I added explicit log export support a couple of weeks ago.

**Comment by VilDegard** [comment]
Sorry @pannal I fixed it after a container reboot. Thanks.
