### ISSUE TITLE
On new TrueNas 12.0 not working

### ISSUE THREAD

**Issue by sstruke** [pannal/Sub-Zero.bundle#745]
In New TrueNas 12.0 some subtitle downloads don't work and some download without a problem
those who do not work write an error "UnicodeDecodeError"
also writes something else about UTF8 but I didn't understand

**Comment by Lokarde** [comment]
Same issue

**Comment by Lokarde** [comment]
A temporary fix : 
A line 580 of file 'Sub-Zero.bundle/Contents/Libraries/Shared/scandir.py', 
replace `_scandir = _scandir_generic if scandir_generic else scandir`
by `_scandir = _scandir_generic #if scandir_generic else scandir`

**Comment by sstruke** [comment]
> A temporary fix :
> A line 580 of file 'Sub-Zero.bundle/Contents/Libraries/Shared/scandir.py',
> replace `_scandir = _scandir_generic if scandir_generic else scandir`
> by `_scandir = _scandir_generic #if scandir_generic else scandir`
Sorry, I can't find this text in the file ("Sub-Zero.bundle / Contents / Libraries / Shared / scandir.py") line 580 is empty
see the attachment
![scandir](https://user-images.githubusercontent.com/39979063/99690368-5ed70200-2a88-11eb-8502-af3fc5111119.jpg)

**Comment by Lokarde** [comment]
Oups, fail
It's the file under `Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py` function `_search_external_subtitles` (line 580)

**Comment by sstruke** [comment]
Thanks for the correction
It works perfectly

**Comment by pannal** [comment]
Interesting. Can someone supply DEBUG logs for this (see Wiki).

This should be fixable in a more generic way.

**Comment by devwal** [comment]
I tried doing this and restarted my Jail server, and still doesnt work. any ideas why?

**Comment by sstruke** [comment]
set your agent database to plex movies and restart
