### ISSUE TITLE
Only subtitles for TV Shows are being downloaded

### ISSUE THREAD

**Issue by Duchys** [pannal/Sub-Zero.bundle#752]
Hello,

I've been having issues with getting Sub-Zero to download subtitles for my movies, even though the subtitles for TV Shows are downloaded successfully. 

In the log files I'm able to see that it is only enabled for TV Shows, even though it is enabled for movies on my Plex server.
`DEBUG (config:687) - I'm enabled for: ['TV Shows']`

Restart of Plex and the plugin did not help.

Below you can find attached screenshots from Plex and Kitana:
![image](https://user-images.githubusercontent.com/31930651/101269380-a343ec80-376e-11eb-8326-838fbb9a31d5.png)
![image](https://user-images.githubusercontent.com/31930651/101269393-c7073280-376e-11eb-8534-6e82cf6ff516.png)
![image](https://user-images.githubusercontent.com/31930651/101269394-ccfd1380-376e-11eb-97af-12973173873a.png)

Logs:
[Logs_201206_02-56-39.zip](https://github.com/pannal/Sub-Zero.bundle/files/5648165/Logs_201206_02-56-39.zip)

Thank you for any help.

**Comment by theDwiz01** [comment]
I've used SubZero for a long time (years, not months).  Up until a few months ago everything was perfect.  Going back until about August..only TV Shows are downloading for me as well.  No movie subs are being grabbed.  I've checked and all my login info for all subtitle sites are accurate.  All my screenshots of my settings are still the same, nothing has changed.  Any ideas why only TV gets grabbed?

**Comment by Smoukus** [comment]
Could the reason be the new Plex Movie Agent?
Plex recently upgraded their Movie agent, but the TV agent wasn't updated.
After the upgrade, my subtitles are being also downloaded only for TV, but not for movies.

**Comment by ukdtom** [comment]
The new agent doesn't work with any python based agents.

**Comment by theDwiz01** [comment]
> The new agent doesn't work with any python based agents.

So is there something else you know of that would work for auto-grabbing subs for movies?  Or think it will ever work in the future?

**Comment by ukdtom** [comment]
Sorry, but clueless here, since I don't use automation myself ;)

**Comment by Duchys** [comment]
> The new agent doesn't work with any python based agents.

Thanks for letting me know, as this issue is with Plex and not the Sub-Yero plugin itself I do not expect resolution to this issue any time soon. 

My questions now is, if it is possible to run the Sub-Zero plugin manually via the command line (or any other method), in order to automatically download the subtitles?

**Comment by Duchys** [comment]
Reverting to the Plex Movie Legacy plugin as mentioned in issue https://github.com/pannal/Sub-Zero.bundle/issues/753 fixed the issue for me. Movie subtitles are now being downloaded automatically.

![image](https://user-images.githubusercontent.com/31930651/103189272-2c60c600-48cc-11eb-848c-8240e8ae5ee1.png)

Thank you for the help.
