### ISSUE TITLE
Folders in libraries

### ISSUE THREAD

**Issue by mwhplx** [pannal/Sub-Zero.bundle#759]
Hello,

I am suddenly seeing .sz_perm_chk in some of my library folders and they are full of giberish looking named folders. They are also quite large (several 10's of GB's in each) and I cant seem to be able to even delete them.

Can you please let me know if there is something I can do about this ?

Thanks
G

**Comment by pannal** [comment]
Those are folders created by SZ to check for correct permissions.

SZ doesn't put anything inside and tries to immediately delete them after creating them. Are you sure you have the right permissions to delete those folders?

Which OS are you on?

The contents of these folders can't have been created by SZ itself.

**Comment by pannal** [comment]
This is _literally_ all SZ does:
```
def check_write_permissions(path):
    if platform.system() == "Windows":
        # physical access check
        check_path = os.path.join(os.path.realpath(path), ".sz_perm_chk")
        try:
            if os.path.exists(check_path):
                os.rmdir(check_path)
            os.mkdir(check_path)
            os.rmdir(check_path)
            return True
        except OSError:
            pass

    else:
        # os.access check
        return os.access(path, os.W_OK | os.X_OK)
    return False
```

**Comment by mwhplx** [comment]
Hello !!

Thank you very much for the reply. It must be some coincidence with something going wrong with the disk at the time SZ was checking... I couldnt even change permissions on the files/folders however Chkdsk resolved the issue thus it was probably a write issue or something to do with the disk (it does not show any smart  errors though).

In any case it is resolved and I thank you so very much for the reply and the awesome software :)

G.
