### ISSUE TITLE
Sub-Zero not considering new "Plex Movie" agent libraries

### ISSUE THREAD

**Issue by xxxxxaaaaaaaannnn** [pannal/Sub-Zero.bundle#770]
Hello,

When running Sub-Zero, I noticed that the libraries with the (new) agent "Plex Movie" are not considered while the ones with "The Movies Database" (or others) are :

Logs : 
DEBUG (config:698) - I'm enabled for: ['Anime', '_downloads']

After I changed _downloads library to "Plex Movie": 
DEBUG (config:698) - I'm enabled for: ['Anime']

Any idea ?

**Comment by pannal** [comment]
Duplicate of #753
