### ISSUE TITLE
Recently Added items list is not accurate

### ISSUE THREAD

**Issue by chopeta** [pannal/Sub-Zero.bundle#78]
Reporting the issue so we won't forget to get it fixed (I am assuming the error is still there since I am using 1.3.6.316 and notice it right away).

**Some background:** My Recently Added episodes for my Shows library always display 200 items (Plex default) and my last item on the list is an item from 10 days...

**The problem:** My SZ settings for autom. schedule are set to 2 weeks but when I go to Channels -> SZ -> Recently Added item show 158 items are show (and that's including all my libraries)...

I am pretty sure something is wrong here with this filter...

**Comment by chopeta** [comment]
I just got a case of an episode that was added yesterday and isn't showing up in the SZ recently added list with max-age of 2 weeks :(

**Comment by pannal** [comment]
Can you give me the addedAt value of the item? `/library/metadata/XXXXX?X-Plex-Token=`, where XXXXX is the item id

**Comment by chopeta** [comment]
I could swear we already did this exercise :)

Here you go: 
```
originallyAvailableAt="2015-10-25" addedAt="1445984527" updatedAt="1446836585"
```

**Comment by pannal** [comment]
I know you love to exercise!

**Comment by chopeta** [comment]
Testing 'recently-added' branch...

Just one question: Do we really need the limit of 100 items per section if we already have max-age to control the amount of items? 100 items in less than 7 days of adding new content into my PMS :) this way I will never made to the 4 weeks max-age.

If we really need the limit, can it be 200? :)

Other than that it seems to be working perfect!

Big thanks @pannal

**Comment by eltismerino** [comment]
The limit comes from Plex, and it's 100 per section, not overall. Is that still not enough?

**Comment by eltismerino** [comment]
OK, try https://github.com/pannal/Sub-Zero.bundle/archive/menu-more.zip - it has the new item browser inside, also. And the limit per section now is 200, I will make that value configurable.

**Comment by chopeta** [comment]
OK... here are some results from my tests with 'menu-more' branch:

1) Minor: If I use the settings button from inside the channel to save a new 'max-age' channel button doesn't get refreshed after I hit 'save'
2) Error: With my libraries 'Recently Added' list only open with max-age set to 3 days. Anything more than 3 days I get an error (I guess some timeout due to too many items). No errors are showing up in the logs. Sometimes even with 2 days I get the crash... you can noticed in the SZ logs that things are still running (PMS responding to SZ requests) while the error in already show in the GUI. I am pretty sure it's some kind of timeout.

Browse All items works fine. Even for my Movies sections which has 1500 items.

**Comment by pannal** [comment]
1) I don't think I can control that.
2) I've pushed a version with an upper limit of 200 items per individual section, can you test that?

**Comment by chopeta** [comment]
Is working chepisimo now! Recently Added now matches with results from Plex Web.

So awesome!!!!! :D

Big thanks @pannal

**Comment by pannal** [comment]
Fixed in the latest release I hope :)
