### ISSUE TITLE
If I enable advance setting, SZ plugin gone???

### ISSUE THREAD

**Issue by IvanR88** [pannal/Sub-Zero.bundle#784]
Please help, because I want to enable Subscene with Movies.

Or is there any other way to enable it without enabling the advance setting?

Here I attach the logs:

[SZLogs.zip](https://github.com/pannal/Sub-Zero.bundle/files/8240770/SZLogs.zip)

**Comment by pannal** [comment]
`ValueError: No JSON object could be decoded`

You messed up the JSON format somehow :)

**Comment by IvanR88** [comment]
I didn't do anything, i swearrrr :))

I just copy and paste as you suggested.. 

But seriously, what should I do then?

**Comment by IvanR88** [comment]
Finally I've the solution!!!

For those who are using Notepad++ to edit, don't use it! Just use the normal way (notepad)

**Comment by pannal** [comment]
Yeah probably formatting and/or mixing of tabs and spaces and/or mixing of CR/LF or something like that.
