### ISSUE TITLE
Sub-Zero invisible in PMS v1.31.2.6739 beta

### ISSUE THREAD

**Issue by sstruke** [pannal/Sub-Zero.bundle#799]
TrueNAS-SCALE-22.12.1 app: suddenly disappeared among agents
It was still working without a problem in January 2023, but now it is not among the agents.
I have checked all rights and nothing helps at all
Probably one of the last updates banned Sub-zero
Does anyone else have similar problems

**Comment by pannal** [comment]
Yes, I've already informed Plex. Seems like there was a refactoring of the `/system/agents` endpoint in PMS v1.31.2.6739 beta which broke SZ. It'll probably be fixed in the next PMS beta.

**Comment by pannal** [comment]
You can downgrade the PMS to v1.31.2.6733 in the meantime.

**Comment by sstruke** [comment]
Thanks for the information

**Comment by pannal** [comment]
Reopening for visibility

**Comment by sstruke** [comment]
-

**Comment by realindiahotel** [comment]
Is this still an issue?

**Comment by realindiahotel** [comment]
Still exists.
