### ISSUE TITLE
Force match episode and season number over hash

### ISSUE THREAD

**Issue by ledge74** [pannal/Sub-Zero.bundle#80]
When looking for episodes subtitles Sub-Zero should match guessit season & episodes numbers with plex data before downloading ; and discard if it doesn't match.

See https://forums.plex.tv/discussion/comment/1056024/#Comment_1056024

**Comment by Roelie** [comment]
I agree. If the season and episode information does not match , the whole subtitle should be dropped and going onto the next potential one.

**Comment by pannal** [comment]
I guess it's time to patch subliminal again :)
By default it favors hash-based matching over anything else (and even simple logic)

**Comment by pannal** [comment]
Will be fixed in next release.

**Comment by ledge74** [comment]
great ! :+1:
