### ISSUE TITLE
Opensubtitles.org should be replaced with .com

### ISSUE THREAD

**Issue by RogertG** [pannal/Sub-Zero.bundle#801]
As far as I know, Opensubtitles.org queries will soon be deprecated, and Opensubtitles.should be used instead. How to change this in the plugin? Thanks!

**Comment by morpheus65535** [comment]
They are using a totally different API so there's no easy way. Good news is that we've have developed a provider that will be compatible with Sub-Zero in Bazarr: https://github.com/morpheus65535/bazarr/blob/master/libs/subliminal_patch/providers/opensubtitlescom.py

Feel free to reuse it but use your own OpenSubtitles.com apikey please.

**Comment by RogertG** [comment]
Thanks @morpheus65535 !
Worked like a charm!
Cheers!
