### ISSUE TITLE
Subzero working for movies, but not TV shows [what am I missing?]

### ISSUE THREAD

**Issue by mimed** [pannal/Sub-Zero.bundle#804]
Hey subzero community, I was hoping you could help me.
I was able to set up subzero for movies, but when it comes to TV shows, the plugin just keeps searching for subs and nothing happens. As I'm a real n00b with this, I thought I'd share my config with you all to see if anyone can spot what might be causing this "malfunction". Any advice will be highly appreciated. Thanks in advance.

![CleanShot 2023-11-13 at 10 34 09@2x](https://github.com/pannal/Sub-Zero.bundle/assets/6992776/940576e0-eaa7-4eab-b647-0152dac9a799)
![CleanShot 2023-11-13 at 10 34 20@2x](https://github.com/pannal/Sub-Zero.bundle/assets/6992776/39b41ff5-d125-4b27-8ff5-d322f17700d5)
![Screen Shot 2023-11-13 at 10 35 33](https://github.com/pannal/Sub-Zero.bundle/assets/6992776/69be96f8-1c50-4a2d-9505-26d902a3a00e)

**Comment by pannal** [comment]
This plugin isn't supported anymore. Please switch to https://www.bazarr.media/
