### ISSUE TITLE
OpenSubtitles.org API now requires VIP membership. Change to OpenSubtitles.com API needed.

### ISSUE THREAD

**Issue by Zonrotan** [pannal/Sub-Zero.bundle#805]
Since january the 1st the OpenSubtitles.org API requires VIP membership.
To avoid this one could allegedly use the OpenSubtitles.com API instead (requires login).

Currently most subtitles that are downloaded by Sub-Zero simply say 
"Become OpenSubtitles.org VIP Member
to get subtitles -> osdb.link/vip"

Would love if this was fixed.
Thanks!

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/releases/tag/2.6.5.3280
