### ISSUE TITLE
Sub-Zero flooding syslog

### ISSUE THREAD

**Issue by dfischer0** [pannal/Sub-Zero.bundle#82]
I have installed the latest Sub-Zero plugin, and it is flooding my syslog with all types of logs. 200MB worth of them :)

I'm running Plex on Ubuntu, and I don't have PLEX_MEDIA_SERVER_USE_SYSLOG=true

**Comment by eltismerino** [comment]
Hey,

the whole logging procedure is controlled by Plex. If you log to syslog and you have `Enable Plex Media Server debug logging` and/or `Enable Plex Media Server verbose logging`, all the plugins' logging facilities log the whole debug output to wherever Plex wants them to.

When disabling debug logging Sub-Zero will still output logs, but only those of the INFO and higher types, which should be far less than all of the debug output.

**Comment by pannal** [comment]
Hey,

the whole logging procedure is controlled by Plex. If you log to syslog and you have Enable Plex Media Server debug logging and/or Enable Plex Media Server verbose logging enabled, all the plugins' logging facilities log the whole debug output to wherever Plex wants them to.

When disabling debug logging Sub-Zero will still output logs, but only those of the INFO and higher types, which should be far less than all of the debug output.

Edit: Ah and you are using the plugin for the first time, so it most likely instantly started the search for recent items with missing subtitles task.

**Comment by dfischer0** [comment]
The thing is, I'm not logging to syslog but for some reason all Plex logging ends up in both syslog and the regular Plex log files...
But I guess this is a Plex issue, not a plugin issue. I'm thus closing this issue.

**Comment by dfischer0** [comment]
I'm reopening this issue because I have disabled Plex debug and verbose logging, and I still get DEBUG logging in /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs/PMS\ Plugin\ Logs/com.plexapp.agents.subzero.log

I get MB upon MB of logs:
-rw-r--r-- 1 plex plex 306K Nov 15 12:46 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log
-rw-r--r-- 1 plex plex 1.0M Nov 15 11:22 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.1
-rw-r--r-- 1 plex plex 1.0M Nov 15 11:22 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.2
-rw-r--r-- 1 plex plex 1.0M Nov 15 11:21 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.3
-rw-r--r-- 1 plex plex 1.0M Nov 15 11:20 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.4
-rw-r--r-- 1 plex plex 1.0M Nov 15 11:19 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.5

And for some reason (which I still don't understand) all these logs get picked up by rsyslog and end up in /var/log/syslog as well, which is unusable. (nota: I'm running on Ubuntu Server 15.10)

**Comment by pannal** [comment]
Can you try editing the Info,plist file of your individual Sub-Zero installation and set PlexPluginConsoleLogging to 0?

**Comment by pannal** [comment]
I still don't know why those logs appear in your syslog, but for the logging itself I'll make the level configurable in the settings, as it currently always is DEBUG for the shared libraries.

**Comment by dfischer0** [comment]
I did try editing the Info,plist file and setting PlexPluginConsoleLogging to 0, and it solved my syslog issue. Of course the agent logs are still flooded by debug messages, but I assume that's normal.

**Comment by dfischer0** [comment]
Ok, I found out why I was getting my syslog flooded: since Ubuntu 14.4, Plex is run as a systemd service and will thus, by default, send all output to syslog. I have changed that by adding StandardOutput=null
in the service file.

**Comment by pannal** [comment]
Both the log level and the console logging will be configurable in the next release.

**Comment by pannal** [comment]
Next release out. Please try and report back!
