### ISSUE TITLE
Subliminal

### ISSUE THREAD

**Issue by Diaoul** [pannal/Sub-Zero.bundle#86]
Thanks for using subliminal.
Please consider contributing to subliminal (issues, PR) when you make changes so other users can benefit from your fixes.
It will save you some maintainance as some of your current patches are not needded anymore.
Also please don't use memory backend for caching, any other kind of caching will do, see [here](http://subliminal.readthedocs.org/en/latest/user/usage.html#configuration).

Thanks

**Comment by eltismerino** [comment]
If I can find the time to do so, I most certainly will.

I'm using the last official version of subliminal (1.0.1), and all of my patches still apply to that version if I'm not mistaken - am I?
Also Sub-Zero's patches are somewhat aggressive at times and don't fit your generic subliminal approach, such as the forced Addic7ed boost on certain criteria, resulting in a score higher than "hash".

Why not use the memory caching? Sub-Zero runs permanently as a service in the PMS sandbox.

**Comment by pannal** [comment]
If I can find the time to do so, I most certainly will.

I'm using the last official version of subliminal (1.0.1), and all of my patches still apply to that version if I'm not mistaken - am I?
Also Sub-Zero's patches are somewhat aggressive at times and don't fit your generic subliminal approach, such as the forced Addic7ed boost on certain criteria, resulting in a score higher than "hash".

Why not use the memory caching? Sub-Zero runs permanently as a service in the PMS sandbox.

**Comment by Diaoul** [comment]
Yes 1.0.1 is latest stable for now, develop branch brings some bugfixes and new features. I hope I'll be able to release it soon.
OK, I thought the cache was lost between subtitle searches. If ones restarts the media center, cache is lost. Does that happen often?

**Comment by eltismerino** [comment]
Nah not really, only after plugin updates.

I'll happily incorporate your new features/bugfixes and drop duplicate patches in my subliminal_patch library. And you're also welcome to get some of the fixes I've done from the Sub-Zero repository. Though, as I said, some are not very subliminal-ish.

**Comment by pannal** [comment]
Nah not really, only after plugin updates.

I'll happily incorporate your new features/bugfixes and drop duplicate patches in my subliminal_patch library. And you're also welcome to get some of the fixes I've done from the Sub-Zero repository. Though, as I said, some are not very subliminal-ish.

**Comment by pannal** [comment]
Seems like you did some serious changes to subliminal in the last few weeks. I guess the next major SZ version will incorporate those and ditch some of my personal patches to the library :)

Great work!

**Comment by eltismerino** [comment]
How's the schedule going? I've seen some changes I could ditch in SZ by updating subliminal. Is there a plan for guessit 2?

**Comment by pannal** [comment]
How's the schedule going? I've seen some changes I could ditch in SZ by updating subliminal. Is there a plan for guessit 2?

**Comment by Diaoul** [comment]
No need to hack around stevedore anymore.
Guessit2 is done.
AsyncPoolProvider too and drastically improve speed.
New scoring algorithm.
Easier to tweak the scoring as you can now pass your own `compute_score` function.
Did a bunch of other fixes and currently implementing some metadata scrapers, namely omdb and tvdb. The REST API is easy and it'll return the correct `year` information and a proper `series` or `title`.
Unfortunately omdb doesn't return any result when searching for "Greys Anatomy" **but** tvdb does!
Every request will be cached so it shouldn't hurt performance.

That would be a 2.0 for subliminal due to the major changes, I'd love to hear your feedback.

**Comment by pannal** [comment]
Sounds awesome. I'll check back after my vacation and will soon start to implement subliminal 2.0!

Thank you for your effort!

**Comment by pannal** [comment]
@Diaoul where are we with this? I'd love to drop my individual patches.

**Comment by pannal** [comment]
Nearly implemented, I was able to drop most of my monkey patching thanks to your rewrite! Great work!

**Comment by pannal** [comment]
@Diaoul how does AsyncPoolProvider handle logging? Are log messages of the individual providers still in the correct order or are they "mushed" together when used?

**Comment by Diaoul** [comment]
Yes the order *per provider* is preserved as there is only one instance of each provider running at the same time within the AsyncPoolProvider.

**Comment by pannal** [comment]
Doesn't that still mean munged output when 2 different providers log at the same time?

**Comment by Diaoul** [comment]
You can have one log line coming from one provider then a second log line coming from a different provider yes. However the integrity of the log line is preserved characters from one log line won't be mixed with another log line.
Not sure if that answers your question

**Comment by pannal** [comment]
Yep, thank you. AsyncProviderPool already is in full effect in sub-zero 2.0.0.0 beta :) 

You've done awesome work with subliminal 2!

**Comment by pannal** [comment]
@Diaoul I wrote you an email, did you get it? :)
