### ISSUE TITLE
skip search when a certain file is present.

### ISSUE THREAD

**Issue by eilandert** [pannal/Sub-Zero.bundle#87]
just an idea as enhancement.

Skip searching for subs in current directory and downstream when a file like .sub.ignore is present.

- Personally I find it easier to touch that file than go through the plex menu's to ignore.
- It's easier to migrate or replace the plex server (more persistent)
- It can be scripted, or used in scripts and other programs.
- If we make a /Storage/Series-complete directory everything inside will be skipped. (just one example of possibilities)

**Comment by pannal** [comment]
Looking into it.

**Comment by pannal** [comment]
Please try https://github.com/pannal/Sub-Zero.bundle/archive/master.zip, you can create the files `subzero.ignore`, `.subzero.ignore`, or `.nosz` anywhere.

**Comment by Ruvetuve** [comment]
Nice feature @pannal!

Maybe you can update the doc section "Ignore list" with info how to apply it. My questions are:
- do i need to make a file or folder with subzero.ignore in it?
- to ignore a episode i need to make a file/folder in: disk/tv/show/season/episode/subzero.ignore?
- to ignore a whole season i need to make a file/folder in: disk/tv/show/season/subzero.ignore?
- to ignore a whole show i need to make a file/folder in: disk/tv/show/subzero.ignore?

**Comment by pannal** [comment]
I will update the docs accordingly soon.

Currently you have the option of creating a _file_ named `subzero.ignore`, `.subzero.ignore`, or `.nosz`.
You can place that anywhere, including season folders, movie folders, series folders and library root folders.

> to ignore a episode i need to make a file/folder: disk/tv/show/season/episode/subzero.ignore?
> to ignore a whole season i need to make a file/folder: disk/tv/show/season/subzero.ignore?
> to ignore a whole show i need to make a file/folder: disk/tv/show/subzero.ignore?
Correct. A file.
