### ISSUE TITLE
Ignore folders

### ISSUE THREAD

**Issue by jobrien2001** [pannal/Sub-Zero.bundle#89]
Would be nice to be able to ignore folders within a library.  I have a script that moves subbed movies/tv shows to a specific folder while keeping the non subbed ones on another.  If i could make your plugin ignore the "already subbed" folder it would be awesome.

**Comment by pannal** [comment]
Why don't you use a separate library for this? I don't really get it.

**Comment by jobrien2001** [comment]
If i use a separate library, plex wont let me filter content from more than 1 library.

**Comment by pannal** [comment]
What exactly are you referring to? I can filter content over 10 libraries and all of my connected servers.

**Comment by jobrien2001** [comment]
but you have to filter them individually. Not sure im being noob but i dont think there is a way to filter for lets say for example an actor across all libraries with the web client, you must set a actor filter within each library (multiple times).  The web client only lets you search by movie title across all libraries.

**Comment by jobrien2001** [comment]
Ill expand on it cause I dont think i explained it well.  I watch a movie of actor "john doe" in it ... it was a great movie so i decide to look for more movies with "john doe" so i click on "john doe" on the webclient and it will only show me results within the current library not from others.

If movie content is split across libraries the webclient wont let you make relationships between the libraries.

**Comment by pannal** [comment]
That's somehow the same as #87 isn't it?

**Comment by jobrien2001** [comment]
Ah yes very similar

**Comment by pannal** [comment]
Closing this, as it's the same as #87

**Comment by pannal** [comment]
Please try https://github.com/pannal/Sub-Zero.bundle/archive/master.zip, you can create the files `subzero.ignore`, `.subzero.ignore`, or `.nosz` anywhere.
