### ISSUE TITLE
Tv show cannot be found (but exist in addic7ed)

### ISSUE THREAD

**Issue by therealjohnsnow** [pannal/Sub-Zero.bundle#90]
Hi excellent work thus far.

I am just installing it for the first time. 

My issue is with the tv show Last Man Standing, it works without issues in default Opensubtitles agent but subtitles cannot be downloaded with Sub Zero. Delving into the logs told me that this is because the file name has 'US' in it e.g. 'Last Man Standing (US) SXXEXX'. Hope this can be fixed :)

Logs attached.

[com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/46468/com.plexapp.agents.subzero.log.txt)

**Comment by therealjohnsnow** [comment]
Just realized it's probably not very polite of me to just dump that big pile of log there. Here is my area of concern:

015-11-28 17:18:06,045 (43fa8470) :  ERROR (logger:38) - subliminal_patch.patch_providers.addic7ed: No show id found for u'Last Man Standing (US)' ({'country': None, 'year': None})

2015-11-28 17:18:31,935 (44296470) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/TV Shows/e/12bb9eab5e7e8b9670e537c29a22914874faab4.bundle/Contents/com.plexapp.agents.subzero

2015-11-28 17:18:43,780 (43fa8470) :  ERROR (logger:38) - subliminal_patch.patch_providers.tvsubtitles: Failed to match Last Man Standing (2011-2015)

2015-11-28 17:18:43,804 (43fa8470) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for u'Last Man Standing (US)' ({u'year': None}) 
   
Regards.

**Comment by pannal** [comment]
Can you re-run this one with the log_level setting set to DEBUG?

I see what's causing this, but I'd like to see the remaining decisions the libraries did (guessit, subliminal).

**Comment by therealjohnsnow** [comment]
Ok here you go.

DEBUG level log for when I refresh Last Man Standing at TV library. Triggered at 12.15pm.

[com.plexapp.agents.subzero.log.1.txt](https://github.com/pannal/Sub-Zero.bundle/files/46486/com.plexapp.agents.subzero.log.1.txt)

[com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/46488/com.plexapp.agents.subzero.log.txt)

**Comment by pannal** [comment]
Thanks. Looking into it.

**Comment by therealjohnsnow** [comment]
Small update...same issue with sister's NAS...Installed the Plugin, all other tv shows matched successfully except for Last Man Standing. Log attached in case needed.

[com.plexapp.agents.subzero-5.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/46658/com.plexapp.agents.subzero-5.log.txt)

Thank you again for your time and effort.

Regards
