### ISSUE TITLE
Allow users to select new subtitle from a list

### ISSUE THREAD

**Issue by phunkysai** [pannal/Sub-Zero.bundle#95]
Sometimes the scene release subtitles are off, so even though we have the "correct" subtitle, the sync is still off, and Subzero won't pull a different sub because it thinks it has the "best" one.

Requested feature would be to have the ability to Browse to the TV episode and have an option that would pull all available subtitles for the episode and let us download a different one (and show us which ones we've already tried).

Another user on the forum also suggested the following in case the above would be too hard to implement:
"A feature request would be for blacklisting the existing or the previously grabbed subtitle during a force refresh."

**Comment by jbreuer95** [comment]
This would be awesome, been using the plugin for some days now and its perfect except for those few subtitles where there out of sync and Sub-Zero thinking its the best one. Any ETA when this can be expected?

**Comment by Ruvetuve** [comment]
@pannal, any update regarding this? I have the feeling development halted.. 

I think the most wanted feature is to select optional Subtitles to download or periodically update the subtitles watching out for better versions.

**Comment by phunkysai** [comment]
Yes please. :-)

**Comment by pannal** [comment]
Development on new features is slow currently, partly because of vacation/illness in the last month.
There has been progress regarding this feature in the development branch, but it isn't ready for the public, yet.

I will keep you updated!

**Comment by phunkysai** [comment]
Great news....keep up the great work!

**Comment by Ruvetuve** [comment]
Thanks @pannal, not intended to rush you. Glad to hear it was because of a well deserved vacation, sorry to hear about your illness. Thank you for your update.

**Comment by pannal** [comment]
This is currently in Release Candidate stage and will be done soon.

**Comment by phunkysai** [comment]
Awesome, you're the man!

**Comment by Ruvetuve** [comment]
Nice, looking forward to it
